_data/data.yaml

EAL picked this site up with the Levenshtein Algo.
myethcrwallet.com
Directed From: /
Traffic: 0.16%
Last Hit: 0 days ago
Yaml checked with: https://codebeautify.org/yaml-validator

Update data.yml - myethcrwallet.com

---

_data/data.yaml

Asks for private key to receive the airdrop, fake omsie go website

Update data.yaml - omise-go.com

---

_data/data.yaml

Asking for private keys for a token airdrop - https://twitter.com/sniko_/status/896765591297683456

update data.yaml - numerai.tech

---

_data/data.yaml

OmiseGo phishing scam - asking for private key to receive airdrop

Update data.yaml - omise-go.net

---

_data/data.yaml

Etherdelta clone, obvious phish.

Update data.yaml - etherdelta-glthub.com

---

_data/data.yaml

https://www.reddit.com/r/ethtrader/comments/6u83fr/bittrex_phishing_email/
Phishing for bittrex account details

Update data.yaml - bittrex.cam

---

_data/data.yaml

Clone of decentraland.org - phishing for eth

Update data.yaml - decentraland.pro

---

_data/data.yaml

Phishing for private keys - MEW clone

Update data.yaml - myetthterwallet.com & enigmatoken.com

---

_data/data.yaml

Phishing. Decentraland.org clone. On the same server as enigmatoken.com

Update data.yaml - decentraland.tech

---

_data/data.yaml

Adding addresses used by domains.

Update data.yaml - known addresses

---

_data/data.yaml

Contract transferred before contract suicide to this address: https://etherscan.io/tx/0xb7f0d837a10028271d7177e86b595b266302f1bc65c9db5cd7a6d48740c2c4de

Ziber.io address

---

_data/data.yaml

Blacklisted on EAL a while ago, recently popped up again on this tx: https://etherscan.io/tx/0x66840ed55126364d95bfc249f800381a39a1b085b17138019503048154023085#comments
See Twitter thread: https://twitter.com/switchingtoguns/status/892786963648053248/photo/1?ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Fdisqus.com%2Fembed%2Fcomments%2F%3Fbase%3Ddefault%26f%3Detherscan%26t_i%3DEtherscan_TxHash_0x66840ed55126364d95bfc249f800381a39a1b085b17138019503048154023085_Comments%26t_u%3Dhttps%253A%252F%252Fetherscan.io%252Ftx%252F0x66840ed55126364d95bfc249f800381a39a1b085b17138019503048154023085%2523disqus%26t_e%3DTransaction%25200x66840ed55126364d95bfc249f800381a39a1b085b17138019503048154023085%26t_d%3DTransaction%2520%25C2%25A00x66840ed55126364d95bfc249f800381a39a1b085b17138019503048154023085%250A%250A% …

wallet-ethereum.net

---

_data/data.yaml

Fake airdrop - asking for private keys

statustoken.im

---

_data/data.yaml

Added status token address: 0x685445fE51B31790538890A6468851AfbF7a0519

statustoken.im address

---

_data/data.yaml

Reported: https://twitter.com/AragonProject/status/902062846980317184

Aragon.one

---

_data/data.yaml

https://www.reddit.com/r/CryptoMarkets/comments/6wmod5/bittrex_phishing_alert_pls_upvote/

bittrex.ltd

---

_data/data.yaml

omise-go.io

---

_data/data.yaml

Reported on etherscan as one of the addresses for this scam: https://etherscan.io/address/0x2268751eafc860781074d25f4bd10ded480310b9#comments

district0x.net address

---

_data/data.yaml

Reported on this tx: https://etherscan.io/tx/0xc9164b0e9d03657b78735be5a3132ef0d51bbb7e91ef9780b0b1861875dbbafd#comments

monetha-crowdsale.com address

---

_data/data.yaml

see https://github.com/409H/EtherAddressLookup/commit/4ae19c91decf1b39fdce435996575143bb365afd

monetha.me

---

_data/data.yaml

see: https://github.com/MyEtherWallet/ethereum-lists/pull/46

bllttriex.com

---

_data/data.yaml

see https://github.com/409H/EtherAddressLookup/commit/475315391418d3721da69f5fdf5066aaff889a4c

etnerscan.io

---

_data/data.yaml

see https://github.com/409H/EtherAddressLookup/commit/5012c911fef8f9aaad072c2af67c1ecb7d48cf66

golem-network.com

---

_data/data.yaml

see https://github.com/409H/EtherAddressLookup/commit/12e75d02ce6e4b5a541faf7e763b746b6f288df4

etherdelta.gilthub.io

---

_data/data.yaml

dmarket.ltd

---

_data/data.yaml

see https://github.com/409H/EtherAddressLookup/commit/813839405bef992fceba8cde78c684c3f20c19a5

kinico.net

---

_data/data.yaml

see https://github.com/409H/EtherAddressLookup/commit/5d75e826838b367567cde1a4523cf6017cb986de

herotoken.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/c323075431f5dddd5beec3dff7bc71aaae22465b

etherdelta.githulb.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d43529689c30e2ae3f2992926447685aa0fad377

atlant.solutions and aventus.group

---

_data/scams.yaml

aventus.pro

---

_data/scams.yaml

vlberate.io

---

_data/scams.yaml

see https://github.com/MetaMask/eth-phishing-detect/pull/52

monetha.ltd

---

_data/scams.yaml

kirkik.com

---

_data/scams.yaml

Fake etherdelta site, stealing private keys

etherdelta.gitnub.io

---

_data/scams.yaml

see https://github.com/MetaMask/eth-phishing-detect/pull/55
The address associated with it was my deposit address. Hoping to use in the future to track to their main address.

the-ether.pro

---

_data/scams.yaml

see https://github.com/MyEtherWallet/ethereum-lists/pull/68

etherdelta.one

---

_data/scams.yaml

rivetzintl.org

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/dad4ed6fcb12dea8c6aade461bd808ef29cce723

omisego.com.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/3582c7ab8032ead20c988522f1e9caf7ce8f8fbf

qtum-token.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/bd06717828d01a1c4c951747ace2a1235ce05a95

linknetwork.co

---

_data/scams.yaml

fake etherdelta, stealing private keys

ethedelta.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/6b2f1b0f2c05faab5a797b0a4a0651762a685c6a

kin-crowdsale.com & kin-klk.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/118700099ef49d3273939d2eb784af174b169269

xn--bttrex-bwa.com

---

_data/scams.yaml

Fake red-pulse.com crowdsale site

red-pulse.tech

---

_data/scams.yaml

red-pulse.tech address

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/77abd75842e4f6829b9bb09bf72dfc0262d47615

ico-nexus.social

---

_data/scams.yaml

fake etherdeltas stealing private keys

ethrdelta.github.io & etherdellta.com

---

_data/scams.yaml

xn--bittrx-mva.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/495a39c901b6f0544795ce7ecd208b2ef70cd1dc

coinbase.com.eslogin.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/c927695ad75b13e2283aa9b617d1d48a6c7b0bf4

enigma-tokens.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/e9f4b1eecca8bcd1a35f6de27e2c1277cb55f247

omise-go.me

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/73f80a7387c60d413d83297f1df8be14b34d962f

tokensale.kyber.digital

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d40eb2ee0eb9a16b7a1af3beca29654ba16f3514

pyro0.github.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/e937b109d9460b83b9d8726c31b720609d0b7606

kyber-network.co

---

_data/scams.yaml

see  https://github.com/409H/EtherAddressLookup/commit/2cec462ded5c89aba745572c8e08363ea8bbe76d

kin.kikpro.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/7de8808cc6ba7779cddd9090169acbba5816bed2

kvnuke.github.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/7cd916a241ae477c46fd4f8b8ac7808b44b7f144

myetherwalletconfirm.com

---

_data/scams.yaml

Fake MEW, stealing private keys with `log.php`

myetherwallet-confirm.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/cbbe867119d7feb0a571b31c4a3b46e9c32f5861

kybernet.network

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/3255671535632c5620cb24c0ef7f8276bfe29736

chainlink.tech

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/70a43ccbe5003f4b4b0b4cf261f5e461407a1b96

change-bank.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/674eca83e7b9322960efa1ac26127a4b1e5cc611

myetherwalletcontract.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/b3eec52e52599524a8e2aace681a243a2323de11

myetherwalletsingin.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d0a5cf7a58e0d279e3eff38de51ab3ce910d66a1

charge-bank.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/137e540c80c8e98881ef6b6ae1ef894d665f5950

change-bank.org

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/281dee2c149055bb86cafccaba001273efd9c885

0xtoken.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/4e79264c1bfe7101b619a96b51320f919a65db01

shapesshift.io

---

_data/scams.yaml

Fake MEW - blocked by metamask and eal with leven and fuzzy search

myetheriwallet.com

---

_data/scams.yaml

see https://github.com/MetaMask/eth-phishing-detect/pull/117

smartcontractlink.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/62e80242be8c71ce83d36cae77d692d0487d1094

myetherwallet-singin.com

---

_data/scams.yaml

Fake Centra Tech crowdsale site - paid Google Ad

centra.credit

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/c48837ffc73e1573dafd92b506a936f20b83e826

air-token.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/66b800a609d6ca1e6bae4faa0d749b8f6342f740

icon.community

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/cda8026247e5024f2a8abceb340d543c0b30c1a1

smartcontract.live

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/b29262132206b74412ba48d9f9198d7b13251054

centra.vip

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/73171a25e8754470579fb60d29c4d2bac91ee6c7

iconn.foundation

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d2392a40808c34c4bf490dcb97b71895cbc99926

bitfienex.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/6ae82c274d6a7af5dc5c814f2fcb77033f19ef29

bitfinex.com.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/10a84cb594fd29027a6d25e770f32e558df2d5c1

happy-coin.org

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/10d0e0745e4dd7cd87e2a01213a542b04c5425e9

cobinhood.org

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d283e184c148fc0bbaa71563585937e80d330592

reall.markets

---

_data/scams.yaml

Fake MEW - stealing private keys with log.php

myetherwalletws.com

---

_data/scams.yaml

Fake MEW - stealing private keys with log.php

myetherwalletntw.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/18342e0c1064931bc1fca5b1e48f881af4245379

myethereumwalletntw.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/384a2760ac2e87584bb763143d6707452295277d

omisegotoken.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/3a3b23a68605fa1851869eb519027eb194f53f61

myetherwalletlogin.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/9bcdc2e60c87bed32b92379757a38c19fe4ce446

coinrbase.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/68d7b983fcd7e446ad22f7c8315c60fc7cbedb90

myetherumwalletview.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/54239e1e6e478802d6032584193d729412b616f1

eventchain.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/39ed30840f7e4d5f1e954762bdef4d5a9b568418

myetherwallets.co

---

_data/scams.yaml

Fake MEW, stealing private keys with `validate.php`

ethewallet.com

---

_data/scams.yaml

myetherwallet.com.vc

---

_data/scams.yaml

Fake MEW, stealing private keys with `log.php`

myetherwallets.info

---

_data/scams.yaml

Fake MEW, stealing keys with `form_action.php` then redirecting you to the legit MEW

myetherwallet.com.ailogin.me

---

_data/scams.yaml

Fake MEW, stealing private keys with `index1.php`

myetherwallets.cc

---

_data/scams.yaml

Fake MEW, stealing keys with `index1.php`

myetherwallets.us

---

_data/scams.yaml

Fake MEW, stealing private keys with `log.php`

myetherwalletsignin.com

---

_data/scams.yaml

Fake https://cindicator.com/ crowdsale site
address: 0x17BD6f815fB71a77dc20E12177c4d763A3f67632

cindicator.pro

---

_data/scams.yaml

Fake MEW - stealing private keys with `h.php`

myetherwallet.money

---

_data/scams.yaml

Phishing for e-mail passwords to beat 2FA to pwn Coinbase accounts

coinkbase.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/c0dfbb6185c974daa8e249844178df228f104747

ibittreix.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/66278294ee29b2d6f5eba9a33e5cf9c1b504984e

shiapeshift.in & shapeshifth.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d73c76d3b5578f1cc7e7996d9dae6b0d7a83de4e

wallet-ethereum.org

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/pull/111

request-network.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/8ef214ced1697f192a154119f07d4de2d6e3958e

real-markets.io

---

_data/scams.yaml

Fake MEW - stealing private keys with validate.php

myelheriwallet.com

---

_data/scams.yaml

Fake MEW - stealing private keys with decrypt?key=xxx

myetherermwallet.com

---

_data/scams.yaml

myethwallct.com

---

_data/scams.yaml

myetheremwallet.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/c0cf77380c664efe8d12fd8bfa1ac493423abc1d

myetherwallet-secure.com

---

_data/scams.yaml

myetherwalletto.com

---

_data/scams.yaml

myetherwalletio.com

---

_data/scams.yaml

Fake MEW, stealing private keys with mail-area2.php

miyetherwallet.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/b45a551e14e59ebdbd6a18ff4e63c2ba3f8ba4d6

myetherwallett.neocities.org

---

_data/scams.yaml

see https://github.com/MetaMask/eth-phishing-detect/pull/156

cobinhood.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/2c22e5266008d3fbdd98dc88e91c744bebbf1c3d

etnerparty.io

---

_data/scams.yaml

etherdetla.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/3ddafe44b0f65349fd58e2f37e78c47a6493bc09

centra-token.com

---

_data/scams.yaml

myetherwalletie.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/3eda5b3e3562f5b5f85471a80ebf807cdc50bcba

district0x.tech

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/edf0adf9a1cef4033c048c34de8659469fc07105

mywetherwailiet.com & myyethwallet.ml

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/7ef518620466a2e15dc11e92a3457c09663bbc1a

golem-network.net

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/7473697f8a35dce893cbbe6e6270af2c4609f551

tenxwallet.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/4ed1430418db5b271e66b3b92723ed996bac392b

enjincoin.sale

---

_data/scams.yaml

Fake MEW, stealing private keys with log.php (bitcoin-tips.com)
https://urlscan.io/result/e5ad75a6-6c07-4d44-a12d-c802c253f0dd#summary (myetherwlallet.com)
https://urlscan.io/result/ec2304ff-47e5-4f89-9ec7-e950f74ad594#summary (bitcoin-tips.com)
> We are happy to announce that we are running a new bounty campaign. For every 1 ETH in your Myetherwallet.com wallet, you will receive 0.1 ETH free. ( EX : you own 1000 ETH, you receive 100 ETH free)
> 
> Please login to https://www.myetherwlallet.com/#view-wallet-info to participate in the bounty campaign
> 
> Thank you,
> 
> The Ethereum DEV Tea

myetherwlallet.com

---

_data/scams.yaml

https://urlscan.io/result/4a1b8bdf-bd34-42f2-87d8-38eaca0806db#summary

myetherwalletiy.com

---

run.js

[WIP] Added logic to fix the pagination issue of NaN

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/36da56859d167f069bfaa8285227d3cd34b61c2b

wanchain.network

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/824c47aa8cbd88adcadd527277bd2b8357207a8c

enijncoin.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d1f2115b6713e8f2dc5a4b56cdb0676b4784dbd4

smartlands.tech

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/453fbcad97b737c298484cbbbfdea00e1ed961f6

enjincoin.me

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/aea773f3504e40f64d27dd02bb9ab2fa14d31844

etherparty.in

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/fb044445c267e4ba020e7d9d0d983df8e170d924

wanchains.org

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/bd1e71664a79005606a276f80f1c6cb4104f30d9

warchain.org

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/47744140eec3c77bc052b1f5d009377e105e7f38

shapeshiff.io

---

_data/scams.yaml

https://urlscan.io/result/a2fdc1c1-a68c-48d1-ae0c-f78c31a5a915#summary

myetherwalletip.com

---

_data/scams.yaml

see https://github.com/MetaMask/eth-phishing-detect/pull/179

myethereumwallet.su

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/0a25fca93dd14c334af1d364d6ebf03b35b643bf

xn--enjncoin-41a.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/89ccfd7185ad29a70c63c0e12d5949262854e71e

omisegoairdrop.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/90e8459c306adb26e4420c65d2f9154bc1b8bdce

vvanchain.org

---

_static/js/search.js
run.js

* You can now search a domain and a public address
* If a domain is present, it will go to the domain page (ie: http://localhost:8080/scam/2)
* If an address is present, it will go to the address page (ie: http://localhost:8080/address/0xD0cC2B24980CBCCA47EF755Da88B220a82291407)

Search view

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/c2d16cb3aab456f9912f51b2d0ba8386bae1aa2c

numerai-token.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/741df4e4f94244c6f8cd3628d9e68bc6414f7b15

paypie.net & paypie.tech

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/a2c1884c9295ce261c43b01147a838831e8ed0fd

upfirng.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/bf67403cab8f475c3b112e40d0100cd4348eae95

myethereumwallct.com

---

_layouts/scam.html
package-lock.json
package.json
run.js

This will show if the domain is blocked by MetaMask or not on `/scam/2172`, using this: https://github.com/MetaMask/eth-phishing-detect

Show MetaMask status

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/0077efb98680978e12231441a6193cdeaaca5561

security-steemit.com.mx

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/e2bfa2ba30d7e890ea75142c8eecd96eada67c5d

cryptoinsidenews.com

---

_data/legit_urls.yaml

Swapy Network is a project from Credit Dream, Inc doing an ICO in couple weeks. More info can be found at https://www.swapy.network or https://www.github.com/swapynetwork. The project was one of the 5 finalists at Consensus 2017 Pitch Competition (May 2017, https://www.coindesk.com/meet-5-finalists-coindesks-consensus-2017-startup-contest/) and one of the 3 finalists at SingularityU Global Grand Challenges Awards 2017 (Prosperity Track, August 2017, https://su.org/summits/su-global-summit/global-grand-challenge-awards/).

Whitelisting Swapy Network official domain

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/5e797ad8d534136985771c74fc1be5b47755d451

www-enigma.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/pull/120

www-request.network

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/65786b415488046b5fd86bb09af5999283d6e554#diff-7d2c56a4f7ef38903da8c53848c4efd6

airswap.in airswap.cc airswaptoken.com

---

_data/scams.yaml

Related to www-enigma.co (https://github.com/MrLuit/EtherScamDB/pull/185)
Fake Enigma site redirects you to MEW to try and steal private keys.
(from www-enigma.co)
```
<div class="modal-body" style="display: flex; flex-direction: column;">
<p>
So as many of you have already requested - here they are! <strong>Your tokens are here!</strong>
<br><br> Please follow these instructions to claim your tokens.
<strong>There are two mandatory steps that you must take:</strong>
<br><br>
<strong>Step 1</strong> - Send 0 (it's a zero) ETH to our pre-sale contract address from your wallet address that you used to participate in presale<br>
<strong>Step 2</strong> - Create a custom token on your wallet
<br><br> Directions below are for the MyEtherWallet, the wallet that was recommended for the token …
```

myetnenwallet.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/eb9630fb4206270ec9ba489f3452eaf1000f165a

xn--bitrex-k17b.com

---

_data/scams.yaml

Sending email (from no-reply@myehterwallet.com) with link to phishing site.

myehterwailet.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/dff1c3c1b1976273309343cb6fd9a094346f1f69

enjincoin.pw

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/f15b52f829461688ed5f80e9fe028035f1fc641a

myewerthwalliet.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/4b73e36f7aaef111de6faa4e1ed0c16031f4d979

first-eth.info

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/e77ac358a4cbb9974baa7cc25e57d243b491c9b3

binancie.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/7aa75fd44e25db90ad86f79a00ec36a57e54c56a

requestnetwork.live

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/ab7a81f300c61b3edce7016f61b065e2326d44c2

request-network.net

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/92b0b8ab54249481d23918ae71cb8f397f3d5f2d

polkodot.network

---

_data/scams.yaml

see https://github.com/MyEtherWallet/ethereum-lists/pull/212

slack.com.ru

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/34578f899c3630582b98b26b28a46185dcc81f37

omegaone.co

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/83b23a1163c63053010b13d31fc17426215a09bc

myetherwaiiett.com + others

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/pull/126

stormxtoken.com

---

_data/scams.yaml

see https://github.com/MyEtherWallet/ethereum-lists/pull/216/

myetherwalletverify.info

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/2fa968eae5b85cf8488934b848b4a5a1190e2e09
see https://github.com/409H/EtherAddressLookup/commit/e0a4a4e6746e33dcaade59ef0c2c76d500ef7520

ralden.network

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/212da24e781a3c2e8175758de1a50824cb8be999

privatix.live

---

_data/scams.yaml

Fake MEW
https://github.com/MyEtherWallet/ethereum-lists/pull/222
https://urlscan.io/result/bb174811-8647-4e86-908d-c7a3ca25b42b#summary

rnyetherwallet.pw

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/cbe51a4d56ec11d5199d574ee176e93be5b88693

storrntoken.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/dc8e8f0b3e6564d9bd5894cbd8b3fb15118d76c8

stormtokens.net

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/b974e2941d3270926d976a27a0fbb7afc8d54d88

myetereumwallet.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/e13a43975e8582b852d37f085e8ae3322b7439df

stormstoken.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/66becf807bced0f0b7266ae2c52099a8f31019d8

raiden.online

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/3336d0882b189451d9f1d6e036b3de6f221db196

stormtoken.cc

---

_data/scams.yaml

privatix.top is impersonating to privatix.io during their ICO
https://urlscan.io/result/844b1f8f-fb0f-4220-baa8-0692823c7fad#summary

Update scams.yaml with privatix.top

---

_data/scams.yaml

impersonating to privatix.io, the 5th attack in the last few days. Similar wallet like privatix.top
https://urlscan.io/result/499b0170-b71d-4ec4-b1a4-8382025c5a83#summary
https://urlscan.io/result/3c34446e-d336-4275-94db-9f780e4dca23#summary

Update scams.yaml with privatix.me

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/d2fc75a2eff1a3d9170286f3bef8e821c5807d4a

ripiocerdit.network

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/01770d8f5e206a1c678283776333a527ef072793

shapishift.io

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/14210efc9c184d0a6e8bf37784b5c16c51e21996

bittrex.cash

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/a83ec5e79e137a1bf710a7234403cf6db7f89bf7

block-v.io & everything else

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/c227bd88ceb7638606672fcee5999e9a0f3b001e

ripiocredits.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/5860d8e746096f898dec29637e798ae5d798e51f

ripiocredit.net

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/422f4515d353264de8d282b775b97e33cda6e4cd

myetherwallat.services

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/pull/141

senstoken.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/6e5f2fc8e896a7ce49b880c566bc034b41380a2a

reqest.network

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/1fe00f4a2845edcf400c28b6e81cc82b6a28fce8

riaden.network

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/b268816581a63690e92189552f06bbdd3f18c269

ripiocreditnetwork.co

---

_data/scams.yaml

https://urlscan.io/result/415ec966-3199-4955-9dab-d3878b0cdc42#summary
The second one is currently just redirecting the original site

Update with 2 spoofed MEW addresses

---

_data/scams.yaml

Stealing private keys with send.php
see https://urlscan.io/result/c5531405-2665-45eb-9da7-f425ec90658f/#summary

mycthewallet.com

---

_data/scams.yaml

https://urlscan.io/result/a97d9177-8a36-4b77-bd82-b6842aaf2950#summary

Adding a spoofed MEW address

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/pull/149

dentacoin.in

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/160a8630eaa66c504809abe711435eaeaadab01e

myetlherwa11et.com

---

_data/scams.yaml

see https://github.com/409H/EtherAddressLookup/commit/18404845d77b5352ecfc5894478ca66719c2130e
Fake ripio credit crowdsale site
https://urlscan.io/result/c14c4855-84d0-4baf-af60-ea193049502a#summary
address: 0xa6B60dd3bE491aAfE5AbA8622b35C0eAd608D3FD

ripiocredlt.network + more

---

_data/scams.yaml

Fake Coinbase site
https://urlscan.io/result/59136fd8-93b3-4465-8b92-b3dce26bfc24#summary

kraken-wallet.com

---

_data/scams.yaml

Fake metalpay site
https://urlscan.io/result/17c406bd-9348-4140-a480-bab024aa3797/#summary

metallpay.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/64ebdfc5-e444-4b78-b2f3-8d1fb2270276#summary
https://twitter.com/phishingalert/status/926021055554248704

myethierwallet.org

---

_data/scams.yaml

Fake Bittrex site, phishing for login details
https://urlscan.io/result/5923b941-af71-4301-bf0e-1d4aa25bfa13#summary

bittrexy.com

---

_data/scams.yaml

Fake metalpay crowdsale site
https://urlscan.io/result/de4363ef-09da-4493-a3ad-fd74c4d82a84#summary

mettalpay.com

---

_data/scams.yaml

https://urlscan.io/result/981a1ac8-5871-4280-80d1-b52323d4063d#summary myetherwalletjson.com
https://urlscan.io/result/dcaf085b-d2da-49fc-9da7-dde283e12dc7#summary xn--metherwallet-1vc.com
https://github.com/MyEtherWallet/ethereum-lists/pull/255

myetherwalletjson.com xn--metherwallet-1vc.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/bb662741-e4fc-405c-af1a-7926425920b9#summary

myetherwalletext.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/b22691c2-aad6-477d-90c6-32b9c8927048#summary

myetherwalletmist.com

---

_data/scams.yaml

Fake airdrop site, asking for private keys
https://urlscan.io/result/bcde35d7-13af-4c5b-a5de-a4854aacd34a#summary

linksmartcontract.com + more

---

_data/scams.yaml

Fake Changelly site
https://urlscan.io/result/dc706e3f-1b33-47d0-afb1-b8569978b3ae#summary

changellyl.net + friends

---

_data/scams.yaml

Fake Quantstamp crowdsale site
https://urlscan.io/result/c190227b-a747-4010-9d3a-3493d2e5e433/#summary
address: 0xfbc79A80ffA84253611e8f9A82F18e9E93Ceee81

quantstamp.com.co + friends

---

_data/scams.yaml

Fake storm token crowdsale site.
https://urlscan.io/result/c650e979-3996-40ff-a66c-dbd60982ea6e#summary
address: 0xF0Fc2d4d550253d8C165C599E0cCCf221c7eb7b5

storm-token.com

---

_data/scams.yaml

Fake Storm Token crowdsale site
https://urlscan.io/result/7bef8e6f-b901-406b-b112-2eeb873f70b6#summary
https://urlscan.io/result/87a6fe1d-58b1-43a4-8917-034be9da20c5#summary
address: 0x316b3b83c33B20249B61DEd124F2620d8E823793

stormtoken.co

---

_data/scams.yaml

Fake Quanstamp crowdsale site
https://urlscan.io/result/35b37b3f-392e-4152-96af-ce856ed449fc#summary
https://urlscan.io/result/70cd8b03-f720-4a80-bccf-056d889f6416#summary
address: 0x0ae775637e63Fa95855246Fd82e96802D05883Fc

xn--quanttamp-42b.com

---

_data/scams.yaml

Fake Storm token crowdsale site
https://urlscan.io/result/13dfa9d8-bdce-4e17-b225-d3d2dfa8c47f/#summary
https://urlscan.io/result/691fa00d-77d3-4ac8-898d-706afd27c229#summary
https://urlscan.io/result/cbd0314a-2913-40f2-82fd-c9aa44e23096#summary

stormltoken.com

---

_data/scams.yaml

Fake Salt Lending aidrop site, asking for private keys
https://urlscan.io/result/6f2c0c64-a509-46b1-8a23-87a66a264319#summary

saltending.com + more

---

_data/scams.yaml

Fake storm token crowdsale site
https://urlscan.io/result/ec82a2e6-25b6-4902-9a2e-a6492d4dd466#summary
https://urlscan.io/result/219cddf8-d69b-4df0-b431-c3671c8462fc#summary
address: 0xA3e52a23060cCDfE186822b52BF60A07451e094e

stormtoken.eu

---

_data/scams.yaml

Fake LINK airdrop site, asking for private keys
https://urlscan.io/result/79fa32c7-8a2f-474c-aff5-14c988e4bd1a#summary

WIP: chainlinksmartcontract.com

---

_data/scams.yaml

Fake Japanese exchange
https://urlscan.io/result/48f9df8a-880e-4c32-aea3-f1ae72e8cba8/#summary

bitflyerjp.com

---

_data/scams.yaml

Fake OmiseGo airdrop site
https://urlscan.io/result/ae6d1a87-85f1-48fa-8f7b-c633c6d8d376#summary

omisegoairdrop.net

---

_data/scams.yaml

https://urlscan.io/result/314a4c9b-36b5-47fc-b065-cc11e7158271#summary

Adding spectre-ai.org

---

_data/scams.yaml

Fake datum.network crowdsale site
https://urlscan.io/result/37d1bb97-63f6-4291-b5f7-3c223c6a1d33#summary
address: 0x2804e8B4c04c655376D18aDA84d46fC345240E0A

datum.sale

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/cb376c5f-c8e5-447a-bbc7-70e433e5a1d8#summary

myetherwalletfork.com

---

_data/scams.yaml

Fake tzero crowdsale site
https://urlscan.io/result/cb46d2a2-1b63-46bc-9bce-ada4f485c08a#summary
https://urlscan.io/result/66453540-7500-4502-bddf-8eb9fd0e9466#summary
address:  0xe54659243F8542d6ABfd15bbff69f62465786756

t-zero.org + friends

---

_data/scams.yaml

https://urlscan.io/result/88577102-7b6e-4447-b135-fb3e5b0cd004#summary

Adding another wallet address to t-zero.org

---

_data/scams.yaml

https://urlscan.io/result/70b00db7-8b75-4b50-81b9-cc4c5daf72c6#summary
no wallet address yet

adding spectre-ai.net

---

_data/scams.yaml

https://urlscan.io/result/969adab2-f805-4ab6-b33d-f8e2e3cd65cc#summary

adding tzero.pw

---

_data/scams.yaml

https://urlscan.io/result/3928e538-2061-429a-8111-e59a86975ab1#summary

adding spectre.site

---

_data/scams.yaml

https://urlscan.io/result/acb85963-c149-479a-98f0-340837635646#summary

adding ico-tzero.com

---

_data/scams.yaml

Fake blockstack.org crowdsale site
https://urlscan.io/result/5f773378-2f8b-4a35-bc32-ca8e4940e1dc/#summary
https://urlscan.io/result/36d8b8c2-7cd6-4841-ad92-68ca4f003f57#summary
```
```

blockstack.network

---

_data/scams.yaml

https://urlscan.io/result/0e7e5cb4-03f8-4289-a72e-a271612f29ba#summary

adding tzero.website

---

_data/scams.yaml

This broke everything when trying to update the status list 😅

Remove space

---

_data/scams.yaml

https://urlscan.io/result/ac406c92-fbdd-4b01-9063-790f44f76b5e#summary

adding tzero-ico.com

---

_data/scams.yaml

https://urlscan.io/result/fd49ea31-eee5-4691-a553-a0431499d2c2#summary

Added xn--metherwalet-ns8ez1g.com

---

_data/scams.yaml

https://urlscan.io/result/b8bd6876-a85b-4c98-bed5-f0438d276e87#summary

adding t0-ico.com

---

_data/scams.yaml

Fake Bittrex
https://urlscan.io/result/56c10945-8971-467a-af79-4f0d1924ccea#summary

 bittrex.one + more

---

_data/scams.yaml

Fake Shapeshift site
https://urlscan.io/result/14a72443-f415-40a1-b870-fb5ab84f83a2#summary

shape-shift.io

---

_data/scams.yaml

https://urlscan.io/result/e5830d20-a33b-464d-b946-2168a7f21170#summary

adding sirinlabs.website

---

_data/scams.yaml

Fake Oracles crowdsale site
https://urlscan.io/result/01a9cd9f-480c-41ec-bb63-1208917ac52c#summary
address: 0x1447b1cB205158D98FdBd312b37ed9dd1481fB62

oracls.network

---

_data/scams.yaml

Fake airdrop site, asking for private keys
https://urlscan.io/result/7a1b7f86-655e-44bb-92ff-cb783fffb999#summary
https://urlscan.io/result/735ed35d-e63a-4e3f-8690-653d49c46069#summary

requestt.network

---

_data/scams.yaml

Fake Coinbase
https://urlscan.io/result/48d385db-a7a7-4f55-a358-744dacb034c5#summary

xn--coinbas-pya.com

---

_data/scams.yaml

Fake Bitstamp site
https://urlscan.io/result/bab17d77-51b8-49cc-9ef9-ed817b7c3f7f#summary
https://urlscan.io/result/e7230925-4e36-4969-b513-beab8488188f#summary
https://twitter.com/Bitstamp/status/933401197171675136

bitstannp.net

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/7ee420a0-9684-467f-83cc-893f31160c8a#summary
https://twitter.com/phishingalert/status/933618502178672640

xn--myetherwllet-0cb.com

---

_data/scams.yaml

Fake envion crowdsale site
https://urlscan.io/result/842e7ee1-368b-43a4-856d-d965b20395d5#summary
address: 0x25CE2252a80c1c4FDf12FD9c608858c23b3094Ef

envoin.org

---

_data/scams.yaml

MyEtherWallet/ethereum-lists#264
https://urlscan.io/result/fdd0504b-88f6-4520-a73b-9b37a5b39544#summary

coinbasenews.co.uk & xn--metherwallet-hmb.com

---

_data/scams.yaml

Fake shapeshift
https://urlscan.io/result/1b83b66d-c0b2-4c06-89f2-7507cdfa861f#summary
https://twitter.com/jmoconnor415/status/933979375686569985

shapeshlft.com

---

_data/scams.yaml

https://urlscan.io/result/0d5493a0-dae4-41f5-91d3-40cc5ed80244#summary

adding gladius.im (impersonating to gladius.io)

---

_data/scams.yaml

Fake wacoin token site
https://urlscan.io/result/5aeb1b47-37a0-4c0d-a19a-82d9eccbf8af/#summary
https://urlscan.io/result/f3652892-96d6-4ceb-bc91-ac3d2dc82f6d#summary
address:  0x57DCF20135B0Cb9D167e8ebFe13b84bfD67645ed

wabitoken.com

---

_data/scams.yaml

Fake gizer.io crowdsale site
https://urlscan.io/result/0f13cf1f-7352-4bce-87d2-677617d0c2cf/#summary
address; 0xa2A3a8e4a1877da1C913df7591ac0D72f27D4510

tokensale.gizer.in

---

_data/scams.yaml

Reported several times by numerous users

myetherwallett.com address

---

_data/scams.yaml

https://urlscan.io/result/29662e7b-696c-4e60-8758-ee00116c9e38#summary

adding t0zero.com

---

_data/scams.yaml

Fake WaBi crowdsale site
https://urlscan.io/result/cbcaea66-9667-4c14-8d1f-bc13d208187d#summary
https://urlscan.io/result/2b61857b-faf5-40f9-9052-64ba0611a85d#summary
address:  0x1cea7999fdafe5d156952ebf1816e8aa67a5485e

ico-wacoin.com + more

---

_data/scams.yaml

https://urlscan.io/result/67aa729b-10fe-4810-b12c-27e44b034943#summary

adding bitclaive.com

---

_data/scams.yaml

Fake Quantstamp site
https://urlscan.io/result/e1b85148-f6f3-406d-a92f-3be9565c7f15/#summary

qauntstanp.com

---

_data/scams.yaml

https://urlscan.io/result/c202ffaa-a66d-4ded-b7d1-72e45fde914e#summary

added gladius.ws (impersonating to gladius.io)

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/e5db7d76-5284-4aea-ae17-cb442d9e2d1f#summary
https://twitter.com/phishingalert/status/936187042823835650

myerherwalet.com

---

_data/scams.yaml

Fake power ledger airdrop
https://urlscan.io/result/4df18746-9f33-4cc6-ad3e-1d1f6580e11d#summary
https://urlscan.io/result/6dba7c2c-3da6-4228-8866-510c7f1a6f48#summary

powerrledger.com

---

_data/scams.yaml

https://urlscan.io/result/29e08052-f785-48ae-b55e-3df0968eb96d#summary

added wallet address for gladius.ws

---

_data/scams.yaml

Fake Bittrex
https://urlscan.io/result/11c8822b-68ad-41db-aac5-a0e0084b36ef#summary

xn--btrex-b4a.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/e6a26981-77de-4193-baf0-3d023badc484#summary

myethlerwallet.eu

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/8a94914f-4410-4617-b7a2-cd37c0cea82f#summary

xn--myethrwllet-2kb3p.com

---

_data/scams.yaml

Fake Raiden network site
https://urlscan.io/result/c38daece-d868-4f02-bda6-3e5cb967ae0f/#summary

raiden-network.org

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/7fc33d97-f5df-4585-9666-a14a59141e20#summary
https://twitter.com/phishingalert/status/937976451869048832

xn--myeherwalle-vici.com

---

_data/scams.yaml

Fake gameflip crowdsale site
https://urlscan.io/result/a2130c13-40a8-4f1b-8857-6745e85699f4#summary
https://urlscan.io/result/afbca6cd-2a54-430a-81d4-ecffc3f8a8a5#summary
address 0x9D0b8447f16d6bC1de2B52d63e9c487bD778a91D

tokensale.gamefllp.com

---

_data/scams.yaml

Fake hellobloom crowdsale site
https://urlscan.io/result/cd1449bc-1503-43a9-afe0-e2be18e1cbc8/#summary
address: 0x51DcD13361C5D921D2C4818e419011301e7BE34e

hellobloom.me

---

_data/scams.yaml

Fake blockchain.info
https://urlscan.io/result/4a7872ed-5151-4a55-ae3b-c68281d294a4#summary

superbitcoin-blockchain.info + more

---

_data/scams.yaml

Fake propsproject token sale site
https://urlscan.io/result/532d9509-aa08-4031-9595-9a2a7d15bda9/#summary
https://urlscan.io/result/753387a0-349a-499c-a8ca-36d75554453e/#summary
address: 0x57DCF20135B0Cb9D167e8ebFe13b84bfD67645ed

propsproject.tech

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/c97c9fff-91e3-4b7c-aa15-ae4adc464a25#summary

xn--myetherwllet-fnb.com

---

_data/scams.yaml

https://urlscan.io/result/1198af56-b7b9-47d1-bbcc-4fa0cfb522ce#summary

add envlon.org

---

_data/scams.yaml

https://urlscan.io/result/c70461e2-d1f7-4bdb-aa85-175891bf8c74/#summary

spectivvr.org

---

_data/scams.yaml

https://urlscan.io/result/99ab2aef-e4d8-4934-a576-98438b864c42#summary

add xn--envon-1sa.org

---

_data/scams.yaml

Fake Ethereum site with a web wallet
https://urlscan.io/result/88665b33-5f95-4269-a321-b59a230627f3#summary
https://urlscan.io/result/528ef19b-b5a1-41ee-a85e-7eff59c341ed#summary

ethereumchain.info

---

_data/scams.yaml

Fake bitstamp
https://twitter.com/switchingtoguns/status/940661516558323712
https://urlscan.io/result/a0391587-c9b1-4f10-ad9c-c17f29bf8bee#summary

xn--btstamp-rfb.net

---

_data/scams.yaml

Fake Envion crowdsale site
https://urlscan.io/result/54502e08-316f-4118-b14d-ae7d636c8582/#summary
https://urlscan.io/result/88fc09df-a36b-488a-9cd7-8439bdac3e71#summary
address: 0x8c9d299cc3C2111499416Cf4E3677328486cFac2

envion.co + more

---

_data/scams.yaml

Fake paxful site
https://urlscan.io/result/c05e3843-1323-4503-b1ff-7857bd2a0f64/#summary
https://twitter.com/paxful/status/942403508271288320
https://twitter.com/intent/user?user_id=912580298205888512

paxful.com.ng

---

_data/scams.yaml

Fake airdrop site asking for private keys
https://urlscan.io/result/89324ff9-1e5f-4fe8-a05b-1207176a3694/#summary
https://urlscan.io/result/e3b98da5-0747-4089-b71b-c193a044cd5c/#summary

tronlab.co

---

_data/scams.yaml

https://urlscan.io/result/67b537f3-19c7-405a-84e1-406135d84baa#summary

adds sirinslabs[.]com

---

_data/scams.yaml

Asking for private keys
see https://github.com/MetaMask/eth-phishing-detect/pull/448

ethtools.com + more

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/b19f7961-645e-4180-bd37-828b8aac9ffc#summary

xn--yeterwallet-bm8ewn.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/2caed5d1-16d6-47a8-a4a0-870d442cf760#summary

myetherwalletet.com

---

_data/scams.yaml

https://urlscan.io/result/3eb0084e-1c8a-4223-8818-8173ee876366#summary

add envione[.]org

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/4970f193-6a65-41be-98f5-e05e259d7ba8#summary

xn--myetewallet-cm8e5y.com + more

---

_data/scams.yaml

Fake Shapeshift
https://urlscan.io/result/a514cd6f-0cba-4f96-a56d-c1247e676a21#summary

xn--hapeshit-ez9c2y.com

---

_data/scams.yaml

https://urlscan.io/result/1c3e11e7-e3de-4840-975c-9f42c9db0003#summary

elherdelta.io

---

_data/scams.yaml

Fake airdrop site asking for private keys
https://urlscan.io/result/dc09f3c5-a2f9-4ac8-bbf9-e06097664119#summary

reqestnetwork.com

---

_data/scams.yaml

Fake wanchain site asking for private keys
https://urlscan.io/result/437cd1e1-1283-4421-8235-d11ad63ec158/#summary
https://urlscan.io/result/6b549936-1c8e-4db4-b1f5-5cc0392ea654#summary
Suspected address: 0x9071322185F6ec582Fe490485aaB21be451713c5

wanchain.tech + more

---

_data/scams.yaml

Fake bluzella crowdsale site
https://urlscan.io/result/573e79be-22e6-4654-8832-6adc1ae1f084/#summary
https://urlscan.io/result/ffcc895a-c38c-4c2a-a14b-e5a35683081b#summary
address: 0xAc82537fae701B2046F62BB718c4857787b0b647

bluzelle.promo and tokensale.bluzelle.promo

---

_data/scams.yaml

Fake cryptokittes
https://urlscan.io/result/11290661-2540-4107-b510-ee0266ff54dd#summary

cloudpetstore.com

---

_data/scams.yaml

tronlab.co & omisegotoken.com address

---

_data/scams.yaml

Fake funfair airdrop site
https://urlscan.io/result/8507d1a4-775c-4df0-b00b-8fc682137018#summary
https://urlscan.io/result/ae2ab0fc-4238-4ed3-be25-3577ddd1ab06#summary
https://urlscan.io/result/ad1f25c4-7075-4d27-94f2-1d2a9da47d5b#summary

funfairtoken.org

---

_data/scams.yaml

Fake bittrex
https://urlscan.io/result/e8969072-0c81-419c-a3d6-47c575aa638d/#summary
see: https://github.com/MetaMask/eth-phishing-detect/pull/617

bittrex.com1987465798.ga

---

_data/scams.yaml

Fake nucleus ico crowdsale site
https://urlscan.io/result/24ed2240-00ed-4686-8285-34e33692f9f7/#summary
https://urlscan.io/result/19881a3b-103d-4783-af39-bafc053c2be7/#summary
address: 0xf962933e44b1DFC771738A034c80D87bDcd96eCC

nucleusico.com

---

_data/scams.yaml

Fake bittrex
https://urlscan.io/result/e9dc91a3-7d31-4641-82c5-ca97eee6280b#summary
https://urlscan.io/result/18720e72-6177-4578-9657-cfad7f631e9d#summary

xn--bittrx-th8b.com

---

_data/scams.yaml

Fake Poloniex. Reported it to SafeBrowsing as well.
https://urlscan.io/result/30b5b50f-673a-4a60-8e0d-7a3b33e8bc6f#summary
https://github.com/MetaMask/eth-phishing-detect/pull/630

xn--polniex-n0a.com

---

_data/scams.yaml

https://urlscan.io/result/328de334-d7b5-402c-8ba3-ad470b1a617e#summary
https://urlscan.io/result/523ada90-2283-4c1c-8897-dda33ffc115f/#summary
https://urlscan.io/result/bf56d7aa-6a78-4666-91b8-b4d358b09a5f#summary

deepbrainchain.co

---

_data/scams.yaml

Fake gifto airdrop site asking for private keys
https://urlscan.io/result/a2780928-1dba-4deb-9e99-ecc199f41b35#summary
https://urlscan.io/result/6ece476c-54dc-43ae-b42a-16b23fd84b26#summary

gifto.tech + more

---

_data/scams.yaml

https://urlscan.io/result/720f6bd4-2706-4c64-9f58-e1f827f5105e#summary

add token-selfkey[.]org

---

_data/scams.yaml

Fake EtherZero website.
https://urlscan.io/result/a4bb5562-ff2e-4dbf-8ea1-26e8aec96eef#summary
https://urlscan.io/result/683900bb-f248-4975-bf7b-6aff9cd81c3f#summary
address: 0xC1dD8Ac971129C8C08333924F58Ff40a50b8bb9a

ethzero-wallet.org

---

_data/scams.yaml

Fake digitexfutures.com ICO website.
https://urlscan.io/result/4afde7c3-11b4-45b8-a319-b15cfb21ec6f#summary
https://urlscan.io/result/57accdb3-0742-4cf9-8cfc-acd3113c2148/#summary

digitexftures.com

---

_data/scams.yaml

Fake Etherzero domain asking for seed phrases and sending them off to `POST https://marketcsgo.ru/admin/bulbikmain.php`
https://urlscan.io/result/9d602c7f-e45b-4b34-98c0-2c5d80063ad6/#summary

etherzeroclaim.com

---

_data/scams.yaml

https://urlscan.io/result/efe9998a-ed13-417a-b933-580beb504e46#summary

icoselfkey[.]org

---

_data/scams.yaml

https://urlscan.io/result/9c987a55-1050-4862-973b-240e19927251#summary
address: 0x660d30d1fbafdc88a1951370cbe2b3094dbf224b

waltontoken.org

---

_data/scams.yaml

https://urlscan.io/result/7075989d-aa1f-4dd4-918e-106606db2159#summary
https://urlscan.io/result/e258e289-e7d4-49b4-a090-09a090c0f17c#summary

tronlabs.network

---

_data/scams.yaml

Fake airdrop site asking for private keys
https://urlscan.io/result/06312d67-fe8a-4ea1-9fed-7161cf92da41/#summary
https://urlscan.io/result/87ce0f61-6a22-4702-b989-815b52c3c62d/#summary

tronlab.site

---

_data/scams.yaml

Fake vechain airdrop asking for private keys
https://urlscan.io/result/a48bd44f-825d-42c6-b208-b31d6544e46b#summary
https://urlscan.io/result/4e1ae728-37b4-4545-9d5f-e60641c874c6#summary

vechain.foundation

---

_data/scams.yaml

https://urlscan.io/result/140c6d0d-9f48-4150-9d4b-986320998611#summary
https://urlscan.io/result/7278d5b3-7466-429d-a385-d54be3a4faf5#summary

appcoinsproject.com

---

_data/scams.yaml

Fake web-wallet for tron - not giving users tokens once sent to address they control
https://urlscan.io/result/670fc845-60fb-4ffb-a9ff-ef856bab5e9f/#summary
address: 0xf4c87c851d772b0f9e72cca0690327f2bc505015

tron-wallet.info

---

_data/scams.yaml

Fake Quanstamp site - hosted on the same server as many other scams/phishing domains
https://urlscan.io/result/282bc4f8-d7a3-428c-b54f-9be92aaf94e2/#summary

quanstamptoken.tk

---

_data/scams.yaml

Fake MEW, slack phishing
https://urlscan.io/result/72c867ab-2b1e-4d45-b186-54a1d474c190#summary

myetherwallet.applytoken.tk

---

_data/scams.yaml

Fake bluzelle crowdsale site
https://urlscan.io/result/14762634-054b-4979-a196-af88a450303d#summary
https://urlscan.io/result/a53c171e-7833-45d6-8115-4df2e6f2f3d9#summary
address: 0xB2A3FCf38979898e695c88947e3373bf1c2E9b37

bluzele.co

---

_data/scams.yaml

https://urlscan.io/result/67222ba2-a109-4522-84ab-5fd31cfb7324/#summary
https://urlscan.io/result/3cfa3827-58ac-483f-8fcc-063f4c19d582#summary
address: 0xB2A3FCf38979898e695c88947e3373bf1c2E9b37

bluzele.sale

---

_data/scams.yaml

https://urlscan.io/result/bf4db025-cfdb-40c0-a6bc-e60eedcce8e3#summary
address: 0x33bf8bde242216da572d6486d641ae0a18137306

ico-bluzelle.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/facd22be-4fc9-4c91-9d20-41d9dc73538a#summary

myeherwalllet.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/97ac1cf8-fced-43a0-949d-74f0e9d06fe0#summary

myehntersvvailct.com

---

_data/scams.yaml

https://urlscan.io/result/c69d6826-37e1-47b7-939e-34b426146571/#summary

bluzelle.eu address

---

_data/scams.yaml

Fake Quanstamp site
https://urlscan.io/result/8f59d238-6b54-4a93-8d9f-b811c4a1598c#summary

xn--quanstamp-8s6d.com + more

---

_data/scams.yaml

https://urlscan.io/result/ea246a1c-0f08-44c7-8ce5-165d7f6f5659/#summary
https://urlscan.io/result/6ddc5de6-9296-41bf-8dc9-09fdb6d6279f#summary
address: 0xf747726200C7FC14Ef4CE267b1F070128C2260Dd

bluzelle-ico.eu

---

_data/scams.yaml

Etherzero site and wallet - saving passwords
https://urlscan.io/result/b6b663fb-5414-4531-83c8-a89eacc2738f#summary
https://urlscan.io/result/ced003f5-53c7-4a86-a98a-56235561f228#summary

ether0.org

---

_data/scams.yaml

Asking for private keys to get free coins
https://urlscan.io/result/fb6501ee-72c0-4e10-9e83-2fee1328a048#summary

ether-zero.net

---

_data/scams.yaml

https://bitcointalk.org/index.php?topic=2607526.msg28510053#msg28510053

ethereum-zero.com address

---

_data/scams.yaml

Fake MEW stealing private keys with log.php
https://urlscan.io/result/30dc52cd-16dc-41d7-8a71-c2af640be203#summary

myenhtersvvailot.com

---

_data/scams.yaml

Fake Vechain airdrop asking for private keys
https://urlscan.io/result/7075e8ef-99cb-42aa-892f-6b4674543e7a#summary
https://urlscan.io/result/bc904a49-87bf-48bd-b485-8cf89d0a7c64#summary
https://urlscan.io/result/b0aa2490-aafa-490b-a5bb-48026b269167#summary

venchainfoundation.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/86edf2cc-124a-40b8-89e4-92e9b09d67ba#summary

xn--metherwalle-jb9et7d.com

---

_data/scams.yaml

Fake Etherzero wallet, phishing for private keys
https://urlscan.io/result/4f0f019f-bb66-4f62-972f-1235e3dca9f6#summary

ethzero-wallet.com

---

_data/scams.yaml

https://urlscan.io/result/3f3e27ad-d5d6-47f8-9182-3062b948950d#summary
address:  0xce686d019E6f692aF646A8dF3BfE789dA97a484f

bluzelle-ico.com

---

_data/scams.yaml

Fake wepower.network
https://urlscan.io/result/2a22eae3-7d13-4959-920f-955e27c1b4f5#summary
https://urlscan.io/result/279ed046-bcd2-4d0d-bbc2-16607927db37#summary
see https://github.com/MetaMask/eth-phishing-detect/pull/712/files

wepowers.network and wepower.vision

---

_data/scams.yaml

Fake Telegram ICO crowdsale site
https://urlscan.io/result/4f71b52f-a388-40ee-a51b-851c7508c984/#summary
https://urlscan.io/result/d3aefdbf-d8bb-443e-b277-969db2bdba15/#summary
address: 0xB9Cfb36060785F6800B1aB9ccC9B4F341d097399

tongramico.com

---

_data/scams.yaml

Fake iEXEC airdrop asking for private keys
https://urlscan.io/result/c223776a-ed59-43a9-bd86-537137a12970#summary
https://urlscan.io/result/3e2e2f78-e444-49e9-9161-676d9eef3571#summary
https://urlscan.io/result/fe4483a9-f566-4775-a2ad-0d0a73054815#summary

iexecplatform.com

---

_data/scams.yaml

xn--condesk-0ya.com
coindesk idn homograph attack
https://urlscan.io/result/6125ff44-df5c-4a9d-b49f-3e24e34a3cfc#summary
xn--condesk-sfb.com
Fake coindesk - redirecting to a uplink referral, but IDN homograph attack on the domain
https://urlscan.io/result/17fd36f2-ffce-4e76-98c3-348bf79072df#summary
xn--coindsk-vs4c.com
Fake coindesk promoting fake SingularityNET 
https://urlscan.io/result/80f5d11b-b64d-498e-8c0e-6e58f3c14121#summary

xn--condesk-0ya.com

---

_data/scams.yaml

Fake Etherzero site
https://urlscan.io/result/7b73b1b4-d388-4cd0-b668-4587b275b0ae/#summary
https://urlscan.io/result/5d07815e-f02e-4043-a9ac-fdf3c2298b22#summary

etlherzero.com

---

_data/scams.yaml

Fake OMG airdrop asking for private keys
https://urlscan.io/result/4d2617d8-077d-4b0c-8e6e-66857138c383#summary

omisegonetwork.site

---

_data/scams.yaml

Fake nucleus vision crowdsale site
https://urlscan.io/result/efd599fa-cf48-4d3a-8f0a-c602582433b4/#summary
https://urlscan.io/result/01ca7f78-6c31-4d14-b8d3-aba940b9281c#summary
address: 0x93574D7c405717D80520944Ee1Cb72D327B01dF5

nucleus-vision.org

---

_data/scams.yaml

bluzelie.com
https://urlscan.io/result/5537a833-7bba-4b40-be15-aaf0092bfb6e#summary
https://urlscan.io/result/b1354966-036e-4abf-abba-37d5f459a846/#summary
address: 0xd5EDb088b7382b397238f5010D14cf10Dd395007
wwwbluzelle.com
Suspicious parked domain - similar to bluzelle (currently doing/did an ICO)
https://urlscan.io/result/6de1d00a-3094-445b-8acc-3133babc24e8#summary

bluzelie.com

---

_data/scams.yaml

Fake Binance
https://urlscan.io/result/5820d9ba-517f-4ceb-9b8a-aa9ccdc13853#summary

xn--bnance-bwa.com

---

_data/scams.yaml

Hosting a fake coinbase UI
https://twitter.com/switchingtoguns/status/955460254191570945
https://urlscan.io/result/7058c38e-54f6-4712-ac28-3de612801a9c#summary

iluminatto.com.br

---

_data/scams.yaml

Fake ink crowdsale site
https://urlscan.io/result/9f053618-4ef5-4f1f-b8ad-4987fef6ce2b#summary
https://urlscan.io/result/4ae89c45-a94e-48dc-b353-5edf844bf4b2#summary
address: 0x94D55B6f8b53903026399ab45294140EAfbFbF44

paywithlnk.com

---

_data/scams.yaml

Fake paywithink crowdsale site
https://urlscan.io/result/205b1728-de62-4d85-ab06-cb5897f3882b#summary

paywithnk.com

---

_data/scams.yaml

Fake coinomi
https://urlscan.io/result/4308d684-820f-477a-983b-36bdc0815f57/#summary
https://urlscan.io/result/ac308846-e514-4fa0-9319-b229b0b8b572#summary

coniomi.com

---

_data/scams.yaml

https://urlscan.io/result/1601e2af-c49e-4a81-8ddf-60a06b62fbd1#summary
https://urlscan.io/result/6cc9318d-ced1-4459-a9a1-a719369ae152#summary
address: 0x8202b590Eca4662446102b3a97E3536aAc8ab941

ton-gramico.com

---

_data/scams.yaml

Fake Vechain airdrop asking for private keys
https://urlscan.io/result/1343c7e2-91e8-4aa1-a075-446038113952#summary
https://urlscan.io/result/2091c0e2-8e5a-4879-ac65-7310dec1a1bf#summary

venchain.foundation

---

_data/scams.yaml

Fake kucoin login
https://urlscan.io/result/3e210336-6353-460c-877a-8d48ab401313#summary
https://twitter.com/switchingtoguns/status/956007910030659587

login-kucoin.net

---

_data/scams.yaml

Fake Gemini phishing for login details
https://urlscan.io/result/fc75b8e7-cb92-4777-abb3-7a6d19b4342d#summary
https://urlscan.io/result/8f282b02-18b2-4540-aca9-ea361212036c#summary

www-gemini.com

---

_data/scams.yaml

Fake telegram ICO
https://urlscan.io/result/75440447-5a4e-4d22-a964-14a5f38e7ffa/#summary
https://urlscan.io/result/b15976d6-e3f6-474f-b14b-695cd673ea35#summary
address: 0xcae77a05ab518492144944fb50572ebfa3595870

gramico.info

---

_data/scams.yaml

Most of these are dormant, but could be harnessed for an attack. Better to be safe than sorry.
xn--polniex-ex4c.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/0371ab6b-32ac-47df-abab-21b00af7aec6/#summary
xn--polniex-s1a.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/b3928990-c29a-428a-93d6-b589759975c1#summary
xn--polonex-ieb.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/b0b7b657-1412-454e-9af7-3d199997298d#summary
xn--polonex-sza.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/13d49057-e2c4-419f-b7cc-a040d92f44f8#summary
xn--polonex-zw4c.com
IDN homograph attack on poloniex exchange
https://urlscan.io/result/ef8f2739-f0d1-4d30-ada9-af7c72a127a5#summary
xn--polonix-ws4c.com
IDN homograph …

Poloniex IDNs

---

_data/scams.yaml

Fake wachain site, asking for private keys and giving a contribution address
https://urlscan.io/result/2ad1d740-c519-4b17-a69f-16ce9758369b/#summary
address: 0xBbDEF8b12BABD3ab6018566BC17eC3Aa302b8348

wanchainfoundation.org

---

_data/scams.yaml

Fake CobinHood
https://urlscan.io/result/67060141-ad4b-4bb5-b2af-819fec05a061#summary
see https://github.com/MetaMask/eth-phishing-detect/pull/750

cobin-hood.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/8df71be0-fce9-4899-9874-bc305d717770/#summary

myenhterswailct.com

---

_data/scams.yaml

Fake nucleaus vision crowdsale site
https://urlscan.io/result/cbafd4f1-bc8d-472f-8ae0-e21c5f5c3416#summary
https://urlscan.io/result/6ff37742-2586-4396-94dc-d75b5c096a01#summary
address: 0x6122EE683dbEe50fD432fE5BdD8Ac055aA3D42b1

nucleuss.vision

---

_data/scams.yaml

nucleus-vision.net
Fake nucleus vision crowdsale site
https://urlscan.io/result/66c5cf06-da6d-4ead-956b-d2a30ef6044b#summary
https://urlscan.io/result/ad122320-38b0-40c3-a8df-fe096337d09e#summary
ledgerwallet.by
Fake LedgerWallet store
https://urlscan.io/result/352d0a63-cb93-435b-b716-d5c9c7231298#summary

nucleus-vision.net and ledgerwallet.by

---

_data/scams.yaml

Fake Wanchain crowdsale site
https://urlscan.io/result/d0b676de-463f-4d9c-89a5-b4048a2c1a3d#summary
address:  0xdF3e77CD5e563f93fC7ecA905d3302e95f9bb150

wanchainalliance.org

---

_data/scams.yaml

Fake Wanchain crowdsale site
https://urlscan.io/result/afcaf046-38e4-41d3-a76b-e41618dbb81f#summary
address: 0xd9D25DcE4c3765855c76F3d2BAccc0755C4d0bc5

wanchainltd.org

---

_data/scams.yaml

Fake Wanchain crowdsale site
https://urlscan.io/result/26bd11f6-7852-42c5-8c9b-7163f0cf4369#summary
address: 0x9B521529D04329C2B0a9F9B7DB18ed775c6cA8FC

wanchainetwork.org

---

_data/scams.yaml

Fake cindicator airdrop asking for private keys
https://urlscan.io/result/fca12de3-d6a8-41ac-848f-ac610f3e1e16#summary
https://urlscan.io/result/b6033dd0-a137-4955-ac8d-42c96a0f2178#summary
address:  0x545f5e5c54d8ac72af1c7de8c070387b73841a24

cindicator.network

---

_data/scams.yaml

Fake beetoken crowdsale site
https://urlscan.io/result/41729511-aa53-4b67-a203-89114cdc9a05/#summary
address; 0xE0b13c073e8173b06062c69A160EbB54e2AF86c3

beetoken-ico.eu

---

_data/scams.yaml

Fake icon airdrop phishing for private keys
https://urlscan.io/result/3dac315b-b71e-4b7d-8fe1-82314f1b0a7a#summary

iconfoundation.site

---

_data/scams.yaml

ico-telegram.io
Fake Telegram ICO site
https://urlscan.io/result/959e8841-2a81-48da-8530-8eeda25a6a04#summary
https://urlscan.io/result/f12a8232-10b7-4207-a4d5-254957cbaaf3#summary
address: 0x88436C2A2f427F2aa641dFd8c6763facf2Bad7bf

ico-telegram.io

---

_data/scams.yaml

Fake Wanchain crowdsale site
https://urlscan.io/result/87f22920-8c5a-4de9-8e87-822e5acd5c0f#summary
address: 0xB76a4770587f76d6c644DeeC275a2c76069b5F14

wanchainfunding.org

---

_data/scams.yaml

Fake Dadi crowdsale site
https://urlscan.io/result/f226c698-6ad4-43ba-a06a-45d487664f72/#summary
address: 0x0d9786138578fcdcce04435592545ef08422d755

dadi-cloud.net

---

_data/scams.yaml

https://urlscan.io/result/71b31b18-c1bc-41bf-8a1b-e6a96c2068a8#summary
https://urlscan.io/result/550d845d-ccdd-4004-8265-6a60b254ddd7#summary
See https://github.com/MetaMask/eth-phishing-detect/issues/764

blockarray.org

---

_data/scams.yaml

Fake app https://play.google.com/store/apps/details?id=com.ether.etherdelta
https://twitter.com/sniko_/status/957971197446295552

EtherDelta andriod app

---

_data/scams.yaml

Fake crowdsale site
https://urlscan.io/result/312e12dc-074b-4eeb-bf24-2f266e106c5a#summary
https://urlscan.io/result/2fa055ce-a089-44e2-826f-14b645c83ff7#summary
address: 0xbE11D0d38Ef4857224032afc9C96647492F726cE
See MetaMask/eth-phishing-detect#766

daditoken.com

---

_data/scams.yaml

Fake Dadi crowdsale site
https://urlscan.io/result/c95fff60-428a-4f88-94e0-a468a9221607/#summary
address: 0xD0Ac32Ab01D9D3EC145EF63f73BF4e222dBCc0fb

daddi.cloud

---

_data/scams.yaml

https://urlscan.io/result/e661f992-6544-4abb-a7ed-f97fd120e7b3#summary

telegramcoin.us + more

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/87f77841-7900-403e-ad03-92bd1c9c73e3#summary

myetherwallet.uk.com

---

_data/scams.yaml

Fake MEW, Binance, Bittrex
https://urlscan.io/result/a7bb365e-2e7f-40b7-beec-ff2902abd7c8#summary
https://urlscan.io/result/cf042b7b-14c1-40b7-b35d-6ce9afc04d74#summary
https://urlscan.io/result/fab8ae19-912a-4c5c-b867-18ff0ba0bda9#summary
https://urlscan.io/result/51cb8437-554d-4592-a136-0c0d642d6306#summary
https://urlscan.io/result/5cc72609-14d1-4c80-a20a-a9ff044899a9#summary
https://urlscan.io/result/ffb4e7e4-8789-4f4e-bdb8-def603cc0797#summary
https://urlscan.io/result/185bc600-bc0c-4351-b19b-248aa7de0f97#summary
https://www.reddit.com/r/CryptoCurrency/comments/7u8svb/psa_new_sneaky_mew_and_exchange_phishing_domains/

Fake MEW, Binance, Bittrex

---

_data/scams.yaml

https://urlscan.io/result/cc45a07f-eea1-42bc-9ae9-078ebcd3f839#summary

xn--myetherallet-nu5f.com

---

_data/scams.yaml

Fake origin airdrop phishing for private keys
https://urlscan.io/result/5a3cb677-4a99-4c1a-a38e-2e139ed6f08f#summary
https://urlscan.io/result/e0c525ad-c911-4bf1-a44a-4bc481add4d3#summary

origintrail.in

---

_data/scams.yaml

xn--shapshift-e4a.com
https://urlscan.io/result/1d2036dc-a45e-48a6-8d99-f97908065df5#summary
xn--shapshift-y4a.com
https://urlscan.io/result/9e1db26b-dc9e-47f4-82df-fb5edaf51304#summary
xn--shpeshift-c2a.com
https://urlscan.io/result/eb4e8994-6f01-437b-9f9c-db59a4dbad59#summary
xn--shpeshift-r1a.com
https://urlscan.io/result/f7b718c1-4ba6-410c-8bcb-e0e654f011e3#summary
xn--shapshift-o4a.com
https://urlscan.io/result/8323faa4-9149-4718-9cec-d4f5526258f5#summary
xn--shpeshift-w2a.com
https://urlscan.io/result/a87b8f00-f6f1-4e82-b614-8c23bace194f#summary
xn--shapeshft-w5a.com
https://urlscan.io/result/59438f10-eaf4-4705-a108-bfa63698cc7f#summary
xn--shapeshft-w5a.com
https://urlscan.io/result/f4bbb8c0-bff0-4f44-b211-57986205ce4f#summary

shapeshift idn homograph attacks

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/4fc69ae6-3170-4f78-a67e-c9959c4ff174#summary

myetherwallet.import-tokens.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/9da51796-6d5f-4fda-9598-eff3664fdcc5#summary

myetherwalletjoin.com

---

_data/scams.yaml

Fake republic crowdsale site
https://urlscan.io/result/07f43b75-6ed6-4c08-a772-857d5698dd37#summary
https://urlscan.io/result/19d02b2d-0621-41c9-980f-19bf4f552bf5#summary
address: 0x94B40ECC7B38F5A9316B03dac4fC663E4D10cd15

republicprotocol.eu

---

_data/scams.yaml

Fake Arcblock.io crowdsale site
https://urlscan.io/result/2c647958-2ff0-4f36-a3b1-831b8d64b34e/#summary
address: 0xd1BDD067f5F1CbD358E2DDe444f8d9f41dE8AE76

arcblock.eu + more

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/687528bd-d23f-4d43-a1ff-cd104c53ff54#summary

rnyetherumwallet.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/59b66a4b-a62e-4da0-99ef-eb626d04a8a8#summary

xn--mytherwallt-cbbv.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/50ec8429-f814-4369-bb4e-a6835d55950d#summary
https://urlscan.io/result/585fe032-7241-4a41-9f11-a313fab10a88#summary
https://urlscan.io/result/e150014f-1469-40d6-bcb1-4c7601f74787#summary

xn--myeterwalle-cm8ev6a.com xn--myeterwalet-cm8epi.com

---

_data/scams.yaml

Fake xmoneta crowdsale site
https://urlscan.io/result/b9ba53ef-3a92-44a5-a8d2-881f600ef924/#summary
https://urlscan.io/result/2e2b8d3f-0aa9-4e4f-97c8-9394e122c17b#summary

xmoneta.co

---

_data/scams.yaml

Fake Fintrux crowdsale site
https://urlscan.io/result/3ec16826-3fe0-4636-aae5-a8ea11a583be/#summary
https://urlscan.io/result/0b85217a-a766-45d8-9216-757dafd3f09f/#summary
address: 0x7Eb28833082eB28fD423aB30Df20afDE98C47DBF

fintrux.co

---

_data/scams.yaml

Fake free coin giveaway
https://urlscan.io/result/bc2fe81e-ccf8-4d72-86da-dc2504cc0db4#summary

cryptoexploite.com

---

_data/scams.yaml

Fake Adhive crowdsale site
https://urlscan.io/result/dc3c5bde-d67f-4ebc-a6b0-af1506f5139f/#summary
https://urlscan.io/result/53034b1b-6003-4abc-8059-04325286dd3c#summary
address: 0x74104E8C7F546C7398d198F6678310cE9D1b8814

adhive.net & tokensale.adhive.net

---

_data/scams.yaml

Fake tron airdrop phishing for private keys
https://urlscan.io/result/3c29db35-fce1-43d9-a704-f23417957b1c#summary
https://urlscan.io/result/63bc3f1b-039b-4097-8e38-7695d7c76249#summary
https://urlscan.io/result/864eebc8-afee-4eef-b9aa-bd271f3c3b02#summary

trx.foundation

---

_data/scams.yaml

Fake fusion crowdsale site.
https://urlscan.io/result/04cd85b7-6530-4944-af28-197cdee50eb3#summary
See; https://github.com/409H/EtherAddressLookup/pull/292

fusion.tokencrowdsale.online

---

_data/scams.yaml

Fake earn crowdsale site
https://urlscan.io/result/d5f6095a-58b4-4018-a5c2-24d3328b6144#summary
address:  0x9e009c57b36aC7e3382697b4c9d3E7092A1CDb42

sale-earn.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/0097d6c3-45fe-4c17-a56e-54a913ad4739#summary
See https://github.com/409H/EtherAddressLookup/pull/294

xn--yethewalle-to2exkhi.com

---

_data/scams.yaml

Fake ETH doubler
https://urlscan.io/result/7e746657-ea58-4222-a197-b98b689b7906#summary

ethexploit.org

---

_data/scams.yaml

Fake dock crowdsale site
https://urlscan.io/result/e7059871-8358-4e49-88b6-4a44b3141d93#summary
https://urlscan.io/result/a474946c-c6ab-482c-9bde-1b7ba91219d0#summary
address: 0x0AF16719353EddC122eAf834638406c499197860
see https://github.com/409H/EtherAddressLookup/pull/296

dock.promo & dock.so

---

_data/scams.yaml

https://urlscan.io/result/2397c869-4e2e-471f-8650-dab5d0a0b8f8/#summary
https://urlscan.io/result/9dd0473d-a2f7-44f5-bae4-a3c687252462#summary
https://urlscan.io/result/ec97d008-a816-414c-bdf2-3364b3256673#summary

jibreltoken.in

---

_data/scams.yaml

Fake nucleus vision crowdsale site
https://urlscan.io/result/865dc618-9cfd-4f69-8bbf-eacaeb26ee05/#summary
https://urlscan.io/result/9ea233a8-428b-4a24-aa71-c05587161cc3#summary
address 0x89E5124B5162A0CEEc512e8bA97Cd5E6F065fd13

nucleus-vision.cc + more

---

_data/scams.yaml

https://urlscan.io/result/5a1e52c0-05aa-45aa-8b8b-731a6979002d#summary

xn--myetheralle-7b9ezl.com

---

_data/scams.yaml

Fake RightMesh crowdsale site
https://urlscan.io/result/6b5a0eea-85a2-42b9-8fd7-dd5ad17db618#summary
address: 0x169b6c7Ed548e45bA9D87B2D32ff27e2D00051Ef

icotoken-current.top

---

_data/scams.yaml

https://urlscan.io/result/fdd576be-daa9-45c5-9733-483e662c78a4#summary
https://urlscan.io/result/9c643098-69f3-4f85-b651-97f6c819a94e#summary

vechain-foundation.com + more

---

_data/scams.yaml

https://urlscan.io/result/26cc4318-816b-4784-95e4-739e3a9a98e8#summary
https://urlscan.io/result/f09ad6dc-7134-4a72-8a32-9c8d6af3d2fb#summary

openplatform.tech

---

_data/scams.yaml

A seed phrase phishing site 
https://urlscan.io/result/19e23873-060a-4b0f-9b5b-80fc93bb201e#summary
see https://github.com/MetaMask/eth-phishing-detect/pull/898

metamaskgiveaway.xyz

---

_data/scams.yaml

dock.so
https://urlscan.io/result/76707794-4c54-489d-8a66-0de4f2b8de3c#summary 0x9546748F47a77408dfBFF0DC22505B2e9a75FdA4
dock-ico.site
https://urlscan.io/result/f31bbf71-3b19-4193-844e-7ac5fa73ddc2#summary
https://urlscan.io/result/674abcce-c971-4768-9978-426086de2298#summary
0x0AF16719353EddC122eAf834638406c499197860
tokensale-dock.io
https://urlscan.io/result/b6194fc2-c393-41a1-a6b1-4db57fb54935#summary
https://urlscan.io/result/ab2d1769-013a-47af-b054-d908f02a7741#summary
0x9CdfC5b0ACA4527a0916412E9dbD6AD85556A494
dock.promo
https://urlscan.io/result/25db3dbb-abe5-4d87-a542-b8c68d51119e#summary
https://urlscan.io/result/98f00e98-bea6-40e7-86e0-390d97ad0359#summary
0x0AF16719353EddC122eAf834638406c499197860
dock.su
https://urlscan.io/result/230081ed-1662-4ffb-ad3e-89a19dbdb8d5#summary …

fake dock crowdsale sites

---

_data/scams.yaml

Fake Eos airdrop site - idn homograph attack - links to xn--myetherallt-pl9elw.com
https://urlscan.io/result/e0013795-54cd-4c54-a69c-09666b9ebfd0/#summary
https://urlscan.io/result/03a41315-680a-48f0-9661-4171faf1125e/#summary

xn--es-8bb.com xn--myetherallt-pl9elw.com + more

---

_data/scams.yaml

Removed legit address
https://twitter.com/FintruX/status/965022819280023552

finetrux.com

---

_data/scams.yaml

Fake fintrux crowdsale site
https://urlscan.io/result/10d2302c-037b-438f-b62a-35797537b605/#summary
address  0xcCdf72DE615b5158BB37931BbCE645aa69221520

fin-trux.com + more

---

_data/scams.yaml

Fake poloniex
https://urlscan.io/result/2fa36a15-48f1-4133-8202-934aa1a87b3c#summary
https://twitter.com/jmoconnor415/status/965032716436582400

xn--polonx-0va26t.com

---

_data/scams.yaml

ICO with a team that don't know about the company
https://urlscan.io/result/dcd46ec4-dc02-41a0-8e19-0d02aa43eb6d#summary
https://twitter.com/MayeeRama/status/965219691152183301

jiocoins.io

---

_data/scams.yaml

Fake Seele crowdsale site
https://urlscan.io/result/66544dbf-abb6-4c99-89d0-cdb9da26329a#summary
https://urlscan.io/result/572b8434-ee3e-4df9-90e0-1ccf172125e3/#summary
address: 0x4bb1c210E3921E0F051ed00e898B9605c902114e

seele.promo seele-ico.eu seele-ico.pro

---

_data/scams.yaml

Fake binance domains, IDN homograph attacks
https://urlscan.io/result/0bdbd58f-ca42-4267-b6f8-d3b0cf517c78
https://urlscan.io/result/7d991acf-c665-486c-a538-3bc1f4f01c96#summary

xn--binnce-5nf.com xn--biace-4l1bb.com

---

_data/scams.yaml

Fake forkdelta
https://urlscan.io/result/08f0bc02-b72d-4b58-ad9e-1773c1d0fba6#summary

forkdeita.github.io

---

_data/scams.yaml

Fake polyswarm crowdsale site
https://urlscan.io/result/59d402d2-3eea-4762-8412-39521433b282/#summary
0xe88379631857c0d8174EFEfDf8DCA25b29610f08

polyswarm.bid

---

_data/scams.yaml

Fake dock crowdsale site
https://urlscan.io/result/53bef3d7-beff-40a8-a8ef-848dac7e8bb9/#summary
address: 0x7ba85E2e55c7598378Fe927aD2Aef2DAc6c45218

sale-dock.com

---

_data/scams.yaml

Fake Polyswarm crowdsale site
https://urlscan.io/result/23433c81-1e63-47d1-ba82-76bf605fb513/#summary
https://urlscan.io/result/11c80d13-a19f-4e23-9a6f-28d0d39129bd#summary
address 0x7dCfD020aD161fBD4C45894ab352582018eA9197

polyswarm.in

---

_data/scams.yaml

Fake Seele crowdsale site
https://urlscan.io/result/c8ab7900-a188-4df4-a9ff-ea3aad98f718/#summary
https://urlscan.io/result/1f7cbe0d-7a92-42d5-ad80-41cecd299340#summary
address  0x0b591a58137f154F59Aea1284166d6A7b49821Fd

seele-token.pro + more

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/39e72de6-54b2-4f5b-8c9e-85879f937c22/#summary

myethervallet.pro

---

_data/scams.yaml

Fake dock site
https://urlscan.io/result/eb5f705b-7542-43df-a4bd-9a8018710c4e#summary
https://urlscan.io/result/53fdcbd9-3d34-4b92-a80c-bbe48a5651ce/#summary

dock.network

---

_data/scams.yaml

Fake Dock crowdsale site
https://urlscan.io/result/72701ae8-a25e-44ff-aa2a-7963a6ad95b8#summary
https://urlscan.io/result/256c76c8-fe07-4b44-a81f-20ad432f54e2#summary
address  0xEc970BbF167beee6fb536f1839418f3D19cE2a69

dock-io.org

---

_data/scams.yaml

Fake polyswarm crowdsale site
https://urlscan.io/result/84a72b79-75a2-4a9a-b650-c0b874853021/#summary
https://urlscan.io/result/f6bfd502-d9b2-4a2d-b990-1421a1f3f594/#summary
address: 0x247733aF8B2BB8e63e3a2A419761c0fd71D40499

polyswarm.pw

---

_data/scams.yaml

Fake dock crowdsale site
https://urlscan.io/result/9305ccbc-80f4-4c8e-b02b-2b49bb0f01da#summary
address 0x9CdfC5b0ACA4527a0916412E9dbD6AD85556A49

dock.click dock-tokensale.eu

---

_data/scams.yaml

Fake polyswarm domain
https://urlscan.io/result/319b9c81-9a41-4a0e-948e-db57b18ed916/#summary

polyswarm.ru

---

_data/scams.yaml

Fake dfinity crowdsale site
https://urlscan.io/result/1ecc6a84-42a9-4577-b448-f674ec210a01#summary
https://urlscan.io/result/0226061d-5b63-4bf4-a186-64a36f07d927#summary
address: 0xf4710562c804087AF20b7396Ce7CbA38B43fB61F

dflnlty.org

---

_data/scams.yaml

Fake TRON airdrop site phishing for private keys
https://urlscan.io/result/eb2e60fe-e74e-42f0-b05c-d35550c7dfdd#summary
https://urlscan.io/result/8597bd89-07af-4a04-9f87-c26eda6d9aba#summary

tron-foundation.org + more

---

_data/scams.yaml

https://urlscan.io/result/f5340e39-9ecc-47a3-8bef-1cf6464afe7e#summary

xn--yeterwallet-bm8eym.com

---

_data/scams.yaml

Fake Petro crowdsale site
https://urlscan.io/result/22731a7e-e834-442c-986e-7d1f44da3982/#summary
https://urlscan.io/result/404d4930-31bf-4847-ac31-13dbb754a684#summary
Address: 0xE977419eF28e71Ed541fF6318cEA9a6392709a48

el-petro-coin.com

---

_data/scams.yaml

https://urlscan.io/result/9e83b1cc-8842-4ed1-97bd-d8a7db34e451#summary

xn--myethewalle-w48erh.com + myetherwallett.site

---

_data/scams.yaml

https://urlscan.io/result/1b68bb7a-3665-49dd-bfcf-f0cf1d01c7f1/loading

xn--myetheralle-jb9exm.com + more

---

_data/scams.yaml

Fake MEW idn homograph attack
https://urlscan.io/result/64f724cd-0477-4685-8a72-916e7b77be7d#summary

xn--metherwalle-jb9ejq.com xn--coindek-s73c.com

---

_data/scams.yaml

Fake ETH giveaway by a SatoshiLite Twitter imposter
https://urlscan.io/result/9cac4738-94d5-43f2-bdff-e57ac381f2df#summary
address: 0x785a751B2E36b2B0Fdb80100B7ca14889a768A22

address-transfer-confirmation.droppages.com

---

_data/scams.yaml

Fake Akasha pre sale
https://urlscan.io/result/e0367b7f-8a9b-4527-9526-96a547c8a405#summary
address; 0x8645eC394f7af95316639dcE6F99c01476B0d888

akasha-world.com

---

_data/scams.yaml

Fake giveaway/trust-trading on Twitter
https://urlscan.io/result/8761e483-2b71-4805-80ae-72ead3511bbd#summary
address: 0xaa2498d85bA7559006f90110A4Bc33c10A06c1AF
Twitter id: 4799304813

6khb.payment-checker-ethereum-id-bslyftexjuwcgv8.filesusr.com

---

_data/scams.yaml

Fake Gonetwork crowdsale site
https://urlscan.io/result/8afd7a9f-fdbe-46c3-8ee4-ed8bfdbe7a22/#summary
address: 0xa8eb559EEb38C6CB6A8BC6C39bAdd86B113cd875

neonexchanges.org

---

_data/scams.yaml

Fake GoNetwork site
https://urlscan.io/result/9730606b-8a73-44f7-a892-7fef63e1f718#summary
address;  0xa8eb559EEb38C6CB6A8BC6C39bAdd86B113cd875

gonetwork-airdrop.co

---

_data/scams.yaml

Fake ForkDelta site
https://urlscan.io/result/e3d76f15-bab0-422c-97af-d4c43ca8204b/#summary
see https://github.com/MetaMask/eth-phishing-detect/issues/1004

forkdelta.io + more

---

_data/scams.yaml

Fake Vechain airdrop phishing for private keys
https://urlscan.io/result/995bdff7-a420-40c0-8b10-bf7330f08925#summary
https://urlscan.io/result/42120a29-b958-4ceb-94b4-0d71f49f2a1d#summary

vechain-foundation.org + more

---

_data/scams.yaml

Fake Dfinity crowdsale site
https://urlscan.io/result/dd90b8d5-ba15-4dc2-9a38-64cf45a29e47#summary
https://urlscan.io/result/e59d157a-4bad-4491-8c04-ece34ef0ceab#summary
address  0xCB89576d5e1627f4a0C64C2bb4d51798e92E8b8F

dfinlty.org

---

_data/scams.yaml

Same page design for trust-trading scams
https://urlscan.io/result/c8e6dcb1-7dfe-4f6d-8951-4f039c6eadb0#summary
https://twitter.com/Palooniex
address  0x37c85A7523B1832B4D0380B2f513e88B66e8c850

transfer-address-confirmation.droppages.com + more

---

_data/scams.yaml

https://urlscan.io/result/12b093e7-6210-413d-bc10-3954917398c3#summary
https://urlscan.io/result/bbb44d9e-fa94-43fe-bfcf-c72a7f99fd66#summary

add hawen[.]io and havven[.]xyz

---

_data/scams.yaml

Fake Adhive crowdsale site
https://urlscan.io/result/b8b5f9fd-5a0e-4e10-9006-9e09308bbdbc#summary
address: 0xC4625787be3fcCfF6AC2971945806AcC167C8CBd

tokensale-adhive.com

---

_data/scams.yaml

Fake ipsx crowdsale site
https://urlscan.io/result/f251b8ae-f559-41f2-a0ef-235a4013e063#summary
address: 0xb8689c29bdc7c84f33706ff0f96eafc222ba6d86

ipsx.promo

---

_data/scams.yaml

Fake dfinity crowdsale site
https://urlscan.io/result/8da3a0bf-1773-4f8e-a8c8-a8fd05c3f9b1/#summary
https://urlscan.io/result/99a5cb76-6b9f-4ce7-90de-170595ca487a#summary
address: 0xe74b02131Ed2184eb94fD357b4f303E6935367f5

dflinity.org

---

_data/scams.yaml

Fake coindesk site promoting a fake MyEtherWallet (xn--yetherwalle-tv8ezt.com)
https://urlscan.io/result/f4e8c17b-74e4-4b19-a16c-4b0a02a632fe/#summary
https://urlscan.io/result/2eb4228c-aa8c-4d40-ba51-00769f5070e7#summary
see https://github.com/409H/EtherAddressLookup/pull/329

xn--coindek-873c.com + more

---

_data/scams.yaml

Fake TRON wallet
https://urlscan.io/result/0de77bc1-840c-421a-8550-8b02cb60f75d#summary

tron-online.org + more

---

_data/scams.yaml

C&C for some phishing sites
https://urlscan.io/result/6e7be669-17f4-4976-9ea5-e8aa0cb02f26#summary
https://urlscan.io/result/4af4d6e0-5139-4248-a58b-ad27a9f58bea#summary
Fixes https://github.com/MetaMask/eth-phishing-detect/issues/1032

meganfoxloveyou.com + more

---

_data/scams.yaml

Fake Havven crowdsale site
https://urlscan.io/result/98ff1861-6c68-4443-984f-5eac2b09e492#summary
address 0x4fafc9291a0112a0ee0928361c02848ff2fdf6bd

ico-havven.org & tokensale-havven.in

---

_data/scams.yaml

https://urlscan.io/result/c05a82de-e61a-436b-9c1a-185cd2b7249c#summary
https://urlscan.io/result/0da46c70-50f6-406a-b133-9492410f0e9e#summary
https://urlscan.io/result/53c44486-4103-49b6-a701-b4959f7156ed#summary
suspected address: 0xBc66E774CE25000950786241b8c5EE3275311Bd7

nucelus.vision

---

_data/scams.yaml

Fake Havven crowdsale
https://urlscan.io/result/3435785a-6dad-4431-88ed-aa23ccba4506#summary
https://urlscan.io/result/7c0ff767-7fe7-452a-b607-46dcd2fa109a#summary
0xBC210eC2EFAda9DF4897Dc9B23c58E96c01eF711

havven.top

---

_data/scams.yaml

Fake Havven crowdsale site
https://urlscan.io/result/70c3f765-18f5-421e-aa0e-63bc04e7a631#summary
https://urlscan.io/result/2e4ce00d-5f19-4fdb-ac7e-af8643ec652e#summary
https://urlscan.io/result/498a96e0-988b-454e-95a4-5542e5ba7422#summary
https://urlscan.io/result/7abc459d-f336-4a58-a273-6a9851086eb3#summary
address:  0xD77B95800f67deB52E0e0988DBf01A311A3ccd80

havvenio.com

---

_data/scams.yaml

Fake tomocoin crowdsale site
https://urlscan.io/result/af4b001e-8308-4015-94ff-8361476a06df#summary
address: 0x717D2041c516573a0e27F552CdB6C5c3EC7B4e09

tomocoln.io

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/68e2e839-0cd6-4d93-8e4b-e64ccdefc470#summary

masanchez.usermd.net

---

_data/scams.yaml

Fake dfinity crowdsale site
https://urlscan.io/result/9e2ee4f7-ecfb-4acc-b4ca-8aca44ffe83e#summary
https://urlscan.io/result/7448636e-a1ae-4c69-abd6-c0cceb85e969#summary
address; 0xC5f6690F7b60FE739908E02AeC46aE07718CEc5f

dftnity.org

---

_data/scams.yaml

Hosting a trust-trading scam
https://urlscan.io/result/2adb135c-346f-45ea-a006-aba4b9c56a95#summary
address: 0x3715b1Ed9bbd5e165aF97619b5C5e13E39F55504

ethereum-promo.bitballoon.com + more

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/b21af979-8ba2-4ef1-91a1-ea544345293c#summary

rnyertherwallet.com

---

_data/scams.yaml

Fake Changelly website
https://urlscan.io/result/afc2a176-cb1a-437c-977d-0a40de3ed876#summary

changlley.org

---

_data/scams.yaml

Fake doc ai crowdsale site
https://urlscan.io/result/64209717-5839-471b-9988-e4b7817ca733#summary
see MetaMask/eth-phishing-detect#1078

docai.science + more

---

_data/scams.yaml

Fake tomocoin crowdsale site
https://urlscan.io/result/29d709e5-97ac-4a61-a3fb-483db01c5e75/#summary
https://urlscan.io/result/5734066a-306c-46d1-bb7d-e7e4e836ab2a/#summary
addresss: 0x38B7Ca3B78c51364095BC56146D25F55AEe0af21

tomocoin.network + more

---

_data/scams.yaml

Hosting a trust trading scam site
https://urlscan.io/result/ebde9203-aa14-4581-a5c4-26d220a0e51c#summary
address: 0xfddBfa1b0B93612b95e3296690b63B74D019370C

eth953883.htmlcomponentservice.com + more

---

_data/scams.yaml

Crowdsale site with fake team
https://urlscan.io/result/f394eb48-ec8d-4851-bed0-0841bbd9f8d3#summary
https://twitter.com/AppletonDave/status/970434000643751937
https://thenextweb.com/hardfork/2018/03/05/ryan-gosling-cryptocurrency-ico/

miroskii.com

---

_data/scams.yaml

Fake Telegram ICO site
https://urlscan.io/result/2d149af8-a46e-4eb2-90c2-b31d42daf17f#summary
https://urlscan.io/result/f3f4f8f1-94ce-4672-a323-4382fe2c5229/#summary

telegram.auction + more

---

_data/scams.yaml

https://urlscan.io/result/5cf69c58-25f9-4eff-b63b-067e141ba8aa#summary
address:  0xD43F2111e4055120196285eC094aA6e96998668b

binance.bitballoon.com + more

---

_data/scams.yaml

https://urlscan.io/result/52bff89e-dc16-47a4-b2bc-ab843eeee1bf#summary
address:  0x23d56797f64640e96FEaF57b7874C897b53ef0E4

ethereum-giveaway.info

---

_data/scams.yaml

https://urlscan.io/result/53b1a7ca-6313-4fcb-9739-9cdae9fb3d8f#summary
https://urlscan.io/result/7e0630b8-9ce0-443f-8873-52ca250df10a
address:  0x508e1101755a4a6ae228b0e18002a816ce3418cE

bonus.etherpayout.com

---

_data/scams.yaml

https://urlscan.io/result/054bf78d-9896-4be1-b698-485e17901ef5#summary
https://urlscan.io/result/241fee89-267c-4bc1-8158-813d635604ec#summary
suspected address:  0xfe821f5509fdea3f72362d001697ad8c11f0c111

gram.vc + more

---

_data/scams.yaml

Fake COSS site
https://urlscan.io/result/1f62246a-77eb-4a64-9db6-65480f615381#summary

cosss.io + more

---

_data/scams.yaml

Trust trading site
https://urlscan.io/result/96b871fd-ff91-49ee-9270-3546b7fe03eb#summary
address:  0x5F58fE612DB5B3E97FAf4A2E8f38B4AE295288Aa

telegra.ph + more

---

_data/scams.yaml

Fake blockchain wallet site
https://urlscan.io/result/619b3f1c-a375-4698-a48e-d97279739867/#summary

blocikchair.info

---

_data/scams.yaml

Coindesk IDN homograph attack
https://urlscan.io/result/7657eb26-9f9e-45ea-958c-2e0b8f9bd8e6#summary

xn--coindes-jhb.com + more

---

_data/scams.yaml

https://urlscan.io/result/c3e24633-e6e0-48f3-9525-d36dd402c5f5#summary

mybinance.info

---

_data/scams.yaml

https://urlscan.io/result/fadf6395-0a84-4481-bc7c-f3681409da78#summary
address:  0x1e3c07Ce10973fCAebC81468af1d3F390d2A4c71

eth-giveaway-706.htmlcomponentservice.com

---

_data/scams.yaml

https://urlscan.io/result/c9ffd9f7-5257-4805-9397-e86d3ad1d9cb#summary
address: 0xb65DB9F684F3BFa45Ad3fB4CDc4120618Ad81f00

eth-giveaway.com & syncfab.eu

---

_data/scams.yaml

https://urlscan.io/result/ee62040a-cb06-4d67-a485-fd5f4b45d9fc#summary
address:  0xD33441A44Da0c1DCEE596aBB7ebDCdBa77c7DDBd

eth-giveaway.info + more

---

_data/scams.yaml

https://urlscan.io/result/b08168e4-20d0-4aa1-9ad3-40801ee73bb8#summary
https://urlscan.io/result/87a295ba-ba34-4534-8db9-710059c7fa2c#summary
address: 0x6642cEc9d02e4e669103a3Ed4F3505F437b8fe73

ico-gram.net

---

_data/scams.yaml

https://urlscan.io/result/6731a5d1-581e-4647-9fcd-82a1846804e7#summary
address:  0x34eeA3e741F9A3e77fB34E0793B1AF36EDC2b0AE

etherscanio.github.io + more

---

_data/scams.yaml

https://urlscan.io/result/85caba12-893e-4496-8fe2-c22be3c4523d#summary

Add celsius-ico[.]network

---

_data/scams.yaml

Trust-trading scam
https://urlscan.io/result/3e0bfb5b-1959-46ed-805f-ab3e3143a0ed#summary
address: 0xAA90aE1b969bc96e82C80E834b5F739E335B7e47

html.house/7htud1qm.html

---

_data/scams.yaml

https://urlscan.io/result/aa804db3-af08-4bb8-97b9-ad5722b2cdfb#summary

add celsiuss[.]network

---

_data/scams.yaml

https://urlscan.io/result/d1227ba5-53fe-4de4-9970-f783a8e9f51e#summary
address; 0x4c7E065915F3B1461248Da453daE0609253E15f1

ethereumtrans.com

---

_data/scams.yaml

originprotocol.online
Fake Origin protocol site
https://urlscan.io/result/841bf6dc-931f-47e8-9d41-69a4058b54b4#summary
see https://github.com/MetaMask/eth-phishing-detect/pull/1173

originprotocol.online

---

_data/scams.yaml

https://urlscan.io/result/cbb1fa46-d9db-4053-8841-9c3b2c7f917a#summary
address: 0x98c29aFea6f69b59AD1790ce2e0EfFc0bd38433F

coinbase-secure-a2k34j.bitballoon.com

---

_data/scams.yaml

Fake funfair airdrop phishing for private keys
https://urlscan.io/result/6a282aff-ccf1-428e-adff-f16eda050f1c#summary
https://urlscan.io/result/5d441727-2622-4147-a03d-8e007ec86e45#summary
https://urlscan.io/result/9cd3582c-d28c-48c1-b170-8fbf692367bf#summary

funfaircoin.org

---

_data/scams.yaml

https://urlscan.io/result/9e4c361c-6946-4ee0-9b60-4cc4b12c7052#summary
https://urlscan.io/result/990c1b48-5da7-4391-bd7d-bf38304694b3#summary
address: 0xa7fA566eF4F221737a7c89C3600F1e456c7D6604

tongram.me

---

_data/scams.yaml

https://urlscan.io/result/f84a57ba-66ab-4060-bcdc-157915f4e2c8#summary
address: 0x47fEa7bB88BECA144E82Ce96A20A25A0974BA6Ba

ethfreeget.com + more

---

_data/scams.yaml

https://urlscan.io/result/346bb98b-3172-4abe-a6b0-d42f9dc0a592#summary
https://urlscan.io/result/fcb7c79e-a4c8-4dee-8a62-3c6f30cd8ce7#summary
address: 0xeab859E0167eae260825cf1c68c1ACe1323452

icotonsale.com

---

_data/scams.yaml

https://urlscan.io/result/904fa9f9-a4c2-4e6d-963c-0e4808ffd470#summary
address: 0x5Bf2Df6EBCf90665d513C761ce5e516D99AE748A

ethereum-transfer.online

---

_data/scams.yaml

https://urlscan.io/result/7c431eaf-208e-4326-b3e6-5dc83360fd66#summary
https://urlscan.io/result/719c7609-e111-4bd8-978f-2ee7da4962c5#summary
address: 0x4dbef9b86bb3174312d1377b2623db2a9caa5137

trust-cryptopayment.com

---

_data/scams.yaml

https://urlscan.io/result/f4a44c0e-7ead-4f43-9675-f93a1bdf0006#summary
address: 0x44ce1DE2379Aa6d6d4ad46c3531b9EEbB71f7F54
see: https://twitter.com/sniko_/status/974336960901902337

binance-promo.net

---

_data/scams.yaml

https://urlscan.io/result/df098457-a0e8-40c5-a77f-21916546c2f2#summary
address;  0xfF2f6c6fbd71a078f1C1781855467D30897b5a33

eth.hn + more

---

_data/scams.yaml

Trust-trading site
https://urlscan.io/result/71e49f5a-b66d-4547-8df7-b65dd1f60298#summary
address: 0x410ebb88525ea799ea9e15a03f794f7f6f2fbdcd

owainpritchard.co.uk

---

_data/scams.yaml

Phishing for private keys
https://urlscan.io/result/d330104d-9d16-49de-9183-6c4ba6a870da#summary

myetherwalletradeico.blogspot.de

---

_data/scams.yaml

https://urlscan.io/result/72e56803-8480-4fb3-8255-24d92efc504d#summary
address:  0xd11d565Ba23b523ef7737AA24BdbB75a06521d87

ethgive.github.io + more

---

_data/scams.yaml

https://urlscan.io/result/4bd6b891-35da-465a-8543-196d15ccc626#summary
address: 0x303345349Da72a28D12d5515F145dD77cB84BACC

etherfreegive.com

---

_data/scams.yaml

https://urlscan.io/result/592848b4-8b04-46cf-bc51-8c97e14832f5#summary
address:  0x14258A5ddCad7001e8ac89B539df7E0f08A34500

eth-promo.com

---

_data/scams.yaml

https://urlscan.io/result/f5df1ffa-90b7-4602-875b-d9c862950dd9#summary
address; 0xe00e1f7117a69c34694ac1815177c93491fc448f

eth-giveaway-vote.bitballoon.com + more

---

_data/scams.yaml

https://urlscan.io/result/616b53db-39ca-4f14-a974-acc8f556a958#summary
See https://github.com/409H/EtherAddressLookup/pull/376

top-mining.pro

---

_data/scams.yaml

Fake Galaxy Esolutions crowdsale site
https://urlscan.io/result/fe543f0d-add1-44a7-b45b-60fd7fa9967d#summary
address:  0x687aE5Cc3978BC07dB0B7f4D76FbAde966cf4Ba8

galaxy-es0lutions.com + more

---

_data/scams.yaml

trust trading scam
https://urlscan.io/result/2e717a63-f528-4ca1-9eee-29f50809ddb7#summary
address 0x70E02b0509D67AdE18914729d3905994585a5087

etherscan-giveaway.epizy.com

---

_data/scams.yaml

https://urlscan.io/result/a3fa5105-1e8f-4e3e-80c0-041503f186d2/#summary
https://urlscan.io/result/98766ef3-3fbd-462c-b31d-4e0023dbf53e#summary
https://urlscan.io/result/d7f5e4c4-3926-4ddc-9ea3-47b6ddfbee47#summary
address: 0xb7de9e51b7d0b7b67195bc8ad1182b7df38abb0b

telegram.ceo

---

_data/scams.yaml

https://urlscan.io/result/7205ad8f-8e61-4fd2-bc29-1d12a38d3724#summary
address:  0x6a0e59Af84F7a9afa5708B5E43C4845b17AedAAc

geth.cc + more

---

_data/scams.yaml

https://urlscan.io/result/c3b0b18b-7af8-4331-9c92-dc7e7d40c5c5#summary
address: 0x40949225c4a1745a9946F6AAf763241c082cb9ac

ethpayment.bitballoon.com

---

_data/scams.yaml

Promoting a Google Chrome extension that will overwrite 0x addresses to their own
https://urlscan.io/result/3b2c7b8d-91d4-46de-92e2-3200c44acd96#summary
https://urlscan.io/result/4a835609-c8e1-419f-9bb7-df81d7bdf46a#summary
https://twitter.com/sniko_/status/975778109294247937

coin-zc.com & xn--bitcon-mwa.com

---

_data/scams.yaml

Fake Metronome crowdsale site
https://urlscan.io/result/57828914-dc4b-4e6f-b661-49f10429a055#summary
address: 0x092A334eA43C0512560f6acF301FA97805cab392

metronome-token.io + i-myetherwalnet.com

---

_data/scams.yaml

ethdrop.info
https://urlscan.io/result/7fa6d5fd-0240-4916-b107-7eeae51e5f20#summary
address: 0xEBA3dbE720092b2c120Fa5b6752936477Ab4Ec6b

ethdrop.info

---

_data/scams.yaml

https://urlscan.io/result/31ac05e3-44d4-4ee4-9e21-8ad4425f6d24#summary
address: 0x62c71581708dD73b10e7aa2249778AEe016eBF0e

ethpayd.com + more

---

_data/scams.yaml

Fake Binance
https://urlscan.io/result/f0af9ec0-c836-4082-a5db-9e106a64ec9f#summary

binancce.ml + more

---

_data/scams.yaml

Fake Hedera Hashgraph crowdsale site
https://urlscan.io/result/4178854b-4b28-469f-a6ab-37bc2e6f1d4e#summary
https://urlscan.io/result/a51e9d44-8f0f-4caf-bf27-c54f421c6605#summary
address: 0x1e071281416B20aC2cd50D2e8093B43f8526940a

hederashashgraph.com

---

_data/scams.yaml

https://urlscan.io/result/fa02059e-53e2-4406-80d2-6ab248c379ba#summary
https://urlscan.io/result/b8628083-290c-47a8-8b68-17e40e230a4b#summary
address: 0xb490cEC960B665B233d6666F8e2626d8bcAE5d44

telegramsale.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/8f9e2bdb-698a-4314-b2b7-cd1f4c74f48e/#summary

nnyiictehervvailiatt.com + more

---

_data/scams.yaml

https://urlscan.io/result/a0e0c5e4-f5cd-4c2f-838b-f5c06780aa54#summary
https://urlscan.io/result/8721690b-1124-4015-93cb-69f5cbeea617#summary
address:  0x31E2f659e5371f95dE47BE79E1d5027caf0da39D

tonpublic.org + ton-telegram.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/45e5304b-560c-485f-a2d9-be763fd45a8c#summary

myetherwallet.heliohost.org

---

_data/scams.yaml

Trust-trading scam
https://urlscan.io/result/a16f62ef-f42e-4df6-af74-46b4f884f4ec#summary
address: 0xefbb57bef8ecab67c45b5c62c5e1b7e5985478de

telegra.ph/Justin-Sun-is-giving-away-20000000-TRON-TRX-03-22-2

---

_data/scams.yaml

Fake Binance
https://urlscan.io/result/ede9d361-8dbb-41ac-a4dc-0e0f725ec1fd#summary

blnnance.com

---

_data/scams.yaml

Gas phishing site - "generates" coins but asking for gas money
https://urlscan.io/result/8d094bfd-6583-4336-85df-1a2d4f4baf7b#summary
https://urlscan.io/result/623e3078-402d-4684-a544-d21f7ddb995c#summary
https://urlscan.io/result/c2fe4ad5-f038-41f8-b03e-8c014b6b5700#summary
https://urlscan.io/result/461c4a8a-e74e-4bd2-b8a5-e5071d7a9e02/#summary
address:
0xaAc6020b6216BE72Af7B3c322dd27cea257276b3
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0xaAc6020b6216BE72Af7B3c322dd27cea257276b3
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0x94D50168D9Bc80cc39AFFbcBA8232AcD89F117A3
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb
0xf3A6F2796d5B16F658431bD7A19087A37eA9fAfb …

coinmakerbot.com + more

---

_data/scams.yaml

Fake Auctus crowdsale site
https://urlscan.io/result/d29ed74c-ce65-4d42-873d-cb5fabe9565c#summary
https://urlscan.io/result/e310dbcf-913b-4bd9-986b-556b52263d5a#summary
https://urlscan.io/result/463f779e-8778-4001-9a31-638ee77d0a8b#summary
address: 0x4ae9971e28d7f422b406ee1f3bb38e1b96637239

auctuss.org

---

_data/scams.yaml

Fake Auctus crowdsale site
https://urlscan.io/result/7cf2b1b8-e332-4bfe-8853-6b947dc1f9d2#summary
address:  0x0EeE28Fc966585B5848F9D65980Cb1621F9b3f8A

auctus.network

---

_data/scams.yaml

https://urlscan.io/result/f62c67f1-31b6-4c64-9105-932e32d963fa#summary
address:  0x474057ADF42f9F955e86aa1142740f9d7763e41E

tronfoundation.me + more

---

_data/scams.yaml

Fake Shivom crowdsale site
https://urlscan.io/result/9deacfae-60f6-4747-880c-4e953d24ac55#summary
address: 0xE886BfCfa373C17dBC07c7B73f1d368339ac5Dfd

shivoms.io

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/475842ba-d15c-4de7-a40a-40b9b7f5ff97#summary

nnyiicteherwailiatt.com + nnyecthenwellat.com

---

_data/scams.yaml

https://urlscan.io/result/dca8e52f-b6cc-4cfe-9f79-92b6f4c9eeca#summary
address:  0x5dfAE1C25EC5232F1D725d5265ceDDD7102BE5B4

ethgiveaway.club + more

---

_data/scams.yaml

https://urlscan.io/result/2bc3d357-ad2c-4577-b06e-7c8348f5daf3#summary
https://urlscan.io/result/dd01b145-5b97-428f-9c11-ba741fa37595#summary
https://urlscan.io/result/9704ce2b-25d7-4430-a337-51fcd449d8f5#summary

kinecosystem.net + more

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/d1e5d763-e142-4667-a079-00167e0615f0#summary

myehcrwalilet.com +  mynbethernvwallet.com

---

_data/scams.yaml

Fake MEW
https://urlscan.io/result/97ec356d-e13d-4590-bf78-cb2fa7d0d7d5/#summary

myetnarvellat.com + more

---

_data/scams.yaml

https://urlscan.io/result/7502848b-37ca-4f4c-9747-e068e48dbf50#summary
https://urlscan.io/result/13f82373-e265-41fc-813f-3712c9b744e3#summary
address:  0x049b01966f721db6EC76097043e9D6ecCaF719B6

cz-binance.com

---

_data/scams.yaml

Trust-trading scam email
https://uploads.disquscdn.com/images/a256fa0b02f553f818b6d231a6b8d95b62e409648b351e20461c57f7fe4b7423.jpg
address: 0x9f4562c9be26c7020909b50ccde3447f1b8c4b21

nsdmilea@gmail.com

---

_data/scams.yaml

https://urlscan.io/result/99df7a1b-a187-4df3-aaa1-afd88ac98302/#summary
address:  0xAba9897C9422b1C30733169D3dA7Ff83D7f23044

get-eth.pl + more

---

_data/scams.yaml

https://urlscan.io/result/bc1a39c6-b716-4e8c-b0cf-f9063ac08bb6#summary

airdrop-bluzelle.com + more

---

_data/scams.yaml

Fake dfinity crowdsale site
https://urlscan.io/result/14a14d73-abda-4b6a-b581-fe126f7163e0#summary
https://urlscan.io/result/4558ccba-b754-46d7-8c64-2c2ee4db552e#summary
address:  0xA95391C51788f884BECA472bf71Cdb000a2eEd65

dfinity.org.in

---

_data/scams.yaml

https://urlscan.io/result/3c86facf-d9ee-4293-b7ab-150b31015e71#summary
address:  0x8D551F2a2d0908854e0E030564261c9Ff2E8dd56

cryptoplus.be + more

---

_data/scams.yaml

myetheurwallet.com
https://urlscan.io/result/d31fe922-28bd-470a-ba54-773554740a48/#summary
myetnarvellat.com
https://urlscan.io/result/931444c3-3bb7-4849-bfc0-479e21add808/#summary
nnyctncrvvallet.com
https://urlscan.io/result/0f7da764-e4a7-49b2-b37f-fe86c50ebbfa/#summary
nnyctncrwalliet.com
https://urlscan.io/result/5bce0ccc-9d3b-48e6-a092-06747461c6b1/#summary
myuuetheraswallet.com
https://urlscan.io/result/2e5507ac-0ca1-4ea0-86e5-c99bbbf53c2b/#summary
myunetherhawallet.com
https://urlscan.io/result/f0e39243-c2e6-4655-bb5c-acd3e829f020/#summary
myotherapywallet.com
https://urlscan.io/result/49e51423-2789-4837-9da7-37a244f72fce/#summary
mybethernvwallet.com
https://urlscan.io/result/8b1f66a2-6ceb-4407-b2d8-3a54fc0093db/#summary
myetherapywalliet.com …

A list of fake MEW domains

---

_data/scams.yaml

https://urlscan.io/result/4c71c0a4-d4bd-4362-975e-7ef67ebd3f74#summary
address;  0x787e8f0e406cb71a22fd2023316f231d0311b14f

tron-nextlevel.bitballoon.com + more

---

_data/scams.yaml

Fake MyCrypto
https://urlscan.io/result/cd8fef7f-8ca8-4abc-ab3f-e3626276c6ee#summary

mycrypto.company

---

_data/scams.yaml

https://urlscan.io/result/970dbe89-c27e-4b8d-96b7-d1df54782dff#summary
address: 0x83ec306df6BEe5320cF6a57A52ff732791c65B47

ethereum-promo2018.bitballoon.com

---

_data/scams.yaml

Fake Telegram ICO
https://urlscan.io/result/e313730b-056e-4f57-81b6-4632ba21d891#summary
address: 0xdDb690eF629a2e9277808c25EB5f9259d939Da

gramtokenico.com

---

_data/scams.yaml

Fake CTR refund page
https://urlscan.io/result/b7d81b16-b2e3-45ec-b521-e7fef6ce0dc0#summary
https://urlscan.io/result/e4ba38c3-b4cf-4dc7-8b1f-3eb42087c391#summary
address:  0x87b4eed5a781d8b847645082410070f002b41e13

centratoken.site + more

---

run.js

MetaMask status was always showing as blocked, even when not blocked.
Now showing blocked urls:
And not-blocked urls:
Note: Images were taken from old Infura blacklist pull, functionality still relies on cron being run to update '\_data\metamaskImports.json'.

uncomplicate and fix metamask-status check

---

_data/scams.yaml

https://urlscan.io/result/578eb2b9-6320-487a-bbe5-108024e446e1#summary
address: 0x25f754ade28ec1ed771ee22efeaed764847181e3

telegra.ph/Bittrex-giving-away-5000-Ethereum-ETH-03-26

---

_data/scams.yaml

https://urlscan.io/result/92ceea90-3cc4-4afc-9d1e-ab0a2066fcaa/#summary
address: 0xb1FaCA3Ef83134815C3e28899Cb132e019EB6616

free-5000eth.com

---

_data/scams.yaml

https://urlscan.io/result/02367f87-57e6-47fe-b7b9-4a62f76b8bf5#summary
https://urlscan.io/result/37cf1270-8cae-4b38-85cd-3f3dca2435c2#summary
address:  0x319Ce3233D17b45d49AAa9414F154832d0F9Aa61

ethhit.com + ethereumpromo.info

---

_data/scams.yaml

free-5000eth.com
https://urlscan.io/result/3928cb92-180f-482d-b63e-53c3bfffd523#summary
address: 0x41Cd1343C6e497C075b7ed1E9f003d65141833E2
giveawayether.com
https://urlscan.io/result/9d1bcab7-f7e2-4318-a52f-6fd3cd8d4680#summary
address: 0x7C14369F68d7812C105a597Beb13FF8dA64520c5
giveaway-ethereum.com
https://urlscan.io/result/fc5b790a-bb33-4cf3-a6b0-828afa2a0901#summary
address: 0xf8178B379Ec4Fd758230D28c55c89c064708DFE5
ethpromo.gift
https://urlscan.io/result/666c6e28-31f7-4ab6-8617-f198b9190f52#summary
address: 0x6a13e6d0251fba7b474cf4468aa157ee0c6a736c
ethergiftwallet.com
https://urlscan.io/result/1073c8cb-e653-44c3-8d78-93446e5922b8

trust-trading scams

---

_data/scams.yaml

Fake Hedera Hashgraph crowdsale site
https://urlscan.io/result/8f171e6b-7227-43ed-bbfc-820b6dc67ced#summary
https://urlscan.io/result/34f61e8f-549d-4c13-8e94-c2a456269489#summary
https://urlscan.io/result/e5cf1c78-552e-43be-98e6-b402ebd0fb34#summary
https://urlscan.io/result/634a0ac0-7542-4f58-a599-8ee3adbe6a00#summary
address:  0x311c65dCBE025eaD81CaB2925b81489123Ce2EdA

hederahashgraph.tokencrowdsale.info

---

_data/scams.yaml

Big props to 409H/EtherAddressLookup#443
5000eth.info
https://urlscan.io/result/406c1fbc-ce4b-419c-98d6-c01e60784ec8/#summary
address:  0xf985aa8117999fa3f0f9e71a20d0fe7b88b9d706
authorize.live
https://urlscan.io/result/52d40e83-39ec-41d2-b5a7-dac3444637ee#summary
address:  0xefeddec5de1aef4c70b264d7b56b6d479b3ba520
azone-web.com
https://urlscan.io/result/e995033a-6e53-4e64-8278-75a807bc38ca/#summary
address:  0x65F6C0e45758526982Fa5f63AC877384ea5a91Bd
binance-giveaway.firebaseapp.com
https://urlscan.io/result/9a773096-ca53-4a18-880c-7d025c27f378/#summary
address:  0x2C05D74Cd9F878b9834a50092043BDE944A60eF8
bitwelfare.biz
https://urlscan.io/result/8c5d0f38-e62f-48b3-870a-ea5dccae2fc7/#summary
address:  0x5ac8306d4C4AC8f95fAB23aCa0b3C41890B77eb6
cryptocurrencies-bitcoin.com …

More eth giveaway domains

---

_data/scams.yaml

https://urlscan.io/result/726b3b82-649e-4d00-bf95-05ac0917abae#summary
address:  0xe00e1f7117a69C34694ac1815177C93491fC448f

eth-give-away.webz.cz + more

---

_data/scams.yaml

https://urlscan.io/result/5759564a-8a90-422c-98f3-a64d2df1d07c#summary
address;  0xF42788CBBdb00a32a981355ec5b9143b3C639c74

ethc.fund + ethereum.czweb.org

---

_data/scams.yaml

https://urlscan.io/result/ac0b23c5-36ff-44b9-9767-798136293672#summary
address: 0x41Cd1343C6e497C075b7ed1E9f003d65141833E2

givingawayethereum.com

---

_data/scams.yaml

https://urlscan.io/result/0083e3ab-1749-4aab-9896-2a2d05d578d7#summary
https://urlscan.io/result/e4bf722e-4bde-453e-89ee-dcbb138f5cb1#summary
address:  0xe00e1f7117a69c34694ac1815177c93491fc448f

ethereum-give.byethost16.com

---

_data/scams.yaml

Article and links pushed via a fake BBC news article and site.
https://urlscan.io/result/a27f3efe-5ce6-4fd9-a66a-61799eaa3cbd#summary
https://urlscan.io/result/7c058395-c892-4f7f-9e39-3d47e3ac284d#summary
https://twitter.com/sniko_/status/984030320642154497

smartolinks.com livivid.com clickmoneysystem1.com + more

---

_data/scams.yaml

https://urlscan.io/result/b452d273-71ab-44fa-83b2-ca0d78ba1bc6
address:  0xe00e1f7117a69c34694ac1815177c93491fc448f

ethereum-giveaway.com

---

_data/scams.yaml

https://urlscan.io/result/b9d3fd76-444c-4ffd-8d2b-2c972103a10c
address;  0x0CfdC4A2c05B1Ff5fCe36d1c1982D8666D7A9813

givingawayeth.com

---

_data/scams.yaml

https://urlscan.io/result/ab3d5a44-8da6-42d1-9f70-5b4565b5ff5c
address:  0x0E0bA79CB92E07555eF7A3fe9e18BA33dd0b6D29

ethereums-2018-give-away.bitballoon.com + more

---

_data/scams.yaml

https://urlscan.io/result/4095eeda-e5e0-4ad0-b9ca-98d96059e616
address: 0x7BBCEe71e2283C445bdB076Bb7FA187726A45D53

ethereum-giveaway.tekcities.com
