MrLuit/EtherScamDB

_data/data.yaml

Reported via etherscan disqus (moderation queue) - confirmed site is cloned of kickico.com (most pages redirect to there except the ico - gives a non-contract address also)

kickico.co & bllttrex.com

---

_data/scams.yaml

starbase.pro
Fake starbase.co site. Phishing for funds.
https://tokenmarket.net/blockchain/ethereum/assets/starbase/
https://twitter.com/StarbaseCo/status/905231250125864960
---
herotokens.io
see: https://github.com/409H/EtherAddressLookup/commit/6207370a662d2850c7376f42f8b4f4ccf58bc3f8
---
omise.com.co
Fake omiseGO site. Airdrop form with classic `sign.php` for the private key.

starbase.pro & herotokens.io & omise.com.co

---

_data/scams.yaml

fake https://protos.tokenhub.com/ crowdsale site - reported by GriffGreen

protostokenhub.com

---

_data/scams.yaml

> This message was shared on all Slack channels in the hope of reaching as many EtherDelta traders as possible.
> 
> Due to the recent security flaw discovered on our servers ( https://medium.com/@rleshner/security-vulnerability-etherdelta-10556d6e72a ), we are asking all our users to remove their private keys from EtherDelta until we issue a hotfix. 
Complying to these measures will ensure the security of your account and the safety of your funds.  
> 
> Please visit https://etherdelta.github.io#removekeys to securely remove your account from our servers.
> 
> We are sorry for any inconvenience this might cause you, but we are taking security seriously and  we are assuring you that our team is working around the clock to issue a hotfix. 
> 
> We will keep you updated on …

etherdelta.su

---

_data/scams.yaml

Adding to the database until their github/website/social media release a statement.
There has been several reports that this ICO (WorldOfBattles / WoB) is questionable. This is the contribution address on their site, and no tokens have been distributed (this isn't a smart contract address also). Their website is now down. Github profile is now down. Many pro-teams that were listed as sponsors have never heard of them.
Reddit thread: https://redd.it/7709pe
Sponsors-not-sponsors: https://twitter.com/HELLRAISERSgg/status/920380136259751936 & https://twitter.com/teamsecret/status/920266260428050432
Cache: https://urlscan.io/result/3f5caf73-c93a-4dcc-860c-44ccbc696592#summary (from google cache October 16, 2017 0821GMT)

worldofbattles.io

---

_data/scams.yaml

Hello,
This is a phishing site against Privatix.
Phishing site: http://privatix.pro
Original site: https://privatix.io
Technical details:
Domain creation date: Yesterday (2017-10-20)
Domain holder: No details - Privacy  Protected, and under CloudFlare
Malicious content: The attacker change the wallet address to his own wallet address - trying to steal money. (https://etherscan.io/address/0x071cf579507DD0661845694F709E68CF7Ea506a4)
More Details:
http://privatix.pro is an impersonating site, aiming to phish customers of Privatix, which is now in the middle of an ICO (selling digital currency). 
Their original website is under https://privatix.io. 
Privatix confirmed this is not their site.
http://privatix.pro had been purchased yesterday (Oct 20), and behind CloudFlare.
This is the 3rd …

Update scams with privatix.pro latest scam

---

_data/scams.yaml

Fake wabi airdrop site, asking for private keys
https://urlscan.io/result/cc12d587-e2f0-45a9-87a7-9945601998b7/#summary
https://urlscan.io/result/c83115d4-0b03-4c94-8b2f-4ebdace5c80b#summary
https://urlscan.io/result/61797582-ea15-4ffa-a658-399f57b562e8#summary
https://twitter.com/StevieMatCrypto/status/942686772609409024
reported address: 0x29e225d888cf11c5e67613bffd30bcf071eb3d4a

wabicoin.co

---

_data/scams.yaml

Fake cointelegraph promoting fake airdrops - promoting `xn--os-g7s.com`
https://urlscan.io/result/dfe4ef7b-ec72-483c-bb4f-61c218a948c2#summary

xn--coinelegraph-wk5f.com

---

_data/scams.yaml

Fake Ethereum web wallet not crediting users the ETH they send
https://urlscan.io/result/b38e8a91-07a4-4a5f-bcd2-86c7a4560142#summary
address: 0xc0fed35b43f59c2bfb1eb544bd8921bfb18140c2

ether-wallet.org

---

_data/scams.yaml

Etherzero domain, but nothing supporting it being the legit domain. Also hosted on a server used before to host other phishing campaigns. Asking for your chain code.
https://urlscan.io/result/377618e7-96dc-4ef6-b4e7-1ba88c0f4d86#summary

ethereum-zero.com

---

_data/scams.yaml

grampreico.com
https://urlscan.io/result/946380cf-37a9-48ee-8c24-f5746a01724c/#summary
address: 0x26F7Eb488661C33c43089aD61944f3231222b32f
tgram.cc
Fake Telegram ICO site
https://urlscan.io/result/fe30f20e-6cd9-4603-85b5-903e154eec1b/#summary

tgram.cc and grampreico.com

---

_data/scams.yaml

Fake kodakcoin domain (www.kodakcoin.com) redirecting to a binance referral. Blacklisted for worst case.
https://urlscan.io/result/e8731acf-e3a9-4637-a0b0-84426e9e0009#summary

wwwkodakcoin.com

---

_data/scams.yaml

Fake blockchain.info website
urlscan cannot resolve it, neither can I.
```
Non-authoritative answer:
Name:    block.chaiins.in
Address:  128.199.45.227
```

block.chaiins.in

---

_data/scams.yaml

Fake beetoken domain redirecting to a binance referral. Blacklisted for worst case.
https://urlscan.io/result/796109f8-e4c0-4ea4-85f0-51a2082fbe26#summary
https://urlscan.io/result/3aa8733f-ebfa-4740-8490-53db2d00b9da#summary

beetolen.com & beetokem.com

---

_data/scams.yaml

address: 0xb2172027cb233198A3945A2c864f1Ec5b7E3b3Da
https://twitter.com/durov/status/944360557318205440?ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Ftechcrunch.com%2F2018%2F01%2F20%2Ftelegram-ico-scammers%2F
see https://github.com/MetaMask/eth-phishing-detect/pull/783

token-gram.org

---

_data/scams.yaml

decentral.market is a fake cryptocurrency news website that posts articles from other sites. When it copies ICO participation guides, it replaces the contribution address with a different address.
Example: Arcblock and Republic Protocol have the same Ethereum address (0xdefb014b9e2f3bd81cdb084821f99b681cfca695).
https://urlscan.io/result/13e72351-ec0c-4ea0-89b4-c2b9e3031197#summary
see https://github.com/409H/EtherAddressLookup/pull/282

decentral.market

---

_data/scams.yaml

promo-give-ethereum.org
Trust-trading scam site. Promoted by Twitter ID: 992951433690398720 (@Aurora_dao_)
https://urlscan.io/result/9cfea787-9e9c-4308-ac22-6ab050e87034/
address:  0x7D922A4f7F24fFcb130c4EEAF291A6475e3e4Dd2
give-ethereum.org
Trust-trading scam site. Promoted by medium-give-ethereum[dot]org and Twitter ID: 992951433690398720 (@Aurora_dao_)
https://urlscan.io/result/407e88cd-8108-4192-8053-8ef3836dcca8
https://urlscan.io/result/265b0fbe-0276-4253-8843-c393d3e475ad/
address:  0x7D922A4f7F24fFcb130c4EEAF291A6475e3e4Dd2
ethereum-giveaway.site
Trust-trading scam site. Promoted by Twitter ID: 132293081 (@Aurora___dao)
https://urlscan.io/result/e107a9cd-bc1b-41f7-8f39-c51c4d2749c5
address:  0x299628fD380813622305517E64eee89BB6a49Ca3 …

promo-give-ethereum.org + more

---

_data/scams.yaml

telegram-token.io
https://urlscan.io/result/0aec803b-c326-4ca4-ad12-3d1fa1598f87
https://urlscan.io/result/bae9712f-b5ce-465b-8ac6-df6f613d2da7
https://twitter.com/sniko_/status/994604991187996672
address:  0x52bEF206E8e0403Cd60d37E48f4F3860D9545556
icostats.io
Fake Icostats site promoting a fake Telegram site, using ICODrops twitter unfurl data
https://urlscan.io/result/d668399e-b22b-4d6d-aa28-2c25e7661ba5/

telegram-token.io + icostats.io

---

_data/scams.yaml

privcoin.io
Fake Ethereum mixer
https://urlscan.io/result/984000c1-2232-43b0-94ab-3f954960bf10/
suspected address:  0xa3e785ee490e1102fe32512973c96Dc7DC876348
free-eth.paperplane.io
https://urlscan.io/result/0d58983b-a077-40eb-bb0c-9955258ccc6a/
address:  0x92cd726CE03cEaa4bF7198ce9c52D05D63ceE575
ihcx.market
Fake Idex market
https://urlscan.io/result/3c3cec2a-4925-4a3f-b615-3210c37f7de9/
https://urlscan.io/result/b60ca10a-76fc-4a30-a930-e280e0b40c50/
helbizcoin.net
Fake airdrop phishing for private keys linking to a fake MyEtherWallet xn--myetherwallt-ovb.net
https://urlscan.io/result/f70319e5-9548-47f9-9c87-5b09bef7b218/
https://urlscan.io/result/f388ff99-cafd-4b53-94c3-f630f2342407/

privcoin.io + more

---

_data/scams.yaml

xn--polonix-17a.com
Possible Fake Poloniex - IDN homograph attack domain
https://urlscan.io/result/dd1c3447-e641-44ab-804c-fa2ba168011a/
xn--tro-k5y.com
Fake Tron site - IDN homograph attack domain - directs user to fake MEW xn--myethewalet-ms8erq.com
https://urlscan.io/result/697570b9-b0b3-4300-bfda-43ee4e9a86e6/

xn--polonix-17a.com + xn--tro-k5y.com

---

_data/scams.yaml

etherfree.tech
Trust-trading scam site, promoted by twitter userid: 330491787
https://urlscan.io/result/16734e7f-017f-454f-ad29-0a60191e75ee
address: 0x8C9D135aC2778e1A7d326932AaD302e7c22c94D7

etherfree.tech

---

_data/scams.yaml

5000ethereum.online
https://urlscan.io/result/6d91fc66-0751-4b26-8a13-016ab6bee276/
address: 0xa5e83199a7ECB6669064d492F15ddC096b6cbAb8
hederahashgaph.com
Fake HederaHashGraph crowdsale site
https://urlscan.io/result/72f0e61c-b7ba-42af-895d-487a696e80e9/
https://urlscan.io/result/10818b4e-04d7-403b-b1bf-52957b2557da/
address: 0x873a35F651892AEe1D9360be80ae904f7D76068f
5000-eth.paperplane.io
https://urlscan.io/result/9cc72afa-df4c-49f9-a640-65bc2cb2e3f5/
address: 0x1691B2F9986598E12C57Aba5bE50ebd5346247E0
ethpromo.org
https://urlscan.io/result/e780ae7d-4702-49f5-874b-bc8802e2d843/
address: 0x52beED3924b0824411D03EA2fE51E429717dcF10
zilliqablockchain.org
Fake Zilliqa airdrop phishing for private keys …

5000ethereum.online + more

---

_data/scams.yaml

ethgiveaway.zkr.kr
https://urlscan.io/result/6a755409-20bc-48b9-8af2-b21b10b2dfb5/
address: 0x9852286460022e5151381361bA4271c7272cF966
eth-promo.wixsite.com
https://urlscan.io/result/9a662a44-7d02-459f-86b6-76a81e2cc6da/
address: 0x9852286460022e5151381361bA4271c7272cF966
calchain.io
Fake airdrop emailing users to go to signupform1.typeform.com via email, which then directs them to xn--myetherwalt-kbb96i.com
https://urlscan.io/result/4192662f-9496-4572-a45c-b24143ff721b/
https://urlscan.io/result/2ca50f69-3fd0-4e91-8cc2-4502977e7e2b/

ethgiveaway.zkr.kr + more

---

_data/scams.yaml

ethofficial.info
https://urlscan.io/result/2528f876-0fd3-4e8a-b7ea-28ba969544c0/
address: 0xfB03e59c83b984DA0f6a5575B955541af28cCC65
getsomeeth.com
https://urlscan.io/result/27470387-5834-4428-8ae0-7b5feadea1fb/
address: 0xdb850d7dC1aDe8eC00CE4269e732d3Aa44286f73
giveawaycrypto.org
https://urlscan.io/result/ff03cb73-050c-4b93-81f6-6b03d49b80c8/
address: 0xeaA4b711e7C025899460b429BeF1ff8155ba4C66

ethofficial.info + more

---

_data/scams.yaml

ethpromo.cc
https://urlscan.io/result/77f317d7-44a8-4774-affc-f1303fc1a409/
address: 0x05e85D73Eaf6fEF228294fdF867aBBa98552A99F
idex-market.eu
Fake idex phishing for keys
https://urlscan.io/result/4fbd0c72-4bca-47eb-890a-8197a14a1a42/
idex-login.net
Fake idex phishing for keys
https://urlscan.io/result/7b3fe2c9-cefe-4463-886c-d4dd3cdd0623/

ethpromo.cc + more

---

_data/scams.yaml

ethereum.website.tk
https://urlscan.io/result/5b2b4fa8-e28e-4ec7-bc2b-6fcdef12551b
address: 0x0E2fA227599b1701cEEEcfBF0c92d8D23b2F493e
ethereum-bonus.com
https://urlscan.io/result/bc0f3c67-c250-4fe1-8763-3e699d199f19/
address: 0x916d37534f95f30c35A60a58150F48c2D0fF4Be2
blttrex.us
https://urlscan.io/result/036952c2-98a8-4388-924e-ee0e50d54ee8/
address: 0x92d43D2f55E077D1beBC6e348a9F4FF64fD4F21A

ethereum.website.tk + more

---

_data/scams.yaml

get.ethpublic.com
https://urlscan.io/result/5e9a29e9-648b-43db-b2f6-510ef6a1f0d7
address: 0xe4fc4C3889B5442391acAD627673F4Ef7Efe7B97
ethpublic.com
https://urlscan.io/result/4177f5a4-4828-442b-9462-2e5c773cb873
address: 0xe349B26753ECa84A2858901d414c612c8c8e20f9
ethereum-get.org
https://urlscan.io/result/2dae7ce1-aa28-432e-b625-6e5253d3ac3e/
address: 0xaBbD5F7D4DE3c91706c73FD7d09b9ec3Ed9cA697

get.ethpublic.com + more

---

_data/scams.yaml

kentra.tech
Fake airdrop directing users to a fake MyEtherWallet - xn--myethrwalt-inbe64c.com
https://urlscan.io/result/5a6ac1e3-1447-4ef8-a0e8-d3f9aaf00f46/
https://urlscan.io/result/a15f09f4-5548-45e5-addc-edc3acf01648/
xn--myethrwalt-inbe64c.com
https://urlscan.io/result/03af7e40-ebcf-4056-ad3f-57f0402d9597/
https://urlscan.io/result/0bcb0635-0977-4d72-a673-618195cbf5d1/
address: 0x0A796062214Cf4FC232Dd8538a19035Ac79a595c

kentra.tech + xn--myethrwalt-inbe64c.com

---

_data/scams.yaml

creteprint-driveways.co.uk
https://urlscan.io/result/fc1a6bf3-235d-458e-a55f-85c1a8d6a88f
address: 0x607c78AeAaBADb84AdC3298fb3077fc75429e8bD
ethype.org
https://urlscan.io/result/6f03f717-aa58-4b9f-a92c-0b88c0e78d1b/
address: 0xB9b848702a47AE78A70D18c45e552aB1637B5908
etherpromotion.org
https://urlscan.io/result/f67991dc-a3e4-4221-b9bf-ef59c39850f7/
address: 0x32Ea6b24675349EDb6dF2896457819289Aad180E

creteprint-driveways.co.uk + more

---

run.js
update.js

Casts addresses as lowercase in the cache and display to allow for /api/check/ for addresses functionality to be case-insensitive.
Fixes #927 
Now lowercase and uppercase addresses in api both return the same content:

Fix addresses get api

---

_data/scams.yaml

ethpromoaction.com
https://urlscan.io/result/e3492e92-5d7a-42e8-ad25-5c9252f03281/
address: 0xBee06db915F38C62D61aBa80932369007bEAe9d8
ethinfo.org
https://urlscan.io/result/c447f9e1-028c-4ade-a59e-400ac2dbb767/
address: 0x34b6341655061f4B5830CD1a7B20A3516043AF57
airgws.org
https://urlscan.io/result/01d49f90-753a-4483-a517-d35b894e5ff7/
address: 0xc364451d6316Be34CB1b8f8B0922fE59d5CF2Ca9

ethpromoaction.com + more

---

_data/scams.yaml

binance-giveaway.com
https://urlscan.io/result/79b97afe-c7e8-4712-9962-e5a12d7bf561/
address: 0x15B4E32d5026A5A9Ad3b68BEcAdceB00B4eB9729

binance-giveaway.com

---

_data/scams.yaml

elon-shares.com
Trust trading scam site (new address)
https://urlscan.io/result/b17b3d31-871e-4393-a25f-831156179bce
address: 0x9c29046A4178d15aA7BE23e6b73Ef0f2E429A9a1
ethshare.org
https://urlscan.io/result/ba9e9637-afda-4032-860a-aa14ad4048e3/
address: 0x03E115D99F005F9df8AcCeC3F3d07F54b593eE96
ethergive.info
https://urlscan.io/result/f78872b8-15be-46be-ad8b-e77dcf1b168d/
address: 0xC71610821ac6042E52Be9d7d76df4c425F30f41f
myetherwalet.heliohost.org
https://urlscan.io/result/324c8485-c0f9-47b9-afe1-b769a109ee6a/
keyfundairdrop.typeform.com
Fake EOS airdrop directing users to myetherwallet.com.signmessage.me (https://bitly.com/2HTNWuj+)
https://urlscan.io/result/832bef2f-3cd3-46bf-95ad-e694a8879fd2/
eosdash.io
Fake EOS …

ethshare.org + more

---

_layouts/search.html
_static/js/search.js

Fixed the eth address search to link correctly. Previously, it was just linking to `/address/undefined`. Also edited the UI for users to know that they can search for more than just domains.
Fixed: #950

Fixed eth address Search

---

_data/scams.yaml

ethereum-event.com
https://urlscan.io/result/0412668a-97ac-4452-aeba-d26d466ea789/
address: 0x6668bD45B15E2775F03e738Ef6257637A9745287
ethereum-giveaway.safe-eth.top
https://urlscan.io/result/0dce4106-5b81-4e70-824d-a3b09960d8db/
address: 0x637336064f49074587a15cFD785D17Ed02Aebf25

ethereum-event.com + ethereum-giveaway.safe-eth.top

---

_data/legit_urls.yaml
_layouts/address.html
_static/js/search.js
run.js
update.js

Added GET ability on /api/check for ETH addresses that have been whitelisted in legit_urls.yaml
Also added to template for endpoints `/address/<address>` to show verified urls:

Added whitelist api GET for ETH addresses from legit_urls

---

_data/scams.yaml

eosauthorithy.com
Fake EOS domain - phishing for private keys with POST /store.php
https://urlscan.io/result/e09358b9-6ae8-4a67-aaf2-14ddc2fd6561
ethereumanniversary.org
https://urlscan.io/result/5780b378-df75-49c5-8459-c6d178a5a4bd
address: 0xaec2Cc8986BB14C0C604d5Adf725BA33920102bc

eosauthorithy.com + ethereumanniversary.org

---

run.js

Fixes case insensitivity issue for /address/<address> pages by changing req.params.address toLowerCase()
Fixed #1093 
Also handles neutral domains like so:

Fixed case insensitivity issue

---

_data/scams.yaml

bittrexl.com
Fake Bittrex login phishing for logins
https://urlscan.io/result/bdb5571d-e320-4d83-9a21-718c0b45cefa
https://urlscan.io/result/826e053b-78ec-4d5a-9d56-f5fce55372e9
idex.xyz
Fake Idex phishing for keys with POST /sendkey.php
https://urlscan.io/result/f8ab0ddb-1e86-4f9d-89e4-074a663d8fd8/
teslagifts.tumblr.com
Promoting trust trading scam sites directing users to http://etherclaims22.top/payment.php
https://urlscan.io/result/d4bf8844-4e8c-4a19-a670-97ca05d8da8a/
address: 0xAB7EC7596fc05BC55AFc07008cC06c1193eD6f9a
brinannce.com
https://urlscan.io/result/8f424bbb-6ae1-4c41-8540-75ded8c985c7/
https://urlscan.io/result/8de488f7-df50-498c-941d-7358943117ab/

bittrexl.com + more

---

_data/scams.yaml

hydrogen-raindrop.bitballoon.com
Pishing site directing to a fake MEW (via https://bit.ly/2ufxyjC).
Originating from fake telegram channel t.me/project_hydro.
https://urlscan.io/result/eeb4035c-909f-4ca8-9af8-96b17e62cd2f
myetherwallet.ethersignmsg.services
Fake MEW.
https://urlscan.io/result/9ca25375-249c-4d6f-ad5b-66d8cba8a0ce

hydrogen-raindrop.bitballoon.com + more

---

_data/scams.yaml

refundcontract-etherwallet.net
Fake MyEtherWallet. Users redirected over email via https://bitly.com/2L3Ua1a+
https://urlscan.io/result/6b13d39e-005e-40bd-ae29-b45bfc88573b/
idexr.market
https://urlscan.io/result/e4951908-3628-491f-98d0-961ebbb422dc/
https://urlscan.io/result/b2db3889-9b3e-48b3-8226-38c284c4ff8d/

refundcontract-etherwallet.net + idexr.market

---

_data/scams.yaml

coinssafe.org
https://urlscan.io/result/df104578-45c5-4980-8471-4a328f5c875a/
address: 0x68AaCF41FA22ecD5ca0BB102dA46b0f503E2E168
idex.group
Fake Idex domain
https://urlscan.io/result/088fcd3d-2019-4949-ae7e-4cad6703c187/

coinssafe.org

---

_data/scams.yaml

idex-market.biz.pl
https://urlscan.io/result/203a5dfa-5488-4956-b219-3a0dc039b917
https://urlscan.io/result/8b2e6516-ffcd-481b-a7b8-dcaa29d037f3
getethereumforfree.com
https://urlscan.io/result/80a28520-7403-442a-b235-f5467e12e626/
address: 0xC7566BA63f39bA75B56EAdc0328F9A76Dbd1ADf3
medium-hitbtc.tumblr.com
Trust trading scam site linking to http://ethereum-return.com/hitbtc/payment.php
https://urlscan.io/result/5b63be29-8112-4707-b451-5f96bf72b1df/
address: 0x8C500BD17174e8604ff9aD3399bD13af245EeF52
ethereum-return.com
https://urlscan.io/result/491ef95c-935f-4541-8a1e-24d207bfea45/
https://urlscan.io/result/f47b89a0-f631-43be-8ed6-885234acf4de/
address: 0x8C500BD17174e8604ff9aD3399bD13af245EeF52

idex-market.biz.pl + more

---

_data/scams.yaml

medeum-airdrop-news.com
Trust trading scam site - linking users to ethereum-transfer.net
https://urlscan.io/result/f163756e-08db-46b1-8528-bcb749d4e6e5/
address: 0x43FA247764BfBe1Beba49111e4ed215524f02c41
ethereum-transfer.net
https://urlscan.io/result/d84279a4-9e1e-414f-a5c3-9752f89c88a3/
address: 0x43FA247764BfBe1Beba49111e4ed215524f02c41

medeum-airdrop-news.com + ethereum-transfer.net

---

_data/scams.yaml

bittrex-sigin.com
Fake Bittrex phishing for logins with POST /verification.php
https://urlscan.io/result/9875a705-35da-420a-bc8a-0c643d0db6dc/
---
giveaway.ether-claim.org
https://urlscan.io/result/4d447289-a35d-43cf-a885-b4a0a44eee71/
address: 0xe1228F81C01b80EfeFAC957483d63a40c6d635e1

bittrex-sigin.com

---

_data/scams.yaml

musk-air.org
https://urlscan.io/result/2dd66c5f-1860-440f-a21c-ea6b6869975d/
address: 0x72696cE345abB71398384e42CfbF6C9A995246c0
safe-claims.info
Trust trading scam site. Linking users to giveawaypromo.byethost14.com
https://urlscan.io/result/eb1d9dd5-6af9-452e-9eda-66278a02eddf/
address: 0x6a9c2ec4f4888d7338fc1b28584aaafeb01e6db3
bitstamp.pw
Fake Bitstamp exchange phishing for logins with POST /_indexSend.php
https://urlscan.io/result/eb5baf6a-4170-4502-986d-1dd07bc6abf5/
https://urlscan.io/result/5e607e6b-d132-4aec-b78b-d1789cefdc42
binance-web.com
Fake Binance exchange phishing for logins with POST /_loginSend.php
https://urlscan.io/result/61e8fd01-eaa0-45d0-a9a3-98cd6160ec25/
https://urlscan.io/result/b259851a-d380-4d5d-8ea3-6b128776ad03/

musk-air.org + more

---

_data/scams.yaml

international.bittrex.com8917321.ga
Fake Bittrex phishing for logins -
https://twitter.com/ANeilan/status/1069746687550386177
https://urlscan.io/result/bc48e861-ec1a-4795-a8c5-aa7a004587a4/
https://urlscan.io/result/4127fcd8-d362-447f-b796-8cd025def2fd/
cryptophonesupport.com
Fake phone support for multiple cryptocurrency products
https://urlscan.io/result/50faf3dd-fc0e-45ad-b3f5-01665389ca9c/
keepstake.github.io
Phishing for MetaMask phrases with POST web3.keepstake.io/process.php
https://urlscan.io/result/7e1a1ce9-e680-4e28-b7e1-533344f0c36d
msg.xn--metherwllt-zmb5581g94a.com
Fake MyEtherWallet phishing for keys with POST /process.php
https://urlscan.io/result/824b459b-f0b9-4f8e-b058-27d29384e19c

international.bittrex.com8917321.ga + more

---

_data/scams.yaml

cash-bitcoin.online
https://urlscan.io/result/05ce8702-5326-4088-9294-3340319ac4fd/
address: 3CnqzLzkrHwCoi94y8Caq2Yw1pQQA94Wvk
yobit--net.com
Fake Yobit phishing for logins with POST /en/_loginSend.php
https://urlscan.io/result/57afad75-bfa0-4cb6-9f98-3c38cc6d8bbe/
supportyobit.net
Fake YoBit phihsing for Yobicodes with POST /login.php
https://urlscan.io/result/eb2706be-2677-4a5b-8ada-13a4c6a5367e/

cash-bitcoin.online + more

---

_layouts/redirect.html
run.js

* Fixes XSS exploit - OBB 724561 (spam404)
* Checks to make sure we have indexed the domain before we show the redirect view
* 404s everything we haven't indexed - no leeching, we only want to give users the redirect to things we know about

Redirect XSS fix
