MrLuit/EtherScamDB

_data/scams.yaml
https://urlscan.io/result/70fdd179-ba44-40cb-82d5-48268eaf7009
address:  0xEB85b4777698c0f41168087cD8d43A2FdEF37BdB
=> gether.fund + more

_data/scams.yaml
https://urlscan.io/result/8c2c90c3-2500-4261-8d7e-34a4545bbb8c
address:  0xB516107DeD86b21F7394c26090ADf0661E6A3759
=> 5000eth-giveaway.online

_data/scams.yaml
Fake Coinbase phishing for private keys
https://urlscan.io/result/1a1beb06-86c6-415b-a695-b335bf53c740
https://urlscan.io/result/deca6e3f-3f39-4414-90f2-9d8f4d273cd5/loading
https://twitter.com/sniko_/status/984914783186116609
=> www-colnbase.com

_data/scams.yaml
Fake coinbase phishing for login details
https://urlscan.io/result/b385775f-1b25-4183-8e02-141d1a6dcd2c
=> xn--conbas-gva1a.com

_data/scams.yaml
https://urlscan.io/result/12871b50-11a7-43ab-9242-0a797f34182b
Address:  0xf605c1C8c1CD6Bc3AA6f7383b86226c583Ab2775
=> eth-giving.com + more

_data/scams.yaml
Fake MEW, stealing private keys
https://urlscan.io/result/633eb8a4-09dc-4d6e-9c94-0ad84cde4bac
https://urlscan.io/result/3b5139de-087d-4c7f-8e71-725ee4fcf48c
https://twitter.com/sniko_/status/985333475732525058
=> localetherwallet.com

_data/scams.yaml
Fake EOSDAC site, stealing keys to get an airdrop
https://urlscan.io/result/07cfe006-bba3-4393-b881-15bdd0b49d51
https://urlscan.io/result/df357eb6-fa02-44b3-98ee-7e7e0f17c61b
https://urlscan.io/result/b1181935-ce7e-4688-842d-ee7172fa49e0
=> eos-dac.com

_data/scams.yaml
https://urlscan.io/result/34241a15-4f42-486f-8089-6103a789c63b
address:  0x713a6f26525B24581Cbe20679811af8680abdddd
=> btc-gifts.info + eth-promotion.getforge.io

_data/scams.yaml
Fake MEW
https://urlscan.io/result/664deaf2-b514-4fb2-887e-8674f27028af
=> myetherwallet-register.com + myetherwallet.lt

_data/scams.yaml
https://urlscan.io/result/8fca9e93-8b55-4b0e-8ba3-c98d3a3216c8
https://urlscan.io/result/4bdbd16e-32d5-418f-8034-9259fb28910d
address:  0x6c20ef21e604028c649247c581e8e49fda6191ca
=> tokentelegram.net

_data/scams.yaml
https://urlscan.io/result/7aa2c4eb-6389-478c-9c8a-d10bb2b072bd
Address:  0xa4Fe2874A4aD464A50CB72a8C0b1a6ab221A7C17
=> ethtotrade.com + more

_data/scams.yaml
Fake origin crowdsale site
https://urlscan.io/result/e43b12e1-bcf8-4b11-89dc-88c699c51443
https://urlscan.io/result/3f626d6c-3315-4b68-a76c-895a2cca1de6
address: 0x0d4f74c538613ed6e6c8c1bc8896ecfd45f5ef23
=> originprotocols.com

_data/scams.yaml
Fake Etherscan
https://urlscan.io/result/5db6c3c6-10d3-4fa5-aede-2ab8ac9819a5
=> etherscan.tech

_data/scams.yaml
https://urlscan.io/result/a471f425-bc7e-432e-82d1-2d63f86f62d5
address:  0xc15FFCceb80e34A780A46795DBD126E2d65C4460
=> get-ether.gift

_data/scams.yaml
Fake EOS airdrop phishing for private keys
https://urlscan.io/result/630684e5-a37d-4c53-8e40-ebd08c487b5b
https://urlscan.io/result/bdf0184c-ab5f-4d66-8759-40810271f603
suspected address:  0xeefa861d00e68aab019df8bf3a9cb689196df41d
=> eos-candy.com

_data/scams.yaml
myetherwalletru.com
https://urlscan.io/result/3c1f52ac-3538-44e1-ade2-d357d9c8e4f5/
i-myetherwallet.com
https://urlscan.io/result/67f1e3f3-6092-48ec-8e06-c216fae8f7aa/
=> Fake MyEtherWallets

_data/scams.yaml
ethereumbonus.online promo.ethereumbonus.online
https://urlscan.io/result/b5249a88-b7d0-4b0f-bcb8-8e7ee8937d35
https://urlscan.io/result/ad7e7c5b-9f61-46b1-bce6-819686047234
address: 0x0967c50BFEC4dBa06E28E8fdbcfD15A23474fAb4
=> ethereumbonus.online & promo.ethereumbonus.online + ethtoget.com

_data/scams.yaml
https://urlscan.io/result/a51ae0a7-a97b-4ea0-b239-a5330acad9b2
=> xn--myethewllet-w48ep6a.com + xn--myetherwalle-occ.com

_data/scams.yaml
Fake Nkm crowdsale site
https://urlscan.io/result/1de8603c-c243-47f4-a666-bf525d425b8b
https://urlscan.io/result/37143334-f4df-4594-bf0e-9cff2de98cfd
address:  0xD243018B2825ad409512a200E744529bc1b129f2
=> nkn-token.io

_data/scams.yaml
https://urlscan.io/result/0b3eeb18-4cf4-412c-abba-d3aa4dbf235f/#summary
address:  0xEF35af4A5037a1E416514f1F016550cf7c865ffc
=> ethhit.org + more

_data/scams.yaml
https://urlscan.io/result/27343378-811a-417a-bc0a-d9bd2c7764a1
address:  0x860B62006Ea05A05c7638D16a106858450bde336
=> win-eth.org

_data/scams.yaml
Fake Dfinity crowdsale site
https://urlscan.io/result/3fa3a950-4263-4ff0-8935-6b5239c7cbfa
https://urlscan.io/result/4048e553-39bb-43c0-ad12-1ed6bb4ab64a
https://urlscan.io/result/d04d8a65-682a-465e-a12f-f5b5f4a8e99a
address: 0x41467711f2d1f6021119fFB113AE0e78251b45fa
=> dfinity.ml + aelftoken.com

_data/scams.yaml
https://urlscan.io/result/80cd5d0a-6c6b-4d96-bc09-db3da72a3f16
address:  0xceEbB2D0cDC85E9774A232Bab74C45Fc883C15e4
=> 5000ethgive.com + more

_data/scams.yaml
Fake MyCrypto - IDN homograph attack
https://urlscan.io/result/9cab0725-3aa6-4e95-9673-002607195d8d
=> xn--mcrypto-rpd.com + more

_data/scams.yaml
https://urlscan.io/result/1b37831a-6968-4c4c-8a7c-9f6a63f22b63
address:  0x9C3C750372e2DBC2f8f2E6C58EdFA6E1d7e463Fd
=> ethereumpomo.online

_data/scams.yaml
https://urlscan.io/result/53891b6d-3d13-4416-82c2-cf52cc768908
address:  0x2e462fDeF8cde7DB82Aa3f7C627731BE94f7C9C4
=> ethforeth.com + more

_data/scams.yaml
Fake MEW
https://urlscan.io/result/7a97cc3e-b644-4fed-8b13-8235957f092b
=> nmyetlerwaliet.com + more

_data/scams.yaml
https://urlscan.io/result/e077a146-2adc-4695-95fd-f13c02edb396
address:  0xEbD411aA59B4456f45529A7Cc203F87c0e104947
=> gether-gift.com + poloniex-withdrawals.bitballoon.com

_data/scams.yaml
https://urlscan.io/result/8b94ca02-1b2b-4162-95d3-8fd881b1fa51
address:  0xf033f0d9c1bf050babe586fddd94d8928f02ac50
=> ethpromoverge.com

_data/scams.yaml
Fake DAV Network crowdsale site
https://urlscan.io/result/cb321a47-4538-4f5e-8c1b-29e1938fb31c
https://urlscan.io/result/e0bd1d91-1279-44d4-8382-8f2c0d3547b2
address:  0xF9319dDdCe472f9Aa0874d0E71d06e30C18990C6
=> dav-network.io

_data/scams.yaml
https://urlscan.io/result/2cf5e8bd-b6a8-4eec-999f-7c4025b52bc8
address:  0xF76DEA0A7ED40E379Cc834cF94a6BdC59ac11044
=> offpromoeth.com

_data/scams.yaml
Fake Shapeshift site, iframe 188.227.75.205
https://urlscan.io/result/74abc7cf-fed6-4d4b-9a4f-e99989660a22/
=> shapeskift.io + shapeslhift.io

_data/scams.yaml
https://urlscan.io/result/8897f2d0-9c98-4dff-80df-51f11f21c281
address: 0x61Cf3335eef3bD86Ae617cd2eA248494Da8B83ca
=> 5000eth-giveaway.getforge.io + get5000eth.com

_data/scams.yaml
https://urlscan.io/result/bac7ede1-59e0-4084-af0f-2bc5084d961d
address: 0x88bDEB65eD500794118D0E5FDf5808d23Bb74E73
=> ethgiveaway.org + more

_data/scams.yaml
https://urlscan.io/result/009e84e6-f710-490c-be37-93244f3da5a0
address: 0xB64f875dAA42173cCAC0b01e502695B61a1A9A64
=> eth-today.rf.gd

_data/scams.yaml
https://urlscan.io/result/fd28d261-f517-42b3-a574-6ccec34f40cb
address:  0x91459992BcbF089851abFfa033559C2eEf120469
=> getyoureth.com

_data/scams.yaml
Fake MEW
https://urlscan.io/result/a873a53d-1acb-41a1-9c49-68dca02bd848
=> nmyetlerwaiiet.com + more

_data/scams.yaml
https://urlscan.io/result/b4fe2b60-87b2-45e5-9ca5-db11bda9a1dc
address: 0xF939D9285fFb6FC05780E9549b161d9e9fac6F7d
=> get-ethereum.cc + freecoiners.com

_data/scams.yaml
https://urlscan.io/result/26dadd21-312c-462c-bb38-81188154c2ab
=> clo-airdrop.info

_data/scams.yaml
Fake MEW serving under a Google ad
https://urlscan.io/result/5aff89d6-024c-4b3b-a1dc-6b12d8509e5d
=> myehterwallet-ht.com + more

_data/scams.yaml
https://urlscan.io/result/8951469a-2a14-4cb7-8624-13cb54ce2827
=> add daostack-token.io

_data/scams.yaml
https://urlscan.io/result/8800f5d3-5e1f-4e8f-9090-4ede7ec09d3a
=> add icolist.sale/daostack/

_data/scams.yaml
https://urlscan.io/result/7faa7f1f-ffb0-4bc2-baa2-66b19aecb52e/
address: 0x1161aCF9a61b8cd951F5364E897c586883a1fE76
=> gift5000-eth.com + more

_data/scams.yaml
MEW IDN homograph attack domain
https://urlscan.io/result/e9a107a4-533f-4ae9-83f4-f104ec036edd/
=> xn--mytherwalet-ms8e53d.com + more MEW idn

_data/scams.yaml
https://urlscan.io/result/9230e776-3afa-4a5f-99c4-de50eef43b4d
address:  0xB5eb9d18C0413535bAf1fA8Bd8BF8F6Ea7fEa47A
=> gift-5000eth.com + more

_data/scams.yaml
Fake LocalEthereum phishing for logins
https://urlscan.io/result/257a1f59-38be-498f-9876-4efc6692ea74
=> localetherieum.com

_data/scams.yaml
https://urlscan.io/result/f0e95843-758c-44a1-89d8-f08df93ea1bd
address: 0xB5eb9d18C0413535bAf1fA8Bd8BF8F6Ea7fEa47A
=> gift5000eth.com + securepayeth.com

_data/scams.yaml
https://urlscan.io/result/33b1d6eb-49ec-4361-874d-a812d58eb584
https://urlscan.io/result/a53618e7-2c77-4088-ae06-0d3d269dd416/
https://urlscan.io/result/1eade241-2ea9-4963-8817-fc6e2ff3ecee/
=> polymath-network.com + more

_data/scams.yaml
https://urlscan.io/result/ea6098ae-8619-43d3-bf50-7085c355fe28
address: 0xf7355cb5278fc4be2f53ce373f7cd9b543d042a1
=> 5000eth-giveaway.com + ethereum-give.czweb.org

_data/scams.yaml
https://urlscan.io/result/560b1b5e-4eea-4f94-968e-a834f2b12ea2/
address:  0xd52fcaf53cd3eFd7E1d484fd9cd2dd21355063e5
=> get-ethereum.gift + more

_data/scams.yaml
https://urlscan.io/result/630171ad-bd31-4395-8a2d-7b44030bb0be
https://urlscan.io/result/dc94cc91-676e-4031-b606-9fd4908c5587
https://urlscan.io/result/7d3d43be-86d9-4511-a454-98f4cb9282bc
address:  0x6d1Ca9Ee33f0806bD37a8ac4c418a0Ecb0c9F086
=> tokentelegram.live

_data/scams.yaml
https://urlscan.io/result/bf95bc60-1729-4808-aecd-18cc982eaad2
https://urlscan.io/result/976b36c1-9d33-4d41-b855-0142242b7de7
address:  0x6c20ef21e604028c649247c581e8e49fda6191ca
=> tokentelegram.info + more

_data/scams.yaml
https://urlscan.io/result/1953bc55-95c5-4d9c-a03a-74c99eb7b035
address:  0x085f9b53aCBff0E4683463FEf1A583d299bd4e25
=> ethereums.cloud + more

_data/scams.yaml
https://urlscan.io/result/77e475da-90a3-4c30-8feb-146c4000a53a
https://urlscan.io/result/fe48c28d-56cb-4f3f-ab6c-dbdb428c9642
address:  0x6D09D33C424932f59Ce9aa777aDf131FB3adbf3E
=> quarkchain-tokensale.io

_data/scams.yaml
https://urlscan.io/result/47ea9dea-25f7-4191-a244-68a3ddeb9be3
address:  0x23397C5d9C6363d67b3a294b677F80f93949bF56
=> 5000ethgift.com

_data/scams.yaml
Fake MyCrypto
https://urlscan.io/result/95bbe52f-2e72-4de9-b315-3b8a07729c3f/
=> mycrypto.promo + more

_data/scams.yaml
https://urlscan.io/result/dbf7d316-e44a-4de5-bfef-38e11481bd2c
address: 0xDcCDCe28bba5B796724f1b50Ab350403D895fE08
=> gift-5000eth.org + ethpromo.net

_data/scams.yaml
https://urlscan.io/result/5391cd4a-0752-4df4-992e-81f0a1cc9acc
address: 0x74f59fD3Fb42295A05975456A6cdfF4e71174Cd5
=> ethereums.live

_data/scams.yaml
https://urlscan.io/result/ace92f80-c38e-447f-8d96-6c04d0f41ab8
address: 0x754Fb6a142eD0043937b676A067F2E367db52fA6
=> promo-ether.com

_data/scams.yaml
https://urlscan.io/result/59c81f8c-8521-4509-a12a-5b4e1240c9a9
address: 0x418Cb18A725A8B1043D2fB402bb71CC29E42e2E9
=> collecteth.com + more

_data/scams.yaml
https://urlscan.io/result/a53d0192-8688-4536-b2e1-21d903a6e651
https://urlscan.io/result/7dfcefc4-26d4-455b-8277-5ca0aa3d7459
address:  0xa0C7d4F3FC7f8A46FB58990228d0B82A0354F371
=> ethereumdrop.batcave.net + etherdrops.com

_data/scams.yaml
https://urlscan.io/result/520a3200-2683-446d-a3b6-0766704f57e2
address:  0x4FbC4C6C416a84e04B2239202396f378d7Af51ee
=> geteths.live + more

_data/scams.yaml
myetherwallet-start.download
https://urlscan.io/result/b1af877c-ce5c-43d0-874a-93bf60dfb037/
myethereumwalletpro.com
https://urlscan.io/result/f7a598f1-74c8-490c-bff1-3058b6b1394c/
myehretewallet.com
https://urlscan.io/result/ce83d94d-ef41-444f-8b1a-db5e5ec37387/
myetherwallet-cash.download
https://urlscan.io/result/84984be9-81c9-494d-ba8f-80abb435ac7a/
myetherwallet-official.download
https://urlscan.io/result/76f1c346-cfe3-49be-aba9-6a5c9f7719c7/
myetrhrerwallet.com
https://urlscan.io/result/4de8a85a-8cca-4fe9-bb24-d1a278268b32/
mynerthwallet.com
https://urlscan.io/result/31feb9e4-d221-41fb-bd97-3226bb1539ac/
mynethwallet.com
https://urlscan.io/result/dcf63838-d454-407c-8798-f835a4ce4823/
mynetwalleteth.com
https://urlscan.io/result/03c82e8f-8491-4756-997d-af7a384d1520/
mynewalleteth.com …
=> Fake/Suspect MyEtherWallet domains

_data/scams.yaml
https://urlscan.io/result/bec556da-d5b2-47dc-9847-40039be26449
address:  0x95C5dB5bD9A0260Fc457Af4F6fc6dE7819D9B1a6
=> ethgiveaways.net + more

_data/scams.yaml
https://urlscan.io/result/b901fd7f-1e4f-438a-8332-81c87bf57691
address:  0xD289Bc0A919E75B824F4DfC376E9F24C119eD3F3
=> giveaway-eth.com + more

_data/scams.yaml
https://urlscan.io/result/1f462e0b-504f-49f4-9968-ad425d5421db
https://urlscan.io/result/1bf36550-9673-4459-8fa6-d7b3747b0455
https://urlscan.io/result/9816be45-05a6-4f47-8dee-e0581f586fe7
address:  0xB3510C6786B90c2065644825bd34C4219f1460FF
=> eosreward.io + more

_data/scams.yaml
Fake Airdrop phishing for private keys
https://urlscan.io/result/eab7273c-d6ae-4cce-8b0a-e45b9714536c
https://urlscan.io/result/08b23aa1-f0bf-48f5-ba53-d07e33430462
https://urlscan.io/result/359de9d2-3cd7-45fe-b880-7eaeaeb0866a
https://www.reddit.com/r/CryptoCurrency/comments/8gdj4z/axpire_scam_warning/
https://imgur.com/a/NakZU4y
=> axpire.tech

_data/scams.yaml
https://urlscan.io/result/157642c4-6fd8-4aa1-b6a2-2c59372236ca
=> Added more addresses for quarkchain-ico.io

_data/scams.yaml
https://urlscan.io/result/369f80f7-6191-4bef-9109-50635606d083
address:  0x78c544EEdE78eb781707A1d46377bf6BE9D028Df
=> get-ethereum.org

_data/scams.yaml
Fake blockchain.info site phishing for logins. Google Ad going through
cken.site
https://urlscan.io/result/75dd4f36-6f89-495a-abeb-8dbdffd91f75
https://urlscan.io/result/d8708cc3-12a7-4461-8573-ed14ad76e07f
https://urlscan.io/result/06acf4c1-61ef-42b3-ad3d-80ce5f7f2152
=> blockchaihs.info

_data/scams.yaml
https://urlscan.io/result/1a8a63f3-90c4-4a3a-a3e5-45d1dd8daa7e/
=> cdnsfiles.com

_data/scams.yaml
https://urlscan.io/result/7a8d4ee6-c7b6-48c8-883b-41ad69a73563
=> add fake medium article

_data/scams.yaml
https://urlscan.io/result/0a958074-e7e3-4d21-a219-134ff37482a6
address:  0xd0bD5Be5DF3681608F5FDA3D003EFaA0371dc4d7
=> eth-giveaway.updog.co

_data/scams.yaml
https://urlscan.io/result/8d525a96-5a4b-4d44-9d51-ea8e9663632f
address:  0x304d66005b5aD49F7Ce54AceBA9bBaDb4A5774db
=> 5000eth.org

_data/scams.yaml
https://urlscan.io/result/d89401e8-c351-44f8-a416-68e84408e42a
address:  0xAd2E834840954231b924b51bFB92C7f457CA30D9
=> giveavvay10000eth.host

_data/scams.yaml
https://urlscan.io/result/e778f394-cb3d-4646-bae2-313020b9408a
address:  0x4F484c32c4810AE8129f1B724b09c663F8341713
=> eth-giveaway.co.nf

_data/scams.yaml
verifiedeth.com
https://urlscan.io/result/a3aed2de-fb5a-4ba6-affb-c7e1521f05c1
address: 0xb0608cA76D2ec6984f652829e887811516E4B846
ethergive.000webhostapp.com
https://urlscan.io/result/719a8862-d055-4153-a5af-ccd0d716e13d
address: 0x7b66563dd534c3e66fee08c995da9d5e77c883f9
5000.ethereumgive.com & ethereumgive.com
https://urlscan.io/result/70efcd4a-322e-46bf-8c58-b3ba6f266300
https://urlscan.io/result/11241859-b855-4b47-8a49-b1ca3ba7aee9
address: 0xf6238cBC1b74b183E54d63A555f867bAA00D92dF
hederahashgraph.online
Fake Hederahashgraph crowdsale site
https://urlscan.io/result/9491c485-9b4d-4b02-a2ac-e700b202eb52
https://urlscan.io/result/831b3c63-ca7d-4983-bfde-80363de4d55c
address: …
=> verifiedeth.com + more

_data/scams.yaml
myetherwallet.access-checker.com
https://urlscan.io/result/261505c9-df0b-44b8-b6e5-8bfcd4400d73
https://twitter.com/mycrypto/status/992507058036424705?s=21
freeeth.info
https://urlscan.io/result/8075899f-3b3d-456e-b44a-fa12d4de0ea6
address:  0xf6238cBC1b74b183E54d63A555f867bAA00D92dF
=> myetherwallet.access-checker.com + more

_layouts/search.html, _static/js/search.js
Complete: 
Adds case-insensitivity to search bar by changing the search text to lowercase.
Now, each search contains the username being searched.
=> Added case-insensitivity and visual indicator of new search

_data/scams.yaml
Fake google doc targeting the DaoStack ICO 
https://ibb.co/kmvpES
=> add fake daostack google doc

_data/scams.yaml
https://urlscan.io/result/02dc9d94-6f57-4492-9d0d-5119dd54fda3
=> add daostack.onuniverse.com

_data/scams.yaml
get-ethereum.ml
https://urlscan.io/result/5fc621f9-da68-46e7-8f38-b0cd59bd7267
address: 0x497E4c58A4106fEE817e3BEce3C5c029e964Eb49
5000eth.net
https://urlscan.io/result/370c0de0-f1b0-41db-b55d-89d519a66ff2/
address: 0x2276f412d2ae5dc2cdc293b0df70a8273f6f6771
claim.payeths.com
https://urlscan.io/result/ca69f450-c79a-4069-895a-df755862e4f1/
address: 0xb48c99C37b7cf4AC0A1c2dcA518782C1FEB4f066
gameofdeception.get-5000-eth.com
https://urlscan.io/result/f8be78d5-494c-498d-843c-2cb1693e754d/
address: 0xf6238cBC1b74b183E54d63A555f867bAA00D92dF
bonus.gift-ethers.com
https://urlscan.io/result/4e277554-3505-420c-a3f5-f56306ec0454/
address: 0x471DBd4D8FCe14EAe3B36EFA8Fa97A3937038DFA …
=> get-ethereum.ml + more

_data/scams.yaml
kinecosystem.io
Fake Kin airdrop phishing for private keys
https://urlscan.io/result/07096412-56d6-45dd-a90c-4928c19be3ce/
https://urlscan.io/result/15b872c4-a369-4954-ba33-5a3f661030ba/
https://urlscan.io/result/27b35185-63dc-43a6-95a6-2f3dda5d610d/
https://urlscan.io/result/765af8ce-e1c3-4a85-bb80-d6c5a949a5dd/
=> kinecosystem.io

_data/scams.yaml
i-idex.market
Fake Idex phishing for private keys. Sends off to POST http://176[.]122[.]20[.]15/sendkey
https://urlscan.io/result/5afc9f77-2d82-405e-956c-691432b92f78/
https://urlscan.io/result/23d70a91-6aee-436d-8145-b7451adaff37/
forkdelta.net
Fake ForkDelta GUI
https://urlscan.io/result/51dee6ed-de25-44ce-b2b1-cd33b9a59849/
=> i-idex.market + forkdelta.net

_data/scams.yaml
xn--tbtc-upa94a.com
Hitbtc IDN homograph attack domain
https://urlscan.io/result/8ba318ad-2de0-4e94-b0e3-ccbca4148adf
xn--itbtc-9g1b.com
HitBtc IDN homograph attack domain
https://urlscan.io/result/b2a99dfa-8942-40e5-9dfe-8f5c4b22e10e
myetherwalleth.org
https://urlscan.io/result/dee9a62f-c4b7-43ea-8741-d312a604bbf2
brickblocks.io
Fake Brickblock crowdsale site
https://urlscan.io/result/62e91cae-f09a-4684-be41-40538dab9d01#summary
address: 0x2Dc5616EC2b9D24906F0e11dC8D8a736392dFeDD
zilliqanetwork.com
Fake Zilliqa airdrop phishing for private keys
https://urlscan.io/result/ab513a2f-d18e-4c45-8ba6-187c7ce18805
https://urlscan.io/result/906a4afa-2e05-476c-af80-5310b1a672f8
https://urlscan.io/result/33146cb3-2b61-41ba-bfd1-967b5478f0bc
brickblock.cc
Fake Brickblock crowdsale …
=> xn--tbtc-upa94a.com + more

_data/scams.yaml
xn--myetherwallt-ovb.net
https://urlscan.io/result/463e92e9-546c-4f8f-b3b7-52c24e52be79
https://urlscan.io/result/0a7b23e9-7654-4230-91b2-f24bc92fafb8
suspected address:  0xa7b8edb0583b478e2b7c431feb4bc6629a6cd1e5
idexmarkets.com
Fake Idex market phishing for private keys - pushing to save.php
https://urlscan.io/result/125859e6-e9ac-4f2b-b6fe-adb5cc06e1da
=> xn--myetherwallt-ovb.net + idexmarkets.com

_data/scams.yaml
collect.ethforyou.com
https://urlscan.io/result/42cae236-4989-4519-a379-5c5352e4c75c
https://urlscan.io/result/c16c7de9-8124-46e3-962f-e70a82772da9
address: 0x3EadB407F81d62D27F63a8881805B1735F70E692
getmyetho.paperplane.io
https://urlscan.io/result/c49b6a1b-d1a8-4d69-9b31-da5341bb3a0c
address: 0x35919ff0a88A0bDFd1b0EF3be574bcF6C1e90e01
brickblockio.info
Fake Brickblock crowdsale site
https://urlscan.io/result/dcfa27a5-4da8-4df7-a648-19339aa8489e/
address: 0xe949A4c861089fBdE6eF1175C23E1485D5970567
giveawayethereum.win
https://urlscan.io/result/8b714acc-b0c5-40b2-b610-9e629235243e
address: 0x8aF1380c436fC019b8055C61d09e3Ee5F182278C
=> collect.ethforyou.com + more

_data/scams.yaml
musk-party-gifts.updog.co
https://urlscan.io/result/910a27b7-0484-4608-8892-61ef3fac0b0d
address:  0x10c44aB858B90E09C725158906F71833fF417ACC
yobittrading.net
Fake Yobit phishing for logins
https://urlscan.io/result/3544d2aa-24ba-4ae9-869b-643b87e717bf/
yobit-trading.net
Fake Yobit phishing for logins
https://urlscan.io/result/666b538b-b924-43d6-8134-227374cfd777/
=> musk-party-gifts.updog.co + more

_data/scams.yaml
xn--bifinex-fb4c.com
Fake Bitfinex promoting a fake giveaway (trust-trading) - IDN homograph attack domain
https://urlscan.io/result/3e2af687-b705-4fb5-9e77-b8b55e073ae4/
https://urlscan.io/result/551eb57d-2c7c-4121-a9dc-ebdc789fe2df/
https://urlscan.io/result/e6e98a26-177a-4a17-8fbc-c7f1e7312c96/
address:  0x09430a9Fb46a1a3B83980768C4cEDF654d8eefa3
xn--blockcain-g95d.com
Fake blockchain domain - IDN homograph attack domain
https://urlscan.io/result/d6155859-055a-40be-991f-8ced9eb5cd01/
xn--coinbas-z8a.info
Fake coinbase domain - IDN homograph attack domain
https://urlscan.io/result/e203d686-3164-44e9-8056-30e652ef36d2/
xn--htbt-3oa0a.com
Fake Hitbtc domain - IDN homograph attack domain
https://urlscan.io/result/b48afb7a-3133-4761-9ec3-a7b62cd0848e/
xn--myethewallt-crb9748g.com
Fake …
=> xn--bifinex-fb4c.com + more

_data/scams.yaml
https://urlscan.io/result/e9c1fb26-228a-4aee-b557-92620c564d57
=> add dav.icocrowdsale.io

_data/scams.yaml
xn--mytherwallet-5vb.net
https://urlscan.io/result/438ede62-8084-45ae-8ba0-f7a903b064a1
i-dexmarket.com
Fake IdexMarket site stealing keys with POST save.php
https://urlscan.io/result/4931c135-5f4c-4fd8-b605-87e7ea86075f
bi-ttrex.com
Fake Bittrex
https://urlscan.io/result/c9a1ded3-a566-4446-b5f7-0fe293bbed0f
www-bittrex.com
Fake Bittrex
https://urlscan.io/result/c2ea4b8a-e18a-496c-b5a5-6c794eb68c57
https://urlscan.io/result/a7649a0d-0b90-47b8-ac1a-df40f72b6f24
=> xn--mytherwallet-5vb.net + more

_data/scams.yaml
quarkchain.live
https://urlscan.io/result/56a45362-3fe9-4d1c-8445-ba9184aa8890/
https://urlscan.io/result/25b5d373-a6e6-4d8d-a6b8-902a12908b12/
address: 0x0a888f0F0b772e17a2ADFd62D3f15CeC72c8D42f
=> quarkchain.live

_data/scams.yaml
zclassiccoins.com
https://urlscan.io/result/ae6be71a-bb9f-49ee-8f11-e2d3ccd1c220/
address: 0xe87d279d090df4ba19c0e19958d9ac61be5c6909
omisegowallet.network
Fake OMG web wallet
https://urlscan.io/result/be714fe2-34d1-4d0e-b38c-bd05ac7865d8
address: 0x4bc2055440dd519fa4d448d2d6899e6604aaedc5
musk.vu
https://urlscan.io/result/2dbe2ff6-c75c-46c4-953a-8b7f19443a9f
address: 0x804A67880F461c2ba4b927a10E99E371962B0F3f
quarkchain-presale.io
https://urlscan.io/result/48f04470-fa5d-4da0-9425-9cc94ef607c3
https://urlscan.io/result/f02dddfb-357f-4e0d-9234-e5a77f8da632
address: 0x05e18136F048d648eE73Dd5D269d590Ff2873C33
ethairdrop.live
https://urlscan.io/result/62ccdbe4-08f5-43c8-98f7-016bc538bc27 …
=> zclassiccoins.com + more

_data/scams.yaml
eth-giveaway.today
https://urlscan.io/result/cb202214-02a1-4a07-a112-f1db79932308/
address:  0x3F2cf669C657316985B01b1B797cb259c97d6551
etherget.online
https://urlscan.io/result/72e80e6c-515a-4e59-9042-5fc7754aeab3/
https://urlscan.io/result/7cda6081-4bba-47ab-85d6-053a6b45f078
address:  0xa8afa9a714e06b9eb1b500617494ac213f2d428a
ethplatform.org
https://urlscan.io/result/da8bf6a1-868a-4125-b26a-0f213d2d684e/
address:  0x54B623C82365ef20680B17301bD949BcD5599Eb9
mycrypton.net
https://urlscan.io/result/2aa06783-eb36-492a-a9c0-3a4a5a774450/
address:  0x7eD44f8b304cD71664Cbe8C94614660859Fca2c6
hydroplatform.org
Fake airdrop directing users to a fake MyEtherWallet …
=> eth-giveaway.today + more

_data/scams.yaml
quarkchains.io
Fake Quarkchains crowdsale site
https://urlscan.io/result/e912cd64-ee28-42ad-86d0-263903c8ee99/
address: 0xd7bb68B0cE5893983e5a2511b87E083609eB6fF9
ethcollection.paperplane.io
https://urlscan.io/result/7d4e356e-cc7a-4b55-b236-8447c54a2150/
address: 0xc8a7eFA8FF219CF002081c10c47F1D5F62b3FEe5
hydroggenplatform.com
Fake Hydro site linking to a fake MyEtherWallet - xn--myetherwalt-crb27c.com
https://urlscan.io/result/1a768393-0abc-4084-b38b-32ec22dd824c/
ldcx.market
Fake idex market phishing for private keys
https://urlscan.io/result/d592ac38-9d4a-4914-a25b-bad24a830aa3/
xn--mytherwallet-5vb.net
https://urlscan.io/result/3b1cb53b-5668-43e7-b25c-692f865f665e/
eth-airdrop.com …
=> quarkchains.io + more

_data/scams.yaml
tokenairdrop.typeform.com
Fake Hydro airdrop directing users to a fake MyEtherWallet - xn--myetherwalt-0rb64c.com. Suspected address: 0xCF02680e5f057D41A68C3DA6221Ade6609833e5a 0xbF30cBF5DD5fbf040A1fA8B7388F756F624AfDeF
https://urlscan.io/result/1e5dd0a1-6dcf-4445-a746-be8f80d2c844/
transfer.saferpayeth.com
https://urlscan.io/result/5afdec3d-44b8-4ecf-8813-23aa8c8d3d93/
address: 0x0f4CF489C65f5001843C525e1f374768DCAD9B99
r5.ms
Fake trading site
https://urlscan.io/result/27a97631-0599-4757-9ac3-209e866413cc/
xn--mytherwalet-3qb97c.com
Fake MyEtherWallet - IDN homograph attack domain. Suspected address: 0x9eEa7Fda3C78cd8C096AE229De8217a94cd1Bcfe 0xA7b8edb0583b478e2b7C431fEb4bc6629a6Cd1E5
https://urlscan.io/result/a032f97c-9928-4fac-9dad-ba796f4b4a25/ …
=> tokenairdrop.typeform.com + more

_data/scams.yaml
quarkchain.pl
https://urlscan.io/result/fa2fa7fb-a09c-4985-a85e-19bbdcb18671/
https://urlscan.io/result/f9631b40-6b5f-4ede-90a6-be1eb1ed04a3/
address: 0x7448dF6E1031d10e237b1481930a074B13FAAbD2
get-5001-ethereum.com
https://urlscan.io/result/c652c593-7a0f-41a2-85d4-007dc61558af/
address: 0x7D922A4f7F24fFcb130c4EEAF291A6475e3e4Dd2
get-5000-ethereum.com
https://urlscan.io/result/f2388aad-4a65-482e-ab39-c7a3d3f47c4a/
address: 0x1056d8d9EbB0E0d8710A0E2A1852d4A09d56464A
myetzerwallet.com
https://urlscan.io/result/22749122-afc6-459f-a507-5c419ed9b759/
promobtc.win
Trust-trading scam site (btc) - address: 14h4Zrd1xVg6Mj3JcYApoi2wY2UXue2ETb
https://urlscan.io/result/f065a6cb-24ee-449d-b846-41a1a4dc77f …
=> quarkchain.pl + more

_data/scams.yaml
xn--therdelta-uf7d.com
Fake EtherDelta - IDN homograph attack domain
https://urlscan.io/result/84a1f753-e1b0-46bf-ba12-40275fbbd15e/
xn--etherdela-ss6d.com
Fake EtherDelta - IDN homograph attack domain
https://urlscan.io/result/a89ad5a4-1086-4efe-b849-4771fb91c224/
xn--etherdelt-876d.com
Fake EtherDelta - IDN homograph attack domain
https://urlscan.io/result/7b37135f-d63c-4cfc-8e01-af1fb30ee878/
waves-ethereum-eth.org
https://urlscan.io/result/8476cf28-aadc-44b3-96fa-5feb8b762a62/
address: 0xfbb62df5cbc8d0bc4c2a0e5c53b8602d49471495
=> waves-ethereum-eth.org

_data/scams.yaml
ethersforme.net
Hosting trust-trading scam sites
https://urlscan.io/result/036cff71-ddd1-4ba5-8ee9-e8268da2f624/
giftethers.com
Hosting trust-trading scam sites
https://urlscan.io/result/7737e929-ae2f-41f2-ae68-90fd59a54387/
m342edium.ethersforme.net
https://urlscan.io/result/c87f1e4e-857d-4dfa-a720-7e17e1c12ee1/
address: 0x40949225c4a1745a9946F6AAf763241c082cb9ac
10000-eth.com
https://urlscan.io/result/7923173e-0dba-4da1-a991-d8eaea193c81/
address: 0x24F7ea54D9CDb021C0788Caab3c1796Aa8b2C161
icostarex.mipropia.com
Trust-trading scam site (btc) - address: 19zfbrhYeFVDcCrDsdpKj3WGCD6KvJbzt7
https://urlscan.io/result/0e615e1d-2b7e-44ee-8e59-ad1998d2eeb2
ethsgive.com …
=> m342edium.ethersforme.net + more

_data/scams.yaml
ebtweinfinance.com
Fake Cointal site
https://urlscan.io/result/ff989c2e-38d1-490a-88e4-dd1198a56049
cardanoethereum.com
https://urlscan.io/result/8873c613-ebae-405b-8fd2-089ef2186416/
address: 0x27075c2f55bD05c8F7009E8b5a1d3cF131806dD5
ethergiveaway.website
https://urlscan.io/result/39f924ea-0bb1-4a91-b78e-39f83e306a94/
address: 0x2511A5cF945e1cDA14E3210d2a56eA0dE1d3E031
output.jsbin.com/jejegu
https://urlscan.io/result/6d723911-f212-4cc0-8885-8f547e737add/
address: 0x3389a9CacB4A3FdbE43DB14D132b3F1e215A835d
get-ethereum.info
https://urlscan.io/result/5e3c5745-1eac-4791-89d6-09cd96173576/
address: 0x1056d8d9EbB0E0d8710A0E2A1852d4A09d56464A
get-event-ethereum.info …
=> ebtweinfinance.com + more

_data/scams.yaml
promo-eths.com
https://urlscan.io/result/895064e4-f592-4699-b014-a2ae51e8ced1
address:  0x24F7ea54D9CDb021C0788Caab3c1796Aa8b2C161
nathanielpopper.promo-eths.com
https://urlscan.io/result/d80f52a8-c689-4e8a-ac30-541d686a74a0
address:  0x24F7ea54D9CDb021C0788Caab3c1796Aa8b2C161
=> promo-eths.com + nathanielpopper.promo-eths.com

_data/scams.yaml
walleteos.org
Fake web wallet phishing for keys (sending to POST test.php)
https://urlscan.io/result/9e7c9e56-7075-4f9f-9c81-9b0965e41439
=> walleteos.org

_data/scams.yaml
claimeth.epizy.com
https://urlscan.io/result/aaede76a-084f-478b-92a9-2f668fc0ea27
https://urlscan.io/result/99843887-f183-42c0-ae4d-9aab94c5abc0
address:  0x40949225c4a1745a9946F6AAf763241c082cb9ac
=> claimeth.epizy.com

_data/scams.yaml
eth-promo.net
https://urlscan.io/result/a5537a9e-d1e7-4a88-bff2-415b9637f59c/
address: 0x18BfF0b35d63B6e19775d3FBbB5a9fa9D7288A74
tdex.market
Fake Idex market 
https://urlscan.io/result/20e663f0-3c64-496f-b282-34446cd47854/
login-myetherwallets.com
https://urlscan.io/result/55bb9bf4-5fe9-41f8-9332-f9ab7938cd34/
ethgive.online
https://urlscan.io/result/5b7cc296-e4fd-4a3c-b6bc-46254be94964/
address: 0xE03C6FDD69e268A00cC93Fa282Fb3ce82afC8B12
=> eth-promo.net + more

_data/scams.yaml
biitbay.com
Fake BitBay phishing for logins
https://urlscan.io/result/3ec3a21c-2cba-4f5f-b958-993a57f2f92f/
https://urlscan.io/result/41d9ef68-c211-46dc-bb09-17b3573dcfef/
kcucoin.com
Fake Kucoin phishing for logins
https://urlscan.io/result/115e223c-93dc-4b3f-a100-1b62432c0e15/
https://urlscan.io/result/47115a44-ddca-4c30-b823-c5b48d2f9303/
vvallbtc.com
Fake Wallbtc site phishing for logins
https://urlscan.io/result/46ab3f47-41a9-4771-a781-ee13cc29625b/
=> biitbay.com + more

_data/scams.yaml
5000eth-promo.com
https://urlscan.io/result/c631b00d-73c7-4959-9442-09a1b130488a
address: 0xa61344257ed7c98b4690572e63797d75b0753f96
myetherofficial.com
Suspect MyEtherWallet domain
https://urlscan.io/result/c18ba254-84b7-49c7-aa3b-26cb26746d1d/
myetherwallat.online
https://urlscan.io/result/1e906a91-0193-4d24-99bd-667487401039/
myetherwalletw.org
Suspect MyEtherWallet domain
https://urlscan.io/result/c337da42-b750-445a-bf9b-b7789b667e68/
myetherwallte.net
Suspect MyEtherWallet domain
https://urlscan.io/result/e6d8432b-5e10-4101-a03e-b086d1acd7ed/
myetherwalret.ru
Fake MyEtherWallet (loading assets from myetlherwallet.pro)
https://urlscan.io/result/85273460-9cb0-4af6-8b3b-991fb88e346b/
login-myetherwallets.com …
=> 5000eth-promo.com + more

_data/scams.yaml
etherdelta.githiub.io
Fake EtherDelta phishing for keys
https://urlscan.io/result/41a55787-4d42-4589-b1c8-b65286b6bb65/
https://urlscan.io/result/c55ea5c2-cb63-4066-88f2-a210259165f2/
ether-promo.org
https://urlscan.io/result/9dac2ed5-2a85-4036-9e2d-aa0b0fdb1f10/
address: 0xf6eb7d25dfb8cd1d8fcb8d1cccab9f6f3e594ea8
ico-telegram.org
https://urlscan.io/result/ee0ea79c-cf88-41a9-b644-5c8bbf6fb275/
address: 0x5a3dEe76449fE47158Bf6b3B68c629c4ecD2554f
atn437.ethgiveeth.com
https://urlscan.io/result/c1e509a1-7d54-42c4-bd50-86e64b12a5c9/
address: 0xa47879FC57ECD8b52bfe7cF61B9bb41B7ef84eFC
ethgiveeth.com
Hosting trust-trading scam sites
https://urlscan.io/result/39eded42-b52b-45bd-b6b8-fbd93dee2c1c/
address: …
=> etherdelta.githiub.io + more

_data/scams.yaml
ethgift.org
https://urlscan.io/result/d358cad2-c827-4fce-bcc9-86a4736b4a9a
address: 0xbCA804D30E8602F3ca47F8C8b3A44f8e03fe1594
hydroraindrop.typeform.com
https://urlscan.io/result/d8c4a13b-c6f4-45bb-90cf-5dabfa918fb9
=> ethgift.org + hydroraindrop.typeform.com

_data/scams.yaml
ethconfirm.info
https://urlscan.io/result/82012737-52af-4be3-9a0c-aea2b0856601/
address:  0x92FA227D01DedeDAE2a50B9Da02413C48a872424
offer.ethsn.com
https://urlscan.io/result/23ad8b13-e953-4feb-8b63-0fb4af476fa8
address:  0xe597880Cb0591c6fc09E1B2778c26CAD34922B82
ethsn.com
https://urlscan.io/result/84912892-f8b7-48a8-ae37-9b5366bbd068
address:  0xe597880Cb0591c6fc09E1B2778c26CAD34922B82
=> ethconfirm.info + more

_data/scams.yaml
get.ico-eth.org
https://urlscan.io/result/4c6e8458-e31b-4284-ab10-cfeeb781b292
address: 0x1901D590f5dDBE8d58c69B324c13F884ca1d0B31
ico-eth.org
https://etherscan.io/address/0x1901D590f5dDBE8d58c69B324c13F884ca1d0B31#comments
address: 0x1901D590f5dDBE8d58c69B324c13F884ca1d0B31
payment-ethereum.online
https://urlscan.io/result/e76b5bfd-efe6-407b-a31a-992128067410/
address: 0xDC3896Be3EB4bB3B3eb2f936348E942796078920
tron-block.info
Fake Tron web wallet
https://urlscan.io/result/ff050d91-d9fa-4ebc-9f5a-56733d5887c0/
address: 0xdd1db171b110fb857311fde3236217894e7e9ab8
neo-online.info
Fake Neo web wallet
https://urlscan.io/result/d206ce53-d9bd-46c4-acc0-fed87b206bad/
=> get.ico-eth.org + more

_data/scams.yaml
mew-ehterwallat.com
Fake MyEtherWallet (iframing 94.100.18.96/my2/)
https://urlscan.io/result/6d9fa1f3-e66a-49ac-9108-f9d215320e59/
94.100.18.96
Fake MyEtherWallet 
https://urlscan.io/result/838a784c-7815-43ce-bddd-ad3b23acf2a6/
get.it-now-eth.com
https://urlscan.io/result/abc7f911-c153-4fe0-98d7-7835f83a1fe5
address: 0x64b212d2fe54db498df6099E5a9AFA8298068f89
it-now-eth.com
https://urlscan.io/result/3fc6d36c-b6ce-4277-a8d2-9bfa105d60f0
address: 0x64b212d2fe54db498df6099E5a9AFA8298068f89
give.promoeth.net
https://urlscan.io/result/1a64a09c-3d37-4856-9764-91b2b0c12e0e/
address: 0x69428858906050E78DBED8e65083d47139766b3F
promoeth.net
https://urlscan.io/result/b39fe3a9-13ce-43f9-b20b-bfb9e528727c/ …
=> mew-ehterwallat.com + more

_data/scams.yaml
eth4everyone.com
https://urlscan.io/result/195115dd-6b79-46bf-a4c2-3868e387441e
address: 0x86A120236c1f595ea53a93736b2E397C27aF802e
ethtransaction.ezyro.com
https://urlscan.io/result/7b821f66-6a4a-419d-beb5-3a3549c4f15c
address: 0xf39f8505c37080998a58bc9bdd946b81d4949004
=> eth4everyone.com + ethtransaction.ezyro.com address

_data/scams.yaml
tron-block.com
Fake TRON web wallet (cannot withdraw)
https://urlscan.io/result/14a0686a-1c27-44ab-ba4c-a6ea20b8d89f/
address: 0xdd1db171b110fb857311fde3236217894e7e9ab8
idex-market.site
Suspicious domain for idex.market
https://urlscan.io/result/d9ecc3e8-8795-4238-924f-5ec4504fd62a/
ethgive.net
https://urlscan.io/result/505224db-3818-4fe6-a8b9-532dc6dd160a/
address: 0x9fe0627303fe40f1631231B4DD016d30c13EafC7
=> tron-block.com + more

_data/scams.yaml
xn--mytherwallet-fvb.net
https://urlscan.io/result/a7324503-42b5-4050-9bf4-06c2c272de38/
xn--myethewllet-ife2794g.com
https://urlscan.io/result/5f8c4c24-6e8f-41ef-ab0b-39c52f408ea6/
xn--metherwallt-crb6719g.com	
https://urlscan.io/result/b5a78112-a797-4595-a38d-019716a88a03/
xn--myeterwllet-nl8er2d.com	
https://urlscan.io/result/e6b65e12-b2c8-4ac7-b1aa-56dcf8940c98/
xn--metherallet-ol9e03c.com	
https://urlscan.io/result/a2acc49e-f314-422b-ac62-1c66b922988c/
xn--mytherwalet-srb45c.com	 …
=> xn--mytherwallet-fvb.net + more

_data/scams.yaml
givefree-eth.com
https://urlscan.io/result/bad66464-c8d9-4b3b-ab76-e5c289c3388a/
address: 0x8c34460976e89EDdE3e2898DC7F23b597d295103
now-5000ether.paperplane.io
https://urlscan.io/result/c93cc8b5-3b23-4410-88f0-13279f277fa0/
address: 0xDC3896Be3EB4bB3B3eb2f936348E942796078920
eth-give.info
https://urlscan.io/result/51efc557-f9d8-4af2-b8b6-5943f6b4a1bd/
address: 0x7eA4270D456BC7B3E1C72f8a21a88a90C3D60147
=> givefree-eth.com + more

_data/scams.yaml
wallets-ether.com
Hosting a fake MyEtherWallet and being promoted by a fake MyEtherWallet account on Etherscan DISQUS channel
https://urlscan.io/result/1af2b467-495d-402e-b7d5-51b26fe0e621
=> wallets-ether.com

_data/scams.yaml
secure375446884521.safeethpay.com
https://urlscan.io/result/bc664136-1940-4072-9186-72472d25905c/
address: 0xF36b756013f80B162e8713fb37dF7dDA0Cd7F143
safeethpay.com
https://urlscan.io/result/a63ba90a-3e4b-453e-9965-13a06540c314/
address: 0xF36b756013f80B162e8713fb37dF7dDA0Cd7F143
xn--myethrwllet-pjb5u.com
Fake MyEtherWallet - IDN homograph attack domain - suspected address: 0x3a878eddb991ebcbc7c8052055b2e5ed5d0d1ba4
https://urlscan.io/result/94054a20-8453-4235-9863-f999b720d974/
https://urlscan.io/result/7065f90d-a3bf-43b5-9d21-0484cf2bd9ea/
quarkchain.in
https://urlscan.io/result/d414bcf8-63a2-4845-a12b-eb62f2bf78d6/
https://urlscan.io/result/1e282255-b773-43a1-b3cb-2f33dd50be48/
address: …
=> secure375446884521.safeethpay.com + more

_data/scams.yaml
claim-eth.com
https://urlscan.io/result/80abf5d0-c83b-4d74-9cc1-009bbe8b5b00/
address: 0x91e35d6c5B7323647e0cc1d274A072AC5CBB4340
send.ethergot.com
https://urlscan.io/result/e4a8052c-e5cf-4830-b13a-d7918c831f91/
https://urlscan.io/result/46877af3-b4c1-47f4-a10d-fd158a8f23e3/
address: 0xeae0B6B040bf8Adc143382d166cc008D8c317b23
ethergot.com
https://urlscan.io/result/a7caa56f-1e41-48e9-9d41-43462a981299/
address: 0xeae0B6B040bf8Adc143382d166cc008D8c317b23
securepay-eth.org
https://urlscan.io/result/4b2c3a06-51e4-43e5-a233-fd2f58b61b1a/
https://urlscan.io/result/8de33899-5a8b-4744-b278-746dba37037b/
address: 0xCdE79393C6F0dEB9B7b51579a386c853fEb8E104
gift-10000eth.com …
=> claim-eth.com + more

_data/scams.yaml
quarkchain.pub
https://urlscan.io/result/d6742e8b-8d03-469b-ae25-6fa235e0c4db/
https://urlscan.io/result/46cc2a3c-1e97-454f-b21d-6a2fd9e8ab06/
address: 0x118db57c34621ACd0A91F02C8c18cD1a3AD7C213
=> quarkchain.pub

_data/scams.yaml
myerherwallet.tk
Suspect MyEtherWallet Domain
https://urlscan.io/result/5f3bb1d7-2047-42fe-997f-834c43aa9664/
myetherwallet.news
https://urlscan.io/result/5b82e270-7518-41a8-8571-48641116a7e9/
myetherwalletz.org
Suspect MyEtherWallet Domain
https://urlscan.io/result/b18b78b5-f226-4dbb-ba74-3dd5a87ee09b/
myethrwallet.org
https://urlscan.io/result/fe2e89d1-3b7b-485e-815f-8e114df0a2cf/
myrvnwallet.com
Suspect domain for MyEtherWallet
https://urlscan.io/result/17202503-543a-49c7-b706-2f7560fb5c81/
xn--myetherwllt-s8a7g.com
https://urlscan.io/result/6a9aa7fc-641b-452b-b599-2d682d14d844/
myetherwanllet.com 
Suspect domain for MyEtherWallet
https://urlscan.io/result/5af1b129-2e53-4481-8da7-ea19e3da5e01/ …
=> myerherwallet.tk + more

_data/scams.yaml
ethpromo.org
https://urlscan.io/result/fa9a4c31-a050-4171-8dd7-fff5e68002fe/
address: 0x07cfB04588154b06E3958b5d70408244102014D5
eth-request.org
https://urlscan.io/result/2fc3c732-b7fa-40c8-89c0-ef98ebfde3ac/
address: 0x718eE443Ffdf50b30a5e8226d4Ff71E605C5cA7C
eths.space
https://urlscan.io/result/2af94512-8176-46bf-9d6e-16cae27a8ed0/
address: 0x096C39aB4fa36cA74A36FE1F4767FF487762f0Aa
btc-gift.org
https://urlscan.io/result/f68afd05-e7a0-4374-a297-61125f285ef3/
myethcrwallet-d.com
Fake MyEtherWallet - iframing 94.100.18.96/my2/ - suspected address: 0x59032DAB819f2457bf01E52D02dd42073D2E7D13
https://urlscan.io/result/f688d3d5-f011-4ed8-839a-86ce1666700f/ …
=> ethpromo.org + more

_data/scams.yaml
lendium.tech
Fake Ledium crowdsale site
https://urlscan.io/result/2b87b81a-a99f-46d8-9d04-6f1260147c20/
xn--myethrwalet-vrb05c.com
https://urlscan.io/result/67a88696-0cb7-4615-8e5a-50ca1456fe92/
https://urlscan.io/result/b120116b-a923-4cd4-8581-03101bd40df5/
kineticairdrop.typeform.com
Fake airdrop directing users to xn--myethrwalet-vrb05c.com
https://urlscan.io/result/1c66fbfc-6120-4950-85b6-2fea7049fc78/
elon-gives-eth.paperplane.io
https://urlscan.io/result/8dcf0bd1-aa10-4b46-b354-dd332c0e9298/
address: 0x458DEa31f89D70eD1923D414E4d4A72E98AD0A4C
rebl984.9999eth.com/?platform=hootsuite
https://urlscan.io/result/c7d48d4c-8b76-404e-8c2c-dfd918cfd29c/
address: 0xCeCF09F9b5c6D4D7651cB83eC8522d5879a300b3 …
=> lendium.tech + more

_data/scams.yaml
tomochain.tech
Fake Tomochain airdrop phishing for private keys
https://urlscan.io/result/e5fee213-90cc-4bd2-9a07-235c3e5e77ad/
https://urlscan.io/result/4e70356c-a0bd-46fb-8697-989bad358ed4/
https://urlscan.io/result/bd186b12-9184-4be9-bf58-349375ec2dce/
geteth.online
https://urlscan.io/result/6a04769a-9384-402b-a104-da9f5f3d3588/
address: geteth.online 
xn--myethrwalet-vrb05c.com/signmsg.html
https://urlscan.io/result/c6b29af2-8d46-4ac6-847b-da28df527b00/
https://urlscan.io/result/195435ed-8d32-4bb3-8987-15503793469b/
ethclaimer.byethost32.com/claim.php
https://urlscan.io/result/703a4532-5e24-43cd-94b3-7b5c06927ced/
eth-give.info …
=> tomochain.tech + more

_data/scams.yaml
got-eth.com
https://urlscan.io/result/2fbd7dd3-efbf-42eb-9aae-074f09567895/
address:  0xb0D2d2791657ce6CdF48b77A1E10F62E9b4Ee74B
=> got-eth.com

_data/scams.yaml
air-eos.com
Fake EOS airdrop phishing for private keys
https://urlscan.io/result/68f65da4-0da8-400e-8d8b-f90becb972f2/
https://urlscan.io/result/4baebde4-1821-47f9-abf3-206c2e95fd00
=> air-eos.com

_data/scams.yaml
coinbase.pro-fork.com
Phishing Coinbase users
https://urlscan.io/result/b60c8734-ef98-4f85-a557-0226586b33c0
https://urlscan.io/result/4f2dd8db-2667-45f4-974e-5b6f6b4c42f9
=> coinbase.pro-fork.com

_data/scams.yaml
eoslaunch.io
Fake EOS site phishing for private keys
https://urlscan.io/result/9a270b7a-d578-4651-a54f-010dc9046951
https://urlscan.io/result/9a270b7a-d578-4651-a54f-010dc9046951
=> eoslaunch.io

_data/scams.yaml
10000eth.net
https://urlscan.io/result/697341bd-582b-4071-9dd8-de97a20058a1
address:  0x135a24A24E524DE187efab379FC655061A67cBD5
=> 10000eth.net

_data/scams.yaml
ethg.me
https://urlscan.io/result/f56b696b-cf85-41e7-858a-e4dff63cc5d8/
address: 0xB9CEe6fa32eb4d0c8F30E3cd335b72461bD9126e
jdex.market
Fake Idex market site stealing private keys
https://urlscan.io/result/d348adc2-a97d-42a9-951c-9b0e777140ce/
idex-myaccount.com
Fake Idex market site stealing private keys
https://urlscan.io/result/ad09dab8-a77a-4567-9109-0853b30edaac/
index-markct.com
Fake Idex market site stealing private keys
https://urlscan.io/result/bb0f9101-30b3-4083-aeb9-a58831886cb5/
ldox.market
Fake Idex market site stealing private keys
https://urlscan.io/result/b8f029df-111f-40c4-b672-53a90748a4c8/
=> ethg.me + more

_data/scams.yaml
ether-giveaway.net 
https://urlscan.io/result/67bfacba-df9e-48db-8762-6466f6c68013/
address: 0x29Aaa966321F7d82E119BBc965a58CB62d703445
output.jsbin.com/ciqukak
https://urlscan.io/result/55f15485-82c3-43ed-8e10-25c3b18abd7c/
address: 0x3389a9CacB4A3FdbE43DB14D132b3F1e215A835d
ethget.me
https://urlscan.io/result/4aa0ab16-ff6f-41cc-84e7-cea8a46840e3/
address: 0x425E0406395243F087100C8F7b67C02217974123
ethbonus.org
https://urlscan.io/result/252f8ba4-770b-4669-aa5b-0d648a9bdaa1/
address: 0xEDfE1d963b32a89E05Dd0Bc0E8F595b4B9Afb544
eth-give.me
https://urlscan.io/result/fef1fdcb-708e-40e8-ac97-9c7d15e11413/
address: 0x7b433D46E875FE540b1eA2D3011113F1B400D3d5
getethnow.com
Trust …
=> ether-giveaway.net  + more

_data/scams.yaml
coinbaseverifier.com
Fake Coinbase phishing for logins and 2fa codes
https://urlscan.io/result/d0fe7e51-605d-4f3a-89b3-9bff24670054
https://urlscan.io/result/e702afd3-75db-4707-bef1-2a614e392d7e
https://urlscan.io/result/d0d176c2-1325-4a1c-896b-3722a0c719bc
https://urlscan.io/result/b14c0553-ba07-4d42-8972-6e5a0130ab80
=> coinbaseverifier.com

_data/scams.yaml
tron-online.info
Fake Tron web wallet
https://urlscan.io/result/8fbb20ce-7a97-4a61-8a23-182b4c66685f/
eth-request.org
https://urlscan.io/result/48ef89e1-c273-416e-b4c6-9c23546d516b/
anatomia.co
Fake airdrop emailing users to a fake MyEtherWallet - xn--myethrwalt-vmbe17c.com/signmsg.htm. Suspected address: 0x4A8b69Bd663e6967a118456a30a51495BDBa704c
https://urlscan.io/result/27a62247-8791-4d7a-a16b-44c028cd5421/
https://urlscan.io/result/8ecf7c62-516d-45c2-8cd3-df8ba3ec863f/
xn--myethrwalt-vmbe17c.com
https://urlscan.io/result/b83f8647-c40b-4970-9b4d-a702886ff3c1/
https://urlscan.io/result/14c102ba-95a8-402a-be8f-515e0736a36b/
myetherwallet.com.verification.atlaserbil.com
Fake MyEtherWallet. Suspected address: …
=> tron-online.info + more

_data/scams.yaml
xn--myethrwalt-zmbt05c.com
https://urlscan.io/result/861e97b0-c9a4-4819-ba78-b01590e31acc/
eth.share-coin.net
https://urlscan.io/result/b561af90-9dda-496a-ad4b-36ece1a5a8fc/
address: 0x81053C561Fd1e5305D05C651FCC2ae7c4ae2CdE6
safe.ethgiver.com
https://urlscan.io/result/18c84986-7163-4122-9ec2-c717d9e82245/
address: 0x798fb97BDA4DB2bdb5F75553F5a1BA73A5EdcF30
ethgiver.com
https://urlscan.io/result/c1e1a918-7380-428c-b686-d124aef1086d/
address: 0x798fb97BDA4DB2bdb5F75553F5a1BA73A5EdcF30
transfer.saferpayeth.com
https://urlscan.io/result/38d57c55-a773-420f-b221-2131509fec57/
saferpayeth.com …
=> xn--myethrwalt-zmbt05c.com + more

_data/scams.yaml
by 162.144.83.154 cross reference. 
[google sheet](https://docs.google.com/spreadsheets/d/1BgLeQjHbjasUCqZY_5tIn8ohX3iXWD_SpU_jDzjVHnE/edit?usp=sharing)
=> ethers.cz + ethergate.space

_data/scams.yaml
xn--mytherwalt-smbh17c.com
https://urlscan.io/result/bdedc869-8da9-4da7-b129-11415daabc50
https://urlscan.io/result/d125ab9a-503c-4cfa-b966-b7c685ca2eea
=> xn--mytherwalt-smbh17c.com

_data/scams.yaml
https://ibb.co/dv6oky
A screenshot of the email asking to send fund to the scam wallet.
=> add email phishing attempt

_data/scams.yaml
=> Add phishing google doc

_data/scams.yaml
ethtopromo.org
https://urlscan.io/result/33450afe-f8cd-4035-b8b6-877803188e71
address: 0x6D0Aef62e321Cf1AFB74A4A305f380d9f5c34c8A
register-eos.io
Fake EOS registration phishing for keys
https://urlscan.io/result/931596ee-5af2-4818-b01d-20505732579a/
https://urlscan.io/result/2dca75c1-e997-45af-9140-2a9375d1cb9e/
ethereum-get.info
https://urlscan.io/result/a6e68320-b32d-4cc9-9f4b-5bc3d2ca9ae1/
address: 0x8715e3E9cBe013bf54de58431a078a650B2Ece1A
xn--myethrwaet-inb90ca.com
https://urlscan.io/result/db3a5037-8399-40cb-9fb8-1521daa0a1c3/
https://urlscan.io/result/d5945023-5f96-4d91-a9da-954cf476ea57/
myetherwallet.com.token.signinverication.signmessage.carpediem.legal
Fake MyEtherWallet. Suspected …
=> ethtopromo.org + more

_data/scams.yaml
idex-info.com
Fake Idex phishing for keys
https://urlscan.io/result/b719ca98-cd52-4a4b-8c7f-45d075e2adbe/
idex-market.org
Fake Idex phishing for keys
https://urlscan.io/result/1bd92ffe-c5d5-470e-a8a6-b2c5a0a45bcb/
myetherewallete.com
Fake MyEtherWallet. Suspected address: 0xc4BD211E5b92235E6426113Cd735B74bC4335d08
https://urlscan.io/result/5f18a880-b187-45d4-99a4-6b4fe16f94cc/
xn--myetherwlet-37a36j.com
Fake MyEtherWallet. IDN homograph attack domain
https://urlscan.io/result/dfa84574-fe59-44a5-8cb7-1d0ef1321977/
https://urlscan.io/result/3b88e2d9-f6cd-4682-8d53-e8c64374d1fc/
xn--myetherwllt-37a50e.com
Fake MyEtherWallet. IDN homograph attack domain
https://urlscan.io/result/7fb69f5a-8ea3-474d-b3ee-82b22cd97dff/
https://urlscan.io/result/eb690243-7fa4-471f-b6ec-7f4b51688ee4/ …
=> idex-info.com + more

_data/scams.yaml
calchain.net
Fake airdrop directing users to a fake MyEtherWallet (xn--myetherwlet-37a36j[dot]com & xn--myetherwllt-37a50e[dot]com). Suspected address:  0x4121cc82607ebab3f334e067f37fe2709c403bf6
https://urlscan.io/result/bd447370-4992-4d03-b41e-ab4afd24103c/
https://urlscan.io/result/892e43a7-10e2-4b57-9a27-996d967f96f5/
ethpays.me
https://etherscan.io/address/0x297A88c749273F2DE6a378A6015Dd624D993C671
address:  0x297A88c749273F2DE6a378A6015Dd624D993C671
=> calchain.net + ethpays.me

_data/scams.yaml
ethgive.me
https://urlscan.io/result/044295a5-002f-42fa-a530-d922d6424ccb
address: 0xCe82F4195C47110978099F86d2B33a8135F71974
ethgives.me
https://urlscan.io/result/b86239f0-1049-4073-b54c-f3549a520fdd/
address: 0x1EC6eCc934eC1aD85Bb4b579CFc53807Da435A4D
promaestros.co.uk
https://urlscan.io/result/4bd51f67-a4b9-4c99-92e5-4a94fa376cbb/
https://urlscan.io/result/7e02c68e-d241-44df-813b-b30ca9e35a02/
https://urlscan.io/result/156b3b31-6881-4786-9c82-b2aeb4742188/
address: 0x410ebb88525ea799ea9e15a03f794f7f6f2fbdcd
ethaddress.neocities.org
https://urlscan.io/result/2fe8bc93-3389-46fe-90a8-c44ad4bb7138/
address: 0x54189eab44661be1b081b4535c050230a787d816
changellyico.bitballoon.com …
=> ethgive.me + more

_data/scams.yaml
xn--myetherwllt-f7a75e.com
https://urlscan.io/result/8d098940-7a44-4f2d-979e-62860d3e39a9/
https://urlscan.io/result/7e3a7ec8-8268-48e6-ae47-5fe72a65f909/
=> xn--myetherwllt-f7a75e.com

_data/scams.yaml
ethpromo.io
https://urlscan.io/result/802c5bce-c40e-42d7-8f6a-cc65d6c5a5bf
address: 0x4Dad23689bEf624aF5d1757A56135901c915FCFD
myetherwallet.com.signinverication.verifcaon.site
Fake MyEtherWallet. Suspected address: 0xCDb26199dB086d54F7b11e50cA4374b4Dd9CE13f
https://urlscan.io/result/66e84dbd-bf6b-4b96-8d16-98dce1025c6f/
https://urlscan.io/result/47be8e46-ddc4-4a93-b776-6847138cc918/
verifywallet.typeform.com
Fake airdrop directing users to a fake MyEtherWallet xn--myethewallet-4nf.net
https://urlscan.io/result/ecf4888e-2f9c-4bea-8f01-40ad98e80dc3/
xn--myethewallet-4nf.net
Fake MyEtherWallet - IDN homograph attack domain. Suspected address: 0x1ee6b25a0e3f855a10916766df3a056e924e5dce
https://urlscan.io/result/073f84b4-ef76-4bfc-8d81-544b26e92afd/ …
=> ethpromo.io + more

_data/scams.yaml
ethgw.info
https://urlscan.io/result/16b8a6c8-009c-4efb-a4e0-40e8ca5029fb
address: 0xB6ADacf355031C10b4FD70eE7FB4acA88A7C216d
ethbigpromo-com.1gb.ru
https://urlscan.io/result/2d53b056-bad2-475d-a409-95838688ba59
address: 0x2c1dF1D2B053E2BF89BB5251AF392bc962326e51
claimcrypto.org
https://urlscan.io/result/b6314c07-986c-4365-8a4f-d6c488311282
address: 0x839DB3994bef8842C0809AB84996bA839fCac11e
=> ethgw.info + more

_data/scams.yaml
saferpayether.com
https://urlscan.io/result/009e33e8-7787-4f64-be5f-731284318afa/
address: 0x4Dad23689bEf624aF5d1757A56135901c915FCFD
ethgive.global
https://urlscan.io/result/46792cd3-e970-48f3-8f9b-62b25e39e02a/
address: 0x9849424a2f3516B70b56D70330c45c25DcCb2C02
ethpromo.info
https://urlscan.io/result/92f5e9e6-1175-417b-86c8-a7ef0f374f6a/
address: 0x88620C720523c822adCdc1d5484915fcD85BAf73
ethereum-promo.org
https://urlscan.io/result/69373894-565e-4aab-8b8e-d5e6c0676ab0/
address: 0x48dcc01a31E38e14F6a63846E371C6e9Cb0C3f3a
crypto-claims.org
https://urlscan.io/result/83bc8915-e840-49e0-9167-e174c72d28dd/
address: 0x839DB3994bef8842C0809AB84996bA839fCac11e
getethnow.com …
=> saferpayether.com + more

_data/scams.yaml
kinetictokenform.typeform.com
Fake airdrop redirecting users to xn--myetherwllt-r7a44e.com
https://urlscan.io/result/ec31a417-ac95-41c6-ab66-b4cbfbf63c07
xn--myetherwllt-r7a44e.com
https://urlscan.io/result/29ae1633-1da5-4c23-bad0-bd7d1ef762ac
=> kinetictokenform.typeform.com + xn--myetherwllt-r7a44e.com

_data/scams.yaml
myetehrewallet.com
https://urlscan.io/result/8e75a814-3f7b-4de0-ac08-2ca577017731/
lbex.market
https://urlscan.io/result/8e75a814-3f7b-4de0-ac08-2ca577017731/
idex-info.net
https://urlscan.io/result/85332caf-df30-4aaa-8fca-16c9970daa4b/
get-eth.win
https://urlscan.io/result/b64e468a-e397-4801-903e-d30c0d216ac2/
address: 0x3BD49b98ffcC5f717eED0c9e78a276Ae979de6e4
eth-claim.org
https://urlscan.io/result/a587f026-fc54-42b2-96db-f4dafe60f183/
address: 0x34d202c37f9609A3d0d44db259ff51Bae8ea2D0f
eth-givebacknow.tumblr.com
https://urlscan.io/result/52ca3146-aafc-4b1e-8371-7e85a97160d0/
address: 0x6CFDdE4E08c9e2CF1b9A32d2C31203966B17f816 …
=> myetehrewallet.com + more

_data/scams.yaml
idexmarket.io
Fake Idex market phishing keys with GET store.php?mapza=&action1=1
https://urlscan.io/result/151f9aff-a89c-4866-bab8-afb3356f4f1a
https://urlscan.io/result/b47a139d-b4a2-4b9c-88db-46ae619274a0
=> idexmarket.io

_data/scams.yaml
keyfund.io
Fake airdrop directing users to a fake MyEtherWallet xn--myethrwalt-vmbe17c.com
https://urlscan.io/result/164ac14a-06a9-4119-9a9b-f22a0fe126db/
https://urlscan.io/result/d8327bb3-ff86-4620-9f6c-716bb93aeca0/
ethereum-promo.xf.cz
https://urlscan.io/result/b68e6017-64fc-40b6-9d6f-8940f0341343/
address: 0x997ad34840281d459251abdf9c90d9a8c6a6e01a
myetherwallet.comsigninverication.signmessage.crocweb.online
Fake MyEtherWallet. Suspected address: 0x6ab2a9088916bf97c248888009b669aa37bab681 0xcdb26199db086d54f7b11e50ca4374b4dd9ce13f 0x5127E8d79160f4cD177F5aC5A1e860acAa59a34B
https://urlscan.io/result/46be63c2-3bf1-470f-88df-edc88c95284d/
https://urlscan.io/result/9d5b4442-7b25-49ab-90f1-715b045ebfd1/
myeosdac.top
Fake EOS airdrop asking for address validation on …
=> keyfund.io + more

_data/scams.yaml
eos-swap.com
Fake EOS countdown, phishing for private keys with POST /VerifyToken.php
https://urlscan.io/result/0a39213a-6447-4660-b663-09fd8fdb8d0c/
=> eos-swap.com

_data/scams.yaml
promotoeth.org
https://urlscan.io/result/b59fd627-9211-4725-a6b4-1b9cabd617d9
address:  0xb733A811edF703701d2403d8196df87306BED6D6
=> promotoeth.org

_static/js/search.js
Casted searches as lowercase, strip protocols, www identifier, and trailing slashes.
Removed notifier about mew/mycrypto split from search banner result.
Fixes Issue #898
=> Fix searches

_data/scams.yaml
idex-market.eu
https://urlscan.io/result/85459fee-49d3-45e1-aa66-953a64dfad5f/
idex-login.net
https://urlscan.io/result/c4515f76-046d-40a0-bccd-7bda2e606663/
index-macro.com
Fake Idex market phishing for keys - iframing 185.156.173.87
https://urlscan.io/result/89e6ea11-f3b0-4ebd-b1ec-5a9535579efb/
185.156.173.87
https://urlscan.io/result/a6b3aa90-655c-4739-bdcd-86f5e606655f/
eos-paperwallet.com
Fake EOS paperwallet generator
https://urlscan.io/result/b1f771e9-684d-413e-a260-f3193b60a902/
=> eos-paperwallet.com + more

_data/scams.yaml
eth-get.com
https://urlscan.io/result/3625920c-652d-4e0f-bdf2-5bced94e57fd/
address: 0xf8abBDc8578B940b82906a2E8da893B164D4FA59
giveaway-ether.info
https://urlscan.io/result/e47f8558-80bc-49d7-a10f-b09c4a9484ed/
address: 0xa78959E1568448a3CF866968872431E710458552
ether-give.club
https://urlscan.io/result/a21636bf-face-4f76-a4b8-66f994d84a70/
address: 0x50a9a8c8ce2bb0ea10f4d4a586ac2d77257b8247
eth.promo-etherum.com
https://urlscan.io/result/8ed60ed2-dd11-44f3-9bf7-751f2ffd668b/
address: 0x2d19F9FEcE6DA18f2899944B0621C5eCeBAa249B
promo-etherum.com
https://urlscan.io/result/f8fde317-2a1d-4238-bf5d-40325eeca1f7/
address: 0x5526dc369bBE6B9B2c5e64BB368C1d3Ccfa58271 …
=> eth-get.com + more

_data/scams.yaml
idek.io
Fake Idex phishing for private keys
https://urlscan.io/result/aeeb5e0f-7581-441d-ac3a-1abb0ec12390/
idex24.io
Fake Idex phishing for private keys
https://urlscan.io/result/b7e9dd3a-0f2e-436f-97a7-4c427342c459/
=> idek.io + more

_data/scams.yaml
collect.bestethgift.com
https://urlscan.io/result/254ba5d8-2842-4d63-8867-ab3126294e2d/
address: 0x3E53A430c39896dAf1b241828e3b5E8D526503fA
bestethgift.com
https://urlscan.io/result/2c59a121-f267-421d-8bd8-b13bf1fb21e3/
address: 0x3E53A430c39896dAf1b241828e3b5E8D526503fA
=> bestethgift.com + collect.bestethgift.com

_data/scams.yaml
idex-market.io
https://urlscan.io/result/08ffdaa2-d86e-4d17-a44a-cfae78b23514/
xn--myethrwaet-inb90ca.com
https://urlscan.io/result/b2015114-24ae-493c-a86b-4c49c1b252c7/
xn--myethrwalt-vmbe17c.com
https://urlscan.io/result/7573ab9d-aea1-47e9-82ac-b81a56c99774/
xn--mytherwalt-smb5a54c.com
https://urlscan.io/result/93fe7000-6a42-4c78-9b6f-aa60cc7a163d/
xn--myethrwalet-vrb15c.com
https://urlscan.io/result/d2102d90-364f-4ca8-9020-cf066b0f3c07/
xn--metherwallt-5hb16a.com …
=> idex-market.io + more

_data/scams.yaml
telegram.vu
https://urlscan.io/result/dfa596be-555c-4e49-a260-3546d732a1ba
address: 0xbf863b57322A1E634388946F942306393A5D4c69
mydeliverycv.com
https://urlscan.io/result/5bf2032c-b012-4b72-a329-bcc17f8c74bb/
ethereumbonus.org
https://urlscan.io/result/5d323899-056d-4d2d-a73f-3568c870a7d1/
address: 0x2271A88623266069352196363c1E54f61C5141E1
ether-giveaway.online
https://urlscan.io/result/16977475-37b5-4290-add5-88fbe718171d/
address: 0x483ec0E946d1d61696Bc8F69ef10365bD80862dc
=> telegram.vu + more

_data/scams.yaml
myiteher.com
https://urlscan.io/result/034d2101-0afe-4a50-b617-b56b920338e7/
musk-giveaway.com
https://urlscan.io/result/b66e97b1-8708-4209-b2d3-fda4cfdb8a07
address: 0x7C875Ee4D4a1B29B41eBb2678dF1F645F28d090B
get-ether.cash
https://urlscan.io/result/30b8bc99-858f-4faf-90ae-4d113d2d90ce/
address: 0x3d7A0fAE63809c4725b13bddDabBb718939AD10e
crypto-claims.org
https://urlscan.io/result/5ded4350-665e-4778-9bcb-5e1167c339d4
address: 0x839DB3994bef8842C0809AB84996bA839fCac11e
free-ethers.com
https://urlscan.io/result/e754bc6e-0f2b-4ce8-9efa-5c995b5c3c37/
address: 0xAa9455da13bA39f5d4E6275337C3D5600CB0f5B4
ethershares.blogspot.nl …
=> myiteher.com + more

_data/scams.yaml
etherskan.io
Fake Etherscan
https://urlscan.io/result/86dbc2d5-6741-45a6-8a8c-40d0d792340f/
etherscan.ltd
https://urlscan.io/result/9c0021c2-2bb9-4d0b-8c52-901984e43841/
address:  0x5c0133DC7E8811B3FADdD1016d0800Dbf5beC2D8
=> etherskan.io + etherscan.ltd

_data/scams.yaml
fantoms.foundation
Fake Fantom crowdsale site
https://urlscan.io/result/2ae25deb-e191-4638-8f76-790258d653e8
address:  0x8d305Fd29aEbd6e0562dE9321d55E7f0E6fbaCaD
=> fantoms.foundation

_data/scams.yaml
myetherwallat.co
https://urlscan.io/result/3c70440b-4d81-4d1f-92fa-2afe17202135/
https://urlscan.io/result/1819f02b-88ab-427f-8c06-2e0420e573c3/
idex-info.com
Reported as fake idex site. Suspected address: 0xFdf02F6BeeF524Df60a066cbE795957F78C63B1D
https://urlscan.io/result/d2726e1b-ad7f-4cd1-a4a1-457123f086b5/
xn--mythrwalet-umbv35c.com
Fake MyEtherWallet - IDN homograph attack domain. Suspected address: 0x604DA69D33a0Df6414c30270434bA4E0e95d8cF6 0x8B170540B63d2F826846f3C0B9E6410B08548Ec3 0x5d4d57cd06fa7fe99e26fdc481b468f77f05073c 0xd53eC8a1478e7128D2D5F131A36462Ca3190fCce
https://urlscan.io/result/3c1f5864-d5ed-4dbb-96f5-a9c07c371630/
https://urlscan.io/result/e43e4f2a-8c3a-49e1-8d3d-15ecb55a830c/
xn--es-8bb.com
Fake EOS. Suspected address: …
=> myetherwallat.co + more

_data/scams.yaml
safe.ethxchanges.com
https://urlscan.io/result/7ddef598-9bc6-40a9-ab1d-4fa28f283da5/
address: 0x27F897EBeeD82240734489D52AA7e39a8cA257E9
ethxchanges.com
https://urlscan.io/result/37c9b0b7-8441-4630-9d89-20136c74e21c/
address: 0x27F897EBeeD82240734489D52AA7e39a8cA257E9
xn--mythrwalet-c7ac47i.com
https://urlscan.io/result/56dda366-2eda-4066-8009-c24029bcce3f
xn--mythrwallt-c7a86c5a.com
https://urlscan.io/result/958680db-9cf0-44ea-9ea1-dc552963bc59
zecblock.info
Fake ZCash web wallet
https://urlscan.io/result/d906bf97-f70b-4b33-af38-3378daa10371/
litecoin-chain.info
Fake Litecoin web wallet
https://urlscan.io/result/955ce8f8-14be-4332-bd16-767f137ac369/
ripple-chain.org
Fake Ripple web wallet …
=> safe.ethxchanges.com + more

_data/scams.yaml
xn--myethrwalett-8vb19c.net
https://urlscan.io/result/870b6b80-baa5-4d0c-b9c1-44bc75d38f2d/
https://urlscan.io/result/134f33a4-1fb7-4e02-9468-73e380d97588/
=> xn--myethrwalett-8vb19c.net + more

_data/scams.yaml
ether-give.club
https://urlscan.io/result/cd5adf1f-97b0-4371-9399-58a202875ebd
address: 0x50a9a8c8ce2bb0ea10f4d4a586ac2d77257b8247
myethertrust.com
https://urlscan.io/result/7a407d1b-72b4-41f3-8a77-9931faced750/
https://urlscan.io/result/95cff247-e7a5-4257-be42-31cefbf91906/
=> myethertrust.com

_data/scams.yaml
etheroll.io
Fake Etheroll
https://urlscan.io/result/10c2378c-fb28-4556-a97d-07f793f42586/
address: 0x521ff702e1eed9e48cbe17e2dae6efd77b9d6876
=> etheroll.io

_data/scams.yaml
xn--myetherrwalet-5hc.net
Fake MyEtherWallet - IDN homograph attack domain. Suspected address: 0x7e25f33c1e3402f2197dab251ce2d73cdbcb77a3
https://urlscan.io/result/451f46eb-10d1-4f73-a3db-accbd07bd231/
https://urlscan.io/result/1a5b2a0e-bc4c-494e-8d9b-a0c70660e94f/
idice.epizy.com
Fake idice GUI
https://urlscan.io/result/afb9685c-b12e-428b-a7c3-fc6c9a32405b
address: 0x9b2D66562bea3EefEc436dF0Fee88Dd89CbE547b
gene.network
Fake crowdsale site directing users to a fake MyEtherWallet http://bahs.edu.tt/https_myetherwallet.com:gese_token_redeem/
https://urlscan.io/result/400cf5f4-43bb-4671-bdba-5508c4113596
bahs.edu.tt
Hosting a fake MyEtherWallet
https://urlscan.io/result/02b1388f-408b-4f7a-811f-dbf5f9f797fa/
https://urlscan.io/result/dc97ff76-e8b7-47db-89bc-91d5335cccc2/
=> xn--myetherrwalet-5hc.net + more

_data/scams.yaml
xn--mythrwalet-smb0a15c.com
https://urlscan.io/result/27f206f0-01e2-4599-9ef6-d0b89a99682f/
https://urlscan.io/result/a37d1745-c7fc-4e97-b3fb-dc7171acd38e
myetherwallet.com.signmsg.info
https://urlscan.io/result/4b28d824-708d-4cf2-be9e-377457c13ec7/
https://urlscan.io/result/025711cb-53cb-4c6e-9c42-ae271ede4d4c/
oracon.io
Fake airdrop directing users to a fake MyEtherWallet - myetherwallet.com.signmsg.info
https://urlscan.io/result/a5e0c558-338c-4ca4-8194-fad5e2130b66/
eth-bonus.org
https://urlscan.io/result/6719abca-cc48-42fc-b0e1-00b123d7efff/
address: 0x577cad8D4C0511AC704cc2d4D0a01d20917A3035
piscorealestate.com
Hosting a fake MyEtherWallet on GoogleAds (cloaked redirect) - …
=> xn--mythrwalet-smb0a15c.com + more

_data/scams.yaml
xn--myetherwalle-mm5f.com
Fake MyEtherWallet - IDN homograph attack domain - not deployed yet
https://urlscan.io/result/b01afd50-265c-40f2-a47b-61d12b458fa4/
xn--myeherwallet-4j5f.net
Fake MyEtherWallet - IDN homograph attack domain - not deployed yet
https://urlscan.io/result/82292a41-b776-4772-bf81-ef99df50fdca/
xn--myethrwllet-q7a5h.com
https://urlscan.io/result/6da58982-b108-46da-8ee9-2c73eb13b48b/
xn--dexmarket-98d.com
Fake Idex - IDN homograph attack domain
https://urlscan.io/result/d5e9d423-b402-4360-b8a9-fcdd1751e609/
=> xn--myetherwalle-mm5f.com + more

_data/scams.yaml
bittrex-id.com
Fake Bittrex phishing for logins
https://urlscan.io/result/09b33e3d-968b-4362-98de-fb396a4804fc/
https://urlscan.io/result/7e400a30-007f-4850-b069-ee2985e1469b/
https://urlscan.io/result/8d7d0414-6f39-4d40-9e51-82b7ba7f95ec/
https://urlscan.io/result/ccd56adb-f65c-4a04-95fc-7e6bd38f93e9/
=> bittrex-id.com

_data/scams.yaml
idex-market.at
Fake idex market phishing for keys
https://urlscan.io/result/b8ff420b-5a25-4d76-853d-beed5b917545/
wallet-idex.net
Fake idex market phishing for keys
https://urlscan.io/result/57e1c18c-5307-4985-98d4-2e1ffc91710a/
=> idex-market.at + wallet-idex.net

_data/scams.yaml
myighther.net
https://urlscan.io/result/c6bb837d-afd6-4f1d-8989-77aa00b58e2f/
eteclum.org
Fake MyMoney login phishing for keys
https://urlscan.io/result/b643e6b0-549c-4f77-aa6f-e840076e9a8e/
https://urlscan.io/result/10ac8b04-50de-4cef-8c2c-0a3e818f34c9/
=> myighther.net + eteclum.org

_data/scams.yaml
ethbonus.org
https://urlscan.io/result/0c68353e-e767-4be2-8b71-32e43162adfb/
new address: 0xBB27D8dB02d9035c0783166eE39269d97a1985e2
=> ethbonus.org

_data/scams.yaml
giveethers.info
https://urlscan.io/result/ff1da622-1372-47c5-8900-a47a00afc0b7
address: 0x77C955a2cb5BCCAf0654d78a3FFcD8bd6cB0c2B8
=> giveethers.info

_data/scams.yaml
eth.blogmedium.top
https://urlscan.io/result/13555aff-7e59-432c-8033-553d6ea0fd82/
address: 0x9aC33De53E16b21250Ba2418150fe07Ce8C7e5e7
eosregistry.site
Stealing seed phrases. Fake EOS register
https://urlscan.io/result/70b178e4-ee6b-411a-a354-e9d9fd92c757/
https://urlscan.io/result/de0c8bc2-b643-446e-9f16-e3a949deb3e8/
xn--coindes-jhb.com
Fake Coindesk promoting a fake EOS article. Suspected address: 0xF9390CdA498171e748cD0B43FF65f747867E3eD3
https://urlscan.io/result/c35aca1b-ef3c-4c1d-ac61-0c79b5254582/
https://urlscan.io/result/5d9b3969-ebda-4160-8277-cdc1ad7e8b92/
=> eth.blogmedium.top + more

_data/scams.yaml
=> ethergive.net

_data/scams.yaml
airtake.info
https://urlscan.io/result/2c0e8447-0ac3-41aa-8638-4736cc48244f
address: 0xB9556A1cb3150148443e9e9E9C29491FF48640Ee
=> airtake.info

_data/scams.yaml
walleteos.io
Fake EOS Wallet site. Sending keys to POST /unlock.php
https://urlscan.io/result/af65bbbe-f99f-43b7-a5bc-f1bf551af912/
originprotocol.typeform.com
Fake Origin crowdsale site
https://urlscan.io/result/fce2403a-41ba-47dd-8c45-096ab8803962/
address: 0x42E0a4818fF863E8d73187279aDfC17b0495f2cF
myefhervvallet.com
https://urlscan.io/result/aac200fd-e3e7-44e7-8997-438bc445edde/
sparkster.be
Fake Sparkster crowdsale site
https://urlscan.io/result/1ce664ab-926e-4044-8885-8d1aac1b162e/
https://urlscan.io/result/5db4b0e8-f89f-4ce6-8471-9e13817817ec/
address: 0x6a1dEA6F4C9D48035D855e8399e20e254F0Ce1ac
etherguide.info
https://urlscan.io/result/81320499-7c8d-4c30-9c7a-7038aaf3d933/
address: 0x4427ee02Ffa0BfAB4206f445a31239323177b587 …
=> walleteos.io + more

_data/scams.yaml
welcome.promotionaleth.com
Trust trading scam site. Promoted with https://bitly.com/2HCBz5w+ and https://bitly.com/2JJQP5y+
https://urlscan.io/result/55ea6c95-e3e9-4cf8-b141-212bd3b9a58f/
address: 0x9951bE5ac7Daf77724A4f7443bef446F6184a377
promotionaleth.com
https://urlscan.io/result/b2dfb9ca-b3bc-4df1-b3cf-047c9c50ddea/
address: 0x9951bE5ac7Daf77724A4f7443bef446F6184a377
=> welcome.promotionaleth.com

_data/scams.yaml
hederahashgraph.tokenico.me
Fake HederaHashGraph crowdsale site
https://urlscan.io/result/48c7d465-45f3-47a8-a33b-b77eb644f42d/
address: 0xEDc702Ed96AccAE315A0F1E8Fa2d5a6bC4FeeA69
secure.ethxchanges.com
https://urlscan.io/result/887699fd-57d7-45d8-b291-c850743e40d7/
address: 0x9d032989F82c0e40202AE5Abd844Ff68181544D2
ethxchanges.com
https://urlscan.io/result/ba752127-9a1f-4822-aab2-cbc1647f6d73/
address: 0x9d032989F82c0e40202AE5Abd844Ff68181544D2
ethgift.io
https://urlscan.io/result/1cca3abe-3d05-43ee-80a2-85e5a6a821e3/
address: 0xcEe56C3d77d814d29b9410c0f74c12781fcE03ff
verify.officialeth.com
https://urlscan.io/result/701e75b3-8341-435f-90e3-3d853ad4697b/
address: …
=> hederahashgraph.tokenico.me + more

_data/scams.yaml
getbigdeals.org
https://urlscan.io/result/862b618b-36fa-4597-9d51-e51ce2a95065
address: 0x1d138d1f0e8E5F67540b6054De7dB08A610F85B4
ethpromotions.org
https://urlscan.io/result/b3160585-929f-4ecd-9155-b2d331e6293d/
address: 0x016c0261C48D089Ac26d0a48f840c9A9d5e203dd
wincheck.org
https://urlscan.io/result/26a16ed0-f949-4835-ba56-640551ddd00b/
address: 0xF1a4b668D15F0E66543e9F1F795cC2B0f97E3ef2
ethfor.info
https://urlscan.io/result/e97b3b14-c8bf-4811-ac6e-4815b6596ebc/
address: 0x2299c90980777Bb9ebf2D8D58a92Cb3AB7F7fAA0
=> getbigdeals.org + more

_data/scams.yaml
ploloneix.com
Fake Poloniex phishing for logins
https://urlscan.io/result/555d63a7-9b45-44b3-b253-1fc9cb2b3aef/
https://urlscan.io/result/fc7bb045-d480-4978-92a1-dc00abec5e4d/
porloneix1.domen-hosting.org
Fake Poloniex phishing for logins
https://urlscan.io/result/28ccee82-8ad6-48e6-8931-9cb264deb130/
https://urlscan.io/result/5ee727e7-58f6-4f16-a47a-7e84ea2d8fb9/
porloneix.com
Fake Poloniex phishing for logins
https://urlscan.io/result/af728fe0-02f5-4868-a00b-bd396ae62f39/
https://urlscan.io/result/8f1aa92f-d601-4a61-b01a-e344f9b05f05/
polroniex.com
Fake Poloniex phishing for logins
https://urlscan.io/result/3c979218-08ce-4183-a4d8-b6f24483c562/
porloniex.com
Fake Poloniex phishing for logins
https://urlscan.io/result/0751f587-0be9-4aa8-99ba-86e24b79002b/ …
=> ploloneix.com + more

_layouts/ip.html, config.example.js, run.js
* Added logic to give links to abuseipdb and urlscan. Also counts the total related scams
Related to https://github.com/MrLuit/EtherScamDB/issues/925
=> AbuseIPDB link

_data/scams.yaml
giveawaypromo.byethost14.com
https://urlscan.io/result/b4b99bc5-c986-4e82-8819-fc5a6e04115e/
address:  0x6a9C2EC4f4888D7338fC1b28584AaAfEb01e6Db3
xn--myethrwllt-y4a7gf.com
https://urlscan.io/result/514607ea-ab4b-450f-8f31-b921cc5889d7
=> giveawaypromo.byethost14.com + xn--myethrwllt-y4a7gf.com

_data/scams.yaml
etherbonus.win
https://urlscan.io/result/30bd9155-e362-4064-947c-7a244284695d/
address: 0x1AE807d7645da9F7F65A3c4A7A8DeaA08bf9EFa4
getethpro.com
https://urlscan.io/result/4e3b561b-3534-446d-961f-0ab907ce8189/
address: 0x701cB175E6cA0EE8DcB61B4598B5a08E2A60bc2A
about.me/vitalik.buterin
https://urlscan.io/result/10be364d-60b8-4c6b-9c25-ddcc072221fc
address: 0x7d5F788097E80D797064FdE23a62CaF8D18Ee5a6
event-ethereum.org.uk
https://urlscan.io/result/4d4ce7fc-420f-42ec-b8b6-1520b29a4147/
address: 0xE3400442Ed7754cB2a43beCB83f801Cce1055Db9
=> etherbonus.win + more

_data/scams.yaml
index-markels.com
Fake Idex Market phishing for keys
https://urlscan.io/result/a295c4d3-1313-4169-b1f9-be9e6f3e3204
=> index-markels.com

_data/scams.yaml
eth-claim.org
https://urlscan.io/result/b9e0175d-1627-42f7-8e07-1b1e5b314d18/
address: 0x87F655E887827eD11Eb3fBC74767B18E142cCced
ethpays.org
https://urlscan.io/result/f0f39673-df5d-422b-b4e6-9b582d4bea77/
address: 0x56ccaA034A0bDb7D3A9515CB580FB5448EfB584C
verify.officialeth.com
https://urlscan.io/result/5c496a5a-cb55-44e6-b355-7b0f58f013e4/
address: 0x6eC56FB2436BA6706CeCD42403B6a1b69fF0817F
safe.ethpaynow.com
https://urlscan.io/result/06ec366f-5e8c-4817-9e80-cbc1ba90027a/
address: 0xa23203C466A57649b83687A3D9129D3EC427C50a
elon-gives.com
https://urlscan.io/result/619af9c7-8cac-4989-a64c-5ddb62ca7997/
address: 0xeb6a066D30c55609fB9f3f6446C6Ef8f27033D2A
=> eth-claim.org + more

_data/scams.yaml
eoscountdown.co
Fake EOS countdown directing users to xn--mythrwalet-smb0a05c.com
https://urlscan.io/result/e7423951-27e5-40bd-bfa7-4bb8327fc247/
xn--mythrwalet-smb0a05c.com
https://urlscan.io/result/4fd4747f-3c2f-4b3a-b0cd-6649643b3327/
https://urlscan.io/result/1609449c-f653-4711-b66a-2db4e8077905/
go.boosteth.com
https://urlscan.io/result/b003ee43-4d5f-4988-a26c-16d5e1a6887d/
address: 0xF7A5a8A2d0D46377a7F9607dF66FF963A23034C2
boosteth.com
https://urlscan.io/result/3605947e-06b8-4e57-939b-a2d24737e2a7/
address: 0xF7A5a8A2d0D46377a7F9607dF66FF963A23034C2
claims.payeth.promo
https://urlscan.io/result/60c13ad5-3269-474f-b026-0ac0e0c31d61/
address: …
=> eoscountdown.co + more

_data/scams.yaml
today-ethereum.com
https://urlscan.io/result/0deae08e-688c-414a-97e6-e3fe675b5344
address: 0x4dD0eF53784030fA675e2677F9CdC2a3e32E956B
ethnow.org
https://urlscan.io/result/045a6b1d-6808-4347-8227-99ce3686cdbd
address: 0x3963C374e0E71018dBA76814c13fdd5458d55898
=> today-ethereum.com + ethnow.org

_data/scams.yaml
index-marketz.com
Fake Idex phishing for keys
https://urlscan.io/result/2f40772d-8fbf-4f6c-b3d9-29f336f7d72d/
68.168.123.85
Fake Idex phishing for keys
https://urlscan.io/result/b5500281-6750-4a4f-88c9-8efe706bfc61/
eth-promos.org
https://urlscan.io/result/000f2e75-1fbb-41eb-8519-136906f920d7/
address: 0xA6f2814C0020c38882e82D9bFde7B485a7297a1D
ethxinfo.com
https://urlscan.io/result/48d9d57f-5b32-48c0-bb8e-956ad5f0391f/
address: 0xA636fafCf1bb16685AF835C2674A7FF022BB67A6
ethereumpromo.org
https://urlscan.io/result/0f69e5a7-b8f1-480d-b5f3-476f0edced8d/
0x224B9f4666472682f3e805f4dC1e0Fc39B7B96fB
eth-giveaway.surge.sh
https://urlscan.io/result/8fcc66ee-4040-42fc-8fa6-3806b5e1e7f4/ …
=> index-marketz.com + more

_data/scams.yaml
ethereumgw.org
https://urlscan.io/result/606005ea-97da-44a0-8b90-00c568b4543b/
address: 0xA6f2814C0020c38882e82D9bFde7B485a7297a1D
epromo.cc
https://urlscan.io/result/c1788f18-d7e8-4f3c-9b09-8907e1ff2ba6/
address: 0xc9194a772c23A595dFAB28E30376f2e16eC39E01
=> ethereumgw.org + epromo.cc

_data/twitter.json
=> updated twitter.json

_data/scams.yaml
giveawaypromo.byethost14.com
https://urlscan.io/result/0937b2ec-aa70-4a5d-8ce1-bf8f608c3a5d
https://urlscan.io/result/33778c52-874b-4fd4-8278-456674e4f415
address: 0x8D3CFe26a635A322F814512d3e09dF75F7CbfBd3
myetherwalllet.online
https://urlscan.io/result/d283b3cf-8d78-4cfb-a652-6d6f7003bc33/
odyssey.plus
Fake Airdrop phishing for private keys
https://urlscan.io/result/81c5f681-3e76-48fe-86ac-e6dd27be6d48/
https://urlscan.io/result/905d3f38-c720-4755-9ed5-0cfee96c8ac7/
https://urlscan.io/result/c8fd8cd5-2e13-4840-aa92-acaa9f8404dd/
address: 0xaf8185ffff6a3508fc5498a5165bf64de0b0a1e5
=> giveawaypromo.byethost14.com + more

_data/twitter.json
=> cz_binatce

_data/scams.yaml
iddexmarket.com
Fake Idex Market phishing for keys
https://urlscan.io/result/32dc9167-d27c-463b-8f22-f7d4b194b22c/
index-marker.com
Suspicious Idex Market domain
https://urlscan.io/result/2756c997-1ea4-4544-897f-ae2dd4f061bd/
index-markels.com
Suspicious Idex market domain
https://urlscan.io/result/fb0c0817-ec17-4342-a014-113125a86db8/
iddexmark.et.com
Suspicious Idex Market Domain
https://urlscan.io/result/a788e178-df3d-43fd-9f07-d588384d7793/
iddexma.rket.com
Suspicious Idex Market Domain
https://urlscan.io/result/9a4fbb8e-90de-41e0-bd63-2c7b49c1f687/
ideexmarket.com
Suspicious Idex Market Domain
https://urlscan.io/result/650e4fb7-6321-4166-9f57-f83e0dde8a28/
idexmarket.com
Suspicious Idex Market Domain
https://urlscan.io/result/40e4d5e3-4054-4ced-b6b6-643d2c565764/
=> iddexmarket.com + more

_data/scams.yaml
indexmarkett-corp.com
Suspicious Idex market site
https://urlscan.io/result/aec5f487-a91d-4dc7-b57a-3c4aeb7f4655/
giveth.ws
https://urlscan.io/result/92d763ea-49f0-4b03-9f03-208cea4cdfd1/
address: 0x89271335DB9d0024F725Ab23415678CdEA3EB368
giveeth.org
https://urlscan.io/result/eb736756-e0d7-494a-b30f-9f07703069a6/
address: 0xA6f2814C0020c38882e82D9bFde7B485a7297a1D
ethereum.org.give-eth.today
https://urlscan.io/result/103b8e43-cfec-467f-bdd6-c5f9ae974743/
address: 0xA213344262535D3EA5EFeAA7f7Cf74e792dA6258
give-eth.today
https://urlscan.io/result/f28cbe7d-fb2e-4162-961c-e04aa7f8a1cf/
address: 0xA213344262535D3EA5EFeAA7f7Cf74e792dA6258
collect-ethaway.com …
=> indexmarkett-corp.com + more

_data/scams.yaml
ethereum-prize.com
https://urlscan.io/result/5c6c1e2e-ea9c-46e0-8255-071b2605b300/
address: 0xc46E1430B1D4B7066B9B6655293492256BA216B9
sharekit.io
https://urlscan.io/result/b81e805c-bcf2-4d16-8b22-c8cdaf8a09a6/
address: 0x89271335DB9d0024F725Ab23415678CdEA3EB368
etherbonus.live
https://urlscan.io/result/eb174f8c-46c4-4184-bfb2-18a2410ca29d
address: 0x5188d13bdd9D7Ac30324a569E2cE42488374738e
fantom-foundation.tech
Fake Fantom crowdsale site
https://urlscan.io/result/21e94e99-d334-4e41-aea6-2dacd8deab4f
address: 0x567211d48BCFc706EDbAf5103196425cDf54289F
sparkster.site
Fake Sparkster crowdsale site
https://urlscan.io/result/9b6c3c08-d7d6-4061-a6d5-3d55b2ca0dbd/ …
=> ethereum-prize.com + more

_data/scams.yaml
myetherwallett.net
Fake MyEtherWallet Domain
https://urlscan.io/result/fa3e5c56-4ceb-4b4b-9572-03f03898c8c3/
magntech.tk
Hosting a fake MyEtherWallet (magntech.tk/01ef43c4b617f6/wallet/)
https://urlscan.io/result/aed35a9c-4e11-4a0d-855b-2c23984b0d1a/
coinzzz.pro
Hosting a fake Aragon giveaway (https://t.me/Aragonofficial & https://t.me/Aragonannoucement)
https://urlscan.io/result/c671b699-419f-49c1-babe-3ae336bc9ea4/
https://urlscan.io/result/e81cdbc9-812f-4937-88d3-7392b4a4cbb5/
today-ethereum.com
https://urlscan.io/result/0deae08e-688c-414a-97e6-e3fe675b5344/
address: 0x4dD0eF53784030fA675e2677F9CdC2a3e32E956B
ico.metronome.bz
Fake Metronome crowdsale site
https://urlscan.io/result/bc9e0689-3793-4d6c-8e77-8420781f5157/ …
=> myetherwallett.net + more

_data/scams.yaml
xn--myeterwallet-o0b.com
https://urlscan.io/result/c365522a-b8a8-418f-9396-856a82d083a8/
=> xn--myeterwallet-o0b.com

_data/scams.yaml
elon-shares.com
https://urlscan.io/result/0df96076-787b-4c6e-8057-ba50a91c249f/
https://urlscan.io/result/68c8544d-5214-44ef-8a20-2592fbef3558/
https://urlscan.io/result/c09c2d7c-01ca-408e-b996-85500f687386/
address: 0xa61a87497E6553e3b1CF66c8b02FA392A0eFF1E3
=> elon-shares.com

_data/twitter.json
+          "952631957057409031": "2nd_entropy",
+	  "958495164686917632": "justin_bons",
+	  "782281263986143234": "cybercapitalbv",
+	  "2229041119": "amadeobrands",
=> Update added whitelisted accounts twitter.json

_data/scams.yaml
get.perfecteth.com
https://urlscan.io/result/4aea6e9f-3c80-4230-8da9-2b6225a6351a/
address: 0x6997726E03707Bf08032B8b6Da935cae80524bCA
perfecteth.com
https://urlscan.io/result/a67d8d88-a5c1-4850-97f1-ccc58e0fd681/
address: 0x6997726E03707Bf08032B8b6Da935cae80524bCA
newsair.org
https://urlscan.io/result/db00b2f1-fc35-4da9-8ae3-407eed4964ac/
address: 0xF1a4b668D15F0E66543e9F1F795cC2B0f97E3ef2
top-ethereum.com
https://urlscan.io/result/dc12715e-257d-469f-9c4f-e68cb57a4e27/
address: 0x83D7Cb758C30d067e99E9f52F9e4f987101aB888
=> get.perfecteth.com + more

_data/scams.yaml
ethereum-claim.org
https://urlscan.io/result/72994984-e750-432f-916f-785e020e1039/
address: 0x2092B75719EC6f1dfE3f0d8C73239aD0297522BE
get.safesteth.com
https://urlscan.io/result/d4bdf505-2e40-4e97-8d48-22826ad999eb/
address: 0x37a8C55F6860e19f353686f5dd9c603ADB8448b6
safesteth.com
https://urlscan.io/result/8d0c3081-0e94-41c0-a7f6-708f8119467a/
address: 0x37a8C55F6860e19f353686f5dd9c603ADB8448b6
secure.ethscan.us
https://urlscan.io/result/02673a53-e59f-4113-acbc-aaec85e715d0/
address: 0x1A11585B374D5827F44e117e07941A8728a5f342
=> ethereum-claim.org + more

_data/scams.yaml
xn--coinbas-z8a.tk
Fake Coinbase - IDN homograph attack domain
https://urlscan.io/result/7e60dc3e-4e96-4583-a44e-e15b63609b32
=> xn--coinbas-z8a.tk

_data/twitter.json
=> Added @mises to twitter

_data/scams.yaml
waves-platform.net
https://urlscan.io/result/4d7ebcdc-7703-4b4b-a232-142a4839447d/
address: 0x074f95064A579de2287B21B6ed33033C18CB80ef
myefherwaliet.com
Fake MyEtherWallet - Suspected address: 0x766316F65C88486bcb59Fd57D5CE0087780c1424
https://urlscan.io/result/a7c2e50d-1a92-4255-88d7-fc3d284ba075/
ethsafe.net
https://urlscan.io/result/20448380-df07-4237-b804-12b9d4aa07c1/
https://urlscan.io/result/99a5d5f8-beed-43a4-84ec-1fd95b8712a1/
address: 0x64Ebd0467304E04F96520aB73C6E07D40aD25970
etherfree.tech
https://urlscan.io/result/f683c28e-f8ae-4d25-9fb0-019631c24933
address: 0x53DB08c95D0D6De34d8318970Bbcb063f82Fcc41
=> waves-platform.net + more

_data/scams.yaml
=> remove duplicate

_data/twitter.json
"22544877": "zquestz",
"390627208": "IvanOnTech",
=> Added Ivan and Zquestz to whitelist

_data/scams.yaml
c-kamowski.fr
Trust trading scam site. Bitcoin address: 19DBRq4M98XaeBjnjx2NuU9MMrTK3u259L
https://urlscan.io/result/373cc8e2-d04f-4a4d-bab5-d0f4d46f8f26
eosprivate.io
Fake KYC directing users to a Fake MyEtherWallet (myetherwallet.com.api.signmessage.me/signmsg.html) via bit.ly/2tj9f2U+
https://urlscan.io/result/1acbf584-c245-4106-9f34-87adf9d833ad/
https://urlscan.io/result/09a72fcb-180c-414a-88a9-aaa9dbe8fa05/
https://urlscan.io/result/b6563c24-0364-44cc-b1c1-e619e2f67f0f/
myetherwallet.com.api.signmessage.me
https://urlscan.io/result/be41ee23-b01a-41be-88f1-be81d6382a7e/
shapeshiftv.com
Suspicious ShapeShift domain
https://urlscan.io/result/194e79ab-0c52-4def-92f0-36b7383fc32e/
get-ether-now.com …
=> c-kamowski.fr + more

_data/scams.yaml
get.personaleth.com
https://urlscan.io/result/5c516db6-b791-45bf-83c0-46c90c9edfb9/
address: 0x9d03A3AD580cC2fb820349d3FF002Fb2FC7a6b19
personaleth.com
https://urlscan.io/result/efb5b67e-2e26-4b85-b065-507d2379b648/
address: 0x9d03A3AD580cC2fb820349d3FF002Fb2FC7a6b19
indexmarket-inc.com
Suspicious Idex Market domain
https://urlscan.io/result/9955cac9-cc6f-44a7-acdb-3af8d164d2f4/
mnyctervailliet.com
https://urlscan.io/result/ceac9e6e-3234-44e5-a112-037f19208329/
mnyidthewallot.com
https://urlscan.io/result/7947fc2a-73c3-47ba-aded-ec99f8cd1ced/
=> get.personaleth.com + more

_data/scams.yaml
idexmarketllc.com
Fake Idex Market phishing for keys
https://urlscan.io/result/da8918fb-bdbf-49ff-8843-339fa0001c9c/
idexwebaa.com
Fake Idex Market phishing for keys
https://urlscan.io/result/11279cd6-8a3f-4c8a-8095-254399b0013e/
ethfast.io
https://urlscan.io/result/efef9eb0-781d-4613-9f9f-342738a92d76/
address: 0x679A8cF6E181EbbcD9d14D0bd9595d8cFB79eCDf
givewaypromo.org
https://urlscan.io/result/0d9eeee9-50b0-41c3-9a49-acc57a732f41/
address: 0x83D7Cb758C30d067e99E9f52F9e4f987101aB888
ethereum-givaway.social
https://urlscan.io/result/a5586740-36ea-4ee5-b247-c65feebe7370/
address: 0x777c6aD16B303639489a38b369e423AA2c491884
=> idexmarketllc.com + more

_data/scams.yaml
ethaction.io
https://urlscan.io/result/4e026223-8976-4fa4-855a-0f0eebe1b92d/
address: 0x679A8cF6E181EbbcD9d14D0bd9595d8cFB79eCDf
24h.szakdoga.net
Trust trading scam site. Suspected address: 0x9f05a98487b64608ddE56A23cD1B031f4C567f3f
https://urlscan.io/result/d85b83d8-1698-4422-8501-e30de42fed64/
address: 0x77C89A9987017Fd0AF1c7d057FfB9e9fA254aa4b
luno-help-desk-update.weebly.com
Reported as a fake Luno login (it is now down)
https://urlscan.io/result/491fc368-0abd-43e7-ad31-7f615cea05c2/
airdropform900.typeform.com
Fake Airdrop directing users to a fake MyEtherWallet (https://myetherwallet.com.api.root.signmsg.me/signmsg.html) - https://bitly.com/2thn41W+. Suspected address: 0x8b9310e47cd2d4aad77735a3218d9420cb152709 …
=> ethaction.io + more

_data/scams.yaml
event-eth.org
https://urlscan.io/result/4db85e1c-5510-445e-9e81-16f945ab2ff1
address: 0x680f7bEa6EbA9AdcD0F47A0DE630CfA8F95Bf0ba
giveawaypromo.org
https://urlscan.io/result/5b862df2-d892-4487-a126-7f8bde13f88b
address: 0x224B9f4666472682f3e805f4dC1e0Fc39B7B96fB
aireth.today
https://urlscan.io/result/cea92a0e-3a97-4159-86dc-f7a41485d11f
https://urlscan.io/result/a529e2d1-6a40-40aa-9ea8-d88c5fc3bb78
address: 0x443F933362D9472ac8Fb9d1C4a8EaD512881630D
=> event-eth.org + giveawaypromo.org

_data/scams.yaml
eos-platform.net
Fake EOS web wallet - email verification from ddddssssmmmm.fvds.ru (188.120.227.79)
https://urlscan.io/result/62b9f333-28fc-4299-8ebc-ba5395d5d4b6/
address: 0x73BAF168D9f5FEe3D845f33b3567Fe916F730838
btcfast.io
Trust trading scam site. Bitcoin address: 33RRw7sdn6SQsNGPAb4fGUuAM9yHfL2ecH
https://urlscan.io/result/a7e2cf99-51cd-4dec-aadf-f9b2c85582e2/
idexxsoftload.com
Fake Idex Market domain phishing for keys
https://urlscan.io/result/a3c9a071-0ca0-4497-9216-c8029bdcbe74/
idexmarket-corps.com
Suspicious Idex Market domain
https://urlscan.io/result/3026568a-8393-4317-8e54-50486f9a3c0b/
=> eos-platform.net + more

_data/scams.yaml
indexmaker-network.com
Suspicious Idex Market domain
https://urlscan.io/result/72ddaed1-55da-47d7-9c24-94bb442936b9/
idexmarket-corp.com
Fake Idex Market phishing for keys
https://urlscan.io/result/d620482b-285a-4835-8e46-96359953ccc6/
idexontime.com
Fake Idex Market phishing for keys
https://urlscan.io/result/0ee144a3-d7f9-4eba-809c-18da00a7de0c/
idexmarketcorp.com
Fake Idex Market phishing for keys
https://urlscan.io/result/24a21740-1078-4f31-9196-0ff9404c0ef9/
idex-marketssite.com
Fake Idex Market phishing for keys
https://urlscan.io/result/e3815962-771d-4286-a3a6-bf8e00327fff/
idexmarket-llc.com
Fake Idex Market phishing for keys
https://urlscan.io/result/22ab3571-c4a2-4944-b6a2-75e97ce4f158/
eth-air-com.1gb.ru …
=> indexmaker-network.com + more

_data/scams.yaml
eosauthority.info
Fake EOS site phishing for private keys (POST store.php)
https://urlscan.io/result/9900e2ed-5aca-4eb8-878a-49c9c6e0efdb/
eosauthority.unstake.xyz
Fake EOS site phishing for private keys
https://urlscan.io/result/a1195d2f-2317-482a-a9b2-b8c6f8e4eda0/
xn--mythrwalet-c7a29cyq.com
https://urlscan.io/result/6d3ef995-0403-48ba-9976-74c49faa8e4a/
https://urlscan.io/result/b90a1212-973c-4fbb-8f22-ce98d3167820/
suretytoken.com
Fake airdrop (HTTrack signatures)
https://urlscan.io/result/1c3e7410-5ff8-4924-b31c-abb59cd31ca0/
https://urlscan.io/result/95307a76-c69a-4b50-b956-674b94286ff4/
getethers.org
https://urlscan.io/result/6c1f677f-6b11-42a0-8ab4-ede93737a86a/
address: …
=> eosauthority.info + more

_data/scams.yaml
e.airdropeos.com
Fake EOS Airdrop phishing for private keys
https://urlscan.io/result/d004a1c0-fa50-4c54-9159-d9ebaab5f024/
https://urlscan.io/result/8f9019f7-78ac-43eb-81d7-3ebfd76f6b50/
=> e.airdropeos.com

_data/scams.yaml
get.ethsupport.net
https://urlscan.io/result/0c7e0e14-420e-4537-aa68-0acbd782025d/
address: 0xC0095047d767857Bb40CC77EF54569d4124984C3
ethsupport.net
https://urlscan.io/result/0818f599-4ac3-44fb-83a7-2ac55c913224/
address: 0xC0095047d767857Bb40CC77EF54569d4124984C3
newsair.info
https://urlscan.io/result/23544306-fe1c-4f6e-8148-6d3fb2dcec82/
address: 0xF1a4b668D15F0E66543e9F1F795cC2B0f97E3ef2
officialgiveaway.org
https://urlscan.io/result/974ca124-e17b-4f55-adf3-d6cfe591e831/
address: 0x83D7Cb758C30d067e99E9f52F9e4f987101aB888
collectionseth.com
https://urlscan.io/result/98d4c6c1-2eff-45a1-8fb3-dce3fbde1c1d/
address: 0xfb997Ea4c102fAd4ec67f8bb069752030C0C0531
=> get.ethsupport.net + more

_data/scams.yaml
myeostrust.com
Fake EOS web wallet phishing for keys (POST /store.php)
https://urlscan.io/result/da324895-cf75-4897-82f4-b0550061c2bd
eosdrop.xn--mythrwallt-c7a86c5a.com
Fake EOS airdrop. Directing users to a fake MyEtherWallet xn--mythrwallt-c7a86c5a.com/signmsg.html via bit.ly/2Jlh9zL+
https://urlscan.io/result/9f701baf-90d3-4cea-83d2-7db93d04230d
https://urlscan.io/result/1e5fe28a-08c0-4093-ad41-68c1b7b16440
eth-claim.net
https://urlscan.io/result/73088752-e7cc-4e5d-a73e-5c4fb9ace29c/
address: 0x45C3eF2bc2719586Cd92766B3895868d3EE9Ef92
ethfreegift.org
https://urlscan.io/result/b69dd93f-4478-4420-845c-f8a2b6d3294c/
address: 0x46Cbc3c3710dC4a632842e155f18f30d4AB38aaC
myenterworlld.com
Fake LocalEtherWallet/MyEtherWallet …
=> myeostrust.com + more

_data/scams.yaml
xn--eosauthorty-wcb.com
Fake EOSAuthority phishing for keys (POST /store.php)
https://urlscan.io/result/b899a6d2-b8e6-4f78-8592-34fbad046aa8/
btc.etherfree.info
Trust trading scam site. Bitcoin address: 18b7PTLaa2TPtn5V5moBwSsWTEm6Ny2n8Y
https://urlscan.io/result/bf88caa6-d8a7-4f1e-aedd-9d92ed30d8a8/
etherfree.info
https://urlscan.io/result/e6dbae7f-adf7-4c65-8c3d-0f600edb6210/
address: 0xba8A5cF96D605B630025E3e2C8bd177391e32122
free-ethers.org
https://urlscan.io/result/332578a1-1a5c-45f3-b8b4-10154f79e383/
address: 0x4c6cdD82bF2B0627350bB660C2a18B2Db8880Ce1
=> xn--eosauthorty-wcb.com + more

_data/scams.yaml
ethereum.odyssey.center
https://urlscan.io/result/3658676c-7027-4976-a5f3-d3196a702eae
=> ethereum.odyssey.center

_data/scams.yaml
give-ethprize.com
https://urlscan.io/result/96353108-4f6c-48ff-9e84-df9d260e6f70
address: 0x257890939F7c0B758897F7Bd49A590B7190043e0
odyssey.center
https://urlscan.io/result/20382cc6-2d4a-4593-8535-72961957422c
https://urlscan.io/result/8e30cf3d-ac91-42d9-9bc2-5a88c91a73a9
world-market.online
https://urlscan.io/result/fd3faf2e-96fe-4fb7-8c6d-a82a2c770766
=> give-ethprize.com + more

_data/scams.yaml
myetherwalett.000webhostapp.com 
https://urlscan.io/result/0c72daf7-d773-4247-82a2-103d39395fdb/
myetherwallet.com.signmsg.icu
https://urlscan.io/result/c191911a-4490-4665-94ab-df5382adb803/
signmsg.icu
Hosting a fake MyEtherWallet (myetherwallet.com.signmsg.icu/signmsg.html)
https://urlscan.io/result/26916e84-67f9-435b-b91a-f30ea0a70d35/
ethofficialpage.us
https://urlscan.io/result/b5c1a5f3-04af-424e-b17e-9b9592825921
address: 0x6891f04E4EdA5Bb6c465132993BD6a5d4F1B0D0B
ethers-free.org
https://urlscan.io/result/e5e21248-2f83-49b8-878c-657ee8f5c163/
address: 0x11608c87d514d55e28eb94984bdbacd3fd38b182
claimethers.org
https://urlscan.io/result/96a6dfa8-6df2-40eb-9301-aef1be2d82d0/ …
=> myetherwalett.000webhostapp.com  + more

_data/scams.yaml
ethextra.net
https://urlscan.io/result/12556668-a423-4090-bf6b-6c04b02c7918/
address: 0xA1FF3Bc95D29C7DFCcD60C2226697b9C9aC0a16b
myetherplace.com
https://urlscan.io/result/41cd8482-cc41-4f7d-84f1-2c65ad469a45/dom/
address: 0x9d748d8f305b54127c57752716b48f23364ac3cd
=> ethextra.net

_data/scams.yaml
ethe.mediumblog.top
https://urlscan.io/result/0e6e0201-890e-4492-918f-f6bfdf7c0483
https://urlscan.io/result/d70def23-866b-41c5-bcea-91ee0a758194
address: 0x336a3f0c4d40b1e39cee72e2e59330daf484848c
=> ethe.mediumblog.top

_data/scams.yaml
ethereum-platform.org
https://urlscan.io/result/ddccc459-924f-44ad-8258-f8b6a6775b8b
address: 0x81C01024dEAaD32B015707F6f3AC948e88463204
bonus.eth-promo.org
https://urlscan.io/result/60888138-9361-4d98-a074-d2c1f3ae8c09
address: 0x2DF62e8d020984D77a5baAEC76aa3473Daf2d313
eth-promo.org
https://urlscan.io/result/f0dbd15f-7f76-4ee0-8e0b-8e2dc4e19687
address: 0x2DF62e8d020984D77a5baAEC76aa3473Daf2d313
binance-eth.github.io
https://urlscan.io/result/fe3761df-b670-4a6d-a074-d8ec810eddca
address: 0xFa9980A7240EA1BEB0B5ce58C0744fCD67f06104
5000eth.io
https://urlscan.io/result/30ec466a-c6de-42d1-9ac4-2b10722a8143
address: 0x679A8cF6E181EbbcD9d14D0bd9595d8cFB79eCDf …
=> ethereum-platform.org + more

_data/scams.yaml
freeethpromo.com
https://urlscan.io/result/6517e1ad-50a0-45f7-bab3-9281aaf79281/
address:  0xcf1d62627BAf1a84BeD11E30cf6CDae0f1B5C296
=> freeethpromo.com

_data/scams.yaml
eos-authority.com
Fake EOS form phishing for private keys
https://urlscan.io/result/c3a099c6-24e1-495b-9deb-36aa9c053cdb/
myethrawallet.com
Fake MyEtherWallet (redirected via https://bitly.com/2yI7J0c+)
https://urlscan.io/result/fe89292b-c7c3-4b27-925c-71b8a0935c80/
=> eos-authority.com + myethrawallet.com

_data/scams.yaml
musk-shares.com
https://urlscan.io/result/8967d058-73fa-45dc-b33f-f9915a8af626
address: 0xFb90119D9e1610dcbC5f3f2e7301aA62e9051916
elon-gift.com
https://urlscan.io/result/ae342491-5337-43ea-a892-6e3dca4fdb4c
address: 0x9c29046A4178d15aA7BE23e6b73Ef0f2E429A9a1
elon-gifts.com
https://urlscan.io/result/b5b2e9de-28c9-48db-9784-4055166a5cb9
address: 0x9c29046A4178d15aA7BE23e6b73Ef0f2E429A9a1
elon-giveaways.com
https://urlscan.io/result/b43e6c75-81a3-469d-93d3-fc184c6b66b1
address: 0x9c29046A4178d15aA7BE23e6b73Ef0f2E429A9a1
valideth.com
https://urlscan.io/result/3494cc40-dd97-4cf1-b01e-f1c55c154143
address: 0x4a36Ce6Ad774329A8e5AD7E6A51a7C3Bcf8cAE3B
musk-shares.com
Trust …
=> musk-shares.com + more

_data/scams.yaml
ethereumdrop.info
https://urlscan.io/result/2bb4f149-9123-4164-9ff3-48b60686e877/
address: 0x9386ff151225710C61747c7e314f317B6330453C
ethpays.info
https://urlscan.io/result/13292ff3-6786-4d3f-864b-391dc0b93727/
address: 0x47d6287a9fC4A1f69c0b20dCC29928Ebb44349c6
eth-give-away.com
https://urlscan.io/result/d2710824-a1ac-4867-af90-44bce2086348/
address: 0x8967f58f726bc35aA10223961fEEa6055a48Aae5
safe.ethpaynet.com
https://urlscan.io/result/1054c4e2-a03c-45cd-8df2-e29a53b619b4/
address: 0x4496370B4F0993152f761bd3b3d1Dd4e7B1b3139
ethpaynet.com
https://urlscan.io/result/8fa971b5-d8bb-44c2-aa8a-91295a5b07d7/
address: 0x4496370B4F0993152f761bd3b3d1Dd4e7B1b3139
getyoureths.com …
=> ethereumdrop.info + more

_data/scams.yaml
telegram.market
https://urlscan.io/result/c2e9b208-c394-4168-a467-8420600d4fbb/
https://urlscan.io/result/148c1e05-eacb-4c84-a0ce-9c32b27f236d/
address: 0xbf0A4A57D66eC0eB94dce2fd0A4aA57f8B0a2530
officialgiveaway.org
https://urlscan.io/result/ca5d7b4d-966d-429d-9eb5-e26343152ebb/
address: 0x224B9f4666472682f3e805f4dC1e0Fc39B7B96fB
=> telegram.market

_data/scams.yaml
Fake EOS web wallet
https://urlscan.io/result/9849f27a-ea51-4532-873a-b37d21ee0ed6/
=> wallet.eostoolkits.io

_data/scams.yaml
ethaway.com
Trust trading scam site (promoted via bit.ly/2Iw0Kae+)
https://urlscan.io/result/038a3df4-dfe1-4981-bf8e-887843c96b70
address: 0x1c40D1a1cAc7C586b9509C565296F91c8441aF9f
eth.tronbonus.network
https://urlscan.io/result/39c13514-f4ea-45a6-ae8d-0eda4284f89f/
address: 0x0f89B38968065A571eeaf34dD6BF2093fb55c20F
eth-gift.net
https://urlscan.io/result/7b85d749-3b52-4bc1-89a5-56d5fb567769/
address: 0x73c9B03B1DaDeA685f34b17DdAFBC11BD6327B6D
eosdark.com
Fake airdrop directing users to a fake MyEtherWallet xn--mytherwaet-y7a46ha.com
https://urlscan.io/result/31015722-adc4-4edb-aeaf-ec9a83f30b5a/
https://urlscan.io/result/f5bf5d08-cd14-43b2-8ac6-55e1d2da9d3b/
xn--mytherwaet-y7a46ha.com
Fake MyEtherWallet domain - IDN homograph attack domain …
=> ethaway.com + more

_data/scams.yaml
xn--eosauthorty-jzb.com
Fake EOS domain - IDN homograph attack domain - phishing for private keys
https://urlscan.io/result/ef5231fd-3992-4cfc-89b2-40f3779a2f38/
xn--eosuthority-m7a.com
Fake EOS domain - IDN homograph attack domain - phishing for private keys
https://urlscan.io/result/76f036bb-6425-4bd4-ae39-3ed83806a9bd/
xn--eosauthorty-kcb.com
Fake EOS domain - IDN homograph attack domain
https://urlscan.io/result/fe2a0744-20a7-486c-9e33-847ee5763660/
xn--eosauthorty-wcb.com
Fake EOS domain - IDN homograph attack domain - phishing for private keys
https://urlscan.io/result/d2f668a3-d806-4cd8-beb3-9edd0dc08aeb/
=> xn--eosauthorty-jzb.com + more

_data/scams.yaml
validbtc.com
https://urlscan.io/result/693d1d60-dff8-436f-acb5-5dcf46ea9502/
address: 0x973cC36EEF960389b1DdDCE82a9f0663Af61809B
ethcelebration.io
https://urlscan.io/result/7ae3bde5-2831-4feb-aa59-a2c4497e1b43/
address: 0x1F319dD5015b1068F102912F970D63B9947E4Cb0
crsafepay.com
https://urlscan.io/result/81fe7ce4-ca02-429f-bb6c-621121fe2037/
address: 0xa2280DdC79183A0dE9D3D90C63c0E7646874d9E0
verify.ethgoldmine.com
https://urlscan.io/result/425e38f8-dcf1-4a2a-8938-74a30eb02231/
address: 0x6C712Ae4986342773eDC37a9ff7fA90B1b52ca6e
ethgoldmine.com
https://urlscan.io/result/308f4d34-53b9-49fd-a313-8b3a2bc2e146/
address: 0x6C712Ae4986342773eDC37a9ff7fA90B1b52ca6e …
=> validbtc.com + more

_data/scams.yaml
myehferwallet.com
https://urlscan.io/result/a363a6b9-766f-4f00-85e5-25b2f7246670/
myetherwallet-signmgs.top
https://urlscan.io/result/da6cc64a-7fa6-434b-8c36-2c01c80c5a5e/
eosauthorithy.info
Fake EOS site phishing for keys with POST store.php
https://urlscan.io/result/44115236-4ad2-4aa0-8876-f81e43670ef0/
ankr-network.tech
Fake Ankr crowdsale site
https://urlscan.io/result/71cfa895-f615-4621-8fe5-16f68d42b16c/
address: 0xaAB92EAd3017703f7f9F3f7Ff71F623cd7a8D164
ankr-network.com.de
Fake Ankr crowdsale site
https://urlscan.io/result/cfa36c6f-fb9d-4e4f-ae06-2192bd9e1d18/
address: 0x3eD46342C7D8D29CA065E8EcA66BBf867A86E897
=> myehferwallet.com + more

_data/legit_urls.yaml
Name: Neodium Network
Website URL: https://neodium.network/
Token name / Ticker: Neodium Network / NN
Token Type: ERC20
About: The Neodium Network is a global decentralized patent ecosystem. Its technology simplifies the process of submitting patents and allows for the voice of the community to be heard through a consensus system. Patents will be stored on the blockchain, making them immutable and secure. Licensing patents will be done through smart contracts, ensuring that all parties meet the agreed upon terms.
Contract: https://etherscan.io/address/0xf03bfb08a807716e3340e175b98b388d2dc56de0
Total/Circulation Supply: 598,000,000 NN
Social media links:
https://twitter.com/NeodiumNetwork/ (over 10k followers )
https://medium.com/@neodiumnetwork/ (9.7k followers) …
=> Added "Neodium Network"

_data/scams.yaml
myethswallets.info
https://urlscan.io/result/69dfaad2-2c22-45bd-b459-c5ad7afe710a/
=> myethswallets.info

_data/scams.yaml
eossauthorithy.com
Fake EOS domain - phishing for private keys with POST /store.php
https://urlscan.io/result/aeba16af-9a74-4d4e-b1f5-bffd855ea479
=> eossauthorithy.com

_data/scams.yaml
eossauthorithy.com
Fake EOS domain - phishing for private keys with POST /store.php
https://urlscan.io/result/aeba16af-9a74-4d4e-b1f5-bffd855ea479
electrum.ink
Fake Electrum site
https://urlscan.io/result/5afe85ec-6c6b-4cb5-9013-00afd1f96f0c/
electrumwallet.ml
Fake Electrum site
https://urlscan.io/result/93e5ccea-db95-4fe4-86dc-5c3045b840fc/
=> eossauthorithy.com + more

_data/scams.yaml
teslaforfree.wordpress.com
https://urlscan.io/result/2dfd48ca-aa79-4cc4-be87-b9d328a56b29/
address: 0x58049616f5cd4b2ccd3654d7015d271a985ff2e7
go.ethtake.com
https://urlscan.io/result/a63ba14d-4205-4a53-b302-e778189336e5/
address: 0x1EFD1B1Ee8174B5421786EF0127EA45076307D8d
ethtake.com
https://urlscan.io/result/0c6d10c7-bbdf-4653-87dd-d565d481333c/
address: 0x1EFD1B1Ee8174B5421786EF0127EA45076307D8d
instagram.com/vitalik_buterin_official/
https://urlscan.io/result/94a7c949-a807-4b4a-9780-8f8a1eaba616/
address: 0x4D021FB560fdC49250A23E4006b584058667BaF7
=> teslaforfree.wordpress.com + more

_data/scams.yaml
idext.market
Fake Idex market. Suspected address: 0x31f530b58efa42dab4bd1789184b4cc6b884dea0
https://urlscan.io/result/c85717c0-7f56-4953-81e1-0bce969e9f9f/
etherdelta.com.ua
https://urlscan.io/result/b2ed10fc-b177-4729-8995-faefdc5fb9b9/
etzerdelta.com
https://urlscan.io/result/0084d818-c498-4af1-a8e7-d4e04755632d/
forkdelta.co
Fake ForkDelta
https://urlscan.io/result/cbef90cf-7a5b-406b-aae8-35e2769adf59/
myeftervvellet.com
https://urlscan.io/result/402b4def-fa9e-4af7-98e2-23f384230e48/
=> idext.market + more

_data/scams.yaml
ethereumstash.org
https://urlscan.io/result/b30b52db-37f8-4c45-b429-ce2921a42cc5
=> ethereumstash.org

_data/scams.yaml
ethtwitter.com
https://urlscan.io/result/92639729-118d-45a9-a421-49f2d75b96d5/
address: 0xa49d41A87F33C1A7B6368c171298266bB193a08f
ethereumstash.org
https://urlscan.io/result/b30b52db-37f8-4c45-b429-ce2921a42cc5
address: 0xAF5bDa8f8b954b03474305FD148c8361CaD4D2cD
eth2018.net
https://urlscan.io/result/06422066-a354-40ae-913c-73556083e491/
address: 0x4F3ca8C465170C0988295e22B5347eF8BB38F2B7
yobit.tilda.ws
Fake Yobit investment site
https://urlscan.io/result/0449b3dd-6f72-402c-9cfd-300772a52ff3/
address: 0x806466179736c54b62dc6e9f844f02b8d67a49e7
=> ethtwitter.com + more

_data/scams.yaml
dapp.doubledouble.io
Fake Ethereum doubler
https://urlscan.io/result/fb577daf-cbe4-49b5-8d79-14413f00b78a/
https://urlscan.io/result/c756b21e-3a88-456d-98c2-54565694eb30/
address: 0x0a4a2413d7c604647c7788fd3564b3c54fe06763 
bitcoinvest.cc
Ponzi scheme
https://urlscan.io/result/21b7aab8-e930-4f0a-9ca1-9a7c1f805489
https://urlscan.io/result/aa42dd7a-864d-4257-a3f0-04a878bb6390
address: 0xaedc8a3afc62a3deee4eb232bfdb28058bf554d8
celebration-eth.com
https://urlscan.io/result/69524210-262e-4b62-83f2-bdfac1eb9001
address: 0xB6eCd180F5CBB9167147394841D31f94EfF77DBf
=> dapp.doubledouble.io + more

_data/scams.yaml
event-eth.org
https://urlscan.io/result/81f1fa6e-7fc2-421d-96d1-802a8e5cb647/
address: 0x1b150B01Dd61d54847A1C538Ab9Fe6F1639CaCbc
=> event-eth.org + more

_data/scams.yaml
=> myethertrust.com address

_data/scams.yaml
pumphash.com
https://urlscan.io/result/7d85cea8-0667-4fdb-a5b3-69cc6b091cdb
address: 0xDd1f234967913C25f176bda85A9825BA880e447E
tronplay.network
Fake Tron airdrop directing users to a fake MyEtherWallet xn--mytherwalet-srb35c.com/signmsg.html via bitly.com/2K90ioo+
https://urlscan.io/result/8e826d40-2b07-43f3-ade4-f14faadd9746/
https://urlscan.io/result/08473218-370c-4d36-8233-8a6fdd4759b8/
xn--mytherwalet-srb35c.com
Fake MyEtherWallet phishing users keys
https://urlscan.io/result/9f6b9d9c-671e-4afd-9d52-aa5983fba80e/
eosauthority.bitballoon.com
Fake EOS site phishing for keys
https://urlscan.io/result/f4756abc-47b0-438e-8d2b-18d66b8c575b/
=> pumphash.com + more

_data/scams.yaml
hitbtc-login.com
Fake Hitbtc site phishing for logins
https://urlscan.io/result/556feb89-8283-43bb-a5d8-6ebedcb9d11d/
https://urlscan.io/result/6d905b16-a7f8-4db4-a897-3e3bd88ec88d/
promobinance.com
Fake Binance site phishing for logins
https://urlscan.io/result/16215007-665e-4295-b01b-158c27b69f28/
bittrex-ix.com
Fake Bittrex site phishing for logins
https://urlscan.io/result/e48cb58b-d1f9-43c0-b14c-fa783a4f3409/
bittrex-app.com
Fake Bittrex site phishing for logins
https://urlscan.io/result/a3ba0b9b-8d10-4f7f-a55a-aced69817420/
bittrecx.com
Fakr Bittrex site phishing for logins
https://urlscan.io/result/14f00645-e1c2-4a7b-b71b-cf892e96c17d/
https://urlscan.io/result/37f41dc5-b351-4256-b3e9-0890b8aadae3/
telegra.ph/Bittrex-giving-away-5000-Ethereum-ETH-03-26 …
=> hitbtc-login.com + more

_data/scams.yaml
xrp-address.org
Fake XRP web wallet
https://urlscan.io/result/73703ee7-63f0-44bd-9615-a6d69921ad24
=> xrp-address.org

_data/scams.yaml
eth-gift.club
https://urlscan.io/result/942929ab-a791-4afe-b65d-86c298f0c13a/
address: 0xce05a1bbff026ef875e94623753642806c0326d8
buterin-giveaway.org
https://urlscan.io/result/c55f494a-9514-4f83-8c32-ce2981a4bb2c/
address: 0xb8eD23977f745865aBBc645f09fc07f82cFde421
freegiveaway-eth.com
https://urlscan.io/result/9f57529c-1831-4b22-91ae-3180a90318fc/
address: 0xa5712afa19d70bb5dd57b91c43fffcaaf077dc3d
support.eth3rdyear.io
https://urlscan.io/result/edfb2648-fbf7-4d10-b3ef-71740100e9a9/
address: 0xE047FB1968B9143CE4284cA0fafC012B3Aa8568D
eth3rdyear.io
https://urlscan.io/result/421b6e1c-ad38-43a5-97de-b87a06a37108/
address: 0xE047FB1968B9143CE4284cA0fafC012B3Aa8568D …
=> eth-gift.club + more

_data/scams.yaml
see https://github.com/MrLuit/EtherScamDB/pull/1095
=> geocities.ws full path

_data/scams.yaml
eosauthority.com.globatalent.network
Fake EOS site phishing for keys with POST /store.php
https://urlscan.io/result/701a8b5d-b14f-4b1e-8157-c3c4b047233a/
https://urlscan.io/result/31efdb00-6ec1-4b1d-84dd-f47a1a391569/
=> eosauthority.com.globatalent.network

_data/scams.yaml
ethbig.net
Trust trading scam site. Being promoted by Twitter user 321652568
https://urlscan.io/result/64816934-168f-4e31-8245-48359ba33d2e
address: 0xA22270850FabDE01E1f5c5879ea65DD82890AF31
vechain-platform.org
Fake VeChain web wallet
https://urlscan.io/result/af61a7f8-45de-4d5e-9ab4-cf5c08900b80/
address: 0xEaAaF85E36267d4a44532E4df628254D6cE7f9cD
vechain-block.com
Fake VeChain web wallet
https://urlscan.io/result/64cc6bd1-65cf-4b4b-91bf-a7f2bbc113ae/
address: 0xaf48cfd4eee2b9f185fda12bf0cbbec5b90ed8c9
----
eth.blogmedium.top
https://urlscan.io/result/e585f1f3-72b4-46ac-8a4c-4d93b97d5edc/
address: 0xAeD20775C1d0D64796C9D023c8a7ac84557BA1Ad
celebration-eth.com
https://urlscan.io/result/29f0f450-ffe5-4e33-aa4a-47f55683f428/
address: …
=> ethbig.net + more

_data/scams.yaml
xn--ethrdelta-iib.com 
Fake EtherDelta - IDN homograph attack domain - stealing keys with POST /store.php
https://urlscan.io/result/d11dcf82-ca26-4962-a742-2097e4d9cd2e
ethergiveaway.site 
https://urlscan.io/result/3d1107af-104c-40b4-bac6-cccafabe213e
0xf3Bc09E9c493F7d446df129168894ff521175326
0x408FaC2d2d3D3AC4E356aA188119F5624FD8C9f6
eosclassic.network
Fake EOSClassic site harvesting user details
https://urlscan.io/result/818abc2c-80aa-45f9-9537-656e7c70aa24
https://urlscan.io/result/81f7d04a-f4b1-4c65-ab00-e1fe304dad39
https://urlscan.io/result/b6f5a2c1-d9e5-4ea1-83fa-66e0775f1a2b/
eosauthority-kyc.com 
Fake EOS site phishing for private keys with POST /store.php
https://urlscan.io/result/333c178c-9c32-4af9-bd59-fad4930b1649
eoscountdown.network
Fake EOS site …
=> xn--ethrdelta-iib.com  + more

_data/scams.yaml
trx.claims
https://urlscan.io/result/7a513cb3-3430-4514-abdb-4685f73630e9
address: 0xD8D0506ED425364EE126819E8b73Fc3160C39D49
coinscrypto.info
https://urlscan.io/result/dd392f10-8ae4-46ac-92cc-98e2ff53ad53
address: 0x8D6be44e86eDfFBe294071a886DdfB4147831BAa
giveaway.eth-safe.net
https://urlscan.io/result/1db6f994-06c8-41e5-9e99-130181d69f25
address: 0x407Ce703A92ACC44c40722dc2256E1D6388BcBf4
ethtransaction.xyz
https://urlscan.io/result/cf72c014-0384-4b2a-821a-6c4a7ab40499
address: 0x8a65C8565504a2BDe31F9c09125f5b9D53B2B07e
bonus-ethereum.com
https://urlscan.io/result/8e23bb70-56d3-4918-a47d-43d470285999
address: 0x4eFbb8a016B8D28d261FE31be1404cF12f4010a2
=> trx.claims + more

_data/scams.yaml
node82.btc-giveaway.info
Trust trading scam site. Bitcoin address: 17ntyMTNJpM6JDdS9M5G2eKgKELuGfzZkr
https://urlscan.io/result/4d027946-90dd-482d-969d-ee96d0692ff3/
https://urlscan.io/result/68b1d00d-2a10-4cac-8c0c-a0fb50d0e079/
texacon-verify-547fcd.bitballoon.com
Hosting a fake airdrop directing users to a fake MyEtherWallet xn--myethrwalt-f7a07c4r.com/signmsg.html via bitly.com/2KNuPHT+
https://urlscan.io/result/9e802a50-5530-4f04-91e1-846b86647879/
https://urlscan.io/result/591989b3-c4f1-476a-87dd-2998867182ad/
kinetictokenforms.typeform.com
Hosting a fake airdrop directing users to a fake MyEtherWallet xn--myethrwalt-f7a07c4r.com/signmsg.html via bitly.com/2KNuPHT+
https://urlscan.io/result/9e802a50-5530-4f04-91e1-846b86647879/ …
=> node82.btc-giveaway.info + more

_data/scams.yaml
myeleherwaret.com
https://urlscan.io/result/26f09d36-9849-4c35-94c3-c03cd951a5e5/
meytherwellat.com
https://urlscan.io/result/dd0e5a19-5a9c-49aa-9c47-7e8a5e70ae46/
=> myeleherwaret.com + meytherwellat.com

_data/scams.yaml
claim.ether33.online
https://urlscan.io/result/a721f09b-cf23-4e0a-9874-319cf6d52e92/
address: 0x336a3f0c4d40b1e39cee72e2e59330daf484848c
mediumblog.org
https://urlscan.io/result/3aafdf23-31eb-469f-8c95-ee5b8b046d79/
address: 0x5208d7f63A089906889A5A9CAed81E9C889E64F8
swswd.ether33.online
https://urlscan.io/result/b721f5ac-5ee1-4d4c-8cb2-7ba13f1562fd/
address: 0x336a3f0c4d40b1e39cee72e2e59330daf484848c
eth22.mediumblog.top
https://urlscan.io/result/bed4f1d8-3808-4d03-84fb-3cdb48eef875/
address: 0x336a3f0c4d40b1e39cee72e2e59330daf484848c
=> claim.ether33.online + more

_data/scams.yaml
bit-airdrop.com
https://urlscan.io/result/ba169205-f2dd-400f-b081-cf0fa7df3c08/
address: 0xD8D0506ED425364EE126819E8b73Fc3160C39D49
giveaway.claimeth.net
https://urlscan.io/result/4fa5dd9b-96dc-44c7-978a-8534dd4bd3c4/
address: 0xc1E6720F94a8D73e77A94d16Fb76f7dd6EdfF54C
encoreofficial.com
https://urlscan.io/result/dbeed85a-2c0a-4383-bdcd-6b63b5e02cab/
address: 0xFa9980A7240EA1BEB0B5ce58C0744fCD67f06104
ethcompetitionrules.cx
https://urlscan.io/result/8a209135-25bd-4655-9ce9-006c888a87d3/
address: 0x8e8f4161c9c3D2D8857230A048DF1Fc6F4326948
offer.supporteth.com
https://urlscan.io/result/2dbe5306-f295-43dc-9f83-2f095f44eac5/
address: …
=> bit-airdrop.com + more

_data/scams.yaml
ethereumfoundationgift.tumblr.com
Trust trading scam site linking to ethe.mediumblog.top/payment.php
https://urlscan.io/result/1e011872-7c62-460b-8266-a633ff065b7e/
address: 0x5208d7f63A089906889A5A9CAed81E9C889E64F8
btcpramengyve.com
Trust trading scam site. Bitcoin address: 34oxKKuq8g7W23gvDD6K3bpbTVCg1FLYGb
https://urlscan.io/result/14575086-86a1-4002-930b-84817f383e62/
claim-btc.org
Trust trading scam site. Bitcoin address: 1FVwwp98FBKJV8MzSFNN38afSHqiYrxXjs
https://urlscan.io/result/a4d0b7b8-53cc-4bba-ac8d-0cdc442ac4e4/
btcbig.org
Trust trading scam site. Bitcoin address: 15HM6dXaUvDdXri3rz44wKv13No57h4TN
https://urlscan.io/result/17b2ab1e-bffb-4728-a591-358459a23f9b/
btcbonus.win
Trust trading scam site. Bitcoin address: 1Co5gnEn1wBTyigfH9udnuUgha27pdETS9 …
=> ethereumfoundationgift.tumblr.com + more

_data/scams.yaml
etherdeltha.info
Suspicious EtherDelta domain
https://urlscan.io/result/3a5f8674-dbe4-4948-a826-f294f19bdecf
forcdelta.com
Fake ForkDelta stealing keys
https://urlscan.io/result/d5b7c135-fc49-4671-b333-5be19d944e64
=> etherdeltha.info + forcdelta.com

_data/scams.yaml
tokenaway.com
https://urlscan.io/result/0bb0a399-3e35-4c48-a2e2-5808f6efcc88/
https://urlscan.io/result/e6a83db6-c133-480c-954c-880ee2bc0049/
address: 0x5CC42d5A4eC44D3Df88F1bef5413F02900A500Af
myetherwallet-msgg.top
https://urlscan.io/result/bc7ef27f-93d7-46f4-a5da-4e769960c0cd/
myetherwailet.pw
Fake MyEtherWallet stealing keys with GET /a.php
https://urlscan.io/result/d3cb93bd-b372-44d4-acd4-b7564f871134/
https://urlscan.io/result/e0faadec-3f76-4b37-952b-7ca8d0e7b52e/
trontoken.tk
Fake TRON promotion redirecting users to myetherwailet.pw
https://urlscan.io/result/67ace301-2868-4e10-9ee7-f39d4171bb5c/
bitcryptonex.com
Fake Exchange. Reported to be associated with yoniex.com
https://urlscan.io/result/c186263e-2343-46c7-86a0-51512f19e426/
address: …
=> tokenaway.com + more

_data/scams.yaml
myertnerwalletr.com
https://urlscan.io/result/42a90c86-3e5b-43de-9623-86ad5a740753/
myetherweallett.com
https://urlscan.io/result/63912e25-5290-43b6-91ac-3fc49bd946d8/
idex.su
Fake Idex stealing keys with GET /store.php?mapza=private_key&action1=1
https://urlscan.io/result/0e31379b-0e73-4774-9b6e-6f71bc727775/
=> myertnerwalletr.com + more

_data/scams.yaml
ethmore.net
https://urlscan.io/result/987cb0d4-9fde-49e7-9f96-ae63832778be/
address: 0x0c2cB2d98F9f5ed558D9560D0E38E47187b2Bfe1
electrunn.org
Fake Electrum wallet download site
https://urlscan.io/result/212ae255-14a8-41ac-8274-f812bd898847/
myehterwallct.com
Fake MyEtherWallet. Stealing keys with GET ____key?key=%7B%22type%22%3A%22Buffer%22%2C%22data%22%3A%5B18%2C52%2C86%2C120%2C158%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C254%2C239%2C239%2C239%2C239%2C239%2C239%2C239%2C239%2C23
https://urlscan.io/result/1cc33869-41d9-4a9c-bbb0-ab0e6f0d99c5/
https://urlscan.io/result/77b85819-e064-43a3-b355-d4d8f85bb1c8/
mychterwallet.com
https://urlscan.io/result/1cc33869-41d9-4a9c-bbb0-ab0e6f0d99c5/
=> ethmore.net + more

_data/scams.yaml
mmyetlherwallett.com
https://urlscan.io/result/10c4f408-500b-4e0b-98cf-1580db64f239/
=> mmyetlherwallett.com

_data/scams.yaml
ethbonus.me
Reported as trust trading scam site. Reported addresss: 0xff8e6af02d41a576a0c82f7835535193e1a6bccc
https://urlscan.io/result/7ff4771e-73f6-4d35-bd35-0fa7b66eb669/
idex.ga
Fake Idex phishing for private keys with POST /data.php
https://urlscan.io/result/311ffd36-acab-478d-8348-11dea749ed55/
https://urlscan.io/result/e7f12c87-22ba-4e35-b4e7-8e7931334e7e/
binanyce.com
https://urlscan.io/result/321dce71-1e84-49f9-bc81-cddd6c473385/
https://urlscan.io/result/6e5669e9-cbc5-4242-8f01-b63a38c2b0bb/
login-binance.net
Fake Binance phishing for logins with POST /_loginSend.php
https://urlscan.io/result/bd02217a-c765-4d03-a949-6b679eada8d8/
https://urlscan.io/result/5be6cac5-a556-40ce-bcab-a9f6d296d75f/
myetherwallet.com.signmessage.icu …
=> ethbonus.me + more

_data/scams.yaml
ethcryptopromos.com
https://urlscan.io/result/fbab4c5f-e91b-4c57-981e-332b1110d8ae/
address: 0xAaaA3b6D0b72aDE31A99C933a8BF737a4E904527
ether-foundation.website
https://urlscan.io/result/cccf2ee9-9fa0-4fd7-a3d6-6f3ab9971686/
https://urlscan.io/result/47ae77f0-0ac7-4090-a878-50c7bc7871d4/
address: 0x52b949fb4678c20873135ce6b3727949432af1d7
ethofficial.net
https://urlscan.io/result/7dd89084-6d85-402d-a665-0ef73643ef5e/
address: 0x3bD330F121c493dB91e59d9125968D3Df090A66F
etherclaim.net
https://urlscan.io/result/8a158e81-7c0c-4e73-bd77-d0c5aa439cd9/
address: 0xab5fD091C56A9B801E945A902e986E894e4f407D
medium.ethereumfoundation.top
Trust trading scam site (also linking to ethe.mediumblog.top) …
=> ethcryptopromos.com + more

_data/scams.yaml
meyetherwealletr.com
https://urlscan.io/result/3dfecfd3-c920-4e14-a62c-54bcfb604034/
myerhterwallett.com
https://urlscan.io/result/2d5ad89b-8b03-449e-b45d-34a6f890599f/
=> meyetherwealletr.com + myerhterwallett.com

_data/scams.yaml
E.g twitter . com/TezosFoundatin/status/1016403603106328576
=> add ethsoffer.com - twitter spambot

_data/scams.yaml
safe.eth10000.org
https://urlscan.io/result/b200a55a-1c7e-49a5-871a-d892fa1cccca/
address: 0xF7d0FcD21D7bF83358656BaAEb3C8c1903Aa9614
eth10000.org
https://urlscan.io/result/b200a55a-1c7e-49a5-871a-d892fa1cccca/
https://urlscan.io/result/1b5a24ff-59fb-42b0-82af-5ade3b5f167a/
address: 0xF7d0FcD21D7bF83358656BaAEb3C8c1903Aa9614
gift-eth.org
https://urlscan.io/result/7430f1ef-d86f-4b53-a0be-93fbe5f4b9a7/
address: 0x8BcB21d162Af74718C583E249Ab112B9E6Ad5267
ethsoffer.com
https://urlscan.io/result/61197b05-f0c2-47a7-a2ef-43110289e8e5/
address: 0xF7fB243Ff0df4B35f5F7Fa5317c128f16E71cF9A
ethonline.io
Fake Ethereum web miner
https://urlscan.io/result/174dff20-67ce-48bc-a05d-dc31659a8e81/
address: …
=> safe.eth10000.org + more

_data/scams.yaml
ethereumpromote.wixsite.com
Trust trading scam site. Promoted by Twitter user id 1012075718405185538. Directed via bit.ly/2sK3rPO+
https://urlscan.io/result/86a81ee8-0925-447d-84e8-c4874a7dd680/
address: 0x159CCfFB293a06Aafaec1b254A00522A2bC40639
ethgive.club
Reported trust trading scam site. Reported address: 0x9E91ea0C442dd2B41CC7fE2d54fAEcd34f59C134
https://urlscan.io/result/50b4d5a1-460b-4eb2-82d8-519526fad919/
etherclaims22.top
https://urlscan.io/result/b17ef239-488e-49b9-b4ab-0c99dc7a7f54/
https://urlscan.io/result/6194fca7-577e-498c-833b-985b85c10de6/
https://urlscan.io/result/420d9009-48f4-4353-a88f-1ed76624b3da/
https://urlscan.io/result/065ebdf3-8118-4a69-8e7e-d4cb2528f8c3/
https://urlscan.io/result/11c055bf-75d6-40d3-a9c4-040c94a87104/
address: …
=> ethereumpromote.wixsite.com + more

_data/scams.yaml
myehtrerwallett.com
Fake MyEtherWallet (not resolved yet)
https://urlscan.io/result/bdab29ad-5dd7-438a-90b0-f0522d04f831/
myetherwallet.com.signmsgs.icu
https://urlscan.io/result/73d1bfe4-dd3d-4e7d-89ea-361bdde6163d/
https://urlscan.io/result/0e3a5706-eb4a-4480-8de1-41fe69480bf6/
miyetherwallet.com
Fake MyEtherWallet (not resolved yet)
https://urlscan.io/result/77c00eb1-02bd-4126-b1c9-70295f8028b1/
myethierwallet.com
https://urlscan.io/result/779dbc21-b2af-4e87-a509-9c83f50fef63/
xn--myetherwalet-yk6f.com
Fake MyEtherWallet - IDN homograph attack domain (not resolved yet)
https://urlscan.io/result/4d7fa24d-6d7f-4b65-b249-0557a319c57b/
omisegoclassic.com
Fake OmiseGo KYC form directing users to a fake MyEtherWallet …
=> myehtrerwallett.com + more

_data/scams.yaml
5000eth-giving.online
https://urlscan.io/result/8a7589ca-3796-4c7a-b617-daf1eca32b06/
address: 0x4FAe1eAb137DaF99E12B5AA7fE963f7EC3Dcd40E
=> 5000eth-giving.online

_data/scams.yaml
ethcontracts.org
https://urlscan.io/result/295a1dbb-886b-4b6c-bf42-b0015aa2917b/
address: 0x52C9DFD68c67aAFc9E3e615fB38824b17deF6432
ethdrop.co
https://urlscan.io/result/9adcc708-bd84-4548-b405-471082e9fe1c/
address: 0xB615a63688104F93E59c44C2E8f2eD9aC0401ee2
twittethpromo.cx
https://urlscan.io/result/fa3e628d-9216-46ee-bfcc-926ffe0e5083/
address: 0x059615eA15F7F0e2A276103127BBAce30223d294
ethaway-instant.com
https://urlscan.io/result/a579fcea-bff1-4c6f-b313-61763a75ed5b/
address: 0xAaaA3b6D0b72aDE31A99C933a8BF737a4E904527
trx.promo
https://urlscan.io/result/cf748b60-b39e-456c-9719-6b72dc7b7d5d/
address: 0xCe9e24Dffdb3DC08EFe33AD3DB858576C3f27D5d
ethcompet.cx
Trust …
=> ethcontracts.org + more

_data/scams.yaml
www.indexmarkket-site.com
Suspicious IDEX market domain
https://urlscan.io/result/118d3ff8-b9b3-4639-8244-5a7ef9153f49/
idexnetone.com
Fake Idex phishing for private keys
https://urlscan.io/result/e22d685d-89c0-4f10-85e6-df6a78bdc1b9/
=> indexmarkket-site.com + more

_data/scams.yaml
ethmore.live
Trust trading scam site. Promoted by twitter id 59058979
https://urlscan.io/result/f717080f-2d14-4332-b68d-981ab8978ddd/
address: 0x68E2EF6244Be67fE149C8309e1c5E978fa1a3Cab
myehtewallet.com
https://urlscan.io/result/f208e7fc-7508-4b6e-b53d-be20fd832b51/
meyehterwallet.com
https://urlscan.io/result/e45b56d3-3173-4b96-915b-be9eb6803bf5/
=> ethmore.live + more

_data/scams.yaml
ethpromotion.info
https://urlscan.io/result/a2d72540-c0cb-4d3e-9f11-c26d0f27a983/
address: 0xbde430F54A63016D8A5F31F243761653728086A2
secure.ethgiftnow.com
https://urlscan.io/result/85a13cd1-9411-4e5d-9319-2228d276884f/
address: 0x3d075995577c0C3c65a466Fee47FfB1bA6a41B02
btcpromotion.info
Trust trading scam site. Bitcoin address: 1FEt2GWxEidTKz1PkFuiccKTMD5AHkdRdq
https://urlscan.io/result/6e552901-cc4f-4267-b42b-358ab99e69f7/
betaclient-rzcoinwaps.cf
Fake Waves client phishing for seed words with POST /sendwaves.php
https://urlscan.io/result/63e559be-ffc3-4bde-8c61-fbad439cbeb1/
----
elon-gift.com
https://urlscan.io/result/a5630c07-f073-46ab-b340-a45a1266b625/
5000eth-giving.online …
=> ethpromotion.info + more

_data/scams.yaml
eosbounty.co
https://urlscan.io/result/c40d22eb-5470-4483-8f2e-c6c2934cb542
address: 0x4E360fAF9F228452aF65C9B7a89AE023363672b4
=> eosbounty.co

_data/scams.yaml
event-eth.com
https://urlscan.io/result/2d9568f7-d92a-4a7d-a29f-dc0867b85d18/
Trust-trading scam.
address: 0xe575D2262f516a392E018BD5Db9AFBC6ae656C92
musk-official-promo.com
https://urlscan.io/result/988138af-c15e-4987-963f-2cbf5a207d16/
Trust-trading scam.
address: 0x1D7BC400d3c6d9D37EC54D0e729cbaDD06dc0390
limited-promo.org
https://urlscan.io/result/56ab8515-1766-4a40-b14d-cf5ede38fdc1/
Trust-trading scam.
address: 0x11775A106157a283873A81E8Ec58394b8d568E06
ethpays99.top
https://urlscan.io/result/2c4e5fc0-9471-4621-8061-b3e355731b92/
Trust-trading scam.
address: 0x336a3f0c4d40b1e39cee72e2e59330daf484848c
0xAB7EC7596fc05BC55AFc07008cC06c1193eD6f9a
=> added new scams: event-eth.com

_data/scams.yaml
token-emrify.com
Fake MyEtherWallet stealing keys with POST demoj.php
https://urlscan.io/result/81532d4f-2451-4297-8418-8aaca3dddd3b/
https://urlscan.io/result/969ed47e-7703-45a7-b39b-5b670e1d978c/
myethwallofficiiall.com
https://urlscan.io/result/3ee4e618-9d17-4bff-88da-b449f203ff30/
myetherwallet-hydrogen.top
Fake MyEtherWallet. Reported address: 0x0591A42188996397FC7Cd6DB729045146c37696c
https://urlscan.io/result/453cc090-0916-4b9c-b13f-b02cc994b360/
myetherwallet.com.apisign.icu
https://urlscan.io/result/f3cf01c7-f857-4147-a031-2aa7cfadfdbe/
hydrogen-platform.com
Fake Hydrogen KYC form directing users to a fake MyEtherWallet myetherwallet.com.apisign.icu/signmsg.html via bit.ly/2zDHzfD+
https://urlscan.io/result/2e80ad5c-db74-473c-b697-36eb3d846cde …
=> token-emrify.com + more

_data/scams.yaml
myetherwallet.com.rootsign.icu
https://urlscan.io/result/0125fca4-e343-4c38-9961-d312a5bfc01b/
https://urlscan.io/result/f10e7a53-33d1-4721-ae16-c7cb9c59c5d1/
https://urlscan.io/result/ca8732f3-a521-4120-a24c-6e4eff8eaa6c/
ether4free.com
https://urlscan.io/result/9154f077-1311-44cc-9cd9-9170e2c3c0e0/
address: 0x8E3f2d9bbd1759e13eBd96d95cEf2fE468009E6c
givefreecoin.com
https://urlscan.io/result/23151134-be23-4bcf-9703-56a8f080a6be/
address: 0x80e02aE8c5d5e482558CaF32004e7d6281445f28
giveusether.com
https://urlscan.io/result/059874c2-a4f6-44d0-a93b-ffca22066bc7/
address: 0x77849c0B55E6b65336C913b850fD5d92B42F68CE
giveusethereum.com …
=> myetherwallet.com.rootsign.icu + more

_data/scams.yaml
cashaaprivate.com/airdrop/
Fake airdrop form directing users to a fake MyEtherWallet
https://urlscan.io/result/62c1eb23-1a08-460d-8484-fdd52c469dda
=> cashaaprivate.com/airdrop/

_data/scams.yaml
neotracler.co
Fake Neotracker phishing for secrets
https://urlscan.io/result/422112c9-1a11-44b2-827f-2d01da212aad/
brimance.com
https://urlscan.io/result/1847fc7b-0492-476e-9214-a4495b3b0126/
https://urlscan.io/result/2f002043-d9b1-4f3e-9865-cc263700812e/
brilmance.com
https://urlscan.io/result/d185b549-63e2-4a9d-8cc7-9a99ac276306/
https://urlscan.io/result/8f88abd2-2dce-4021-b9f3-2e6bd4512af1/
blirmance.com
https://urlscan.io/result/0e28431c-30c6-41b2-9a83-68aaa7ef072e/
https://urlscan.io/result/8eb166ea-05b9-4dfc-a83b-08c9d4a55940/
brinonce.com
https://urlscan.io/result/42e2eaa8-8582-41dc-881f-d559f821115f/ …
=> neotracler.co + more

_data/scams.yaml
idixmarket.info
Fake Idex market phishing for private keys
https://urlscan.io/result/dc70e3c0-69c7-4f93-b61c-bf6a0846a3eb/
coinbaise.com
Fake Coinbase phishing for logins
https://urlscan.io/result/8ddefe71-b3f6-457c-a099-4ddfe0edd22b/
=> idixmarket.info + coinbaise.com

_data/scams.yaml
walletico.com
Fake Idex site phishing for keys
https://urlscan.io/result/d914dec6-68ed-4eb7-a04a-42e5b5e8ae52
=> walletico.com

_layouts/scamdomain.html, _static/css/scam.css, run.js
Added security tips for some domains. Phishing - MyCrypto/MyEtherWallet, Scamming - Trust-Trading, and Fake ICOs. 
Example:
Closes #1127
=> Added some security tips

_static/js/search.js
=> Fixed search for neutral eth addresses

_data/scams.yaml
index-markett-network.com
Fake Idex market redirecting to idexmarkketslogin.com
https://urlscan.io/result/00b77930-ebd4-4685-924a-69372d0624bc
idexmarkketslogin.com
Fake Idex market phishing for private keys (iframing ideeweb1.com)
https://urlscan.io/result/064098d1-05c2-40b1-96f1-d2312fa5edba/
ideeweb1.com
Fake Idex market phishing for private keys
https://urlscan.io/result/d1876449-32c8-49a5-92bb-e8969f31fac6/
https://urlscan.io/result/35ce3c7e-04f5-4cd5-ba36-7eabd96c01e5/
=> index-markett-network.com + more

_data/scams.yaml
idexmarket.me
Suspicious IDEX domain - kit not deployed yet
https://urlscan.io/result/3c43b379-a307-453a-b6ae-d9ab0d08380e/
johnmcafee.ethgivings.net
Trust trading scam site directing to secure.ethgivings.net/payment.php
https://urlscan.io/result/38a4a051-611b-40d9-94e9-44952649a6e8/
address: 0x2B164ae662a0AB1832C87cb4A226EFEC56219FB6
ethpays99.top
https://urlscan.io/result/f3b04e8e-19a6-458f-8bf3-8db3c39c4a5d/
address: 0x5cf03f522dcbe4efeed2462759da179b50230969
idex.press
https://urlscan.io/result/30996fb5-d9e3-4eb8-843b-452710cfc82d/
https://urlscan.io/result/1b12f777-521e-470a-9553-9abdfecd745c/
tronics.promo
https://urlscan.io/result/9859fa20-f4b0-40e4-a027-d800b35567e6/
address: …
=> idexmarket.me + more

_data/scams.yaml
ether-event.com
https://urlscan.io/result/49acbd6f-d2fe-4dc2-bab6-1c7d07440aa7/
address: 0x8729Abb00a517bBA3d615ed13E7C9C55aB311D41
w-eos.com
Fake EOS web wallet
https://urlscan.io/result/925c99e3-2f68-4926-b28f-bb90f2267934
address: 0x5Ef4EC670246Af663F64aFf354a30Ca54B43DAFD
----
top-ethereum.com
https://urlscan.io/result/d79c68ea-90fa-41d7-b33d-97bd9df45d0d/
address: 0x9844F5C5F9aA7146a74ffC7b9227742acFA71dEa
=> ether-event.com + more

_data/scams.yaml
idexchange.pro
Fake Idex market phishing for keys with POST /save.php
https://urlscan.io/result/a9d53a62-db97-4d65-9b61-7d8b5f48d0a5/
etherdelta.com.ua
Fake EtherDelta phishing for keys with POST /admm/rdy.php
https://urlscan.io/result/eb4a17af-d881-4954-908a-55a027214585/
https://urlscan.io/result/9ba56114-afe2-4927-9858-155fc78f50a3/
=> idexchange.pro

_data/scams.yaml
blvonance.com
Reported as a fake Binance phishing for logins
https://urlscan.io/result/f375909a-da1b-4a76-8629-2d0f86b4b63a/
airdrop-event.info
https://urlscan.io/result/e02449e4-1459-4290-96df-0af1f6cfc70c/
address: 0xb0d46Eb7e6Aac501BcCE47F05aCe37527B8B329a
currency.promo
https://urlscan.io/result/1e64b341-7609-46fd-9d3e-cd5d6370c9b0/
address: 0xD8D0506ED425364EE126819E8b73Fc3160C39D49
czgive.site
https://urlscan.io/result/79ab4bcf-c270-4453-b1e3-911c0b35cb77/
address: 0x44610ceE8C56D34e80468243065e3a319250e32a
verify.bonuseth.info
https://urlscan.io/result/23a94987-48a7-4972-a225-7aee40cf8413/
address: 0x429D386Adc915adE21593609B1b89b976B2F2af4
get.bigethgift.com …
=> blvonance.com + more

_data/scams.yaml
www-bitfinex.com
Fake Bitfinex phishing for private keys
https://urlscan.io/result/8ac56fd4-b00c-4369-8d0e-61627e1c06f2/
https://twitter.com/sniko_/status/1020078544922214400
=> www-bitfinex.com

_data/scams.yaml
ethzerdelta.com
https://urlscan.io/result/06c8bdf0-48f3-4fa2-a903-9f0b7f90e9cd/
forkdelta.su
Fake ForkDelta
https://urlscan.io/result/34423533-15a7-4e8c-bd97-6a96eddc3977/
forkdeltagithub.info
Fake ForkDelta 
https://urlscan.io/result/40ea39a4-6fd7-4813-ace3-66aad41ccc0a/
myethrewallett.com
https://urlscan.io/result/5171b40f-b679-4035-ab8e-001f5bc80bc9/
=> ethzerdelta.com + more

_data/scams.yaml
myetherwalletmessage.signauth.icu/signmsg.html
Fake MyEtherWallet phishing for keys with POST /log.php
https://urlscan.io/result/56538d37-bb02-4e88-9e4d-a4f49116325e
=> myetherwalletmessage.signauth.icu/signmsg.html

_data/scams.yaml
login.blockchaim.co
https://urlscan.io/result/66142f8a-f22b-41af-8f20-8e14add2287e/
https://urlscan.io/result/237b03d0-003b-429b-a403-28732740bca9/
transactionlist.info
Hosting subdomains for phishing NEO and MEW users
=> login.blockchaim.co

_data/scams.yaml
mcafee.promo
https://urlscan.io/result/53a9bb6f-cc47-44d6-b5ae-a473ec5bc93b/
address: 0xD8D0506ED425364EE126819E8b73Fc3160C39D49
eth60.top
https://urlscan.io/result/cf408e48-82d3-4bc8-a77c-b6aaade8d155
address: 0xab7ec7596fc05bc55afc07008cc06c1193ed6f9a
getfree-eth.org
https://urlscan.io/result/7b0125bd-957d-4eb5-a0f9-f7860340e575/
address: 0x2B1C266E2a39a7a30aED472Fad47d6b6AB953F7e
vaxx.co
https://urlscan.io/result/a62acc3a-d00f-47ed-8915-697e8804c243/
address: 0xD8D0506ED425364EE126819E8b73Fc3160C39D49
cryptoether.info
https://urlscan.io/result/005d3c60-0798-428d-92b1-0225f4c271c3/
address: 0xA4F06F1afB7B8589D1F4609257e5010C30eD3D2b
coincapitals.org …
=> mcafee.promo + more

_data/scams.yaml
getethernow.org
https://urlscan.io/result/eec0ccd1-115e-4da6-b008-3ba28a0c789a/
address: 0x7aA266963882F13eB0Ab5920E16aFeF2F26cDa8f
officialairdrop.com
https://urlscan.io/result/b3b488c7-01e2-4dde-abf6-5d3e2dcf09dd/
https://urlscan.io/result/ef945c75-0598-48e5-8fd9-3b974ef0643f/
address: 0x451ba6133b64829398fe074ae649a7998acb16f3
eth-event.com
https://urlscan.io/result/22bab091-fa4d-4ee0-be17-e2fa83240360/
address: 0x8729Abb00a517bBA3d615ed13E7C9C55aB311D41
ethclose.info
https://urlscan.io/result/32ed5540-a90b-430f-8ec0-bad957bfb940/
address: 0x74a01390635D8D4016827fA3AfB1A0f6c33eD8d8
freecoindrop.com
https://urlscan.io/result/09fecd3b-2b74-4399-9993-c112e66a585f …
=> getethernow.org + more

_data/scams.yaml
sociall.ooo
Fake Social.io crowdsale site - t.me/sociallairdropbot
https://urlscan.io/result/43e37009-9e35-4d36-b89b-5ac33b3b1453/
ether-gift.website
https://urlscan.io/result/8016c7ef-cc4f-4414-88b6-d155a2dfea1d/
address: 0x52b949fb4678c20873135ce6b3727949432af1d7
authorize-transfer.droppages.com
Trust trading scam site via bit.ly/2ELCNLl+
https://urlscan.io/result/79306081-e1d0-44ff-ae3f-ae1045c31749/
address: 0x5e3eC117baf30044A1b08267208a130E7D69704E
login-binance.com
Suspicious binance domain targetting login
https://urlscan.io/result/81b53d27-384f-406f-90e1-fa8512d8e205/
authhitbtc.com
Suspcious hitbtc domain targetting login
https://urlscan.io/result/1263ba89-6297-446c-8ddf-a0274cb8ef76/
hltbtc.cam
Fake Hitbtc phishing for logins …
=> sociall.ooo + more

_data/scams.yaml
idex-markt-roosen-gmbh.com
Suspicious domain targetting idex users (being iframed on idex-market.me)
https://urlscan.io/result/037c8054-f7cb-4881-9b3f-f5903348460a/
idex-market.me
Suspicious domain targetting idex users (iframing idex-markt-roosen-gmbh.com)
https://urlscan.io/result/c2361e20-385f-403a-a0d7-40f9f3188397/
iclex-market.com
Suspicious domain targetting idex users
https://urlscan.io/result/3f5eb5f9-3934-4640-b0f4-02483558f071/
xn--dex-market-58a.com
Suspicious domain targetting idex users
https://urlscan.io/result/612a4b4f-dcb1-4d46-8d63-036e627e8957/
idex-markett.com
Suspicious domain targetting idex users
https://urlscan.io/result/12e97d2e-67c2-428d-b6d4-c9cc0730dde0/
medium.getethernow.top
Trust trading scam site - directing to verify.ethereumnow.top/payment.php …
=> idex-markt-roosen-gmbh.com + more

_data/scams.yaml
stellar-w.com
Fake Stellar Web Wallet
https://urlscan.io/result/72c75eaf-6f1c-4979-b2eb-21fdf8ca7c52/
bitfinex.im
Fake Bitfinex phishing for logins
https://urlscan.io/result/8b8efb76-488d-413e-a4f0-a58980a6a819/
https://urlscan.io/result/a8c107ca-75dd-438e-9e41-491d10e83d18/
https://urlscan.io/result/0b1e4fdf-371d-4ba5-a3f4-85e1383fff4a/
https://urlscan.io/result/8353c837-48b1-4183-a241-29c27007026f/
=> stellar-w.com + bitfinex.im

_data/scams.yaml
dailycurrency.ml
https://urlscan.io/result/7f1521ae-b823-457b-9dc9-7e736028cab5/
https://urlscan.io/result/7f1521ae-b823-457b-9dc9-7e736028cab5/
https://urlscan.io/result/3dc9e2ff-75a5-4cb7-bf19-a0b9a20947e7/
address: 0xFc6BB078EC56C85E8f7adDFed0F2dE6CB86ee3c3
ethgivewaypromo.info
https://urlscan.io/result/7dc550d7-6553-4ed1-8b6f-885057d1b84a/
address: 0xC597498f0d102036ff7bf9fDa401F3174d2E9D96
xn--etherem-y24c.com
Fake Ethereum site - IDN homograph attack domain - directing users to xn--mythrwallt-yq3ecf.com/#eth-staking - email sent from info@mail5-ethereum.com
https://urlscan.io/result/097223bf-c71b-4f9a-8ac6-ca406b5c5a08/
https://urlscan.io/result/e6317331-faa5-48b0-bd58-02b9f526eb13/
=> dailycurrency.ml + more

_data/scams.yaml
giveaway-binance.com
https://urlscan.io/result/7094b937-c77d-41f6-b076-028c1c5c290f/
https://urlscan.io/result/46d0c737-a73f-4560-a5df-f6dbdb957355/
address: 0x6B0A6C142905ce6c1db7276d8878a3e7846675d9
ethereumclaim.net
https://urlscan.io/result/e7326ff1-71b2-47e0-a003-cef4eecf3a57/
address: 0xf19c11540E012227466a59cadE5F7fCf8dC1d1D1
ethescan.info
https://urlscan.io/result/2444b8be-2094-44e1-ab25-82db15495e65/
address: 0x68e45B998240d77FbE30BE84bd8397a51F0EF962
verify.getbigeth.com
Trust trading scam site - directed via bitly.com/2mFoh0d+
https://urlscan.io/result/2a5fe3a3-eb98-4d96-a29b-981d708f5076/
address: 0x215e7E7eDEfdA37EB39df17B8b91DA9a60d85530
getbigeth.com …
=> giveaway-binance.com + more

_data/scams.yaml
bitfanex.com
Fake Bitfinex phishing for logins with an admin panel /admm/
https://urlscan.io/result/23c59cf2-a14e-4cd2-9f59-0b8cf05f9666/
https://urlscan.io/result/389537a8-c4ef-4dbe-b646-322ee2f4bc35/
idex-market.ph
Suspicious Idex market domain
https://urlscan.io/result/9e68cea7-ea72-40d7-be55-89f147e9e36e/
idex-market.com.ru
Suspicious Idex market domain
https://urlscan.io/result/afeb40ca-a4ff-4d07-89b9-ab5cd14d28cd/
idex.com.ua
Suspicious Idex market domain
https://urlscan.io/result/e1b9a0e9-c8da-4478-bace-b26dd54d4713/
idex-markef.org
Suspicious Idex market domain
https://urlscan.io/result/749cb1bb-a303-48b4-a922-f625ba9748c5/
idexx-corpcom.com.ph
Suspicious Idex market domain
https://urlscan.io/result/9b5805b9-52a8-4811-a518-0d3d4b49952b/
idex-markef.io
Suspicious Idex market domain …
=> bitfanex.com + more

_data/scams.yaml
promo.etherpay.site
https://urlscan.io/result/c25398ce-5917-4712-9d72-02f2fefdb842/
address: 0x562109A47a469CA0c385d654Bb0AF14c98cf6E12
bnb-token.org
Fake Binance token sale site
https://urlscan.io/result/c3760aac-bd21-4eed-b206-b5932871c687
address: 0xBC025972d6DCEbE52793A2B19dE53CF621Cf1EDc
blog.mediumpromo.top
https://urlscan.io/result/94993f3b-9727-4f82-a6ec-d86c8e23415e/
address: 0x5cf03f522dcbe4efeed2462759da179b50230969
medium-promotion.com
Trust trading scam site - directing users to celebration-eth.com
https://urlscan.io/result/4f3da146-09a1-4cdb-8fe4-cb636f0de6cf/
address: 0xed6B90c028310122AF361ce84a4604afBED40910
celebration-eth.com
https://urlscan.io/result/5e6198ca-0c56-4d8b-a68d-5d2744c5ae98/ …
=> promo.etherpay.site + more

_data/scams.yaml
eosgas.co
Fake EOS airdrop KYC form directing users to a fake MyEtherWallet myetherwallet.com.api4.icu/signmsg.html via bit.ly/2JVvRwS+
https://urlscan.io/result/3ad275df-322e-45ca-beec-ccc89711dba2/
https://urlscan.io/result/45e65da1-1ed0-4de8-9666-75b2e1d4a8d9/
myetherwallet.com.api4.icu
Fake MyEtherWallet. Reported address: 0xBCA08E0DB1634B272E42630e2f1E7C4b92148B8d
https://urlscan.io/result/d157d105-ea96-4273-a019-93ebd9fbe36a/
get-ethereum.net
https://urlscan.io/result/d7edb34c-4ac7-48cf-a2ab-717f65f360c8
address: 0x30faC621bD26F6828551a79807ed3c2a70b1b082
airdrops.promo
https://urlscan.io/result/d65a5990-456e-4141-8dd0-6253d8e51fa8/
address: 0x76bb5b6177096b337c79F2f948Aa08b0db5f5211
binance.claims
Trust trading scam site. Bitcoin …
=> eosgas.co + more

_data/scams.yaml
myetherwallet.com.api5.icu
https://urlscan.io/result/e423c6cb-d724-46bd-a0e3-2ace67036892/
nuetheriumllet.com
https://urlscan.io/result/820b403b-9721-4f97-9b76-0cc698185673/
myelhervvalet.com
https://urlscan.io/result/18939730-4948-4058-8b84-378b2bb170c9/
seositesworld.online
https://urlscan.io/result/7bf86e59-f033-4661-8af1-2d5ceca60d5d/
https://urlscan.io/result/049e0863-26db-4154-8449-eab144fa19d5/
=> myetherwallet.com.api5.icu + more

_data/scams.yaml
claimprize.org
https://urlscan.io/result/5e4f3c33-1ca8-450b-bc00-76ac1909bfd9/
address: 0xaE34b154ADA796cFEbE8a60D265d266eF809Fb05
eosgas.net
Fake EOS KYC form directing users to a fake MyEtherWallet myetherwallet.com.api6.icu/signmsg.html via bit.ly/2LrOL4a+
https://urlscan.io/result/4cf40f3b-6ce0-4180-8b57-59d7708138cf/
https://urlscan.io/result/fdc2c7c0-6e1f-4531-bd33-d63381338239/
myetherwallet.com.api6.icu
https://urlscan.io/result/0b1ddd32-0b26-4a64-884f-93c218885caf/
=> claimprize.org + more

_data/scams.yaml
myetherwallet-hydrosign.space
https://urlscan.io/result/f50443b9-c7de-4165-96a2-5619aeb82b73/
dailycurrency.promo
https://urlscan.io/result/0195f8c0-0d74-42f7-bc09-e7e7b5a13c01/
address: 0xA51960dF18ca816B738A401AC310656fBA0d52EF
claimsafe.org
Trust trading scam site directing to giveawaypromo.byethost14.com
https://urlscan.io/result/b8d77f21-c046-4dae-845f-7605ae5e888e/
address: 0xE5E71b33c6a05910A5bDb05b9fC4c826711de336
musk-present.blogspot.com
Trust trading scam site directing users to musk-official-promo.com/e/
https://urlscan.io/result/e59e57ae-3c83-4d48-8f27-0f5268a26550
address: 0xbC55B0f2DbAF492FC8adf35c0f9939eb5Fe92131
binance-get.claims
https://urlscan.io/result/3f6961d3-61f8-4c5d-804f-0f2f08efd33e/
address: …
=> myetherwallet-hydrosign.space + more

_data/scams.yaml
descentx.com
Fake web wallet stealing keys with POST cryptocurrency-prediction.com/unu.php
https://urlscan.io/result/e5b80829-3370-453f-9d9d-a010e797da72/
https://urlscan.io/result/83388558-8f1e-4896-9752-0a01953ae20e/
myetherwalletv.org
https://urlscan.io/result/18d62a43-6f14-436a-b798-9592295402bb/
idex-market.trade
Fake Idex phishing for keys
https://urlscan.io/result/43a572e4-818c-4dbd-87ea-4659253b3d3d/
btc-binance.com
Trust trading scam site. Bitcoin address: 12z4fAETZTXehv8Y2v3GcD7jjdgG38Ppor
https://urlscan.io/result/01c34a43-279d-414f-8273-25838c15e77f/
eth-away.com
https://urlscan.io/result/600887b2-66ef-4fa1-9458-ee7517a0a84b/
address: 0x0A0bA956038d4a66002D612648332B9c4ab7646C
theethpromogive.net …
=> descentx.com + more

_data/scams.yaml
ethcryptocomp.cx
https://urlscan.io/result/511ccdbb-7838-4b78-9ab8-ee5d87d4b97d/
address: 0xBe3E5cBa8cb230678a7bF5ECdaE37783C8dF89bd
ethpromoui.com
https://urlscan.io/result/a40eeb63-d9c9-4a56-9681-70e09a2fc4cb/
address: 0xBe3E5cBa8cb230678a7bF5ECdaE37783C8dF89bd
ethpromonow.com
https://urlscan.io/result/88c0d14b-6c6c-43c1-a00c-45d4860e273b/
address: 0x8e8f4161c9c3D2D8857230A048DF1Fc6F4326948
eth-give-away-promo.com
https://urlscan.io/result/eb7cd6a8-9530-46e7-a58d-85246f0d0352/
address: 0x14B7716c688875Bcf54D5Ff47cAd4FcA6B3834fA
eth-promo-give-away.com
https://urlscan.io/result/5a1d2736-2b46-4465-9ed1-5aef0d3a3938/
address: 0x14B7716c688875Bcf54D5Ff47cAd4FcA6B3834fA …
=> ethcryptocomp.cx + more

_data/scams.yaml
bitfilinex.com
Fake Bitfinex
https://urlscan.io/result/6b849bd4-4b57-4952-802e-1cf1de8c6109/
=> bitfilinex.com

_data/scams.yaml
blgem.blogspot.com
https://urlscan.io/result/8ab4a318-b7c3-4632-a546-9b3d6db3cd96
address: 0xBDd6c2d0a22B1aFA22Fc0F5381EB08621DB5929b
airdrop.delivery
https://urlscan.io/result/74f75358-060f-45ac-b992-9969b5fceb22
address: 0x76bb5b6177096b337c79F2f948Aa08b0db5f5211
giveawayofficial.info
https://urlscan.io/result/f20c7bb7-9791-48f2-8a1e-7994873c18d8/
address: 0xC597498f0d102036ff7bf9fDa401F3174d2E9D96
binance.delivery
https://urlscan.io/result/10781994-7815-4117-bad1-7a907f361960/
address: 0x76bb5b6177096b337c79F2f948Aa08b0db5f5211
eth-binance.com
https://urlscan.io/result/f4481f49-7caa-4661-8b49-d8380782b0ee/
address: 0x27Ec5a27E521364699b870e5D8B5245D97CD0031 …
=> blgem.blogspot.com + more

_data/scams.yaml
kuciorn.hosstinger.info
Fake Kucoin phishing for logins
https://urlscan.io/result/7f0b36d3-ae3b-4b13-89b5-d46068eca77f/
https://urlscan.io/result/4e52047c-71fb-4bc1-8676-b6d16a848d5c
lhitlbtc.hosstinger.info
Fake Hitbtc phishing for logins
https://urlscan.io/result/4e3dbccf-028f-472d-8d3d-a9e8c9e25bbb/
https://urlscan.io/result/c1fab32f-4fc8-4d52-b631-4d9dcd7a3f89/
shapeshift-exchange.online
Fake Shapeshift
https://urlscan.io/result/07e59781-3423-4071-8879-2f51fdd1190c
address: 0xcfb10450BB6e7F77b856bf6dF74EA56dD92304AD 
fgcoin.io
https://urlscan.io/result/ae46d698-66cc-4cd5-8fa4-b6c462af343a/
address: 0xfb2050604A065CF9699bcF07b33ACCB6f5c27231
john-mcafee.com
Trust trading scam site linking users to evotrustllc.com/bt/ …
=> kuciorn.hosstinger.info + more

_data/scams.yaml
eth-giveaway.space
https://urlscan.io/result/9d072597-6866-48aa-8cc1-4b8a400349ff/
https://urlscan.io/result/42c9c103-2d77-43ac-bc91-a3e599dbe82a/
address: 0x7f7Be29BD339a38FAcE53918dC8cDBF6a06bC7e7
claimprize.xyz
https://urlscan.io/result/8c1e0c1a-8050-42ed-976b-042d0b684121/
https://urlscan.io/result/704404fd-dff5-43fb-ba27-887272fb933e/
address: 0xA2922aE30Ff11c0fEf6E250b3892A451BDd533f1
ethereum-transfer.com
https://urlscan.io/result/150fe500-8c51-42f7-baf2-60331a08137d/
address: 0xbA32570e4c276C74e6DC67BFa6F82253228BD1cD
ethfast.top
https://urlscan.io/result/b4522b1b-c7cf-454c-bb2e-552a1a9276bd/
address: 0xa0a51563Ca933ECDf030f84425dEF24ab8cC6733
medium-promo.com
Trust trading scam site. …
=> eth-giveaway.space + more

_layouts/default.html, _layouts/scamdomain.html, config.example.js, run.js, update.js
* Added logic to disable DNS lookups - we don't want people running ESDB locally to expose themselves to known bad actors - https://github.com/MrLuit/EtherScamDB/issues/1184
* Redesigned the domain view - having the security tips in a green div causes confusion if the domain is bad IMHO.
=> Toggle DNS lookups

_data/scams.yaml
blovrnance.com
https://urlscan.io/result/aeb6c222-cece-41c5-b6e4-03373d6167f7/
https://urlscan.io/result/71bb9c81-aea6-408a-bc50-0e3cc4730c8a/
bingmancol.com
Used in Google Ads (UK) to redirect to blovrnance.com - Fake Binance
https://urlscan.io/result/46cc98a3-a7eb-40c3-bfd2-e5e80475e7b8/
biflnex.com
Fake Bitfinex phishing for logins
https://urlscan.io/result/7f0a3439-ff10-475f-b2a7-ad417f64409c/
blfinex.com
Suspicious Bitfinex domain
https://urlscan.io/result/048eec5c-c0ab-494a-8e33-bb5c77193b78/
bnbnews.org
https://urlscan.io/result/c284190c-064c-4430-a9b5-90784ca76e61/
address: 0x797Ab7505608A943A4f00E275aD6F2a514b8e038
btcdrop.top
Trust trading scam site. Bitcoin address: 187R5KKL5oT2hUrdGH3yJv8H36N3BSnsii …
=> blovrnance.com + more

_data/scams.yaml
fantom-foundation.de
Fake MyEtherWallet stealing keys with POST /eth
https://urlscan.io/result/23259a32-eea6-46f2-b18c-8d5f5f3e02ab
bincomance.com
https://urlscan.io/result/afd6e5b5-217f-4b44-b5dd-5b3f425b0c53/
https://urlscan.io/result/d307b06f-f104-46b4-bcc8-3f2959b10962/
https://urlscan.io/result/6cb33362-e1ed-4874-a5a1-65d433355445/
kraken-authentication.com
Suspicious kraken domain
https://urlscan.io/result/e6a7aac5-e9fc-4466-956a-cc4568ed3c6d/
kraken-we.com
Fake Kraken phishing for logins
https://urlscan.io/result/7270f948-74cd-4e57-9feb-118efa79fb34/
kraken-ix.com
Suspcious kraken domain
https://urlscan.io/result/0c7452cf-e834-487d-b0f5-3a944c1bc94a/
kraken-on.com
Suspcious kraken domain
https://urlscan.io/result/c1143730-4d22-48fd-9898-8c325710bcd0/ …
=> fantom-foundation.de + more

_data/scams.yaml
clubeth.live
https://urlscan.io/result/40fd1fdf-2d33-43a6-938f-cdd246654f13/
address: 0x420eDd527F217b56Ab9b0fdf7A6C553Fe78EB2aa
myethgift.com
https://urlscan.io/result/dfd17208-abdf-416a-8fba-ed2d2d463c09/
address: 0xCBA1E79e47DD511B87Dcc69B279953543d453fC5
clubbtc.live
Trust trading scam site. Bitcoin address: 18dCxtGHAzWbrGBxPQyW4WqSV7N94HQuHt
https://urlscan.io/result/21ec73f2-2634-49a5-9fe9-af1fa93f2c4b/
binance-official.com
https://urlscan.io/result/78dffe72-0356-4e06-a79f-1111f28ecbd6/
https://urlscan.io/result/c42435a3-915b-46f9-a338-15d2cdb5fbaf/
shapeshift-exchange.io
Suspicious Shapeshift domain
https://urlscan.io/result/e19c587c-2f17-44f3-a5e0-c704beacbfd9/
view-wallel.info …
=> clubeth.live + more

_data/scams.yaml
kraken-ixz.com
Fake Kraken phishing for logins
https://urlscan.io/result/f3e9370a-661c-40c7-9a19-56ddbe04befa/
kraken-check.com
Fake Kraken phishing for logins
https://urlscan.io/result/1c0a2bae-af8b-4c4f-b78b-1b97cd80e2e0/
airdrops.delivery
https://urlscan.io/result/3ebe277c-a5b0-42db-bb96-4d709709be0c/
address: 0xCe9e24Dffdb3DC08EFe33AD3DB858576C3f27D5d
=> kraken-ixz.com + more

_data/scams.yaml
ethereum-promotion.org
https://urlscan.io/result/694fd146-6792-4a52-b384-6815ed566688/
address: 0x1e1041d4e5E03D90E6350f8A239d8C0E9770F036
ethmore.io
https://urlscan.io/result/6963c2a1-515e-4f56-bf32-9d09c40c0698/
address: 0x4Fcff4B71481562Cd6Fdb0FDc7e25F3a8Db55598
buzcoinio.com
Fake Buzcoin crowdsale site
https://urlscan.io/result/8d285f70-08d7-4d95-89a1-3fec74c6f332/
address: 0x86dDF5b305B9081fB5208e903EDeB013510997cd
official-promotion.org
https://urlscan.io/result/660cdb0b-4d01-430b-a2fc-34d07c8790c0/
address: 0x11775A106157a283873A81E8Ec58394b8d568E06
tron-presents.blogspot.com
Trust trading scam site. Directing users to airdropseth.info
https://urlscan.io/result/57434afe-e3fb-4b4d-a93d-60c7e40d16fa/
address: …
=> ethereum-promotion.org + more

_data/scams.yaml
aronum.com
Fake Arionum site
https://urlscan.io/result/ec23d6ce-ea1e-49dd-841d-206104d433b9/
vechainx.io
Fake Vechain KYC directing users to myetherwallet.com.api10.icu/signmsg.html via bitly.com/2Md9p46+
https://urlscan.io/result/b62f0d62-b717-4f8c-9732-9dd0f517607e
https://urlscan.io/result/d660ad6b-33b1-4f46-893a-36b7b2025389/
etherdrop.top
https://urlscan.io/result/7a5cdd5c-43b2-4f73-a923-d98b52f993de/
address: 0x820C415a17Bf165a174e6B55232D956202d9470f
ether-gather.com
https://urlscan.io/result/7b984852-176d-4970-b4ec-c1beb31175da
address: 0x5A733412E4fbB89e7EBB7EFbbd1B79D5fdA4F4cC
safeclaims.info
https://urlscan.io/result/fd723f44-cfa6-4772-8eda-9169f3addd1a/ …
=> aronum.com + more

_data/scams.yaml
xn--etereum-yt3c.com
Fake Ethereum site
https://urlscan.io/result/23dec8b8-eecb-4183-a85c-ddfd66953c77/
https://urlscan.io/result/027acc0e-0e02-49ed-a3bc-72737bd566d3/
=> xn--etereum-yt3c.com

_data/scams.yaml
ethereu.mfoundation.cf
https://urlscan.io/result/0dc3e861-cafc-458c-9306-92e51a41cdf6
https://urlscan.io/result/44d64698-c52c-4f1f-b516-5d0bd4ed0036/
address: 0xb5f3A62E8f0468efEc0A65b81c09E8b46D1F9158
=> ethereu.mfoundation.cf

_data/scams.yaml
bigethereum.org
https://urlscan.io/result/6dadf12c-efcd-4df3-a5c6-6bd8a53fea48/
address: 0x6F0041B3906048528a6760a1BC9627A201A83E38
giftofeth.info
https://urlscan.io/result/3a28a408-bfc6-4eb1-bd54-7c8033224478/
https://urlscan.io/result/29e342ad-d2bd-4c6f-a3e7-7c0a6a5239ed/
address: 0x1e21312d1e05a13A7d4aF51fFf776b93D5324111
address: 0xe55996c55E188FbCf95eD6Ca96Fa933171c05fA0
crypto-promo.website
https://urlscan.io/result/dc41f39d-6d28-44a2-bfa1-e121364be66c/
address: 0x52b949fb4678c20873135ce6b3727949432af1d7
btcdrop.in
https://urlscan.io/result/a37ff67d-b556-4813-be88-6f475259e6c8/
address: 0x820C415a17Bf165a174e6B55232D956202d9470f
ethdrop.in …
=> bigethereum.org + more

_data/scams.yaml
forkdelta.biz
Suspicious forkdelta domain - not active yet
https://urlscan.io/result/67a484e9-17a2-48f2-953e-aa978661b44a/
https-myetherwallet.net
Fake Forkdelta
https://urlscan.io/result/378469cb-f410-48c8-b536-79fb2fde2094/
https://urlscan.io/result/c8a05fb6-6a62-486e-a8b3-c53549923437/
etherdeita.top
Suspicious etherdelta domain - not active yet
https://urlscan.io/result/10290394-962c-49eb-a699-e401c546cc67/
etherdeita.site
Suspicious etherdelta domain - not active yet
https://urlscan.io/result/6419b1f5-ef2f-45df-b2a4-17cb7a3d041e/
mycryrptto.com
Fake MyCrypto
https://urlscan.io/result/418dd2a7-2e39-4eb0-adf2-dfefdf101152/
myethervvallet.ru
https://urlscan.io/result/891ab622-1068-4bdf-8c93-233e9f0a27d4/
myethervvallet.top …
=> forkdelta.biz + more

_data/scams.yaml
bjlttrex.com
Fake Bittrex phishing for logins
https://urlscan.io/result/541805cc-c8b0-4815-bf7e-3fb388f17dcb/
https://urlscan.io/result/dc8d4336-5bb5-4892-bd37-b48d3fe4a887/
blocrkchein.com
https://urlscan.io/result/b89a7128-9f29-4919-a9c3-ab2ba562a6fa/
https://urlscan.io/result/450b7438-6e01-4ad0-8395-0219787cc601/
blrockchein.com
https://urlscan.io/result/5bae187c-4d34-463c-8869-7f4dbd090906/
https://urlscan.io/result/129d4be7-4daa-4e60-9ed1-5c385a760d01/
exrno.su
Fake Exmo phishing for logins
https://urlscan.io/result/925bf758-f330-4256-b913-4ed26f87f094/
gaterhub.net
Fake Gatehub phishing for logins
https://urlscan.io/result/fbbe1e72-40e3-4483-be95-25501fd72ba6/ …
=> bjlttrex.com + more

_data/scams.yaml
safeclaims.space
https://urlscan.io/result/91d7d993-51ac-4546-a003-9374e5820d79/
address: 0xe2e55d8889141495e8442ED4ba48c6f2E638071d
safeclaims.net
https://urlscan.io/result/20c7b0be-218e-4a93-992c-ad8b2da4aa1a/
address: 0xdd944483Ace0a893C328877608e7975B4Ec987Ab
myethgift.net
https://urlscan.io/result/36014ba5-1568-4836-a8b8-225ab0e0fe72/
address: 0x335E40277f127c620560FaF1cfa001E5899864ad
official.ethx10.com
https://urlscan.io/result/8ea14e66-9c0a-46bc-9492-35053165a848/
address: 0xdd0D7fcCDF1142B0157d34866c404a249eeA2Eb8
ethx10.com
https://urlscan.io/result/f48043f1-420f-4ad9-9476-44237ba98543/
address: 0xdd0D7fcCDF1142B0157d34866c404a249eeA2Eb8
elon-giveaway.org …
=> safeclaims.space

_data/scams.yaml
bliovnarnce.com
https://urlscan.io/result/fa4e4f05-fdd5-4c3e-ab30-0b5f837f12e6/
https://urlscan.io/result/10e2733f-5ea1-4c48-83b1-00e8531deabb
meyhferwallet.com
https://urlscan.io/result/db9d7b0c-1295-44f8-b78f-0afb8878d005/
=> bliovnarnce.com + more

_data/scams.yaml
airdropbox.site
https://urlscan.io/result/2e7003b2-9f3c-4d4b-bb1b-71cc6cd4d6ac/
address: 0xEd8c8830cFC51F306C4765598cF3EE50ad8d978A
ethereum-giveaway.top
https://urlscan.io/result/ce4fac3e-1641-462b-8f04-c89a7f5b2f6b/
https://urlscan.io/result/d7f4fa14-b70c-404c-b675-ab41c9a45439/
address: 0xcB3f9c4cD5D31B4D6DB04a63f5A414779cFe6Fc7
address: 0x9DbF942bE15c70c4E1Fb8c0D1B53007377bCaa09
etherescan.net
https://urlscan.io/result/a824fabf-c063-41cb-8397-a367d3aef784/
address: 0x1707BC69d91F86A6000d318E85D07B00747152FE
transaction.status-eth.top
https://urlscan.io/result/fc1b87e1-a57c-4240-b2fb-0280248e9fef/
https://urlscan.io/result/a045125c-48fd-49f1-bacc-8007b6324182/
address: …
=> airdropbox.site + more

_data/scams.yaml
xn--bnanc-r51bze.com
Fake Binance - IDN homograph attack domain
https://urlscan.io/result/23f13b42-7281-4502-a330-19b2362cafce/
ycbit.net
Suspcious Yobit phishing for logins (not deployed yet)
https://urlscan.io/result/336676b4-d765-4f4a-aa6e-5e75686ba7b3/
kuccin.com
Suspcious Kucoin (not deployed yet)
https://urlscan.io/result/142167bc-a626-435e-9e43-9586f508b67e/
lnitbtc.com
Suspcious Hitbtc (not deployed yet)
https://urlscan.io/result/0242fd36-fc10-45e6-8ed6-26700ce07481/
www-nycryqto.com
Suspicious mycrypto domain
https://urlscan.io/result/a86bc4cb-06a6-4282-bbc7-69ae43518834/
www-nycryptos.com
Suspicious mycrypto domain
https://urlscan.io/result/e99a5f5f-c13e-4d79-b4c2-fd2a25fbd571/
go.ethers.pw
https://urlscan.io/result/2bc5066e-7bfa-4942-8c56-6dd9a533a29c/ …
=> xn--bnanc-r51bze.com + more

_data/scams.yaml
kralkem.com
Fake Kraken exchange phishing for logins
https://urlscan.io/result/419b2765-0235-4b23-bf5f-23e9e7e664e0/
blockchalim.info
https://urlscan.io/result/68f0288a-a08f-418b-8097-fd35eade647e/
neo-tracler.co
Fake Neo wallet phishing for keys
https://urlscan.io/result/02795a3c-b069-40d8-b129-85c65a766e07/
https://urlscan.io/result/d2988f88-6f65-4b95-80d1-322d8878ae8c/
app-bittrex.com
Fake Bittrex exchange phishing for logins
https://urlscan.io/result/672f5a63-bd95-4bb3-9431-a124924f0198/
=> kralkem.com + more

_data/scams.yaml
ethcoin.store
https://urlscan.io/result/0964f3ff-c164-4671-a0ec-bb3ca6bfe20c
https://urlscan.io/result/884df2b5-d1f0-4d7f-b1fe-a32a509b2936
=> ethcoin.store

_data/scams.yaml
xn--omiseg-ul8b.com
Fake OmiseGo publication linking to a fake MyEtherWallet xn--myethrwalle-6qb4278g.com/#contracts
https://urlscan.io/result/2b86d579-3cac-44dd-8147-e52e9e863e8d
https://urlscan.io/result/4c6e80a7-ffce-4dc7-b707-9104669936fd
xn--myethrwalle-6qb4278g.com
Fake MyEtherWallet - IDN homograph attack - phishing for keys
https://urlscan.io/result/c3d99bd1-d309-4c42-a68a-d0fe0bf449d8
myethervvallet.net
https://urlscan.io/result/2d8b4d34-10da-4381-9cd0-6bb6617dcf9b/
myehterwelliet.com
https://urlscan.io/result/381b05a5-97c5-4545-9fd6-236bb65876a1/
=> xn--omiseg-ul8b.com + more

_data/scams.yaml
cbase-pro.com
Fake coinbase pro - https://twitter.com/olihough86/status/1029125099696340994
https://urlscan.io/result/af467c0e-25c6-44a9-be21-d5a54ac5a186/
https://urlscan.io/result/0beba238-84c6-4b09-b50c-91e7eb063589/
ethereumprize.io
https://urlscan.io/result/856e71e2-6286-445e-aa46-6f5254182e9d/
address: 0x1d2Ba50dfA3C78Da0E56f62D3a9e80a4D20Da363
airdropsvert.xyz
https://urlscan.io/result/8b6f4c1d-b17c-41de-81cc-4c29be4f94ac/
https://urlscan.io/result/d044a855-39c4-4714-9422-9cdda3a1e090/
address: 0xA2922aE30Ff11c0fEf6E250b3892A451BDd533f1
etherium.host
https://urlscan.io/result/4959e702-707a-488c-9c23-ba9e07cf579b/
address: 0x2A37A183eb7f18caE3fcB967404E472729f21E96
claimeth.top …
=> cbase-pro.com + more

_data/scams.yaml
binance.com.eth-bonus.me
https://urlscan.io/result/cca63234-d444-4f44-b049-bf0078dfeea7/
address: 0x2b5d022D3396c412A58C7be8897BC8d3E0C823c3
eth-bonus.me
https://urlscan.io/result/dfa23b00-36b5-47e2-9d13-e1d29a4323ef
address: 0x2b5d022D3396c412A58C7be8897BC8d3E0C823c3
elon-musk.company
https://urlscan.io/result/6f093846-52d8-434f-97e0-1628b69ee2c5/
address: 0x574D4CeA313269e482f4b53d889A940241D99e45
safe-eth.info
https://urlscan.io/result/4077c06c-a939-440e-9879-d2766fe9bcc6/
address: 0x4974fa50E11fD8F534093eA856a98574f8Bf2A50
promotion-eth.com
https://urlscan.io/result/688f1d19-b0c8-49ae-a40b-a11304fdf09a/
address: 0xB3B35fB20695F3ce1Bd56c56E4df20d8ce222943 …
=> binance.com.eth-bonus.me + more

_data/scams.yaml
api-binance.co
Fake Binance phishing for logins with POST /_loginSend.php
https://urlscan.io/result/a9cbe649-6f60-4b51-b56a-ef3811c337a1/
https://urlscan.io/result/70b9d199-26fd-466a-9008-d866854dc522
=> api-binance.co

_data/scams.yaml
accounts-blockchain.info
Suspicious blockchain domain
https://urlscan.io/result/deda84e6-f6c0-42ec-9b3f-9a9169ac0866/
binance.com87654897.ml
Fake Binance phishing for logins with POST /submit.php
https://urlscan.io/result/41635e91-f904-4f77-bbaa-6226f3a74850/
https://urlscan.io/result/31a65816-9192-4147-8210-f5b4083fe4c2
https://urlscan.io/result/0819056a-5af8-4d7c-8dd1-2e5cf32ef0ad
https://urlscan.io/result/c462b09f-493e-46b4-94a7-ec609b6f4bc7
binance-in.com
Fake Binance phishing for logins with POST /indexSend.php
https://urlscan.io/result/c7436d40-bf7b-4019-ab32-dcbebc14ff87/
bittrex-br.com
Fake Bittrex phishing for logins
https://urlscan.io/result/c5584bbf-7180-4dfd-88fc-f202cac834b8/
https://urlscan.io/result/59e90326-c125-402c-8589-493ecbd6450c/
=> accounts-blockchain.info + more

_data/scams.yaml
safe.justgeteth.com
https://urlscan.io/result/d1181880-427f-4c9e-812d-04a478bdce91/
address: 0x0a7DDe263eb93F69acD1671A223C5C93faA73701
promotion-eth.net
https://urlscan.io/result/f85fcf8d-7173-4b99-9d2a-713e6070f97c/
address: 0xE2621777f2d10D2fc5cf2F7F48d680044F2e49A8
eth-airdrop.info
https://urlscan.io/result/433262fd-3414-4f2e-bd88-b5f0e16bab5b/
address: 0x0EaB14A501a8125387B0C1E2BD13a217CEe45EBa
mediurn.press
Trust trading scam site. Linking to ethereum10000.press via buff.ly/2MgM5Xd+
https://urlscan.io/result/0f285f79-1ea5-43c5-8b93-fedcaf5f491c/
ethereum10000.press
https://urlscan.io/result/c8fe777e-939a-4571-8490-c20d58a79b1f
address: 0x688e8d92fcFf37b37f0b3910120f0ce906f12483 …
=> safe.justgeteth.com + more

_data/scams.yaml
eth-club.club
Scam giveaway
https://urlscan.io/result/f412b62f-58cf-409f-8a6e-759f131b51fe
address: 0x0F23430D929F24b86CB3Bf375B94d96361d0420a
ethgiving.000webhostapp.com
https://urlscan.io/result/aa1ddea3-edd5-4b52-9912-56571585bb90
address: 0xA324120643DDe9D520A06691010F086B12D5cA02
mediumapp.org
https://urlscan.io/result/1f126452-8ab2-49d2-b27f-cc18d95e3579/
address: 0xBc91d37841f58Fc8611AB045C240BD5241090B86
ethpromosend.com
https://urlscan.io/result/7a37e2ed-3493-4e92-b673-35bcfde81421/
address: 0xB23452b9e14f7770C0aD879Fb4dA1e70Bf661EEe
giveaway-coinbase.top
https://urlscan.io/result/bca0d853-ed93-4d30-b1a4-ff66e76b0e2f/
address: 0xDF50C2DA0a52f2a3a231eD38fA1B79Ad97ab9563
eth5000.in
Trust …
=> eth-club.club + more

_data/scams.yaml
ethgetbonus.eu
https://urlscan.io/result/26ad9a82-a8cc-4d33-97de-65b703fc9830/
address: 0x606188614094946E0fcD05a0c94D51Ff586fb01b
eth-official.claims
https://urlscan.io/result/2f82dc8a-9eb8-4b79-9cd8-cac3167c70f0/
address: 0x2C11e2b870472a32027500bF0faCCeB7200e768b
ethresults.info
https://urlscan.io/result/3e572f67-7f97-4856-99d1-bf3bc6c0b507/
https://urlscan.io/result/56fbb409-c06c-496f-8df7-1a5e5fccbc4f/
https://urlscan.io/result/326bfcb3-5d68-4272-a935-750f13af68d4/
address: 0xfC930BC7AA32b14a87F49A4E120Ff54f8F0a5E05
address: 0xDD0385e83fc3cBeFc00c47716774d71ee583805A
address: 0xcf75D0bF4E47f3dB616a28D1Cf8d4153D3957edA
ethereumdrop.eu …
=> ethgetbonus.eu + more

_data/scams.yaml
bestchagne.com
Fake BestChange exchange site
https://urlscan.io/result/a30bd448-1274-40ba-b236-0642cae6d3f3/
biftinex.org
Fake Bitfinex phihsing for logins
https://urlscan.io/result/d3e10088-d2ad-4a62-9120-da2af8be07d1/
myehterwellet.org 
https://urlscan.io/result/7de8a430-a7b9-41ec-b58d-a35b191d9140/
ethclaim.top
https://urlscan.io/result/f99f179f-2730-4bbf-b2cb-72d59b95f584
address: 0xA3570c82D03bBf8C337799FE3f502729D3Cf0DBc
bittrex-n.com
Fake Bittrex phishing for logins with POST /indexSend.php
https://urlscan.io/result/951fc35f-0059-406f-b7bb-a71fdf1cd872/
eth-airdrop.biz
https://urlscan.io/result/889364a4-b93e-449d-94c5-3a8f0ebbe231/
address: 0x4A0d6F59e4e689506122FC7691Ea0B3c9e9f7964
ethfs.info …
=> bestchagne.com + more

_layouts/default.html
Link to Medium article about changes: https://medium.com/@etherscamdb/breaking-api-changes-in-v3-646217a22bac
Announcement appears in the top of the screen.
=> Added an announcement about v3.0.0 breaking API changes

_data/scams.yaml
eth-secure.top
https://urlscan.io/result/45bb021a-58ec-48b9-9090-505569ca9495/
address: 0x0084515449B037205A33d6d3940a5684126Aa4b5
ether-promo.biz
https://urlscan.io/result/ca2eb306-0951-4d4b-9f1a-ea6bc7c102b4/
https://urlscan.io/result/7a69cd15-be9c-402e-9584-4fd6c274f0b3/
address: 0xfB864b083B6284a864cd3A18378e65baBd13Ce1B
address: 0xD6D07d0463C3157725804055dA4aFd36201EA99D
medium-ether-blog.info
Trust trading scam site. Linking users to ether-promo.biz
https://urlscan.io/result/10a88169-16c1-44d8-9495-686c3734826a/
address: 0xD6D07d0463C3157725804055dA4aFd36201EA99D
eth-return-now.borec.cz
https://urlscan.io/result/de05a86d-3191-4361-9528-d11f387380e7/
address: 0x28f45192fD495bd9CBB312a6080d086D14481Ebc …
=> eth-secure.top + more

_data/scams.yaml
walletverify.info
Fake DDEX phishing for keys
https://urlscan.io/result/a8552b93-4ca3-44df-9c5f-0cdd2676f0be/
myetherwallet.com.walletverify.info
https://urlscan.io/result/7562ef29-977a-4781-ac9b-2955ba27b9c7/
=> walletverify.info + more

_data/scams.yaml
myethervvallet.pw
https://urlscan.io/result/143cd7af-f9fb-48d0-94d3-c0b5483ea0a6/
https://urlscan.io/result/a0a7f550-807f-4590-a796-b958d866ed41/
myetherwallet.co.za
https://urlscan.io/result/b450ea9e-b9fd-41b2-b5fb-29078c84fdf1/
myetherwallett.fhapp.xyz
https://urlscan.io/result/e1ebff8f-fbb1-4cf5-abb1-683de3ed1416/
web-binance.com
https://urlscan.io/result/2d36def6-08a4-4859-987d-b8996c9ed02f/
https://urlscan.io/result/cf726ea8-b33e-4a04-aead-427b1624ed55/
xn--bittrxx-vya.com
Fake Bittrex phishing for logins with POST /../loginn.php
https://urlscan.io/result/2056085a-ad0a-4767-ba43-13ec25bd32a4/
memonero.co
Fake MyMonero phishing for logins …
=> myethervvallet.pw + more

_data/twitter.json
=> twitter.json

_data/scams.yaml
ethtw.info
https://urlscan.io/result/35bb01ee-d99e-4a0a-922a-f77987b8aee9/
address: 0x813ca840322E3795702300bB3eBAF7aEE9aF9536
address: 0x26A022e559eC404C142eC873F1cde696ac97915B
ethertake.org
https://urlscan.io/result/eb9b855b-2b91-4e25-962c-5bc03a9e1d29/
address: 0xf6fc6941643384Ccd56ad8f084beEB338B77128A
ethereum-giveaway.czweb.org
https://urlscan.io/result/78f1c6f1-17d9-4c3c-8b86-c38f24ae2685/
address: 0x31fca2139b07c2a97287de51f0219a34f4181710
ethshift.website
https://urlscan.io/result/fa41a13b-3cf6-4543-a8a6-75723e81c545/
address: 0xA9A53dCD4C6BC74Ae56cC52CE48390D85BE98c80
gathereth.com
https://urlscan.io/result/3d3f5052-3bcb-44e6-87cc-341794b4e5bc/
address: …
=> ethtw.info + more

_data/scams.yaml
ethpromogiving.com
https://urlscan.io/result/f949b410-96f9-476f-844b-e9d1e9fb53a5/
address: 0x14a11E2eF83895918da176165e33025e02e472dE
ethpromogiving.net
https://urlscan.io/result/0d35570d-5336-4e7f-8010-d76d6f0d9d83/
address: 0x478dc7121A0339Fbba4cC5b4AcBB8a119c8a8f19
ethpromosend.net
https://urlscan.io/result/045902ee-d476-4ad4-bcf2-ac34e7038abd/
address: 0x04A96F1B6f661793787B527F3114f33d7e413B4d
ethpromodonate.com
https://urlscan.io/result/e51d6ab0-ae18-4766-bdc1-77d51bbfb791/
address: 0xB23452b9e14f7770C0aD879Fb4dA1e70Bf661EEe
ethpromogive.info
https://urlscan.io/result/ca8a75bb-9222-4942-9811-9672eb2f8b4f/
address: 0x6bed8445ADa86419243f95A5BB14BC599D62B295 …
=> ethpromogiving.com + more

_data/scams.yaml
verify.10000eth.pro
https://urlscan.io/result/968c2841-2c22-4239-96ed-886db53eab30/
address: 0x7bc060459dd2730d912B654EC98cacDeE2b6927d
10000eth.pro
https://urlscan.io/result/e86c61ca-b06a-4edd-bf3d-cea19f68a483/
address: 0xf950000A614e53d35505A40764e7Ebc100FCf0dF
eth-twitter.com
https://urlscan.io/result/42953818-9698-4728-b87c-d062eab4f066/
https://urlscan.io/result/6734599b-8c62-45f1-92fd-af7eedcc4ca2/
address: 0x5De81CAEFeE2f158964a65F0e19bd5e5EE94602a
address: 0x4577a58d2b8AF56827bba7A81Cc63896327bA968
ethfor.blogspot.com
Trust trading scam site (iframing ethcap.info)
https://urlscan.io/result/5c5d430b-f487-40ac-b3d3-55c443119db8/
address: 0x26A022e559eC404C142eC873F1cde696ac97915B
address: …
=> verify.10000eth.pro + more

_data/scams.yaml
coinbase.tx-pr0.com
Fake coinbase phishing for logins with POST /simple.php
https://urlscan.io/result/04c4dc83-2e87-45ad-b85b-72f5c8295f97
exploretransactions.info
Fake Idex phishing for keys with POST /callback.php
https://urlscan.io/result/afa2e8c4-f0bc-4030-b133-e2ca408fafc4/
blockcnalh.com
Suspicious blockchain domain - nothing deployed yet
https://urlscan.io/result/1802a204-e7e0-4ec0-a571-c522a5260995/
blockcnaln.com
Suspicious blockchain domain - nothing deployed yet
https://urlscan.io/result/94cda40e-5b7c-4504-a34d-96fece321606/
blt-mex.com
Suspicious Bitmex domain - nothing deployed yet
https://urlscan.io/result/c406eb6f-d8ff-414b-9610-2721f3ab5ee8/
kueoin.com
Suspicious Kucoin domain - nothing deployed yet
https://urlscan.io/result/38a5a714-fc35-4aa2-8d2c-b0ba8eb4aa59/ …
=> coinbase.tx-pr0.com + more

_data/scams.yaml
ethereum-foundation.info
https://urlscan.io/result/8eaee372-6b02-4c23-b53c-44a44f9cde22/
https://urlscan.io/result/38312c4d-4199-490d-92f9-ae275a825cc1/
address: 0x6372fe3cD2244286E727027426479181C91E33B3
bitcashout.wixsite.com
Ponzi scheme
https://urlscan.io/result/fb5017af-2854-4acb-8c4a-3cff27997245/
https://urlscan.io/result/dc5cacb5-697c-44ef-be9f-e6a90eb942b4/
address: 0xaba49b563feed7f617ae2fcff86c3a6e8821c387
bigcryptogift.info
https://urlscan.io/result/b1711365-f8f3-4329-b93b-805417ab66c2/
https://urlscan.io/result/2afa66f9-11a7-44f2-bcb0-49ea095f7d1b/
address: 0x046E3A705d9bCd0E53D2b45161B48E39f4Bc4090
address: 0x0D3832c74ED42b084806Bf23FCCbf3193CC596Af
claim-binance.com …
=> ethereum-foundation.info + more

_data/scams.yaml
hitbtc1.website
Fake HitBTC phishing for logins with POST / _loginSend.php
https://urlscan.io/result/5cc48f6a-b75d-445b-8a8c-f7e2ecbae625
https://urlscan.io/result/03465e2c-c934-493c-8b0b-65f5cd67d48c
promo-giving.ga
https://urlscan.io/result/448643d8-cf73-4cf0-8998-38c0d90866fd/
https://urlscan.io/result/6dc333c2-fc64-48c3-b469-789841857ded/
address: 0xadea1fc3493feb9fddc1629e37e5580c21470d7c
address: 0x0a0d6500a7365fbd500f06811abef4de95c7a9a5
mediumlast.ml
https://urlscan.io/result/0a6ed2f1-a314-4484-a1da-fa76b4bd71ce/
https://urlscan.io/result/23462996-6cf6-4150-bd0c-847f2862196c/
https://urlscan.io/result/24fcaf6b-21ff-47e3-82a0-5448f7098bcd/
https://urlscan.io/result/f08bb965-0b68-472a-9154-73c02aff7bc2/
address: …
=> hitbtc1.website + more

_data/scams.yaml
ethereum-bonus.biz
https://urlscan.io/result/08d937e9-5a38-4fcc-a54b-319e585c37b3/
address: 0x7862f3EC65e013bfC42f6905C0E373B5B2c65c51
bigcryptogift.borec.cz
https://urlscan.io/result/ec35cd29-fdc1-481c-8ec1-42d19e36a6f5/
address: 0x9Bd1ab6BE3c0Ed45Bab095335F6d16f0Ff18109c
website-events.website
https://urlscan.io/result/9989bf3b-2612-4580-90b3-c8c4bc33caaa/
https://urlscan.io/result/0530cb30-5d7c-4206-b5b6-d141e7fdead1/
https://urlscan.io/result/3a60b2f4-627b-4fa9-b119-1a8c7ba71979/
address: 0x7D69D57b025Aa1e5029194582eB85608dB84cFb5
satoshilite-eth.tumblr.com
Trust trading scam site. Linking users to get-eth-now.com/eth/
https://urlscan.io/result/319d0354-ce06-43f5-872f-b858d69ba5b9/
stellarterm.org
Fake Stellar …
=> ethereum-bonus.biz + more

_data/scams.yaml
idexmark.online
https://urlscan.io/result/5c785bb5-2fe3-4946-bf0a-b64585b7c414/
https://urlscan.io/result/5652f6ab-c39f-4755-a281-5c49911a4a89/
eth-gifting.com
https://urlscan.io/result/13b34ee3-3fbb-4d81-ba43-dbcf299f029b/
address: 0x5d0Dbbf6460Ba020A5ab06006Ea447ffC7612b2d
=> idexmark.online + eth-gifting.com

_data/scams.yaml
binanceethereum.com
https://urlscan.io/result/964a7fe8-6065-4197-a8df-b1ccb8adbef7/
address: 0xe7300a38788EE039B20aE36C80dFEEb3a53d3a06
idex.marketing
Fake Idex
https://urlscan.io/result/f4024aef-74a2-4a18-90e0-00bc53255ba0/
https://urlscan.io/result/03fa84b6-d037-481a-b96a-127c210218e5/
httpsmyetherwallet.pw
Fake MyEtherWallet phishing for keys with POST /hbz.php
https://urlscan.io/result/286b383c-38ff-4cf2-87d9-a3070d49006c/
=> binanceethereum.com + more

_data/scams.yaml
google.com.tokensale.ws
Fake Google crowdsale site
https://urlscan.io/result/51df4bee-f037-43be-8561-892e70a28dd5/
https://urlscan.io/result/c5804ad2-d3f1-4197-9dcb-ea248c7a11e5/
address: 0x89f4d39667Aa080502c517B613A6c92786aa14Bd
=> google.com.tokensale.ws

_data/scams.yaml
ether-claim.net
https://urlscan.io/result/390a0631-e3ab-43bc-a542-1c0632a9d017/
address: 0x5b5039BE7A3A8b779D21908F1000E221f3574fa5
airdropvert.info
https://urlscan.io/result/7d547a4a-710f-49d7-b96f-8e7086efece3/
address: 0xA2922aE30Ff11c0fEf6E250b3892A451BDd533f1
bigcryptogift.net
https://urlscan.io/result/07de1985-bd67-4d86-85d5-54018eada860/
https://urlscan.io/result/e6a2b460-ccf7-4c18-ae14-7a0abdf313e4/
address: 0xeCE7dE131f2E338C6E76291ED597b359B2B3Be7D
eth-give.io
https://urlscan.io/result/1ce446a9-03e8-4038-a380-673210d05fda/
address: 0xA5e89FA321377b4136793db32fa6AfE78a2BCE3b
mcafeepromo.xyz
https://urlscan.io/result/85c81d64-0680-4cc0-9633-e5c442d74133/ …
=> ether-claim.net + more

_data/scams.yaml
binanblog.blogspot.com
https://urlscan.io/result/21d11b83-fcdf-4fb8-9241-e04b35dc3077/
etherfast.eu
https://urlscan.io/result/9482f60a-4bd9-4d29-bdc9-9f4ec01c8f16/
address: 0x3b10Aa9856b7026bd5C33491e8dA8108DdF5aC83
ethreum.ru
https://urlscan.io/result/a2ccdc1f-e69a-46b8-9f03-2116e4c5d2cf/
address: 0x077Ab20cd24146DdCd6FE7b805Ae007F29E4D842
eth-official.fund
https://urlscan.io/result/c4b595c3-8a98-4b80-a8f3-9abcfe5e189d/
address: 0x6372fe3cD2244286E727027426479181C91E33B3
bonuseth.top
https://urlscan.io/result/5a2cafa0-b7e7-41ff-8d35-ef810f2d9d4b/
address: 0xD877A34bcF28d6753fD4aF2e3c29C861D048aE8f …
=> binanblog.blogspot.com + more

_data/scams.yaml
Fake Bitmex phishing for logins with POST /send1.php
https://urlscan.io/result/a64759bd-8a75-4e39-8067-348299f80fcc/
https://urlscan.io/result/9226315a-f67b-46d5-a044-b522e2ef9f6d/
https://urlscan.io/result/49b761d3-7224-4918-aaaa-b210557fc8cd/
lbtsx.com
Hosting a fake Cex.io exchange login phishing for logins with POST
/indexSend.php
https://urlscan.io/result/0548c9cd-c0dd-4a05-84b5-c7936637ff70/
xn--bimex-leb.com
Suspicious bitmex domain - not deployed yet
https://urlscan.io/result/9dd986d0-95bc-4370-8e69-1757830f01e4/
bitmex-login.com
Suspicious bitmex domain - not deployed yet
https://urlscan.io/result/5db88041-eeab-48c4-ab59-53cd0bd7d977/y
=> biltmex.com

_data/scams.yaml
Fake Bitmex phishing for logins with POST /indexSend.php
https://urlscan.io/result/27c1278f-a3e7-4c46-a593-19d8b80d4aa5/
airdrop-eth.website
https://urlscan.io/result/7bc5e0f2-5549-4a0b-b008-7ce9c52a38ee/
https://urlscan.io/result/d6a966f5-1066-4bec-9f25-c42209703be4/
address: 0xB8ba72C75Af66CBE7E8Dd72c7176AaE678Eb0fE5
address: 0x995000b1f9429233a53F53f6475a3EfdD8dAED11
access.ethsupply.com
https://urlscan.io/result/daf8bc3f-ab03-4ab2-95be-3aa87df7b641/#summary
https://urlscan.io/result/3493edd2-13cf-42c3-a22e-857653ca8351/
address: 0xcc64bf09359451aD56A06326b1aF5cDB0f3938B3
address: 0xAD274Ba3De7f07C7973c7b40b0111Ff53Dd14B06
ethereumpromo.io
https://urlscan.io/result/e95407bb-4bd9-40ae-a078-4d683451d111/#summary …
=> bitmex-in.co

_data/scams.yaml
Suspicious bitmex domain
https://urlscan.io/result/39db4c08-0f60-4ee8-bd22-cf9baf601c1a/
myetalonwindow.info
https://urlscan.io/result/d5eca6ee-691f-4612-b953-95b4cc4bf7a4/
=> lbitmex-in.com

_data/scams.yaml
https://urlscan.io/result/3194bdc5-fd8b-4fa6-a288-f30135f72892/
myetherwallet.co.nz
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/6dab8af2-ef51-4913-a894-882ac88caeef/
myethforkwallet.com.ru
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/4947578d-69d5-4416-b530-34bf52b08517/
myethherwalletr.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/82e20adb-21f0-4ad2-86f5-4223594859ce/
ww25.myethereum.info
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/0dc4fa4b-3043-4640-a3fa-afa668db4255/
myethswalet.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/c4ac4554-8f62-4925-bf6d-8a35d6d9d4a0/ …
=> myetherwallat.club + more

_data/scams.yaml
Fake Binance phishing for logins with POST /processar_1.php
https://urlscan.io/result/a957bd1a-998b-4e32-95de-ea4a6f75359c
=> log-in-binance.com

_data/scams.yaml
xn--myeherwllet-wte7564g.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/d66057e9-ce7b-4a04-bab4-684f845d75ab/
myetherwallet-sigen.space
Fake MyEtherWallet phishing for keys. Reported address:
0x0591a42188996397fc7cd6db729045146c37696c
https://urlscan.io/result/772a2502-ad1c-4438-8548-843f157cfb7e/
enternow.info
https://urlscan.io/result/637d3c67-44a0-4093-8fa1-04ff4394b3a5/
address: 0x015fcA1D09287823e634AE51237ee1eeFF03D9d5
claim-event-eth.com
https://urlscan.io/result/a733f108-57fd-4ea4-9da0-5d085584e2e9/
address: 0xe575D2262f516a392E018BD5Db9AFBC6ae656C92
claim-giveaway.club
https://urlscan.io/result/7a675356-81e1-4f85-a413-fd7ed472795e/ …
=> xn--myeherwllet-wte7564g.com + more

_data/scams.yaml
Suspicious Binance domain (same infra as log-in-binance.com)
https://urlscan.io/result/d6d60680-720d-4c33-af19-617572b71cf6/
xn--methewallet-v48e1x.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/42d75e4f-18dd-40a5-a015-d5a605123374/
xn--myethrewalle-xoc.com
Suspicious MyEtherWallet domain - nothing deployed yet
https://urlscan.io/result/95537436-47d1-4903-aae1-5a376e34ecb5/
=> binance-lgin.com + more

_data/scams.yaml
https://urlscan.io/result/6431b352-c9ed-4aec-87eb-f60923309cf1/
address: 0x94FF38C3e18Bb715CD9061810942d16a587C6566
air-drop-ethmark.website
https://urlscan.io/result/843d93a1-876f-441c-925a-954edc7f2d35/
address: 0x3DCF0AA2d91376F974678f509f2e69c88467089c
ethboom.eu
https://urlscan.io/result/2b7be9a2-e4b2-4f0f-991e-370d038c2d34/
address: 0x98a630280447461Ab2156919b0941EbdEAE5Bc41
dontmiss.info
https://urlscan.io/result/fb8c5df9-798d-48f8-bb8c-cc52ff787fcd/
address: 0x015fcA1D09287823e634AE51237ee1eeFF03D9d5
top-ethereum.net
https://urlscan.io/result/3ce25724-254d-44fe-87db-a47c8c0717e5/
address: 0x015fcA1D09287823e634AE51237ee1eeFF03D9d5
airdrops.services
Trust trading …
=> claim-nowgift.com

_data/scams.yaml
https://etherscamdb.info/domain/eth-bonus-live-binance.com
address:0x77d15104C41dEf5DAd6D5423206bf04621D9d9C1
ethbinance.org
https://urlscan.io/result/1d470edc-8133-442d-8897-c4db3f17cc6b/
address: 0x3e9163816B073c2ce425C99E68bA8aE7CaAEc067
xn--bockchain-0sb.com
Suspicious Blockchain domain
https://urlscan.io/result/bbbd0d4b-3000-4cf6-a131-1150e9b4509b/
myetherwalllet.xyz
https://urlscan.io/result/9f76bba1-96ad-4864-923c-c162db994940/
myetherswallet.website
https://urlscan.io/result/a4a87bd9-00ba-47d0-969b-c9a4d1a01bf3/
blockchalh.com
Suspicious Blockchain domain
https://urlscan.io/result/8bddef85-eb0b-43fb-8b38-cdf4bfabf83b/
blokclhain.com
Suspicious Blockchain domain …
=> eth-bonus-live-binance.com

_data/scams.yaml
https://urlscan.io/result/2f05c793-6b2a-46f1-b8c3-91756fc1dd9e/
address: 0x552C94E34f62ca14D9F2bEC6F1E59b11EfB25B89
secure.ethaccess.online
https://urlscan.io/result/6d67ee9a-8f8e-4759-8471-2e6edb01ce0f/
https://urlscan.io/result/650df9f0-7f73-47a0-8495-8c0200a62daa/
https://urlscan.io/result/4edea407-5879-4f35-92a5-ed89d4beb8e8/
address: 0x2519A00724Ca9d3CdF1fe5F9995D2EE886F48fEA
address: 0x3d89bD83AdD0d4F54aa84943c2241D27e3866D8C
address: 0x88C2A596eb0Bc49b237baEa9f2dEB41C3125C4cF
tesla.center
https://urlscan.io/result/beb44e85-2599-4da1-bc55-cd69ffa2f6f2/
address: 0x3f796b2b5c7c5b87f6885b3160a2261d463b46cc
go.payeth.online
https://urlscan.io/result/b7fa8863-a40c-4e94-bf13-b6eb2b2fc987/ …
=> infoclaimeth.ucoz.org

src/app.js, src/classes/scam.class.js, src/scripts/update.js, src/utils/router.js, src/views/pages/address.ejs, src/views/pages/domain.ejs
Fixed #1254 by making Urlscan image link out to correct Urlscan record.
Fixed #1252 
Fixed #1260
=> v3.0.0 - Bug Fixes [WIP]

_data/scams.yaml
blokclnain.com
https://urlscan.io/result/d3605842-c030-46dc-ae91-47ae66a2de60
giftreturn.mysteria.cz
https://urlscan.io/result/f6458d01-724c-4eaf-bd53-f2ccd2ed05cd/
address: 0x7Fc94073a3aDf4553D59D09E0b0808bB9d408735
ethdrop.cn
https://urlscan.io/result/93c04c17-7852-43d7-a665-0d6603f688d9/
address: 0x23E34BBCCB320951D8D5db864ccE0BA9452ae663
giveaways24.info
https://urlscan.io/result/05d9154f-f2c8-4ed1-af01-56a1e2714737/
address: 0xC7a25050f5F067762e070dfBC3198B9DFD6a2Ad1
airdrop-live.com
https://urlscan.io/result/00f7982d-4437-44d8-8a6f-efeb4827f811/
address: 0x2F0D741580d9dBC27E51e5DBe83f5797f868C2e0
grijub.blogspot.com …
=> blokclnain.com + more

_data/scams.yaml
https://urlscan.io/result/ba1c385b-0797-439a-9d80-d788b7040820
address: 0x124c0c9a23e1c4c04b10cc1eda4934f9818c7ec6
=> selleth.io

_data/scams.yaml
Trust trading scam site. Linking users to elonmusk.fund/e/
https://urlscan.io/result/da9eb451-dc85-4095-b32c-dcc92e93d5d8/
address: 0x08afea4eC3659A2e478F81fef2B784176a0B7D2F
elonmusk.fund
https://urlscan.io/result/512de643-7033-413a-9985-bbd770559748/
address: 0x08afea4eC3659A2e478F81fef2B784176a0B7D2F
loginbinance-com.umbler.net
Fake binance phishing for logins with POST /processar_1.php
https://urlscan.io/result/0949343d-1f7b-4546-a3a1-8f598223d03e/
=> elonmusk.ltd + more

_data/scams.yaml
https://urlscan.io/result/21ae7db2-4abc-43f4-a800-0df782112fde/
binance-ether.org
https://urlscan.io/result/bbf4c9d6-e344-4c6d-9d76-6348f87812a3/
address: 0x2784574e2405A7d3be1259B5F00412Ae652018f4
mywindorwallert.space
https://urlscan.io/result/0940becd-7e67-493d-a12a-ae26348f3660/
neostracker.com
Fake NEO tracker phishing for keys -
https://twitter.com/jmoconnor415/status/1035688910188212224
https://urlscan.io/result/c0865dd6-b334-42af-9a1a-927769de0f4b/
=> ethertoken.online

_data/scams.yaml
Fake ICO (fake team) -
https://steemit.com/scam/@iamdeadlyz/fake-airdrops-and-icos-everywhere
https://urlscan.io/result/f1429ad7-0017-4476-a5cb-31ce5a2d4c65/
binancethereum.com
Suspicious Binance domain
https://urlscan.io/result/f84a6d1a-6956-4bc0-8071-3200012103aa/
mailbinance.com
Suspicious Binance domain
https://urlscan.io/result/88ce6b6d-d65e-45b9-becb-f4ba0d753fd3/
btc-bonus-live2-binance.com
13pz3N4ug6M3VZ4gKUnPjNpPJFyXEeniPd
https://urlscan.io/result/55358de0-1bcc-4434-945a-c860f915730e/
monero-my.com
Fake MyMonero -
https://twitter.com/jmoconnor415/status/1036085542989967360
https://urlscan.io/result/68e782da-c8e0-4b2f-97c8-8245263f42e8/
eth4123left.pw
https://urlscan.io/result/975c5969-82d4-491c-bb2b-01d4eb4c30e1/ …
=> pumpkinpro.io

_data/scams.yaml
wetimox.blogspot.com 
https://urlscan.io/result/5048eb19-f5d5-4810-be92-ae4c13eb09d5/
buterinpromo.cn
https://urlscan.io/result/c63541fb-1b97-4b10-9c68-47f5f7a72bae/
address: 0x0aB4Fc631d194BB135dc7a3f99580Cf7df3eEAE0
airdrop-portal.com
https://urlscan.io/result/ad9b385b-c58c-465a-98d9-0b9a2960929b/
https://urlscan.io/result/cbdc4e0e-fca2-41a7-bcfd-2b43d1f7a702/
address: 0x2F0D741580d9dBC27E51e5DBe83f5797f868C2e0
address: 0xcd39300c31776AB6303fC64B930c1109c008eA0A
eth24win.co.nf
https://urlscan.io/result/9b09843f-2f82-48cf-999b-b7a2d7218a58/
address: 0x8cAE2a8734d781a8ceC7E2F514DA6f5072F7a6e0
give-eth.biz …
=> wetimox.blogspot.com + more

_data/scams.yaml
Fake Tezbox phishing for keys
https://urlscan.io/result/8150c8cf-6a39-46ad-8aae-50f52f5e187f
https://urlscan.io/result/37a2668e-1cd8-4c40-9e22-0853ec60ba20
=> tezbox.net

_data/scams.yaml
https://urlscan.io/result/877f19a5-56b7-404b-8f4d-93d0a0f00312/
send.ethparty.us
https://urlscan.io/result/4b143611-9823-4cb6-bc93-0dd06e428cfd/
address: 0x8Bb8a410e770a693C169a6b2B5286297d9eccbeD
ethparty.us
https://urlscan.io/result/10f6b73e-93bf-4adb-a251-3a4c14bc0aa1
address: 0xF97Cb2b86deE9C33c7624Fd7412889543cCA7F5A
ethaway.000webhostapp.com
https://urlscan.io/result/7b562473-53b4-46b5-b4ce-3e107837b3f8/
address: 0x44610ceE8C56D34e80468243065e3a319250e32a
blognance.blogspot.com
https://urlscan.io/result/aabcc513-6e01-4462-9a71-083a2da63f8e/
september-promo.com …
=> axibovs.blogspot.com

_data/scams.yaml
https://urlscan.io/result/a3e8aa00-5421-4ae1-b51e-9cb5058b75f7/
https://urlscan.io/result/b29d0d62-4a04-44de-af6d-705b869cc1d3/
address: 0x0aB4Fc631d194BB135dc7a3f99580Cf7df3eEAE0
=> ethmixdrop.pro

_data/scams.yaml
Ponzi scheme
https://urlscan.io/result/d4eb6998-39e8-40e8-8334-bbfe7a5efe77
address: 0xAF6240821a0CBb6e4B65E9fEEb4F79f737BbbD18
ethbonus.live
https://urlscan.io/result/9c7187eb-ca8c-46fc-9ccb-54ab276348c5/
address: 0xA592F4891fF2D233C93B641Af65069Ed663295bC
ethactive.online
https://urlscan.io/result/b618ba68-0ff4-40b5-a25a-b7a83f8a3f75/
address: 0xc8F1Ec8fA60AB597B8Bc74568c22AA86F3D5F4fb
eth-take.com
https://urlscan.io/result/881daea9-bbda-45cb-86f8-e4cd1c7d6704/
address: 0x784790ffba7136Cfb2DD8F6671DD7626a6C5F3e4
crypto-giveaway.xyz
https://urlscan.io/result/49dbbece-5407-4173-afda-b8eb600637e9/
address: 0x1b858871c8FdC0C782F60B350Eecc58D82c216c1
ether-prize.com …
=> panemicav2.rf.gd + more

_data/scams.yaml
https://urlscan.io/result/0dd525be-bfcc-459e-80bb-835d3890daaa/
address: 0x964A7C09E3dB065ece947FdB7f90bf0068a6F98e
claim.safepaycoins.com
https://urlscan.io/result/10ed968e-5e42-4e5c-9aca-3cb64334e5ea/
address: 0x4349B24Ee0Bb23c51569E63B2c1d457Dd75464D7
airdrop-exchange.com
https://urlscan.io/result/1a4394c5-f1d7-42fe-b267-f5668afbda11/
address: 0xcd39300c31776AB6303fC64B930c1109c008eA0A
secure.eth-claim.online
https://urlscan.io/result/29f2e1d3-01f6-4287-a833-454a861656a3/
address: 0x7069BB601755F69c81560192ecC2a62Fed1c20B5
medium.in.net
Trust trading scam site. Directing users to kutt.it/KjHyKL ->
giveaways24.info
https://urlscan.io/result/48bbd55a-f1b9-4927-8013-a35b46c6aec8/#summary …
=> medium-io.site

_data/scams.yaml
ethereum4ever.com
Ponzi scheme
https://urlscan.io/result/cc0a55e1-6092-45ec-b26c-322edb318ae4/
https://urlscan.io/result/b1e0dd89-06d7-457a-bad6-110948341646/
address: 0x2B22b2c65B185182786F087c1A0035B5Ed76bbb7
contagion.cf
Ponzi scheme
https://urlscan.io/result/cd557b42-8f6e-42df-9576-64b75f30c68e/
address: 0xc601f6938c75c4ca03eaad570701d86e607771db 
333eth.io
Ponzi scheme
https://urlscan.io/result/230530fc-36da-486d-8f03-b221354d2a8f/
address: 0x311f71389e3DE68f7B2097Ad02c6aD7B2dDE4C71
september-bonus.com
https://urlscan.io/result/b8679990-5004-4b76-a955-f972a7080f6b/
https://urlscan.io/result/35a0b686-b941-4454-a406-21078fb169aa/
https://urlscan.io/result/284e54b4-670b-4e27-81b4-b86c137b1aa3/
address: 0xc2c43555aC0FB6fe3A2c9CB9B5b61BFe4f726F9f
address: …
=>  elctrurn.org + more

_data/scams.yaml
Fake StellarTerm phishing for keys with POST login.php
https://urlscan.io/result/52dd22ed-3b1e-4769-b676-1e9d153e7e30/
mixprize.cn
https://urlscan.io/result/6d0904de-96aa-4d9f-acc4-7b80059df0ee/
address: 0x3422258C54c75B879ec7B2B1050186A2c0EB0ebD
medium-secure.com
https://urlscan.io/result/1fc9cfdf-2772-49bb-9f6e-42b52847ca74/
address: 0x058E49378461C239DAE065114cD9fA1c0dBC25C1
ginexis.blogspot.com
https://urlscan.io/result/d1d6ad65-a9e4-4b83-89c2-da44ae96c5f7/
giftsatoshi.space
https://urlscan.io/result/c31c3f04-83d8-47d2-a918-d57ffe2322be/
address: 0x8e85939D6C149a6d2a173b5425306797e6934075
=> bonus.client-stellarterm.com

_data/scams.yaml
https://urlscan.io/result/e42a5bff-9cba-42f3-92d8-672547a7a6d1/
https://urlscan.io/result/89783a08-1867-4ba4-891d-32c68c38480f/
address: 0x976B3B64A42cf04d735583004c298aA4E62A913c
bnbdexethcampaign.com
https://urlscan.io/result/a5fadcd5-c340-468c-92bc-db7e66e9c134/
https://urlscan.io/result/39d295f4-55d2-410e-b9e1-7338c2d72d0d/
address: 0x976B3B64A42cf04d735583004c298aA4E62A913c
bnbexchangeethspecialcampaign.com
https://urlscan.io/result/ca9ee292-74ff-41ff-9720-fdbaccbfea8b/
https://urlscan.io/result/492dbd84-9053-4fdf-8cde-fe4905565aa9
address: 0x976B3B64A42cf04d735583004c298aA4E62A913c
bnbexchangespecialethcampaign.com
https://urlscan.io/result/93a4213d-67d6-41d2-a82e-e38cb46d833b/ …
=> bnbethspecialcampaigns.com + more

_data/scams.yaml
https://urlscan.io/result/6ae4cb32-e700-400e-a826-30333f9231a5/
https://urlscan.io/result/a01ff437-e293-40a5-83e8-d593115365d8/
airdrops-exchange.com
https://urlscan.io/result/29cc656d-267a-4013-8d9b-349a4b500d39/
address: 0xFD8999B60a72c51Ea892db66F5ef0C58F2ecD6d3
buterindrop.eu
https://urlscan.io/result/65aab62e-1554-403a-9119-d405d18d1d09/
address: 0x3422258C54c75B879ec7B2B1050186A2c0EB0ebD
campaign.etheraction.in
https://urlscan.io/result/d74eeb74-dba4-4f06-8edb-7a6bc59a957a/
https://urlscan.io/result/eca91222-3966-4d75-81bc-e2353b2584e7/
address: 0xB9D957ed3c592Cea30F715B80f08A86614648295
address: 0x6ecce18C9C35167E174033d9f9F6e4B356Cd2B45
etheraction.in …
=> message.xn--mytherwalet-3qb10c.com

_data/scams.yaml
coinbasesecuritytokens.com
Suspicious Coinbase domain
https://urlscan.io/result/13575392-6133-4d06-9d3a-662411a3b3a6/
coinbasepay.info
Ponzi scheme. Wrong company number 10829913
https://urlscan.io/result/7a23c64a-e4fd-4a0e-b45e-e257e5663022/
hitbtcrecovery.com
Suspicious hitbtc domain
https://urlscan.io/result/20f3f032-c754-4ce8-9c76-813e50f50a29/
hitbtc-ads.com
Suspicious hitbtc domain
https://urlscan.io/result/479ca000-aa45-49a5-9117-213f07c16cbb/
hitbtc-adv.com
Suspicious hitbtc domain
https://urlscan.io/result/da5b52a3-a35b-4363-a41f-c59192d251fb/
gemini-wallet.com
Suspicious Gemini domain
https://urlscan.io/result/738e1c5e-c4f5-47e6-a858-16c1a08d2f7f/
gemini2fa.com
Suspicious Gemini domain
https://urlscan.io/result/3eda48f8-f0a1-4c0a-836c-0330d60fb73f/
geminiaccount.com
Suspicious …
=> coinbasesecuritytokens.com + more

_data/scams.yaml
Ponzi scheme - unverified contract - 'This is a game, not an investment.
Your profit is funded by new players.'
https://urlscan.io/result/4296df6b-15af-4248-85ed-60df6ef0aed2
https://urlscan.io/result/c3d96e64-5a6a-4c60-b2d5-5f03dd7462fa
address: 0xFaD05ee13c8e0Ec94E5eE9Dc056DC451B2Ad6b1d
safe.minedtokens.com
https://urlscan.io/result/d5888947-ae2d-41cd-907a-44e6d784b08a/
https://urlscan.io/result/e5528161-9c0a-4564-bba9-8e0a7ed0a6d9/
address: 0xF9B14517E630aacc5C9c9429cBE969aa61B3Adc9
address: 0x8Bfe1C609CdF6E7e43C5CD8910Bd566a2C142688
smartsend-5000.website
https://urlscan.io/result/7cd1623f-92e5-40c4-ab08-33be9629ae92/
address: 0x566e797616526498bc274597805F0d4a2682a6a6
airdropeth.tech …
=> earn.dailydivs.com + more

_data/scams.yaml
Fake Bitcoin mixer - https://bitcointalk.org/index.php?topic=5025688.0
https://urlscan.io/result/fd39170e-2b79-42e5-9f01-5b92e2f084fd/
safe.paynowcoins.com
https://urlscan.io/result/44657c4b-d9e2-4679-8d48-9c7dd36233c5/
address: 0x35bF085175dc3e3f750BFfA53711FB4ACDBF2aed
paynowcoins.com
https://urlscan.io/result/5324b938-981c-4a6c-910e-11aecfc15287
https://urlscan.io/result/2de23606-562f-4d82-bc0b-335066587e48/
address: 0x35bF085175dc3e3f750BFfA53711FB4ACDBF2aed
go1.giftether.top
https://urlscan.io/result/415aea36-68b0-4c2f-b852-59eec8d3dd9a/
https://urlscan.io/result/7b7c3339-7fc7-4a4f-86c2-4a618f4e6a7f/
https://urlscan.io/result/46c3e89a-02ab-4713-9c28-0add97bf305d/
address: …
=> bitblender.me + more

_data/scams.yaml
idex-market.exchange
Fake Idex phishing for keys
https://urlscan.io/result/52917934-1864-4615-a088-9132aa61336d/
https://urlscan.io/result/0e2156cb-d86e-4b24-a931-731b768d43e8/
protect.minedcoins.online
https://urlscan.io/result/8ec2655a-5eef-454f-bebb-ff22099e9bc0/
address: 0x9EDe16Fd45A94c5bE23a6aB09651b7E26Ce171C3
minedcoins.online
https://urlscan.io/result/27d250f5-1a79-423b-9ae7-9bf8838d1fea
https://urlscan.io/result/eb981f49-f571-4bf7-bf0d-b34980a060c5
address: 0x2aA40BB0993b5a2d00DA4c1CD9555c626974C1a9
go2.giftether.top
https://urlscan.io/result/ffec017c-cb93-46b3-9cf0-cf5bd07a18d5/
address: 0xc2d251394A1211B9a87ac8E0B42F431138a2D465
contract-verify.space …
=> idex-market.exchange + more

_data/scams.yaml
https://urlscan.io/result/592b615c-eac7-41d2-9622-27dfff03c5df/
address: 0x504c839dB36171D13f1B78Ab323CF3eA084995FA
crypto-win.club
https://urlscan.io/result/337e879f-8891-4515-b930-e9337cf924ee/
https://urlscan.io/result/bbe46dd3-5dd9-459f-825a-bf3d9d7ccc65/
address: 0x5c5452D1a4FB7175812de3b4a4F1c34D5Bc5a261
crypto-medium.com
https://urlscan.io/result/f639b597-ca74-4cc9-8a21-38a6b422cbe4/
https://urlscan.io/result/9b94ac59-8337-4891-83d1-ebe6fa1c41dd/
address: 0x520C7DD3d265B6eDd88C623D4C9EddAcBf082eA6
getairdrop.eu
https://urlscan.io/result/26af60e1-11a4-41c7-b203-65a659386a0d/
address: 0x362f1d7C705f0d8f38786b4D6eFd6eCC54199be6
sending-smartcontract.website …
=> cryptoeth.live + more

_data/scams.yaml
safe.geteasycrypto.com
3LxsigmQyvJ3LU3UBwY9s4QWqoF6jBYA82
https://urlscan.io/result/3c24dd44-02ea-4089-8c87-550a205032a5/
address: 0x7B31c59e00393f56fEa6884bB24166b24B99C62A
geteasycrypto.com
https://urlscan.io/result/6ad5a29b-cad2-4294-8733-312314cb7900/
https://urlscan.io/result/0a424d12-94d6-44eb-94d2-fc92c2cf2f09/
address: 0x7B31c59e00393f56fEa6884bB24166b24B99C62A
lixozy.blogspot.com
https://urlscan.io/result/2ad1fc81-3625-44ed-b38b-164f96f6a0e5/
eloncrypto.info
https://urlscan.io/result/9cc64611-3a24-4cb0-8f0a-24566dc7d931/
address: 0x7Fdfaa3154D3Cb82E90f5fDE8c52a95D66211705
mediumcoinbase.tumblr.com …
=> safe.geteasycrypto.com + more

_data/scams.yaml
tesla-giveaways.space
https://urlscan.io/result/9642888a-7577-4b96-99fe-7da7fb620049/
https://urlscan.io/result/85cc3e50-4c9e-4094-b3bc-4a5505f57799/
address: 0x98fd213B5b0105Bb50A980D07Ac6Fbeee86e4535
top-ethereum.info
https://urlscan.io/result/3ca17ee2-7f69-456b-b5a2-57fc696e2e96/
address: 0x684eDE6645f1b71D77E0AEAC519114EE8Be3c410
mnaxy.blogspot.com
https://urlscan.io/result/0f593221-397a-4d52-ba3b-7ac774d2ba2c/
go3.giftether.top
https://urlscan.io/result/5ffd6c7f-c5fa-4740-9681-759563cb8436/
https://urlscan.io/result/32b610fd-9562-4408-a2f5-4a475f2fc357/
address: 0xcd25243c156BB49A1c0AEA4EDa701649621D26E4
address: …
=>  tesla-giveaways.space + more

_data/scams.yaml
https://urlscan.io/result/720fb9ff-9e15-40d3-a235-ae49e5c56539/
https://urlscan.io/result/be5e36eb-fcbd-4976-8d87-ee497ea1ef02/
address: 0xb119eA0fA97C926DD55ff11CB90a1A0d578dC57E
cryptobtc.club
1NZrzg9CPa5hMQkJBYrY9v6ReitdNgSFJE
https://urlscan.io/result/11819e76-e862-4bf7-8af6-75bcbf1f67d8
idex-market.pro
https://urlscan.io/result/eafe86e3-7a39-42e6-8517-3f280b76776b/
https://urlscan.io/result/15278436-5a84-4cc5-9155-8a1fa2d416cb/
=> bnb-ethcampaign.com + more

_data/scams.yaml
infinitimoney.com
Ponzi scheme
https://urlscan.io/result/11cfa8a5-93f6-41be-a9dc-0e47908704e1
https://urlscan.io/result/b7609c85-f635-4700-ad17-c16970ff1736
address: 0x536a6Ba0D913d5D6A4ce2C6eB7eD0de3c0f0b89E
smart-gift.website
https://urlscan.io/result/21ac8750-febc-4699-85ea-27a528d92767/
address: 0x4CF5dB8f049d6Ca78a8a41e1Ab2c04b90BAE5FC1
coinshare.xyz
https://urlscan.io/result/aae91e93-750f-4488-8f08-8b3049b31e76/
https://urlscan.io/result/3b412525-d8f9-4d6c-ae90-38653ddb6a86
address: 0x0eEA73Bc675d3012d3d602bd03cbF51A4B64EAeE
buterintoday.eu
https://urlscan.io/result/c242af45-fef8-4f8c-a1a6-387261528059/
address: 0x362f1d7C705f0d8f38786b4D6eFd6eCC54199be6
tronics.tech …
=> infinitimoney.com + more

_data/scams.yaml
https://urlscan.io/result/bad0ca02-249c-4915-afd1-c46846da09eb/
address: 0x5D445ce69fF9d8096D57444906c193F0eE577BF2
payetherer20.000webhostapp.com
https://urlscan.io/result/138c80bc-f828-460a-84d1-c20b3d4a971d/
address: 0xB3ec0CaD78b4dDD0bfdA3edfD517DfC185ba8E34
vggs.info
https://urlscan.io/result/635619d1-dc1d-481d-bbca-26ea1cb79df7/
address: 0x0167409E6106EC3E3f05A09FCf04606918d21aD5
go4.giftether.top
https://urlscan.io/result/77d13110-6aa8-4c91-aff2-35bc8852f465/
https://urlscan.io/result/e7e5c1b3-b48f-4b95-bedf-a6d624513f3e/
address: 0x58b62D0e9Cf118c6EeBE4Ce7e9680a8Ec533c094
address: 0xd03e202205168b8d0eF6c7fa9c27Cb71b42f9E06
etherium.org.payment.7d16-srv.site …
=> topcryptogift.org + more

_data/scams.yaml
https://urlscan.io/result/039b6587-8161-43da-aa5e-3637373593b2/
https://urlscan.io/result/7e2c749f-4290-462a-90f7-6f49b1a92461/
address: 0xf94b8e0ceba6dcd1b888fe02141dd9d0b8e67715
=> gramnetwork.net

_data/legit_urls.yaml, update.js
* Added logic to check the whitelist before a domain is added to a blacklist.
* This occurs because we have, for example, Twitter accounts blacklisted
Fixes https://github.com/MrLuit/EtherScamDB/issues/1181
Fixes https://github.com/MrLuit/EtherScamDB/issues/1296
=> [ HOTFIX #1296 ] Fixes bug that caused legit domains to be on the blacklist api

_data/scams.yaml
myetherwallet-knc.space
https://urlscan.io/result/fdfb8200-eff7-4180-9b00-f7f0d0ad32b7/
=> myetherwallet-knc.space

_data/scams.yaml
i-dex.market
Fake Idex market phishing for keys with POST /log.php
https://urlscan.io/result/b08684d2-a7a6-480a-b4aa-7dfc588a6c1b/
bittcrex.com
Fake Kraken exchange phishing for logins
https://urlscan.io/result/388f4c47-4fc5-487c-90e6-1010b956dd9b/
https://urlscan.io/result/9fb20acc-6cfa-48d1-be52-d67704f5d220/
myetherwallet-knt.space
https://urlscan.io/result/56f0994b-6797-42fe-977c-00b1fddddb3e/
=> i-dex.market + more

_data/scams.yaml
bcrypto.club
14XSy5CK6yGz1UVAU9gGbqSowdUtaNF9gB
https://urlscan.io/result/c91d2d60-e5bb-4544-9c17-9d9dd2c88f71
address: 0x474057ADF42f9F955e86aa1142740f9d7763e41E
myctherwallet.net
https://urlscan.io/result/4ce571bc-2389-439b-9e9e-8f12f832ee6c/
go5.giftether.top
https://urlscan.io/result/625355f1-de39-49d2-abc5-f99057f58eab/
address: 0xf4dDDAf909BFB371ACAf2b7eD6a3BA0d70BF4843
etherium.org.payment.7d17-srv.site
https://phishcheck.me/114279/details
https://urlscan.io/result/8b0d7d44-29a5-4f63-8380-fa85e16321da/
address: 0x2Cf904052D9FF15C18D6061E569B09925A6F0aC0
address: 0x960Cf466795efc2D47CD37Ad01Bb43BfAaAE3618
bigbonus.eu …
=> bcrypto.club + more

_data/scams.yaml
forkdeilta.app
Fake ForkDelta phishing for keys with POST /login.php
https://urlscan.io/result/1fec5228-d7e0-47fd-984e-1b379bac1990/
verify.xn--mytherwalet-3qb10c.com
Fake MyEtherWallet -
https://twitter.com/jmoconnor415/status/1043944124112502784
https://urlscan.io/result/b96088b3-ce5c-40b0-a829-1a06da404e52/
https://urlscan.io/result/36d75666-ed04-4ce5-a0d5-5d83a3a85f94/
getfreeethhh.blogspot.com
Trust trading scam site. Linking users to getyoureth.network
https://urlscan.io/result/a6292c61-85e7-49d7-a8ac-147adc578c4d/
address: 0x88997942776A5de1f1A89d86A46BFF0c9F8EDb01
getfreebitcoin.network
1FVwwp98FBKJV8MzSFNN38afSHqiYrxXjs
https://urlscan.io/result/32761d9e-62ee-4749-91cb-e39c32f8309c/
coinaction.xyz …
=> forkdeilta.app + more

_data/scams.yaml
xn--hibtc-leb.com
Fake HitBTC site phishing for logins
https://urlscan.io/result/0d96ce90-d98d-45be-b778-47d8b3f88d3c/
https://urlscan.io/result/6b36c96f-3bdf-4b0a-a8b1-56fa05d89cdc
hitbtc-eu.com
Suspicious HitBTC domain - nothing deployed yet
https://urlscan.io/result/d1ecb433-6316-437b-8667-4075d93f55b1/
hitbtc.cam
Suspicious HitBTC domain - kit not deployed yet
https://urlscan.io/result/ba69b284-0423-47c8-a185-96b6dd56c87a/
get-5k-promo.website
https://urlscan.io/result/81212193-2547-4b17-b351-fdcbfa6b26be/
address: 0xfCF10F54105223dfCD8edCe0C62352A059ce1E19
freshbonus.eu
https://urlscan.io/result/2bcb2983-3fb9-46e9-a5c2-de0c071a597c/
https://urlscan.io/result/af85d031-4a26-49d8-9b0c-d03cec8b321e/ …
=> xn--hibtc-leb.com + more

_data/scams.yaml
Ponzi scheme - closed contract. Fork of 12hourtrains which is a fork of
dailyroi.fun - https://twitter.com/sniko_/status/1044575038232498176
https://urlscan.io/result/936b39f5-8e21-4ad5-bb6d-623ea8a811c4/
address: 0x22cff91f77a2ed675f3ab4aee16e15b27f6f275c
etherium.org.payment.7d19-srv.site
https://urlscan.io/result/42c43753-5a1d-4ce7-bcbb-057c39b0c66d/
address: 0x4ff4c15af13F6D4950448104D9B97387A03dA6f9
atmbtc.biz
Scam investment site. See
https://twitter.com/sniko_/status/1044666608449441792
https://urlscan.io/result/a75e1944-ea92-49e1-b0dc-01ac3de6cb80/
https://urlscan.io/result/2f88571c-c043-4a9d-a3d2-584a559d981e
best-gift.website
https://urlscan.io/result/e1a28a19-99a5-4bbd-a21a-b91543c99302/
address: …
=> doubleroi.surge.sh

_data/scams.yaml
https://urlscan.io/result/a852572e-682a-4098-a7c3-95054eea162d/
send-status.info
Fake EtherDelta phishing for keys with POST /callback.php
https://urlscan.io/result/88c965e5-f68c-4dec-a770-d1a9169b6be8
paxful.com.pl
Fake Paxful exchange phishing for logins with POST ./temp.php
https://urlscan.io/result/59fda966-f84c-4f1c-b689-3076c7b7084e/
myetherwallet-id.space
https://urlscan.io/result/e259c810-4c57-445c-acdf-a06235cf2884/
eth-databasecontract.website
https://urlscan.io/result/f24bc62a-9635-4285-8d05-c47b49e29703/
address: 0xc57597f5fC469386AB8C53740b5Cf6c4A78e8EeC
geteos.eu
Fake EOS site phishing for keys with POST /
https://urlscan.io/result/f5b53d6d-4e63-495b-8213-df2531a499a6/
--- …
=> myetnerwallet.com.send-status.info

_data/scams.yaml
https://urlscan.io/result/263b7cad-6d4f-469b-93d1-a41c251438fc/
giftethnow.website
https://urlscan.io/result/6c9a7294-f1a0-4360-b05b-43eb797bdc7a/
address: 0xc57597f5fC469386AB8C53740b5Cf6c4A78e8EeC
etherium.org.payment.7t20-srv.site
https://urlscan.io/result/1d558e94-7aa8-4fbe-9655-5695c06e9a19/
address:0x75B60BA032cf8eE0b4BBd78bfbD7D99caF70A176
x-gives.blogspot.com
Trust trading scam site. Tron address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
https://urlscan.io/result/6ec9ff11-d50f-438c-9c79-d8aee4b9f3e3/
https://urlscan.io/result/544fdd78-35d2-419e-a437-8edaf8a1fdec/
btcgive.kissr.com
Trust trading scam site. bitcoin address: …
=> myetherwallet.auth.slgnmsg.info

_data/scams.yaml
getyourcoins.org
17VZwSSY5dBCfmSdF5pTRQyS44SPq6icug
https://urlscan.io/result/7a6914c5-9baf-4a55-9fd7-0752f735030d/
https://urlscan.io/result/c57cd68b-adba-4107-aae1-c7363d72e845/
https://urlscan.io/result/85123e38-9e22-4d40-83e4-ba68e1ea67a2/
address: 0x19B619237de51AF8e1CBd989Cd4E01E7299df4De
binance-giveaway.webcindario.com
https://urlscan.io/result/939e0b87-c840-4380-9804-bb9dbe2107e7/
address: 0x4D6102BcBe452015a7D656a97dE3F30f10054Ceb
cryptopromo.kissr.com
Trust trading scam site. Linking users to ethgive.kissr.com and
btcgive.kissr.com
https://urlscan.io/result/ba416d4d-0da9-4ae6-8cc6-b009e83d4692/
address: 0xCae453Eb95B584331A8A5945D8138ceEED9d5Af6
gift-today.website …
=> getyourcoins.org + more

_data/scams.yaml
Trust trading scam site. Tron address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
https://urlscan.io/result/09c8e0b9-0cd0-438c-992c-3cf087be2784/
airdrop-event.com
39PnC2ePuRPPuiqSxGHSiDqmhhWtTtjsFK
https://urlscan.io/result/2c726dd0-0203-4ca8-ba98-7f36a5938144/
https://urlscan.io/result/b42d58a8-8736-44f2-b877-c8a1dca2b00f/
address: 0xcd39300c31776AB6303fC64B930c1109c008eA0A
myetherwallet-shl.space
Fake MyEtherWallet phishing for keys with POST /app/keys.php
https://urlscan.io/result/a24a99ee-756a-4b15-b534-3d3e95203935/
https://urlscan.io/result/81881af6-c27d-4a68-9580-82975b54eba9/
get.fastcryptogift.com
https://urlscan.io/result/685495a8-ceeb-4cf3-87b3-cd918061da71/
https://urlscan.io/result/8d0b9260-b448-4da5-b867-f970b9144cdb/ …
=> sgivex.blogspot.com

_data/scams.yaml
santechstroywalker.site
Fake Idex phishing for keys with POST /furia.php
https://urlscan.io/result/251781f9-7831-43f6-b280-bbda759de241/
https://urlscan.io/result/53046820-bdf4-4cb2-91b2-d8c3a136b51b/
firecrypto.info
Fake exchange asking for 0.01BTC deposit to verify. See full scam at
https://redd.it/9ks9ux. Bitcoin address:
1PTAaVk6onxkgU1ZXxMfcPG9txgQ6rYVef
https://urlscan.io/result/0a61a824-2dd8-433c-b75c-3c78e9d336f8
address: 0x1E711A766cD4EC07C590EeF54A112190B4826b4e
cew.safewallet.replayattack.us
Fake MyEtherWallet/ClassicEtherWallet
https://urlscan.io/result/0158e0eb-40cf-42d8-af6b-7c03f6054e86/
medium.com.7t23-srv.site
Trust trading scam site. Linking users to
www.etherium.org.payment.7t23-srv.site/promo/10000-eth-giveaway/ …
=> santechstroywalker.site + more

_data/scams.yaml
send-gift.website
https://urlscan.io/result/e3cefa35-81c7-4a95-9ac1-a0501efb995f/
address: 0xd9a1968Aec13220e91A31D602f2519262B38dD3A
etherium.org.payment.7t24-srv.site
https://urlscan.io/result/03ce9812-9595-4b28-b4c1-9a7f48a9d961/
address: 0xff0e20E3A7575D823302bbB27E233c23f2c3070b
medium.com.7t24-srv.site
Trust trading scam site. Linking users to
etherium.org.payment.7t24-srv.site
https://urlscan.io/result/c07e0215-137a-4b4a-8bc7-b7faeba5cf22
address: 0xff0e20E3A7575D823302bbB27E233c23f2c3070b
airdrops.technology
https://urlscan.io/result/f86028e9-5876-46b9-8e97-d44f92b472f6
address: 0xB1843d1Eb962dA7760A80fC91B442491cf437492
myetherwallet-cpt.space …
=> send-gift.website + more

_data/scams.yaml
binance.com6537261.ml
Fake Binance phishing for logins with POST /function.php
https://urlscan.io/result/5713f0c5-594f-4cab-bef2-bcbbeac1aed9/
binance.com762381.cf
Fake Binance phishing for logins with POST /function.php
https://urlscan.io/result/5fe05bc5-7b90-4752-b7f6-15d19d0eec8e/
vitalik-campaign.xyz
1DzUBk8PDjQKdBgo5YG4qzk6icCH3GaPxJ
https://urlscan.io/result/539137c8-fdda-429f-8e4a-547ffb5db6c5/
https://urlscan.io/result/90c30e66-16c7-44cc-917c-0529f73ff780/
address: 0xe45AA28d270A049B489CcbB156C2e2c3De0d571d
getgift.tech
13Lo1Pjh8DKpq9Fvf5aNb1hfnHVDxQBoqE 19w6pZoUKTKzEtFZQJNnV6RjztPbFU8xSV
https://urlscan.io/result/45d6335f-6380-44fd-8506-2df658e6667d/ …
=> binance.com6537261.ml + more

_data/scams.yaml
paxful.com-bitcoin-wallet-trade-escrow.paxfulsecure.com
Fake Paxful phishing for logins with POST /login.php
https://urlscan.io/result/b7ea3da1-5e07-490c-a412-98d2b603e38f/
mnyicthervallict.com
Fake MyEtherWallet phishing for keys with POST /log.php
https://urlscan.io/result/7ab5af27-0cbd-4bff-9eaf-4098a625bb6a/
mnyidthewalliot.com
Fake MyEtherWallet phishing for keys with POST /log.php
https://urlscan.io/result/a854ec38-56c0-4d4c-880c-19eff8af82e1/
binchaincampaign.com
36CfVjvns6ce1ijpdKB8YKeBVzVpxCfRrH
https://urlscan.io/result/a140f939-4dac-4f05-8773-ecac1cb3da6d/
https://urlscan.io/result/eb9ac249-fe28-4683-8bd5-2b48897e0fc3/
binachaincompetition.com
36CfVjvns6ce1ijpdKB8YKeBVzVpxCfRrH …
=> paxful.com-bitcoin-wallet-trade-escrow.paxfulsecure.com + more

_data/scams.yaml
Fake Binance phishing for logins with POST /trox_admin/Api/login_user
https://urlscan.io/result/4603a298-c38f-4c69-9c8a-050a5da79869
https://urlscan.io/result/bd343d58-6428-4542-ac81-0afe47eaa40f/
https://urlscan.io/result/a89f21a4-de92-4982-bbe6-e51b1a14bbde/
https://urlscan.io/result/8be7bdab-fb10-4305-ac16-39beaeb441b9/
https://urlscan.io/result/e2efe63c-375a-4c4b-a289-ba461803ce2e/
idex.auroradapp.market
Fake Idex phishing for logins with POST /log.php
https://urlscan.io/result/e03356a8-9e86-4957-b4f1-0e57343192f4/
https://urlscan.io/result/8bf66d13-2e7a-4809-821a-92005f33597b/
=> xn--biinanc-z8a.com + idex.auroradapp.market

_data/scams.yaml
Fake MyEtherWallet phishing for keys with POST /api.etherscan.io.php
https://urlscan.io/result/c819d36f-261c-4ebd-8c31-5afc11e547a5/
hitloek.info
Fake HitBTC phishing for logins with POST /controller/email.php (also
hosting a Gmail phishing kit on www.hitloek.info/gmail)
https://urlscan.io/result/95f3e526-74e3-4466-b11d-a2a9e125d319/
https://urlscan.io/result/f2a640ce-688b-4537-a0c6-910fca83e024/
https://urlscan.io/result/c32f96e6-0bf0-487d-b03c-93c0ac42c7f6/
https://urlscan.io/result/66e1d3b1-1b6f-4b7b-b657-efa929f051d8/
ethiz.blogspot.com
https://urlscan.io/result/95a33411-7b4a-495a-b8df-b1e231bc7a1d/
gi-ve.blogspot.com
Trust trading scam site. Litecoin address:
LaXXasBpGtqnzi7AMywnujYeD3BFD1NFv2 …
=> xn--mythwallet-n7ac.com

_data/scams.yaml
electrun.org
Stealing phrases with POST /check.php
https://urlscan.io/result/4d282fc0-6beb-4d2f-aab0-d21e01efc400
b-crypto.me
1AZXBeoGtCnK5jVHaDBoNphsND2dLWtRE2
https://urlscan.io/result/390bc165-05e9-4873-96fa-ef24c8f5db86/
arbitragecoins.com
Scam bot - steals deposits - many many online reports
https://urlscan.io/result/0c42ceaf-833c-4b7e-b328-2c448bcc4303/
address: 0x3258674d5eb5cfca42c18585b95fff50e098ebd4
apexone.online
Clone of apexone.io
https://urlscan.io/result/1feff908-d6d2-439d-8d42-eac0e7236e58/
https://urlscan.io/result/afb0eb6a-a522-4d77-b3f4-b0937000762b/
address: 0x23f1909f7a65cba4d2a4a42ee1ba7d9772c3ba93
=> electrun.org + more

_data/scams.yaml
bittrex-ydd.com
Suspicious Bittrex domain
https://urlscan.io/result/917fc25e-a76e-41a7-bff4-00c31c7a63de/
bittrex-web.com
Suspicious Bittrex domain
https://urlscan.io/result/5a13c2c0-9b1b-45db-bc09-72fbeb5f7580/
hitbtc.website
Suspicious HitBTC domain
https://urlscan.io/result/fbcce038-65e9-476f-a5d7-9c76fdeea134/
scris.club
Fake Idex phishing for secrets with POST /furia.php
https://urlscan.io/result/fc8ee675-5a0a-4161-a14a-0ca574811c11/
=> bittrex-ydd.com

_data/scams.yaml
Suspicious IDEX market domain
https://urlscan.io/result/6bcec480-a253-44c0-ad7c-6703abafa2da/
polonniex.online
Fake Poloniex phishing for logins with POST /login.php
https://urlscan.io/result/20ad0cce-79ca-4ea5-a3ed-dbf421e85a68/
niceihash.com
Fake Nicehash domain
https://urlscan.io/result/84d55dcf-7bb0-401c-97ec-34639aab802d/
=> xn--dex-uma.market

_data/scams.yaml
Fake MyEtherWallet phishing for keys with POST /store.php
https://urlscan.io/result/e643d75e-3a61-442e-8769-44591f09c91d/
coinsender.tech
13v7acoch2p4otKN8cpvp3n2LHxbSB1XdE
https://urlscan.io/result/366f12c4-0c59-4f5e-9d04-6cd2f2612b44/
https://urlscan.io/result/5c651b82-1942-4cca-82eb-6deaf1476ddf/
https://urlscan.io/result/1980b69b-59d9-452c-94bc-d7d7e2514a1b/
address: 0xC0EcBcd3a5977921FaFEcffdf96b4Bcae1573B99
myetherwallet.byethost11.com
https://urlscan.io/result/f81448e6-905a-488b-972c-01fc3a1d8c6a
coindesk-login.com
Fake Coindesk site
https://urlscan.io/result/bd4cb715-7fc1-4ad7-922f-f0a0a484a2ac/
=> myetherwallet.notextbook.net

_data/scams.yaml
poloniex.com135i478847258477.ml
Suspicious Poloniex domain
https://urlscan.io/result/f54ac314-3533-4003-873d-6c89b6a0019e/
https://urlscan.io/result/208aa07d-8130-454c-b0c8-4e7224e38f31/
mnyicthervvalliet.com
Fake MyEtherWallet phishing for keys with POST /log.php
https://urlscan.io/result/cd19391d-131d-4124-98b2-13ddf1ad2837/
dexchainevent.com
3FasziSrvWpZi8Wn8atj73Jtv4ZxqNNYb6
https://urlscan.io/result/33faa49e-9c18-40a7-bac3-3fb3d2841775/
https://urlscan.io/result/56c2d9ce-f5a2-46c7-a87f-3337318307fc/
bnbethairdropp.com
3Bx287cHkqzt1uGmw71v4GuEsqHvBpANgY
https://urlscan.io/result/598ec7a0-2cda-4ffe-b8eb-afafe00d1d53/
https://urlscan.io/result/6820741c-ad4a-416a-b49d-3d01f5cf434b/
mniyehtcwallict.com …
=> poloniex.com135i478847258477.ml + more

_data/legit_urls.yaml, _data/scams.yaml
line-crypto.com
Scam exchange
https://urlscan.io/result/9698ca7d-b6a1-48a5-ae3e-91177f8e2ccd
address: 0x1E711A766cD4EC07C590EeF54A112190B4826b4e
etherdelta.icu
Fake EtherDelta phishing for keys with POST /api.php
https://urlscan.io/result/c288eecd-d902-4ae4-8ff8-fe058644439b/
xtrony.blogspot.com
Trust trading scam site. Tron address:
address:TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r
https://urlscan.io/result/96886f2c-6d2b-4bb1-9e21-e53cb460f0e2/
dexlauncch.com
https://urlscan.io/result/f6733eb0-1129-4e98-8504-3bdbc31c7f6b/
https://urlscan.io/result/944df75c-441b-47e2-8f32-3ac3419a981b/
address: 0xd22066c4e511698b626aea89cf70FbA5Fd3f37d4
account-myetherwallet.info
Fake MyEtherWallet phishing for keys with POST
eecb7fd7e1f1d74fee5ccd2.info …
=> line-crypto.com + more

_data/scams.yaml
supportbinance.890m.com 
15r1s7ggDSRKQJpCsyvPnSJzCsgcGgJcuy
https://urlscan.io/result/9d66f17d-bd8b-4640-88b6-311e9370294a/
https://urlscan.io/result/c5cf0ffd-a0d8-4471-8a72-25009aae7574/
kralken.co
Fake Kraken exchange phishing for logins with POST /login.php
https://urlscan.io/result/b3f8280b-fdeb-40ad-8aab-2d8e8403286f/
bilttrex.co
Fake Bittrex exchange phishing for logins with POST /Account/Login
https://urlscan.io/result/1c976016-4b33-4099-b7a4-b9cba34123e9/
polroneix.com
Fake Binance phishing for logins with POST /send.php (prob mixed webserver
config or loading default vhost)
https://urlscan.io/result/6fff9191-ec5f-48da-9933-8090c017d63b/
https://urlscan.io/result/3d5853e8-08a2-46e6-9bdc-b28474fc8871
bimanrce.com
Fake Binance phishing for …
=>  supportbinance.890m.com + more

_data/scams.yaml
hitbtc.pratiktlyukleme.com
Fake Hitbtc phishing for logins (and email passwords) with POST
/index--_.php
https://urlscan.io/result/e765ba95-72d8-42d7-a8d7-2ff194e3ad0b/
https://urlscan.io/result/986e280f-30c6-4911-b1c9-798c137c16fa/
https://urlscan.io/result/97f07f9c-751b-4b56-b948-34c7d832abd0/
https://urlscan.io/result/a2063477-b41e-412b-be61-c944483055e6/
https://urlscan.io/result/834c522a-83a9-4f80-a1ba-34c2bbd755a2/
https://urlscan.io/result/828ed034-50c3-4096-bc71-59863281cdce/
xn--mercaox-rrb.com
Fake Mercatox phishing for logins with POST /auth/ajax_process.php
https://urlscan.io/result/32320fc4-fb7f-4f72-b11d-affdeed9988e/
https://urlscan.io/result/16f756d9-9149-4901-9c34-74dab7332776/
xn--phld-rqa7a.com
Suspicious uphold domain …
=>  hitbtc.pratiktlyukleme.com + more

_data/scams.yaml
etherdelta.ru
Fake EtherDelta phishing for keys with POST /api.php
https://urlscan.io/result/2f84b6f1-8fd7-4a37-b59a-3c083a4723a7/
ethereumgifting.com
https://urlscan.io/result/156bcaf4-978f-4239-8d8c-a645790278d1
https://urlscan.io/result/6997849b-ead6-49ea-9426-2bb61550d868/
https://urlscan.io/result/d985fcdd-4025-4b75-9c43-af67b8e9e63f/
address: 0x1865bf39ec9712f5f3d57cf423495c318939ab3e
address: 0xd79Ab5cd842c068E4F592c18EE3FaC4E806D4C31
paxful.com.autaro.tk
Fake Paxful phishing for logins with POST /loginid.php
https://urlscan.io/result/ab3c7f2c-82fa-4abc-8692-328da7dd787a/
participate.ethereum-giveaway.net
https://urlscan.io/result/9f629ed8-e062-4473-b232-4a674e43033f/
https://urlscan.io/result/c026878a-2941-4f02-b062-800155a70da7/ …
=> etherdelta.ru

_data/scams.yaml
musk.plus
https://urlscan.io/result/23bef290-1b08-40d3-b7df-d49a76ddab80/
address: 1KAGE12gtYVfizicQSDQmnPHYfA29bu8Da
spacex.plus
https://urlscan.io/result/f2a0e033-c026-41ab-bb49-b5a3f047d167/
address: 1KAGE12gtYVfizicQSDQmnPHYfA29bu8Da
elongift.space
https://urlscan.io/result/483da8c4-e3b6-41c5-9ab2-4b4d7d2c9bfb/
https://urlscan.io/result/0d5e77c4-2080-4828-bb82-7829de42fc5c/
address: 0x548F0678ff6B82c2C97913Ef3B0F2C515ef2594c
musk.fund
https://urlscan.io/result/0be481c1-4436-4b94-9770-a93dda3b3b50/
address: 1KAGE12gtYVfizicQSDQmnPHYfA29bu8Da
=> musk.plus + more

_data/scams.yaml
xlm-wallet.com
Fake MyEtherWallet phishing for keys with POST /send.php and POST
/sign.php (lumens/claim.html)
https://urlscan.io/result/e9d7df2f-29bd-4765-aee1-5e0800405f3c/
https://urlscan.io/result/0a0ae860-02d6-487a-bcd8-41664438ff8e/
getpetrocoin.com
Fake PetroCoin crowdsale site
https://urlscan.io/result/caf41eb5-91ff-462c-b1e7-3c645e03fce4/
address: 0x02fd82cba3bae39484d5eb7f75b5f3d5f418c691
paxosbounty.com
Fake Paxos bounty program
https://urlscan.io/result/024c08f8-1463-455c-b503-82b992dfe28d/
address: 0xF31b4F7550833a746f788b36f2b292E5fA49a248
spacex.to
https://urlscan.io/result/b94ec642-db15-4ebd-b5f0-b3ae022b16d5
address: 1K5P32Z8Md4rio8PPdw18Tp3Xx5WHmg2ES
myetherwalletmsg.com
Fake MyEtherWallet phishing for keys with POST /store.php …
=> xlm-wallet.com + more

_data/scams.yaml
bitcointolk.org
Fake Bitcoin talk forum phishing for logins
https://urlscan.io/result/7b4db913-0bd3-4b85-8948-8a87f8367bfb
coinbase.xm-login2.com
Fake Coinbase phishing for logins
https://urlscan.io/result/ea5e11dd-0134-4b7e-a158-77e4fb605757/
etherdesk.co
https://urlscan.io/result/4d5a6595-217d-4a83-8b0b-b4a219c110e2
address: 0x015f17e2851eA392351b7f259e4CFd03dc443CeF
binancedecentralized.icu
https://urlscan.io/result/a1eb5789-cf8b-441e-8327-bd0d1254d645
address: 0x9a88031270e35db9D3254Bf66B92f64969D90440
=> bitcointolk.org + more

_data/scams.yaml
xn--blocchn-4ya8tls.com
Fake blockchain phishing for logins with POST /wallet/sessions - api_code
= 1770d5d9-bcea-4d28-ad21-6cbd5be018a8
https://urlscan.io/result/c31eb602-0191-464d-9104-b28bec33eb30/
xn--myeterwaliet-fs4f.com
Suspicious MyEtherWallet domain (Apache2 default page)
https://urlscan.io/result/25fb980e-6e75-492a-8799-4d8bfab157ef/
xn--myeherwallet-fpc.com
Suspicious MyEtherWallet domain (Namecheap default page)
https://urlscan.io/result/5043650e-1eb7-44f1-9f91-d460094d1e44/
xn--blockhan-w0a6d.com
Fake Blockchain phishing for logins with POST /wallet/sessions
https://urlscan.io/result/4da5cd5d-0cc1-4d28-8df9-e363cbb81ce6/
xn--bockhain-v0a06f.com
Fake Blockchain phishing for logins with POST /wallet/sessions
https://urlscan.io/result/b4da9a59-488f-4897-8a24-d68bcb4f46d6/ …
=> xn--blocchn-4ya8tls.com + more

_data/scams.yaml
get-10000-ethereum.org
https://urlscan.io/result/0f0c86ad-eeb6-4206-8a79-0296a1913a85/
address: 0x8D630073940fDE8112C6a5295Ba3e490cA992ee8
btc-crypto.me
https://urlscan.io/result/da646732-aca9-46a5-b0cd-4e19cc099437/
address: 1GiJEkXQevPAoeuLALo2cVh2WPFxQfu21E
tesla-gift.com
Trust trading scam site - linking to crypto-giveaway.net
https://urlscan.io/result/520b4f18-81ad-4c3a-a77a-9663a501a95c/
address: 0x579C0Fcc6D58731fD94de76A13390ABe330d9106
---
crypto-giveaway.net
https://urlscan.io/result/2d2c61bf-c8af-470b-a98a-a8db4e85a0b2/
address: 0x579C0Fcc6D58731fD94de76A13390ABe330d9106
=> get-10000-ethereum.org + more

_data/scams.yaml
dexairdropevent.com
https://urlscan.io/result/ec48e5f6-ef22-41d7-90cf-a646fe9877e8/
https://urlscan.io/result/3c6ad9ae-1eb9-44c5-a1a7-41ad411f7617/
address: 3HcX7kMQnn5QpaRvKyCgPSGa8MLfDYT2Sm
eth.tronnetwork.pw
https://urlscan.io/result/1565156a-720c-45d6-bd86-bd28fe808f40/
address: 0x8B0e77fE177d555408339E26921bE7d76D398d8a
btc.tronnetwork.pw
https://urlscan.io/result/7b69b3ac-36dd-49f0-bb9f-54fc266d0f27/
address: 1EBp8h9BGh4pJ4ZcE17Fo5pp7CRDd48y9u
pool-neo.blogspot.com
https://urlscan.io/result/c1e0313e-dbfc-4d57-9bf5-7215f7d675f3/
binance-giveaways.com
Trust trading scam site (found on open server) …
=> dexairdropevent.com + more

_data/scams.yaml
tesla-crypto.info
Trust trading scam site linking users to elon-share.info
https://urlscan.io/result/aa3fec3e-68dd-4eca-a506-09865b276692
address: 0x0ad24a61a0371d1dfe47c3b74169aaa5807efb31
eth.binancegift.pro
https://urlscan.io/result/1689aacd-86de-4f86-b614-6f35a4692390/
address: 0x8F46233dAFd44b331753E53b8785b9D83fBba463
idex.com.ru
https://urlscan.io/result/8b87ddfe-3e35-4829-9e7d-0e52803535d8/
https://urlscan.io/result/aed69d20-ecbd-46b4-bce6-0a2cce05cfd8
ibex.cc
Fake Idex phishing for keys with POST /post.php
https://urlscan.io/result/081ffa71-1445-438d-855f-cff7907d1cd8/
etherdelta.com.ru
Fake EtherDelta phishing for keys with POST /api.php
https://urlscan.io/result/26cf7b95-688d-479e-9c65-c300c3306bec/ …
=> tesla-crypto.info + more

_data/scams.yaml
huobiairdrop.info
Fake airdrop phishing keys with POST /postback.php
https://urlscan.io/result/ad4ea592-855f-421d-8bb6-3df60b4bda3c/
huobiairdrop.org
Fake airdrop phishing keys with POST /postback.php
https://urlscan.io/result/97075d19-3f93-4baa-984e-c54766e0addd/
huobiairdrop.top
Fake airdrop phishing keys with POST /postback.php
https://urlscan.io/result/d86c8d15-8159-4b2f-8d7c-d39700478dca/
blockchain.lcgiin.com
Fake Blockchain phishing for logins with POST /send.php
https://urlscan.io/result/2e784e67-c525-4358-adf5-436666c136f5/
blockchain.llogin.co
Fake Blockchain phishing for logins with POST /send.php
https://urlscan.io/result/58a963fa-f651-47ba-b671-4066600d4de0/
blcokchain.llogin.co
Fake Blockchain phishing for logins with POST /send.php …
=> huobiairdrop.info + more

_data/scams.yaml
cryptoblackfriday.blogspot.com
https://urlscan.io/result/e6cd0329-70bf-4e36-b779-1a54644d4633
freecryptogift.org
Trust trading scam site. XRP address: rCozquBhPba8D4hnCJh5DzJVZxZtNFGbV
https://urlscan.io/result/ab41fd9d-14a2-4b5f-a4db-e5e5d8280114
https://urlscan.io/result/12440fe7-21c9-4dd6-aaa3-4263cbce7b20
https://urlscan.io/result/4375a548-e24d-4d48-8f0b-7219603b8e07
https://urlscan.io/result/629a4dbd-eac7-41ee-b7ee-beed0cd50aac
address: 189p87dMz7FeFdp98AGkmYo4ScMYgqUAkh
address: 0xC82e2dfC140FB5D94B612af056c45d08C6560c84
tronblackfriday.blogspot.com
Trust trading scam site.
https://urlscan.io/result/fe6020b4-6a5a-45a3-bc6f-ad7c14f3353b/
btc-gift.tech …
=> cryptoblackfriday.blogspot.com + more

_data/scams.yaml
poloniextron.blogspot.com
https://urlscan.io/result/4987ba9a-96d0-4bda-b5e8-23db481f8fd0/
medium-ether.com
https://urlscan.io/result/c84f0df4-5443-4ac3-96bb-cdd619ffda60
address: 0x9068327FF0f5E99aF7D1AEfC5310e4560C32b84B
gift-btc.net
https://urlscan.io/result/083ee581-7df5-4d21-8857-fafc84d57e13/
address: 18oVCJ1h7MzpPk899FJiTWRb7Wm3FU8fjS
myetnerwallet.com.application-send.info
Fake MyEtherWallet phishing for keys with POST /callback.php
https://urlscan.io/result/320822ff-19c3-4f6d-b6cb-473227f43fe1/
application-send.info
Fake IDEX phishing for keys with POST /callback.php
https://urlscan.io/result/acb80e9c-f66a-4d4b-911c-df58d23cd485/loading
mediumz.top …
=>  poloniextron.blogspot.com + more

_data/scams.yaml
spacex.delivery
https://urlscan.io/result/dee85389-ef0b-4179-ba72-29a652b19ee2/
https://urlscan.io/result/f9d6d631-3856-404d-8e9f-f05a82ba4cdf/
https://urlscan.io/result/4b7fe234-8512-4039-9769-4a0d5e8cbb78/
address: 19wt8vVvEDLEgp766s7q67nwNG5WyYQNgo
address: 0x16881a3B5Bd0f6b2f8C547dcf9bD74442EAdDCf9
xn--metherwllt-f2d4888f9va.com
Fake MyEtherWallet phishing for keys POST /process.php
https://urlscan.io/result/9abd27f4-4a1d-4e3b-adeb-1712be25525d/
get-eth-now.online
https://urlscan.io/result/a303e68a-0751-4f2b-b7d3-42d05db1ac5f/
address: 0x3C98B49694c18ab0492A048eE213e2c3d3B3e0Ff
=> spacex.delivery + more

_data/scams.yaml
coinbase.pro-cax.com
Fake Coinbase phishing for logins with POST /action.php
https://urlscan.io/result/0d99d238-c5d2-4a0b-8927-66f242b6b538/
poloniexneo.blogspot.com
https://urlscan.io/result/09d86d62-391c-4955-9643-9b1dffe14449/
binance.eth-win.com
https://urlscan.io/result/8d44bc11-0e99-4099-a853-a45f72997b47/
https://urlscan.io/result/cc99720f-85e5-454d-9874-13cdfba3872b/
address: 0x886af3F44F4CbC38819aCe2C82442c1905c0D22c
address: 0xB4C4523E092f2340557D7298B1541D954b0a3902
huobiglob.live
https://urlscan.io/result/61d75256-2c2d-434e-bd00-0947ff818d2f/
address: 0x5Aa31CecF59B98ed7DeED6a6Fc3e3771c1B11AaA
mediumpost.top …
=> coinbase.pro-cax.com + more

_data/scams.yaml
ethnew.store
https://urlscan.io/result/212a5643-6987-4448-8069-4bb3d0e40b7a/
musk.claims
https://urlscan.io/result/a9db5309-babb-4d98-9a7a-8d6d9796c61b/
musk.click
Trust trading scam site - linking users to spacex.gives (not up yet)
https://urlscan.io/result/a5410d0c-07d0-46b5-9575-68cc4423017f/
spacex.gives
Trust trading scam site (not up yet)
https://urlscan.io/result/313c8eb3-a411-401a-a6dc-cedd7c949465/
blockchain-update.bounceme.net
Fake Blockchain phishing for logins with POST /next1.php
https://urlscan.io/result/3a210119-fdb9-4d97-ac9c-f9965e2d2b9c/
coinbene.net
Fake Coinbene phishing for logins with POST /login.php
https://urlscan.io/result/b6436adb-2b8d-40f5-a57a-ee674014d77b/ …
=> ethnew.store + more

_data/scams.yaml
cryptokucoin.blogspot.com
Trust trading scam site (XRP)
https://urlscan.io/result/63213174-2f94-4888-a8d0-c9cea85acfa4/
address: rGD1q9qfHd9gYbm9VUdcBXjumAaMZen8tr
neokucoin.blogspot.com
Trust trading scam site (NEO)
https://urlscan.io/result/68e65ea7-f33b-4b84-9b83-d24467bb3ca4/
=> cryptokucoin.blogspot.com + neokucoin.blogspot.com

_data/scams.yaml
tronkucoin.blogspot.com
https://urlscan.io/result/59db98d8-f61b-4e74-b853-6153d7ed7c4f/
xn--bibo-eo5a.com
Fake Bibox domain - kit not deployed yet
https://urlscan.io/result/ea664f17-fe6d-4726-bd07-0cc77c5cd5e0/
paxfulldashboard.com
Fake Paxful phishing for logins with POST /
https://urlscan.io/result/5798c769-68bf-49ec-9b5e-9146a9e14093/
info.paxfulverify.com
Fake Paxful phishing for logins with POST /com.php
https://urlscan.io/result/fcaecbbd-d917-43f8-9152-54187ae7cbc4
paxfulverify.com
Fake Paxful phishing for logins with POST /com.php
https://urlscan.io/result/02a455fb-b5f6-4399-922a-6ad3a265a2fd
myetherwallet-xyo.space
Fake MyEtherWallet phishing for keys with POST /app/keys.php …
=> tronkucoin.blogspot.com+ more

_data/scams.yaml
bbxotc.tech
https://urlscan.io/result/6a795a69-fa70-4a77-b927-63490c738b2a/
https://urlscan.io/result/33c338f4-d407-4e6e-85d3-229bf32128b5/
address: 0x8BdA591ac93925f485cd420A47A48EBa87985ea0
btc-gifts.net
https://urlscan.io/result/a6358246-767e-421d-9db6-771beaf75839/
https://urlscan.io/result/5e8d9a9f-79a0-4a3e-a3f6-83faa25d2498/
https://urlscan.io/result/49d82325-8fb3-4263-9645-f2f7c37e87b9/
address: 13GJitKdQKcbaiJuNRmUf8F7roh9FfSFTG
address: 0x9404C08c6ae0cd5F1FdbC558c7A61D3D7Bff07e6
---
binance-claims.com
https://urlscan.io/result/ab19497f-2f05-413b-94ee-8e6b84cd22de/
address: 1J75vF5koGVgKXNewrZkcMBS1eJkyLcdcC
=> bbxotc.tech + btc-gifts.net

_data/scams.yaml
coinbase.prows-ax.com
Fake Coinbase phishing for logins
https://urlscan.io/result/8fe8aead-d531-452e-9abf-8e7212078197/
bitcointoolmining.com
Fake BTC/ETH generator asking for funds to gas to send x eth to whatever
address you want
https://urlscan.io/result/a1482145-7a86-443d-91e7-4d4efbd774b9/
address: 1EmqvYW2AGVbmtsM1M7vTyB1V9E75xaa9Q
address: 0x18365A89E092CCC31d2A49ab5CB697564Ec81bCF
idexethereum.online
https://urlscan.io/result/3d9cd5e9-9499-47bc-adb3-e01c80479ca8/
=> coinbase.prows-ax.com + more

_data/scams.yaml
coinbase.pro-xca.com
Fake Coinbase stealing keys with POST /action.php
https://urlscan.io/result/a79d2b66-11d7-4589-84bb-3941598c372f
doublecoinio.jdevcloud.com
Coin doubling scam (and email and public address harvester)
https://urlscan.io/result/ac9e3c36-61aa-4dbc-92be-0a865636c685/
https://urlscan.io/result/847fc504-9e56-4f35-acf3-0814da0b6a4a/
https://urlscan.io/result/4d428125-a99c-4498-9eeb-163e6df33dff/
mediium.org
https://urlscan.io/result/104d81ee-3a14-41d4-a702-9f1b899956b8/
https://urlscan.io/result/7971b8d8-ab99-4431-b0a5-273997b36d45/
address: TX9oqhThyQdGXrDMacRXAvsWPoxQspQLFw
myetherwallet-be.space
Fake MyEtherWallet phishing for keys with POST /app/keys.php
https://urlscan.io/result/be43a3a8-91f2-48ba-8ed4-090678989795/ …
=> coinbase.pro-xca.com + more

_data/scams.yaml
xn--eoscorearbitratio-l6c.io
Fake ECAF site harvesting user data
https://urlscan.io/result/1a244036-0169-4d07-ab17-196d101c2f90/
myetherwallet.96.lt
https://urlscan.io/result/fcbb884b-27e7-4f15-8a00-fce7a555a447/
dec-kucoin.blogspot.com
https://urlscan.io/result/4ddd6779-1af9-428f-b9e9-6e9f714299d5/
trx-kucoin.blogspot.com
https://urlscan.io/result/21da564d-7403-49a1-ae49-4cdb0c6fd80d/
neo-kucoin.blogspot.com
https://urlscan.io/result/ca7e5bb2-d4c2-4996-b214-1169b27c356d/
cryptobountymco.com
Fake bounty program …
=> xn--eoscorearbitratio-l6c.io + more

_data/scams.yaml
myeltherwaliet.com
Fake MyEtherWallet phishing for keys with GET /en/c.php?data=xxxx&m=1.
Reported address: 0x6Fce6D2cECA868AC809d1e8D52e9fC3b8690118f
https://urlscan.io/result/25efd1f1-60b3-4ee7-83a6-c847ca275483/
myetherwallet-tgt.space
Fake MyEtherWallet phishing for keys with POST /app/keys.php
https://urlscan.io/result/1b12d50a-6cd6-4367-ab68-f8475016d128/
----
xn--coindsk-vs4c.com
Fake coindesk promoting fake SingularityNET - reported address:
0x7cdf272058894f70e3a7ace593628ad2bc0f574d
https://urlscan.io/result/1085f293-c6fc-4e6f-b32d-b417110e52c3/
=> myeltherwaliet.com + more

_data/scams.yaml
meduim.online/@officialmcafee/Johh-McAfee-Official-Eth-AirDrop/post/airdrop/
Trust-Trading scam site
Reported address: 0x4eB1d2050017Cf862939340c017a31aa2d59d8d8
https://urlscan.io/result/301f5342-6f8b-483d-8a01-f1f6028f3882
=> meduim.online

_data/scams.yaml
quarkairdrop.com
Fake airdrop phishing for keys with POST /sign.php
https://urlscan.io/result/5db4001e-d790-4b53-8c21-f98c4cd7387b/
https://urlscan.io/result/acbdb58e-5ae5-49b8-8437-6b76238b8e9b/
https://urlscan.io/result/f24b7c40-1b98-4628-aab3-d567acbaf3e1/
crypterium.site
Fake airdrop phishing for keys with POST /sign.php
https://urlscan.io/result/3208fea9-4814-4616-8cf8-12ff48f4ef9c/
https://urlscan.io/result/c01cf142-9767-4a68-91c5-79fe57931853/
https://urlscan.io/result/e07da894-778f-4a0d-b11e-e262aca4ee3b/
etherdelta.pro
Fake EtherDelta phishing for keys with POST /api.php
https://urlscan.io/result/cd7cab90-fd09-41c4-aaaa-c0b7c8d02db6
bitcashsv.org
Fake BitcoinCashSV splitter and email harvesrer
https://urlscan.io/result/f6a22947-7126-4faa-bdf7-b9fa9d3a81ec/
address: …
=> quarkairdrop.com + more

_data/scams.yaml
ether-contest.com
https://urlscan.io/result/be7e8b6f-bd02-4210-bd9c-67be4aedcbf5/
https://urlscan.io/result/f9d5845d-729e-4544-a1b8-670740c90ec3/
address: 0x81E4B65b9330C5693d38430111D7Eb174615bDD6
dex-huobiglo.info
https://urlscan.io/result/1051fc75-87ac-42b1-9587-60fae3c88f96/
https://urlscan.io/result/f4a4a41c-9f8b-401a-8ac3-36ceebfc20ed/
address: 0x57aa0ca8ddc99096d150f0dd1e1bd50616d809c8
address: bc1qw9cz3095dxnt5hkfdyltueen9g7j5w5u6c0zq9
telegra.ph/Crypto-Bible-team-are-giving-away-500-ETH-12-22-2
https://urlscan.io/result/9aaa2953-bb03-4948-ad32-6082b8eec0c5/
address: 0x95115419b09e8cea70a9bdbca3fee8c5e118b228
=> ether-contest.com + more

_data/scams.yaml
bittlrex.com
Fake Bittrex phishing for logins with POST /Account/Login
https://urlscan.io/result/e05e7cce-056a-4ae8-be8a-4059729ad1b8/
https://urlscan.io/result/9b3843c9-cb8f-4bd9-9c87-e1e7a72f37d1/
xn--binnce-rhc.com
Trust trading scam site - linking users to
www.binance.exchange2018.support/event
https://urlscan.io/result/dbd027bf-21b2-44ca-9e40-caa6aa336120/
address: 3HzQJ3CGQKkWuxGSiWW286PePSed7tgKWp
binance.exchange2018.support
https://urlscan.io/result/307d137b-93d9-4a07-8fa7-c78ec8ea438c/
https://urlscan.io/result/771cae8a-4b00-400e-a194-168a458c3479/
address: 3HzQJ3CGQKkWuxGSiWW286PePSed7tgKWp
binancehelpdesk.com
Fake helpdesk harvesting user emails
https://urlscan.io/result/84cdf127-f04d-46dd-a846-7c7791157b1a/
pumapay.io.giveaway-user.com
Fake …
=> bittlrex.com + more

_data/scams.yaml
crypto-positive.club
https://urlscan.io/result/0641a867-2b8f-4eef-a97e-c40457b135a9/
address: 1CKK4yMGjcbzEG8hWSdtNSQcoV8PDiGzDk
trustwallet.com.erc-20-tokens-gift.com
Fake TrustWallet bonus site phishing for keys with POST /claim.php
https://urlscan.io/result/fc05aadd-3f9c-4469-ab85-97dee762ea89/
https://urlscan.io/result/9baf231c-53d5-4208-8346-ee295253bd14/
https://urlscan.io/result/5c40fb87-d8e2-4aec-81b3-1586041e7e0b/
=> crypto-positive.club + more

_data/scams.yaml
coinbase-airdrop.top
https://urlscan.io/result/5797f848-6bce-494b-9965-9b2d6cd291ad/
https://urlscan.io/result/72943f79-196d-4ca6-98eb-a9c5051c727b/
https://urlscan.io/result/79cf52d8-9f84-4524-92bb-85d1e46a8649/
address: 1MpLjpT44A5yyRbtGG61rtpgwxdJB3onsB
coinbase-btc.xyz
https://urlscan.io/result/8587b1af-4500-4653-b741-3d5d1a35ffc8/
https://urlscan.io/result/b38627e4-3ea1-41db-adf0-46c3734794e6/
https://urlscan.io/result/140e9ae1-4fdd-4868-954f-168f4737b77d/
address: 1MpLjpT44A5yyRbtGG61rtpgwxdJB3onsB
kucoindectrx.blogspot.com
https://urlscan.io/result/c01ea702-9d1c-4cce-9382-1f69b7bd5843/
jaxx.im
Fake Jaxx download - …
=> coinbase-airdrop.top + more

_data/scams.yaml
ethtokens.online
https://urlscan.io/result/fa0bb22e-c94d-4dc7-bc03-f20c1113a260
binance-competition.net
https://urlscan.io/result/c44b7bba-0c55-4309-af0e-2424140503c4/
https://urlscan.io/result/5809145b-94bc-4be8-8493-637674e483ba/
address: 0x7b904DF207858b9A4fCD0d9538ef633beD316287
excdus.org
Fake Exodus site
https://urlscan.io/result/c3cac28d-a5d5-4c28-9aa5-9d11df66e8f5/
https://urlscan.io/result/3062a1f8-a007-44d2-b605-d23fb28ecfd9/
giveawayxneo.blogspot.com
https://urlscan.io/result/32e80443-3707-4acd-aaba-44f234c1eed0/
=> ethtokens.online + more

_data/scams.yaml
Fake MyEtherWallet phishing for keys with POST /zakaz.php
https://urlscan.io/result/7dccd70a-8a6b-4831-87ae-7146236063ba/
crystal-profit.com
https://urlscan.io/result/735a9aa2-b027-42c1-b048-949463dbf498/
https://urlscan.io/result/e04fda12-13af-4cac-a993-18eb9d9ca781/
address: 0x8255F34903440ff046169b12ea848ce6f083A631
address: 13LbKNisvCje3vFSchUoRn9BxTLj6wFHqP
=> ethnowa-wallet.com

_data/scams.yaml
biboxpr.icu
https://urlscan.io/result/bbe6cfbb-4da6-44cf-87f8-c1cf5db7c55a/
https://urlscan.io/result/84141710-8669-494b-8eaf-b0fba4f163ef/
address: 0x3331f67F5b2544Fb0f2d7C90F7b8109d24bF6e7c
=> biboxpr.icu

_data/scams.yaml
cryptobridge.su
Fake CryptoBridge exchange phishing for details with POST /login/login.php
https://urlscan.io/result/29b000e4-dd0d-4fe7-9302-485f0276a55f/
xrp-giveaway.com
https://urlscan.io/result/88344037-b595-47f6-b0c1-304181116dce/
https://urlscan.io/result/c5d24623-4bd8-4e4c-a60d-bb4a639c01a8/
address: raBesxXx7QQ1RdboXXZHhjaKSyW19JptMt
=> cryptobridge.su + xrp-giveaway.com

_data/scams.yaml
newyearcrypto.blogspot.com
https://urlscan.io/result/b6adfa3c-78e3-46fa-91ef-3b7d448290fc/
https://urlscan.io/result/c3cbce1c-9e35-42fc-96a2-175a81bf623f/
https://urlscan.io/result/0925f917-653e-450b-bc25-c206d633f42a/
https://urlscan.io/result/5c5b9c93-b945-46b1-bc73-da784c4f1baf/
address: Ae2tdPwUPEZGpHCMV2L7iMY4vUGX6Pzx5U2YgQD1wK7ZUzKVmgg5RRmp2dF (ada)
address: TPcDNYz4AxCaLCY2Xx4i95jGYwCjUrxg5r (trx)
address:  0x55B775Ea2CA493c082F3e17A8433e4D220FBB8d8 (eth)
address: 1JSeDGPmq74JP2RQXqJFdHH3L2jcie3w4X (btc)
newyearneo.blogspot.com
https://urlscan.io/result/59ef5bb9-9f0e-43a7-83eb-3b7e0b9f282f/
cryptocashback.org
Directing users to a Malware chrome extension
(liachincjagnalnmahhaioaogkngbmhf) to …
=> newyearcrypto.blogspot.com + more

_data/scams.yaml
gowincoin.com
https://urlscan.io/result/765f29f5-7f6c-47b5-8173-0e96ee266938/
https://urlscan.io/result/af65279f-2211-456e-b990-9ddaf3315b14/
https://urlscan.io/result/7ccced8c-4fe5-4e90-8463-eadbdd418cfe/
address: 1ApXtisCrsykSmzCXsRFL6mhtKQUdN6eQB
address: 0x8583EE650C6566503d1d9DD3FaE76498e7E4CcAA
delta.money
Phishing for keys with POST /api/auth/generate_info
https://urlscan.io/result/34e77b3c-a8f9-4bb7-b199-27259f4d158e/
coinsupergive.live
https://urlscan.io/result/3518e07a-afd1-4f81-9079-d5722d9380c1/
https://urlscan.io/result/068290b9-de6a-4d7c-83c7-31929c1ad0d8/
address: 0x9d79AeEce49694B01B2d2A44Ba2c240De48959C9
ethers-claim.com
https://urlscan.io/result/94822477-9469-41d7-89be-509ca5903d6c/
address: …
=> gowincoin.com + more

_data/twitter.json
Thanks for considering my request.
"157412428": "kevinkoosk",
=> Please add @kevinkoosk to whitelist

_data/scams.yaml
idex.ru.com
https://urlscan.io/result/90bb2811-5f1f-493d-95e9-c22209daad93
https://urlscan.io/result/d84a7170-dcf3-467e-a519-e60c3f689f98
hydroproject.io
Phishing for private keys with POST /api/v1.php - reported address
0xac1Ee036c52D20aD437A1DC46056b9aBF0cF1Ca0
https://urlscan.io/result/0555da55-9afe-4631-be2c-e39b41e29a98/
---
coinsupergive.live
https://urlscan.io/result/4a17a80f-62b7-438d-bc6c-a7d6560d1719/
address: 0xecb8D2E87573d5a0aB2662591121B4de29294070
=> idex.ru.com + more

_data/scams.yaml
karatbars-affiliate-bonus.com
Hosting a Fake MyEtherWallet phishing for keys with POST /claim.php
https://urlscan.io/result/67737929-35f3-4b2b-8a38-dd24d14d11bc/
https://urlscan.io/result/9cc478c9-92d2-47fc-bf9d-4a34e3c665b6/
https://urlscan.io/result/109e099b-c998-4f37-8dd1-bab316e71fde/
etcvwallet.com
Fake ETCV wallet phishing for keys with POST /api - reported address:
0x144826ded37a161f4d0aa7e5884131750022703c
https://urlscan.io/result/44deccff-e384-434b-95f5-a850bb4d6ef4/
https://urlscan.io/result/cb6a6411-54f4-4e77-9004-e80c3efbe0f3/
telegra.ph/Manual-unblocking-procedure-for-block-of-transaction-due-to-jam-on-mempool-01-09
Fake announcement from dx.exchange to phish funds
https://urlscan.io/result/5a0ce984-dca6-435b-92e4-d6fb3c5a1c7f/
address: …
=> karatbars-affiliate-bonus.com + more

_data/scams.yaml
myetherwallet-dfz.space
https://urlscan.io/result/b53bec02-6d3c-4a8e-b665-efb4d35ac4c5/
ethnowawallet.com
https://urlscan.io/result/e64447e3-c8bf-4f90-b2fc-f170c57bc403/
wallet.bancor.network.xbancor.online
Fake Bancor wallet phishing for keys with POST /javascript.php
https://urlscan.io/result/906d5b80-e8c9-405b-b3d6-f6366c17a66b
ethereumcv.io
Linking users to a phishing wallet https://ethereumcv.io/
https://urlscan.io/result/e07c38cb-ea8e-45b3-8bc5-573f164a3398/
ethereumcv.info
Scamming users for ETH
https://urlscan.io/result/ae7be8ac-3108-411f-a637-c19a7386d039/
https://urlscan.io/result/241e0b96-24a3-4ae4-99a1-17c50bece295/
address: 0x237abde05ac2f992a44436bfee8b3219a329c5a0
tesla-promo.tech …
=> myetherwallet-dfz.space + more

_data/scams.yaml
etcv-wallet.com
Fake ETCV wallet phishing for keys with POST /api (base64 encoded)
https://urlscan.io/result/cdd9ca50-e58c-4f6e-ac6c-6a1fc1170c07
wallet.hydroproject.io
Phishing for private keys with POST /api/v1.php
https://urlscan.io/result/3a8fcd27-7e11-4a1a-8671-20c39d37f798/
=> etcv-wallet.com + wallet.hydroproject.io

_data/scams.yaml
dex-hbiglobal.info
https://urlscan.io/result/bd8b316b-2db0-455d-9083-f7ab71ed6372/
https://urlscan.io/result/5689a49c-d280-406b-9132-e6f2d9645c13/
address: 0x8A6762E718beb7e6af9AB3868320c3C5137ADc6C
xn--vww-krakn-2f7d.com
Fake Kraken phishing for logins with POST /login/login.php
https://urlscan.io/result/917dd463-376f-41d3-a9b1-c6f110a2770a/
https://urlscan.io/result/60fd7f17-917f-4027-811b-bb9df39ad28f/
bonus-stellarterm.com
Fake Stellar bonus phishing for secrets with POST /login.php
https://urlscan.io/result/3542ce67-39c8-4e18-a81f-03e3cc31184a
betabindex.com
https://urlscan.io/result/fe24c040-142f-4bd9-9e3c-2cadcf07c763/
https://urlscan.io/result/30416096-6c53-43bd-aae9-70f5482636df/
address: 3Atw5T74MLwzYoMht8T4CK6yVibngwkRjk …
=> dex-hbiglobal.info + more

_data/scams.yaml
janbinancexrp.blogspot.com
https://urlscan.io/result/92ce3568-d27c-4d18-a98d-b2d73a2f8046/
address: rGD1q9qfHd9gYbm9VUdcBXjumAaMZen8tr
janbinance.blogspot.com
https://urlscan.io/result/418507d6-4ec4-4fa7-a297-925fa2b2dfcd/
https://urlscan.io/result/e013b5ca-bc49-4155-8ff5-980b5f0bbf97/
address: 1JSeDGPmq74JP2RQXqJFdHH3L2jcie3w4X
coinbit24.site
Scam bitcoin doubler
https://urlscan.io/result/27d93054-c3af-4474-909f-ffa5ef66d1ec/
https://urlscan.io/result/64764e04-6924-4d17-9ca2-a8e4b3d8b939/
address: 1LeYK9J5aVEHdCNuwqBi2UQEFarmXewHvk
idex-market.live
Fake Idex market phishing for keys with POST /log.php
https://urlscan.io/result/5f5c4219-0c66-4e90-ab10-a4f38c4908c4/ …
=> janbinancexrp.blogspot.com + more

_data/scams.yaml
btc-promo.net
https://urlscan.io/result/174696f7-93ea-46c5-9b7e-8e4196ee8eb4/
https://urlscan.io/result/99723685-b931-43e9-896a-7bc7c141dd03/
https://urlscan.io/result/e7bc9d2c-c5d2-4240-8272-8a2c63e72b9c/
address: 1AHkrJ55mxbUBEe1bn5MQNzH1sP8zSuKqS
address: 0x9145Cb518FD02877FE8efA077c3EAd95235fDA22
waves-x.com
Fake waves project linking to client-wavesx.com that is stealing seed
phrases
https://urlscan.io/result/0731dcc7-b3dd-4826-9518-579e99e27f7a/
etcv-wallet.co
Fake Ethereum wallet phishing for keys with POST /send.php
https://urlscan.io/result/5bc06a22-0ca5-4680-83a5-d45ec091550e/
bttlaunchpad.com
https://urlscan.io/result/2ce24d5c-92b2-4ce8-96d9-93384e429416/
https://urlscan.io/result/04868730-60b5-43da-9f93-9ce5e62ad1e7/ …
=> btc-promo.net + more

.gitignore, run.js
* So we can claim the etherscamdb.info on OBB + security researchers have a place to look if they want to open comms.
=> Added route for security.txt

_data/scams.yaml
ltcpro.live 
https://urlscan.io/result/cba0573b-f0e1-4854-9cef-fc906e9bd940/
https://urlscan.io/result/4cc760e8-2a31-4ef9-9661-3e19a2b3c5b1/
address: MMdDAFeUu7saKRZKzy6H855jp5sWvP7zUp
ltcpro.xyz
https://urlscan.io/result/e0c5b202-019b-422a-9209-9385bbb329a1/
https://urlscan.io/result/32cdde11-3c08-4c75-8e62-38ffab8e9ce7/
address: MU1X2NuRCPC43h71KKLns3gve6Ust9Zghe
doublebitcoin.cc 
https://urlscan.io/result/8d848c4b-0e48-4c56-a1d4-48bc99863da5/
https://urlscan.io/result/832ac89b-8ac9-4507-bad5-9a4f5f94f727/
address: 3FVJwsWDYntJ5ZMDeHoRCHjeiDDeuqsp5P
trondiscount.com
Fake trx/btc exchange & hosting private key phishing POST
/vechain/mailer.php
https://urlscan.io/result/b8a422a1-be4a-4674-a679-180a1c2b5f47 …
=> ltcpro.live + more

_data/scams.yaml
Fake LocalEthereum phishing for logins with POST /login.php nad 2fa codes
with POST /send.php
https://urlscan.io/result/89a2c472-ea3e-4d5b-adc7-0dd59e711e6f/
https://urlscan.io/result/99ab6ad7-f7c5-439e-b57a-2014b4594ece/
https://urlscan.io/result/5bf341ef-84b1-4a5a-b7e4-5197e16ac605/
=> localethereum.com.support-ticket-report.com

_data/scams.yaml
eloncity.sale
Fake ElonCity crowdsale site
https://urlscan.io/result/237088f9-a3ee-446a-933c-62a3bc23e7e9/
https://urlscan.io/result/c7bf3b6e-298a-4c2d-8b65-b51b789c1946/
address: 0xA82E2B7EE7c92d6062db14de092A4838a816b1f0
mana-gift.com
Fake Decentraland giveaway (fake MANA contract)
https://urlscan.io/result/bd09f1da-51bd-432b-add0-c9f124791a21/
https://urlscan.io/result/bce15e47-f63d-4600-a2c3-962fbb0989d6/
address: 0x65440e4CE8a9a596a20EC8f910DfC8b1a20c5f7a
digitexfutures.site
Fake airdrop phishing for keys with POST /sign.php
https://urlscan.io/result/0d1cb8a2-f3a6-4b74-b659-a6f6d2f7466d/
https://urlscan.io/result/616dd778-77bd-4e64-9f53-416eef649971/
https://urlscan.io/result/fd1a20fe-5281-4e10-9ef4-a94b80d425b1/
=> eloncity.sale + more

_data/twitter.json
Add @mysticryuujin to whitelist
=> Add @mysticryuujin

_data/scams.yaml
bttpromotion.github.io
Fake Tron/Bittorrent promotion
https://urlscan.io/result/2ea68909-d513-4a7e-b118-76236172ecf8
https://urlscan.io/result/80ed833b-cfd0-479d-ba0b-cc6ee545fc82
address: TXRMhqQjhG5tauwP2XPdspWdKsJm5qh81e
telos-foundation.io
Fake Telos foundation
https://urlscan.io/result/1e332137-378a-4c16-804f-6d26cd1951fb/
https://urlscan.io/result/30c354db-4d33-49eb-9874-7ac4e9cb19d5
binancegive.com
https://urlscan.io/result/eeb3055e-9c15-46d6-9964-27f188fed12d/
https://urlscan.io/result/d7cfac9d-2b84-47b6-8417-dd22a0d93c5c/
address: 0x2f8debdCF62eB537871dAEDe11F790D84DDF35cf
idexgroup.online
Fake MyEtherWallet phishing keys with POST /bot/bot.php
https://urlscan.io/result/5e13b9fc-67c8-46da-afbb-52600d0c9e83
=> bttpromotion.github.io + more

_data/scams.yaml
buteringift.com
Force downloads [Private]BTC-Claimer.rar -
https://app.any.run/tasks/7194647f-4d76-4e09-a6d2-a7548a99f253 &
https://www.virustotal.com/#/file/85cec9925cce2a697c3114c83eb864f892c0d11d9864c37b6987cff7eb1f7ee2/detection
https://urlscan.io/result/02db8a34-d7c3-4491-87bc-be58f9ba5bc3/
quick2xbtc.com
Trust trading scam site - btc doubler
https://urlscan.io/result/77c8d283-9ce5-4f8d-8759-93538d1f4912/
https://urlscan.io/result/235c5988-099f-422f-a7b3-f0abc3cd1891/
address: 1EM1GKe1NhkcAL5SLrSVS2SopXqzeDy4nz
doublecrypto.ml
Trust trading scam site - btc doubler
https://urlscan.io/result/a1dfa6aa-124b-4f3e-8151-72721e58fc5f/
address: 3Mm5maydqMipR9iVtc9vk6dGYzbV7rMkje
doubleinvestment.cf
Trust trading scam site - btc doubler …
=>  buteringift.com + more

_data/scams.yaml
circlemix.io
Trust trading scam site - btc doubler
https://urlscan.io/result/411be7a4-f49a-4221-920a-ca371a372a49
https://urlscan.io/result/64b3ef01-91e2-4ec9-8686-4fb937c10f58
address: 33XkXTi4cPW8M3uoDYJDkPHXHZs6wVFJ6U
jancrypto.blogspot.com
https://urlscan.io/result/0f113c1e-f3a3-4321-9777-3549eefb89b7/
wallet-support.com
Hosting fake support channels for exchanges (1-844-455-0666) Twitter ID:
1077133359707500546
https://urlscan.io/result/aba63131-1aee-4d08-beb3-c49f4aa122eb/
https://urlscan.io/result/a7b71451-e9c5-4356-9e1b-0f0d4608af11/
seth-transaction.info
Fake MyEtherWallet phishing for keys with POST /callback.php
https://urlscan.io/result/e072eb24-62e1-4c13-91ba-beee0175a61e
cryptocreditfoundation.com …
=> circlemix.io + more

_data/scams.yaml
btcaim.com
Fake Bitcoin generator
https://urlscan.io/result/274ea593-aa9d-4dd9-931a-de6f17a4871a/
address: 3DrrDwv49rfJowvUsoYFKk5GDFQQwZQei8
address: 374YucVfN8tbsXG9SKXh2JzcEraJ21U7QA
address: 3JdHFWi1sqypAPGowKnhvxnxogr5Faky8p
address: 14jcbn3K3CjN8g7LVHbYXFvKuHxwi8Xn7L
bizzilion.com
Fake team - see https://bitcointalk.org/index.php?topic=5100342.0
https://urlscan.io/result/e2b00828-1690-4e0c-8116-c0b351adcdf6/
https://urlscan.io/result/4dd3c359-f9e1-448c-a11a-226f622dbaa1/
address: 39U67RrCzsLEVtihGQceRFZAkPBGT8XYZK
address: 0x35a95d5f0c8f676bb7b2dab47d6368a4ad5cbf8a
xn--medum-vsa.com
Trust trading scam site (also see https://bitly.com/2FPOULl+)
https://urlscan.io/result/dd23ad4e-9075-42a8-b8e2-86d6db386bf4/
address: 0x444f5672d88264c4a1289C2ABa1826F9b4f14D49
=> btcaim.com + more

_data/scams.yaml
cryptoexcoins.com
Reported fake exchange - very insecure. Blacklisting for user security -
https://twitter.com/sniko_/status/1090022435116732416
address: 3QNP28LkQqsC9nVG5aothDF6oj7jixHi3Z (btc)
address: 0x5018a34c512a092a8620dea08fd0f078c71f7d92 (eth)
address: qq6qzcaphg3ygysue8lawxan5khscskgwcc6fywx7a (bsv)
address: t1R2tWtBWr7Us5PSXoLJZgEPoxPbNL8uk5C (zec)
address: 0x5d09a152f788dad9ee09a04cc8d7d933713e9cb0 (E2C)
ethtokens.store
https://urlscan.io/result/ccaad918-59f2-4890-a4d7-603e4a1c0552/
bitcoin-generator.network
Fake Bitcoin generator (trust trading)
https://urlscan.io/result/dc7fb829-1d28-4a54-96d5-db1d54737181
address: 1GjvX7WnKTHTx1eWqjTz5b2af1huXmpyst
=> cryptoexcoins.com + more

_data/scams.yaml
idexmarket.website
https://urlscan.io/result/00c6cc1f-c248-489d-b54d-d3d64ea0422c
https://urlscan.io/result/f8c778dc-2faa-445a-afe7-9d0ee13fbbec
stellar-lightning.org
Pointing users to a fake wallet (xllwallet.com) phishing for keys -
https://twitter.com/sniko_/status/1090797481103900672
https://urlscan.io/result/8492db48-3638-454e-ac58-0b8a94d02984
xllwallet.com
Fake XLM fork phishing for keys with POST /
https://urlscan.io/result/345598be-64f5-44df-9bb7-854cad29c1ec
=> idexmarket.website + more

_data/scams.yaml
myetheresswallet.com
Fake MyEtherWallet phishing for keys with GET /en/c.php?data=xxx
https://urlscan.io/result/909ed882-ac1b-41fe-b403-6e1a9bd0093f/
bitaeon.top
Fake BitAeon phishing for logins with POST /send.php
https://urlscan.io/result/97140333-cd7f-4790-967d-59e09013d3fd/
https://urlscan.io/result/db5f4e19-cb8a-4da0-ac1c-6422a6dd2d87
btrmartgve.com
https://urlscan.io/result/5cbcea63-dbc7-4b97-ae46-f1592297bff4/
https://urlscan.io/result/70effb7c-4594-4691-808f-602c87660f9e/
address: 0xa1B04A60a35854d0749aE39B0346BCEb55247ecC `
=> myetheresswallet.com

_data/scams.yaml
dexbetalaunch.com
https://urlscan.io/result/1c9b66ae-8789-495a-a8ee-e7bc34596166/
https://urlscan.io/result/4a2343df-35a9-485a-a78d-f0775147aef4/
https://urlscan.io/result/d3d960be-ac50-4a97-9077-356313412c1e/
address: 0x5B2b8b9c674e67F718BB54Cc62C2a2E13308229c
address: 1MpLjpT44A5yyRbtGG61rtpgwxdJB3onsB
airdropxneo.blogspot.com
https://urlscan.io/result/7cc9f92d-910f-43c9-9607-1c79c1a8c905/
claim-xyotokens.com
Fake MyEtherWallet phishing for keys with POST /claim.php
https://urlscan.io/result/e2433429-c047-46f8-af67-988736270472/
bitcoin4future.club
Scamming users with guaranteed investment opportunities
https://urlscan.io/result/7731b421-3729-46e3-adfd-687f4585a163/ …
=> dexbetalaunch.com + more

_data/scams.yaml
giveaway-x.blogspot.com
https://urlscan.io/result/b797424a-8b1f-4712-b55b-f00e9bef4e36/
airdropxneo.blogspot.com
https://urlscan.io/result/d47d9828-d535-4db4-970f-412aefc7bef9/
etherchange.tech
https://urlscan.io/result/171edaf3-9241-49b6-b47b-e89204189fac
=> giveaway-x.blogspot.com + more

_data/scams.yaml
eth4free.com
https://urlscan.io/result/cb5db62b-1cd0-4529-b223-7acbe903ef9a/
address: 0x839BaaCA91Cbcf6c1632c55E1AE031C6B270df19
getfree-neo.blogspot.my
https://urlscan.io/result/ecd30a4f-884d-4036-979f-58730f1b5227/
getfree-neo.blogspot.com
https://urlscan.io/result/b683b33c-0305-490e-8766-eb6d3fe8fecc/
binjerseygbpeur.com
https://urlscan.io/result/e6489514-bfe1-44a4-8b34-45ba087e3258/
https://urlscan.io/result/0770614b-1ddc-41a0-9b8c-0eaf56358664/
address: 0x32C648164D27A2fe26329bB0CFf5C379cd1178f9
address: 3D2sKMHnC6P6XKmC5kohCGZ4FvWMUaZgow
get-freecrypto.blogspot.com …
=> eth4free.com + more

_data/scams.yaml
myetherwallet.com-7da3a890-214u-23c1-14a19-87536g0f4cd4.site
Fake MyEtherWallet phishing for keys with POST /mail-area2.php
https://urlscan.io/result/3e257e39-dfa4-4499-b4e0-863136daf1f1/
myetherwallet.com-7da3a890-214u-23c1-14a19-87536g0f4cb2.site
Fake MyEtherWallet phishing for keys with POST /mail-area2.php
https://urlscan.io/result/51bca8ed-beb4-4baa-b3b2-11982d4883e8/
bittorrent.foundation
https://urlscan.io/result/979afd5e-5e40-46b3-b30d-086fcc8833b9
https://urlscan.io/result/5a179820-968a-4af1-baaa-9ecaeca0eaa0
address: TDLcipJPJMT6iCFava8B9A1gGiKJvBRWzn (trx)
bakktplatform.io
Fake Bakkt website - see
https://discourse.trustory.io/t/best-trustories-of-the-week-10/634/61
https://urlscan.io/result/f5545c3d-e213-4f39-883c-1ee724f8b19d …
=> myetherwallet.com-7da3a890-214u-23c1-14a19-87536g0f4cd4.site + more

_data/scams.yaml
xn--hitbt-8xa.com
Fake HitBTC phishing for logins with POST /indexSend.php
https://urlscan.io/result/86db3041-f724-484b-a11a-5a68b5afccd3
idexmarket.space
https://urlscan.io/result/2e073846-c47d-4a7a-8499-289b5c1dff9e/
https://urlscan.io/result/d2a0794c-b4b7-4291-9650-f8906622a5e6/
lucalbltcoins.com
Fake LocalBitcoins phishing for logins
https://urlscan.io/result/a6fbada0-39e7-4f1d-a10e-4fe44f73c805/
ttrxtrx.blogspot.com
https://urlscan.io/result/474485c4-aaf6-49cd-84af-c718a7124054
address: TRyZs5aTpVrS6ZgWb1NxCnGjktxHYtrD1F (trx)
xrpxrp.blogspot.com
https://urlscan.io/result/eeda01e2-722e-4327-a77d-9b4b673820b8
address: rne6bY8h8SFEdvSezLADvVDfTiAcVov6js (xrp)
bittorrent.pro …
=> xn--hitbt-8xa.com + more

_data/scams.yaml
bittrex-m.com
Fake Bittrex phishing for logins with POST /account/loginn.php
https://urlscan.io/result/0d96d85c-06b0-4aab-97c7-b8f5e2859edc/
https://urlscan.io/result/f8afb39f-88c7-4dcc-8e56-442c8acb38dd/
https://urlscan.io/result/f62d55e4-db31-4c42-99dc-8b3e59e7fea0/
https://urlscan.io/result/b6d1192a-464d-46d4-b7be-d1623cdbaf5e/
ldex.exchange
Fake Idex phishing for key siwht GET /c.php?data=xxx
https://urlscan.io/result/a4c07bb9-2888-4fd4-a861-7327a8b96666/
https://urlscan.io/result/231dee40-c63f-44ec-95dd-95ffe90e5cae/
=> bittrex-m.com + ldex.exchange

_data/scams.yaml
electrumupgrade.org
Fake Electrum site
https://urlscan.io/result/a840554b-3958-496d-b15b-850fca2ae146/
electrumdownload.com
Fake Electrum site
https://urlscan.io/result/fa785e0e-3dda-49db-a784-0e2be8842051/
ldexmarket.com
Fake Idex Market phishing for keys with GET /c.php?data=xxx
https://urlscan.io/result/9162af61-3937-4271-954d-f0e8cc4835c5/
enjin.pro
Fake airdrop phishing for keys with POST /sign.php
https://urlscan.io/result/cac3684c-1488-4125-98b4-4c4711d1cc39/
https://urlscan.io/result/51f1ac14-c9ce-414f-b749-ab4c80849c4b/
https://urlscan.io/result/64c06f2a-2c35-4aaf-ae27-9700ab32bf85/
tronxcash.com
Fake exchange - see cryptoxwallet.net & firecrypto.info
https://urlscan.io/result/c5b49075-ff25-4baa-91be-c4ff932f16e0/
address: 3832HHXdLGBDeHWjE7VkFmWnjeJhAXAYQ2
address: …
=> electrumupgrade.org + more

_data/scams.yaml
bintrx.blogspot.com
https://urlscan.io/result/ff739523-b6e8-4a76-af56-7cbb7d8d0875
address: TRyZs5aTpVrS6ZgWb1NxCnGjktxHYtrD1F (trx)
bin-ance.blogspot.com.tr
https://urlscan.io/result/ed04e87b-576e-4574-9394-9d8881a892cc
address: 0x55B775Ea2CA493c082F3e17A8433e4D220FBB8d8 (eth)
binaxrp.blogspot.com
https://urlscan.io/result/0b0e4e5d-1558-4768-8a44-bcdccda29a0c
address: rne6bY8h8SFEdvSezLADvVDfTiAcVov6js (xrp)
itubeonline.com
Fake KyberSwap HTTrack signature
https://urlscan.io/result/2c1def52-017c-4069-9682-db240d9b8c70
unfreeze-paxful.com
Fake Paxful phishing for logins with POST /post.php
https://urlscan.io/result/4524f97e-6938-4842-ba2c-d6965a478409/
https://urlscan.io/result/bcddd030-db3f-40b6-b72b-5b62ae05618f …
=> bintrx.blogspot.com + more

_data/scams.yaml
binanxrp.blogspot.com
https://urlscan.io/result/13e8ae8a-2816-4f57-9f2c-b3fd78d6570a/
address: rne6bY8h8SFEdvSezLADvVDfTiAcVov6js (xrp)
binannn.blogspot.com
https://urlscan.io/result/2c546991-e024-4410-8ab9-c41616343d5b/
myetherwallet.com.access-wallet.info
Fake MyEtherWallet phishing for keys with POST /callback.php
https://urlscan.io/result/9c0a298f-ebc1-44f7-94be-084b0291a7a4/
electrumfix.com
Fake Electrum site
https://urlscan.io/result/ca37c42e-02f4-47ae-849b-c3dfd07640d6/
electrumsource.org
Fake Electrum site
https://urlscan.io/result/6b86eed1-67cd-4354-a994-0856282b3a28/
bltaddress.org
Fake bitaddress.org site generating non-secret secrets …
=> binanxrp.blogspot.com + more

_data/scams.yaml
vintage-myethereswallet.com
Fake MyEtherWallet phishing for keys with GET /en/c.php?data=xxx
https://urlscan.io/result/6148218e-226c-46eb-8a5d-6eb8d09fd0a0/
bitcoin-mixer.tk
Directing users to download a AZORult rar via bit.ly/2UU9FsT+ -
https://app.any.run/tasks/84e612b8-75da-4803-81e4-19a57e7523e5
https://urlscan.io/result/c8d88403-f426-407e-993e-79a53d600096/
bittrex-login.inter-cliente.online
Fake Bittrex phishing for logins with POST /acess/indexSend.php
https://urlscan.io/result/b992bb5a-fe7f-4099-b600-eb9f6dc15b1c
wallets-trezor.ltd
Fake Trezor site phishing for seeds phrases with POST /mail.php
https://urlscan.io/result/e6f8a426-bbdf-4d6d-abcb-78871fad32cf/
store-trezor.eu
Fake Trezor store
https://urlscan.io/result/4197f5f2-bc99-4626-bb22-beff41aab358 …
=> vintage-myethereswallet.com + more

_data/scams.yaml
atomcwallet.com
Fake AtomicWallet -
https://www.virustotal.com/#/url/81e6b251d36b8ec8efcb0317c246abc687fd207218ec0e9cda07448ed124ed02/detection
https://urlscan.io/result/5c7e61a2-c08c-4633-a484-fffaf8d36123/
https://urlscan.io/result/bdf40337-7d2d-4182-8870-5846e2ef5ec1/
atomcwallet.club
Fake AtomicWallet -
https://www.virustotal.com/#/url/66c8e0f91030056747096e0112816595199af1883aae42db2375453be6d70b7b/detection
https://urlscan.io/result/ca6901f3-affb-44d7-9bd3-0555dfee3a34/
atomswallet.co
Fake AtomicWallet -
https://www.virustotal.com/#/url/1334bdf1ff3f87a37d3f4fe7ef929af21609f2704804e0077c9b9e061290f64f/detection
https://urlscan.io/result/c21440f7-c048-445b-aee1-efdf49ac403f/
atomswallet.me
Fake AtomicWallet -
https://www.virustotal.com/#/url/36e7f34f8894da35bfa7252ed9d4c1702c34b9ce4c42 …
=> atomcwallet.com + more

_data/scams.yaml
rntherwallet.xyz
Fake MyEtherWallet phishing for keys with POST
https://smtpjs.com/v2/smtp.aspx? (emails to davidwatson00712345@gmail.com)
https://urlscan.io/result/7b3b1e33-a53f-4799-bb75-ff5193f9b420/
xn--medum-85a.com
Fake Medium promoting TRX trust trading
https://urlscan.io/result/d674fb6a-9097-431e-959a-148c7c5e0050/
https://urlscan.io/result/00c682a6-2747-44b3-af4f-a87e74c39ac0/
address: TVyFiVhjShJ2iwgyxiKF9A6AZXzBhErRRw
rntherwallet.icu
Fake MyEtherWallet phishing for keys with POST
https://smtpjs.com/v2/smtp.aspx? (emails to davidwatson00712345@gmail.com
SecureToken=9708d982-a2fd-4261-a28b-a5d57d12a98e)
https://urlscan.io/result/98f2b2db-1924-4579-b133-b120813c2c84/
electrumhome.org
Fake Electrum site
https://urlscan.io/result/967c6d75-9b72-4b9c-a32f-52bf178021e0/ …
=> rntherwallet.xyz + more

_data/scams.yaml
electrum.org.uk
Fake Electrum site -
https://www.virustotal.com/#/url/65ec39474cfe0827c87a650cf885552101a78f52aa3a8b30e37ccd5ac2bbf8ff/detection
https://urlscan.io/result/0195e96b-775c-4275-9cfd-8025e981b263/
https://urlscan.io/result/38ed73af-47e3-4fb7-b4de-b3b01b7aa283/
rnyuthevallet.xyz
https://urlscan.io/result/f757caf8-d5ff-4c7d-86d4-293f1da2aaf4/
fetch-ai.net
Fake FetchAI crowdsale site
https://urlscan.io/result/81b6abd3-32e7-41b0-ad74-f6bdab01857f/
address: 1BzSWghdNus1FMF55HSAMdo1u3s76Uc2aw
address: 0x56d0644c14745db2d2cE0De5c5BEf914CedC1aEa
paxfull.ga
Fake Paxful phishing for logins with POST /index.php
https://urlscan.io/result/f5f7dbb6-2ea9-495c-bd0a-86ff6ea0161a/
musk.center
https://urlscan.io/result/5fc0f4af-c26d-472e-afa0-03d32ef28b9 …
=> electrum.org.uk + more

_data/scams.yaml
paxfultrade.xyz
Fake Paxful phishing for logins with POST /login.php
https://urlscan.io/result/d65c8e98-45e1-4b78-80ae-27c9be820b1e
fetchai.eu
Fake FetchAI crowdsale site
https://urlscan.io/result/d78137ae-dbfc-4233-95f7-18ec884d4ad2/
https://urlscan.io/result/2455d387-cd9f-4283-8964-43276271be44/
address: 0x56d0644c14745db2d2cE0De5c5BEf914CedC1aEa
address: 1BzSWghdNus1FMF55HSAMdo1u3s76Uc2aw
binance-support-number.com
Fake Binance support number
https://urlscan.io/result/90f0bf92-417d-47da-bfce-b78cf4624b70
httpsmyetherwallet.com
Fake MyEtherWallet phishing for keys with POST /decrypt.php
https://urlscan.io/result/8a3d462e-870b-44cd-b3ab-d8edaa4dbfe3/
deltafork.app
Fake ForkDelta phishing for keys with POST /decrypt.php
https://urlscan.io/result/170eff6b-4ade-4266-a225-ebdaed23c827 …
=> paxfultrade.xyz + more

_data/scams.yaml
monero-rings.org
Linking users to a fake web wallet (https://myxrmwallet.com/) phishing for
keys
https://urlscan.io/result/e57087ea-f006-4eae-b6f2-da8acd05f554/
myxrmwallet.com
Fake web wallet phishing for keys with POST /
https://urlscan.io/result/c53ed140-9679-4735-b499-3126e25b3406/
binance-testnet.site
https://urlscan.io/result/c61acb92-1a11-4ed0-81bd-d5559b3e02d6
https://urlscan.io/result/15861a76-9dea-4cee-a98b-d071e9559828
https://urlscan.io/result/7a824426-b4cc-4d6a-ae83-530a5a81b96b
https://urlscan.io/result/8f3b361c-3c0e-4630-8eee-6a1451343ca9
address: 15ve8wAoinFEaq9tUzgPCU79v5qb9JmgX4
addres: 0x5584d5ab83d9E338a89769C66df095212BC528E3
electrex.info
https://urlscan.io/result/71b86bee-9182-4bbb-962e-08b45c4a2c9d/ …
=> monero-rings.org + more

_data/scams.yaml
p-eos.one
Fake PEOS site
https://urlscan.io/result/0a7ab1f9-b500-4763-8816-0b5071321d7f/
https://urlscan.io/result/2cc8df45-799c-453b-939e-4df985dc5891/
npxs.pro
Fake Pundix airdrop phishing for keys with POST /sign.php (Redirected
from x-crypto.info/pundiX)
https://urlscan.io/result/a6719652-27f5-4b58-a4fc-dad6d7ee7b8f/
https://urlscan.io/result/0f18780f-42f7-45fe-b6ff-1521b05c1bfa/
https://urlscan.io/result/a00c4590-7728-4424-99c4-3eeba3bcbfa6
ethereum-constantinople.com
Fake MyEtherWallet -
https://app.any.run/tasks/383deada-390b-41da-aa1c-04edf5df4999
https://urlscan.io/result/08589d49-ba7f-48fe-97e1-e2ff18c79e3d/
gift7500xlm.org
Fake XLM giveaway phishing for secrets with POST /butut_xlm.php
https://urlscan.io/result/59f0a157-8512-40b1-b42d-dc42c5a81358/ …
=> p-eos.one + more

_data/scams.yaml
wallet.elitetreum.com
Asking for private keys and sending to the backend via POST /import-wallet
and sending it to user email in plaintext
https://urlscan.io/result/82704121-0fc5-4149-af05-155319e7621b
dogx.dog
Fake team - see
https://twitter.com/ummjackson/status/1102780962918682624?s=19
https://urlscan.io/result/7553aaa6-4aaf-4dca-9148-bf12d18ccbea/
cryptoxinvest.com
Fake exchange - same kit as crypton-exchange.com
https://urlscan.io/result/aaa9be14-092d-4777-a217-7fb7d7e7b88e/
address: 3NGovcBojWQXjTc1m1YUji6NkuVwZi27i7
address: 0xEe18e156a020F2b2B2DcdEC3A9476E61fBDE1e48
celer.space
Fake Celer Network crowdsale site
https://urlscan.io/result/f59c59de-11cb-4bc8-9192-922ef64b203f
https://urlscan.io/result/48d989a5-7183-41e8-9e1f-a923b6ba774b
address: …
=> wallet.elitetreum.com + more

_data/scams.yaml
huobiairdrop.com
Using fake MetaMask alerts to get users to install a CX
coigcglbjbcoklkkfnombicaacmkphcm
https://urlscan.io/result/5ca20875-4a30-4870-a396-83af762c192a
get-gift-stellar.org
Fake Stellar airdrop with POST /kapuyuak.php
https://urlscan.io/result/216817aa-e43c-488c-bed2-9d3d8d90d688/
https://urlscan.io/result/2eee1474-6903-4c95-8e0c-0822f412319d/
ethers-live.com
https://urlscan.io/result/8c5cfe97-be1a-4949-ba7d-808493f232bf/
address: 0xd51B910A21F091995a2fDBc54f8ae2F981506B5f
=> huobiairdrop.com + more

_data/scams.yaml
ethersale.online
Fake MyEtherWallet phishing for keys with POST /send_private_key.php -
redirected via https://bitly.com/senerth+
https://urlscan.io/result/d9b56743-6edb-41d9-b21c-0a026ab5161b/
https://urlscan.io/result/d5d6788b-f50c-4b3e-9fc2-bc66b3f4bc3d/
kraken-login.ml
Fake Kraken phishing for logins with POST /logins.php
https://urlscan.io/result/a723b3d0-c61a-46ef-ba55-b8c4c2dc10b0/
https://urlscan.io/result/7ba42821-2d0a-485f-9762-5a12dc30f5b6/
kraken-login.ga
Fake Kraken phishing for logins with POST /
https://urlscan.io/result/093febf8-fb4a-43bc-a7b7-a56cf37e2374/
https://urlscan.io/result/99e62065-4899-46ba-ba45-eeb1dfe9b6fa/
gram-network.net
https://urlscan.io/result/d9fe7764-c2ea-401f-af3d-f752aeac0d62/
address: 12RbQmtZ1nmSndK4vxtnzmpNXjLpbjEHce …
=> ethersale.online + more

_data/scams.yaml
bitcoinvest.tech
Trust trading scam site - fake investment harvesting addresses and emails
https://urlscan.io/result/07b35ad3-c32e-478d-8c3c-ca33411cc73f
https://urlscan.io/result/73932ead-805d-4fd9-8072-bd98d1d2b562/
https://urlscan.io/result/3c5e169e-72d0-4d5b-b42d-2db128accfd7/
https://urlscan.io/result/934683b1-67b5-48a2-8bda-5c2a0aca63dc/
bestcdanje.org.ru
Fake BestChange - reported address
0xe0eEC9b102facC20e299b3adAFB20B5003a4350f
https://urlscan.io/result/87a8ec8d-7ef4-4fed-80cc-c4a6ecfc80ee
hmqfoundation.com
Fake HMQ crowdsale site
https://urlscan.io/result/eb0cc621-2006-4872-bc6f-a50972304486/
address: 1LvNgSpd58Dj8oujCJHr9PsVBFch71Y9Me (BTC)
address: 0xc1b439273B8Ba8ab5489d5Ed945F559f90d92988 (ETH)
address:
47v1cXsUdPN6vLeCwzCFAbAw8VjNEoMXSfLMpGkg76z9jPVM1wxxpmmjUvGDxnZQak4TqDM1 …
=> bitcoinvest.tech + more

_data/scams.yaml
kraken-com.ga
Fake Kraken phishing for logins with POST /logins.php
https://urlscan.io/result/5cb66131-0a63-44cc-bf08-cb19da93bd39/
exoduswallet.online
Fake Exodus wallet -
https://www.virustotal.com/#/url/2b4cae74b5ddc266bbfba1c3f9f816d13c083bb4c00f3579b5da3e29a5560e3a/detection
https://urlscan.io/result/2dddab9c-eea8-47b5-bb45-e700126c80fb/
https://urlscan.io/result/c9101add-147e-4efa-ba0b-67755b4bce83/
bitcoinarmory.tech
Fake bitcoin armory site (HTTrack fingerprint)
https://urlscan.io/result/c265b5b8-42dd-4ef5-a33c-b19376c35870/
celer.today
Fake Celer crowdsale site
https://urlscan.io/result/1a4805db-7cbd-40e6-b716-dae23f94264b/
https://urlscan.io/result/a083b764-9a0b-45da-8fb1-ebae9021e043/
address: 0x0669398307EfeFB60030ff328a0cB6A3A840182c
celer.site
Fake Celer crowdsale site …
=> kraken-com.ga + more

_data/scams.yaml
celerc.network
Fake Celer crowdsale site
https://urlscan.io/result/bddb1381-2413-40ad-8636-8d9547c20dc2/
https://urlscan.io/result/19fa0d2b-184a-4167-a40e-e228c7a6d858
address: 0x70A1d170d055d0B5eddA1056747119550cfc40Cc
address: 1BzSWghdNus1FMF55HSAMdo1u3s76Uc2aw
electrumproject.org
Fake Electrum site -
https://www.virustotal.com/#/url/180557c8ee08b9dc8bf7b0fa191980c9150e94878260fd8ac686bbd2e704904d/detection
https://urlscan.io/result/01cc8abb-b000-4e6a-88a5-c4beb0556df0
https://urlscan.io/result/c7edf944-4dba-4224-8d91-991b11d8e715/
idex.money
Fake Idex phishing for keys with POST /send_1.php
https://urlscan.io/result/5981655e-d339-4f13-96dc-3de260bfc108/
https://urlscan.io/result/362a8f8f-edfb-4b65-9d98-17a8aa8fba3c/
https://urlscan.io/result/64caa884-b3de-4499-ad96-8bfb7615a74e …
=> celerc.network + more

_data/scams.yaml
wbscoins.com
Fake exchange phishing for KYC data
https://urlscan.io/result/331a71c1-bf4f-48bf-bd1a-db6fcf7e11a5/
neotracker.me
Fake NeoTracker
https://urlscan.io/result/250bbcfa-6c0f-454e-97f4-883e71664d87/
gift-wallet-stellar.org
Fake Stellar giveaway phishing for keys with POST /kapuyuak.php
https://urlscan.io/result/5ed2a589-2aef-47e8-8b90-9e9ccbea36de/
wasabibitcoinwallet.org
Fake Wasabi wallet - https://redd.it/b3qcrv
https://urlscan.io/result/29d1fac2-7344-4f5f-88cf-9a772fcb4577/
https://urlscan.io/result/ed4ab77a-7459-4bad-b126-833515e5e133/
usddex.io
Token sale of stablecoin, now ghosting everyone
https://urlscan.io/result/d146bb91-9723-493d-ac8d-a2ae4dfeef84/
address: 0xaEa3846E14beC1ba8F562844d39b1215A1D588C6
mithril.pro
Fake airdrop phishing for keys with POST /sign.php …
=> wbscoins.com + more

_data/scams.yaml
ildexmarket.info
Fake IDEX phishing for keys with POST /log.php
https://urlscan.io/result/545391a7-4707-4c90-9e52-a69bb293f058/
https://urlscan.io/result/862b2a78-57e0-46b9-94e3-8470b603b767/
bitcoin-gold-blockchain.info
Fake blockchain (bitcoin gold branded) phishing for keys with POST
/php/send.php
https://urlscan.io/result/aa50f4bf-0add-430f-a288-85e0206964a9/
https://urlscan.io/result/5b273551-9dba-430f-baf4-76f8199917f6
https://urlscan.io/result/9ca3e282-7171-4237-9d92-fd8ad3e6691d/
100x-mlt-btc.com
https://urlscan.io/result/40633505-17d7-4393-a4ba-cb1cb904600d/
address: 1DZjEc1xRnEszyXwBbH27NEajrgcqX8emr
constantinopleplus.io
Scamming users - fake partners
https://urlscan.io/result/eb4a5f0a-6a0b-40bd-8bf8-f4b6d3ae9269/
address: …
=> ildexmarket.info

_data/scams.yaml
paraetherwallet.com
Fake MyEtherWallet phishing for keys with POST /paramining.php
https://urlscan.io/result/a39c1872-3113-4262-bfb1-7c8723682fce
https://urlscan.io/result/ceb53bd7-aee1-4549-bee3-ae40785f2fc8/loading
earnfreebitcoins.org
Fake bitcoin minter
https://urlscan.io/result/3b4cf6f0-78d3-41c6-bc50-5a89c22846ea/
address: 1Q3EfbS5j9DBndLFqVGJPpd7qCmzXuRe8T
myethyogawallclass.icu
Fake MyEtherWallet phishing for keys with POST
/vintage/apl.etherscan.io.php
https://urlscan.io/result/cdf645d4-88dd-450c-a8ef-e2e5dca7d6aa/
https://urlscan.io/result/c285333b-da57-42ba-8c07-2517f4d6dd6b/
wowx.io
Hacked ICO page (requires KYC) blocking until they confirmed recontrol
https://urlscan.io/result/a6cc351c-566e-4cf1-b976-d393b1c4fbde/
https://urlscan.io/result/05c6e965-92ea-4313-bb7d-9dec10e9bd9f/ …
=> paraetherwallet.com + more

_data/scams.yaml
myethantiwallcafe.club
Fake MyEtherWallet phishing for keys. Suspected address:
0x18ffda6e10338378159411135f78bfa98f18298a
https://urlscan.io/result/b70e9f54-1c31-45c9-9660-d07c34f669c4
ripplebonus.blogspot.com
https://urlscan.io/result/8ec8edc9-b6b6-4bba-a299-3560aa2d9848
address: rhTCdpaZQSKbHNYY85xPLMEWQbyxYr4SFY
idexx.site
https://urlscan.io/result/45f68220-b850-433b-927f-720a938ebdc5
https://urlscan.io/result/e26b8059-30f9-4b7d-abf0-66e0feefe7d1/
kucoin-activity.com
https://urlscan.io/result/7bc2e956-3b89-44f3-885c-761166473871/
address: 0x6f431A1B6c368cD3ABB7BAcDCf0625D6749F1980
ethereum2.online
Phishing for secrets with POST /send_private_key.php …
=> myethantiwallcafe.club + more

_data/scams.yaml
bitcoinru-wallet.site
Fake Bitcoin wallet phishing for details with POST /mail.php
https://urlscan.io/result/3ea495de-0f0f-4d17-b18b-97e7921534b0/
bitcoin24-wallet.site
Fake Bitcoin wallet phishing for details with POST /mail.php
https://urlscan.io/result/6ed0502b-9a9e-4eb6-b4c4-1ebf904a47ca/
blokhchian-wallet.xyz
Fake Blockchain wallet phishing for logins with POST /./
https://urlscan.io/result/cfa495c9-2be3-4c2f-9dc4-d13a90775d86/
bloclkchaln.online
https://urlscan.io/result/9118f6ed-9a09-4866-8400-088b38051c3c/
gram.one
https://urlscan.io/result/9f8c3c83-7beb-4b8b-a7bc-8f18277b4f12/
address: 1GvEMyf8CidhNi3zZXb3VpP6mbxvdRSmq6 (btc)
address: 0x482729ad79e5da6c48c0e7a4b3e67ba13ceb7404 (eth)
address: …
=> bitcoinru-wallet.site + more

_data/scams.yaml
gruzovyespecavtovesy.online
Fake MyEtherWallet phishing for keys with POST /apl.etherscan.io.php
https://urlscan.io/result/4a5683bd-7021-4b23-a5ac-4963fec5dd8a/
https://urlscan.io/result/6efcfe81-917f-4dc5-9ef4-099f675eba20/
gdax.us
Fake exchange (same as your-btc.co.uk)
https://urlscan.io/result/d83e522a-136b-4f54-a99a-7e36092f98e1/
https://urlscan.io/result/50043a43-f60f-4d0f-a48e-f74be960f5c6/
address: 1Gj9TYmGjCFsNjPrkDcauGEMewiX2YSbDL (btc)
address: 0x0bb4251b8c5e8acb27d6809d77a10aa1cacc5144 (eth)
address: qzh7l8neh3v868uzu74qpyat4gjz2rdv0yhjktqcp2 (bch)
hillstrade.net
Fake exchange (same as your-btc.co.uk)
https://urlscan.io/result/b2dbf1d4-2148-4e69-bcfe-eb808a9f15e1/
address: 1LPTQoiGTDmbrLB76g5w7ceJa4wShPAG9Z (btc)
address: 0x84a8e201cfce8a10b1e721e1940a78a3326b7c97 (eth) …
=> gruzovyespecavtovesy.online + more

_data/scams.yaml
dex-launch.com
https://urlscan.io/result/026541e0-ed85-4e86-962c-4da56e6b60fa/
https://urlscan.io/result/3f4a029e-5945-4c75-9d2c-c738a50f1dfb/
https://urlscan.io/result/b77b1ee9-c855-47c2-a271-804e4277dd5f/
https://urlscan.io/result/d099bcff-fbef-41c8-b916-7671ab547d7f/
address: 1PgkghXGCzPbaAzU4kfaRnmqrnsr3iZgWi
address: 0x8bbA1a1c5e9F72C2CE97A240A7878Dd4AE803b61
digitexfutures.com.claim-token-dgtx.com
Hosting a fake MyEtherWallet phishing for secrets with POST /claim.php -
see https://twitter.com/myetherwallet/status/1118207507455889409
https://urlscan.io/result/0820fd82-244d-4659-a745-42e1d01c44e4/
https://urlscan.io/result/18ce2b13-39ca-4ba1-9cce-317adf42d3d2/
bin-dex.club
https://urlscan.io/result/09a2cc6d-2bc3-4e87-a15f-385b062aeee2/ …
=> dex-launch.com + more

_data/scams.yaml
buterin-promo.info
https://urlscan.io/result/3a14cf4c-604f-4eaf-83d1-0a481c6ef513/
https://urlscan.io/result/a7e3f131-4c2b-4b43-b2bf-b0aa1cb93fa9/
address: 0x7Aca311F96b05B944511cDE7891702784E2a50aE
matic.live
Fake Matic crowdsale site
https://urlscan.io/result/ef63099e-4f70-41a4-b5cd-bf6f54ec676a/
https://urlscan.io/result/96c15c92-3a01-4b8e-960c-edbbf2321cba/
address: 0x64B57f49A854533722435652054d0F924f7aCDe7
bountyxrp.blogspot.am
https://urlscan.io/result/a1873c6e-e01b-4473-9d68-e3a6c8351b3f/
address: rhTCdpaZQSKbHNYY85xPLMEWQbyxYr4SFY
bountyxrp.blogspot.com
https://urlscan.io/result/a1873c6e-e01b-4473-9d68-e3a6c8351b3f/
https://urlscan.io/result/02ccfbb0-0abd-439a-b8d8-70b0d204104f/
address: …
=> buterin-promo.info + more

_data/scams.yaml
btc-gift.com
https://urlscan.io/result/ce46540e-e452-4c69-81bd-9c7752170084/
https://urlscan.io/result/8e5ca287-0a83-4e82-af69-b113a882b8ca/
address: 121p6887pfo6Fx1axCapkuvdqHdWMcYKp1
idex.pw
https://urlscan.io/result/d85fc44c-5e4c-46f0-9361-852cf837602a/
https://urlscan.io/result/b6ab2ae5-e52c-4313-af4c-3c9289e121d7/
trustswallet.xyz
Fake TrustWallet site
https://urlscan.io/result/0bd67a55-7734-4dfc-90c8-525e15f2dccd/
coinpromo.fund
https://urlscan.io/result/fee23e44-bb39-4787-b317-0ce0d1d5ab0b/
https://urlscan.io/result/896ba613-2082-440f-b908-ead2410e2b9b/
https://urlscan.io/result/db282e63-5050-4cc6-8d73-afec361f2569/
https://urlscan.io/result/cb13e2df-b8b7-4e2d-87d7-28bbacb771e9/
address: …
=> btc-gift.com + more

_data/scams.yaml
client-tezbox.com
Fake tezos wallet phishing for secrets with with POST
/mydashwallets.org/tezos/seed.php
https://urlscan.io/result/1d1494f4-3c83-40c5-9662-85e38ea45346
mybitcoinqrcode.com
Fake bitcoin QR generator
https://urlscan.io/result/f2eb6721-04aa-4220-9832-776870db1718/
https://urlscan.io/result/4d27d394-6b27-43a7-8412-2b54a7ac506d
address: 17h3y4KNfh2U6vgddQTTFDz1paqfX54s5z
official-elon.space
https://urlscan.io/result/3bfed510-d0ee-4b6a-b678-ead67ff3b483/
https://urlscan.io/result/d10961cb-579d-4400-8421-1cd3a601dced/
https://urlscan.io/result/cb47e9c0-7e43-4e33-bbf6-5b7aac96cb91/
address: 0x40F726d6D1b858824061ad96E88101231216C7d0
address: 1HdVcd5HPieFXFwz4ybhRuPzn3kMnmv3eZ
airdrop-running.info …
=> client-tezbox.com + more

_data/scams.yaml
idexx.pw
Fake Idex phishing for secrets with POST /log.php
https://urlscan.io/result/b097498b-9b57-4c23-9eab-45dd0fdd5431/
https://urlscan.io/result/d6e0a15e-dfa1-43b4-ab97-37d19ba3a7ec/
exmo.in.ua
Fake Exmo phishing for logins with POST /login.php - hosting malware
https://app.any.run/tasks/73b283ff-ee2f-4e23-ac14-4c7ce9e17795
https://app.any.run/tasks/a13f7c6b-4f9c-411b-87d7-f9293347e013
https://urlscan.io/result/2f003853-1f9b-4036-ab5a-697a67a5a617/
https://urlscan.io/result/ec13d4ab-35bc-4a68-9084-8a429427b5f8/
https://urlscan.io/result/d581e690-4563-466d-b5cd-553d837e9c1a/
tesla-gift.space
https://urlscan.io/result/47d2b133-c34c-4677-9c4e-ecfa9f767935/
https://urlscan.io/result/c1904720-7731-4221-85ee-12c4784fa220/ …
=> idexx.pw + more

_data/scams.yaml
btc-pro.co
Fake Trezor store phishing for secrets with POST /home/mail.php
https://urlscan.io/result/ae703212-ebfd-44a8-bd6d-fba332fca104
https://urlscan.io/result/9c41dcf5-30f5-4f5a-b2f5-c062f634562b/
https://urlscan.io/result/2c18eea4-384d-432b-89c3-5f8add477540/
platform-bitmex.com
https://urlscan.io/result/4524225e-4567-4a27-852b-a49df048394a/
https://urlscan.io/result/0fb2ea0d-cd97-4d4e-98b8-3e26e42ab3b7/
https://urlscan.io/result/73fbc7d3-a857-4a59-bc64-32a0854fe86c/
address: 1MghhGjVABo5NrBjXMmyYsydsuvLVVRG35
address: 0x760774022517950FC1874B66Cc71a83752F2fa89
constantinoplehardfork.cf
https://urlscan.io/result/e2012213-8393-4a9e-83ca-829b6ea434d3
https://urlscan.io/result/f241b706-95a2-489b-8d01-20f977712c61
address: …
=> btc-pro.co + more

_data/scams.yaml
receive-ethereum.com
https://urlscan.io/result/e4a2e62a-f3ae-4dbb-8f30-b47fb3ef67e1/
address: 0x0f746E54EE888E9953aDa918D4bA02AC696b1147
dextestnet-binance.com
https://urlscan.io/result/31226c40-86d2-4f0b-b33b-a976b2fe3ca6/
https://urlscan.io/result/a8bf8e86-6bd6-40c1-87ee-d745a5d292c6/
https://urlscan.io/result/6d69faa5-571c-4516-b33b-2a49e7b2fc16/
https://urlscan.io/result/6bd2d9b4-a44f-4dfc-85fb-860fb12f2d2f/
address: 12MkxkxyCuzQcHc74NUw9rDjFoiPkFnHzz
address: 0x83e8846bb3e2D3167C65d5C41CF2a4cAb23E6197
dexbinance.in
https://urlscan.io/result/d2a8d93d-fecd-4129-8f2c-3861f9ab9944/
https://urlscan.io/result/9bf590d5-7629-4771-b923-aea30796e743/
https://urlscan.io/result/f0c4e499-7f70-4131-a040-9c089c4870f9/ …
=> receive-ethereum.com + more

_data/scams.yaml
telos-fundation.io
Fake Telos foundation site harvesting EOS usernames
https://urlscan.io/result/1694d9e8-bb38-4547-b32c-0819dda251ea/
https://urlscan.io/result/0eb0d7ba-a7c9-4fa0-af2d-1a23d15fc06e/
mycofterwallet.com
Fake MyEtherWallet phishing for keys with POST /sending.php
https://urlscan.io/result/58664401-8e5f-4e0c-8a07-bf7941701e6d/
promo-tesla.store
https://urlscan.io/result/05270bd4-fbf9-4151-a22e-19c533a98734
https://urlscan.io/result/386ba0ec-0e92-42d4-ba88-694e172b0f2d/
https://urlscan.io/result/bfad079c-c865-4f7a-9a50-3275a89983b3/
address: 1KfEHjqt9v3hJD1Ru7rYnMg32z6C6Nh93H
address: 0xF36965e734ce6F1AbE3b66F0F819B3a8A9bd547C
cryptogiveaways.top
https://urlscan.io/result/246881a2-b807-4834-ac0a-22116a9e6737/ …
=> telos-fundation.io + more

_data/scams.yaml
binance-margin.com
https://urlscan.io/result/08ba4fd9-160e-479a-9d8e-1a318fdc97cf/
https://urlscan.io/result/d62612e4-e4cf-49d4-9d11-ad596815ebb8/
https://urlscan.io/result/d21fec12-60aa-4088-bf63-f3becfff4b1a/
address: 13YacKcXWpeFgEwY3M5EMnZVZn8A84mu5D
address: 0x59CbD436237318F7Cb9C92ddB060b1a023598363
iidex.pw
https://urlscan.io/result/8527f675-cf04-40cd-959d-40c1bc68324f/
https://urlscan.io/result/79ecd415-2f09-4094-828b-e48db15bfa87/
id-ex.pw
https://urlscan.io/result/389eaac3-5d15-4ac3-910c-2f50ecc0b726/
https://urlscan.io/result/c5834c18-35c0-44ea-bf41-afb2a0b95251/
binance-client.com
Fake binance client - offering malware …
=> binance-margin.com + more

_data/scams.yaml
Fake download of MyCrypto -
https://twitter.com/sniko_/status/1135893510878576640
https://urlscan.io/result/aa15f5d4-17d7-4b5c-8878-80b9894d8bb1/
dogepay.info
C2 server for cryptocurrency malware -
https://twitter.com/sniko_/status/1135893510878576640
https://urlscan.io/result/accb3155-b918-44f9-bb75-d2e302b7bdc7/
https://urlscan.io/result/20a69dad-bb34-486b-b314-caeab61026f4/
https://urlscan.io/result/1d7ada8e-fac1-4c29-b240-811b8347643d/
iddex.pw
Fake idex phishing for keys with POST /log.php
https://urlscan.io/result/6a9a307b-cac6-49b6-87c7-8d2050f4a4eb/
https://urlscan.io/result/5546fcf1-1147-472c-8c16-93f64b2b8c76/
localbilcolns.net
Fake LocalBitcoins phishing for logins
https://urlscan.io/result/30447a80-c875-41a1-9472-ce7a38470dc5/ …
=> mycrypto-wallet.info

_data/scams.yaml
mcafee.site
https://urlscan.io/result/fad7d7d5-75e5-4be0-88ee-5c67a3c6ac74/
address: 0x0EB3c94e03DbfC2b7CF50dcfA0173bc53e1d4185
john.mcafee.getforge.io
https://urlscan.io/result/9c41d2bf-a2b8-4895-a9fb-efbed5257629/
https://urlscan.io/result/6326ae22-6822-46d5-90ac-31413e35f993/
address: 16cBDFXSMMPbiJ3kW4DrW7tj1toPE1311t
address: 0x0621871F8636ab81abD3bA6D06d807B330C35FF3
news.binance-app.org
https://urlscan.io/result/695b9a03-b8bc-439c-8b47-29e2894aa6ea/
https://urlscan.io/result/2b2aa033-a22c-4bf2-ae86-726dde712827/
https://uploads.disquscdn.com/images/101a197b8cc57290806a0e9d74366ae433b460944cdc5f3f03420912414a5046.png
address: 0xcDEa1b9b05E383F13028551E934eCc65208a65b7
address: …
=> mcafee.site + more

_data/scams.yaml
mediumcdn.today
https://urlscan.io/result/be902435-0946-442e-9c11-136182614dc7/
address: 0x0CD4ea9B68CEd287Fc25923B071C0b1a0a14e9c6  (eth)
coinexminer.site
Scam investment platform
https://urlscan.io/result/13115683-2892-483c-9e9f-7049303e98e1
address: 1DTjjxNfdgAT8cGuHpuCR4v4zwzxjwXN8Z (btc)
bit-donor.com
Scam investment platform
https://urlscan.io/result/3762466d-53df-45cb-bab3-a4eebd799a7e
https://urlscan.io/result/359ea00e-1478-43ec-9546-4cbc23947d92/
address: 1Fr2VJ2pgMsAktcLonHUqBnZbu7H1zZLpH (btc)
sf520pk.com
Stealing mnemonics with POST /api/find_by_mnemonic - see
https://twitter.com/sniko_/status/1140759034292838400
https://urlscan.io/result/23c2d916-8884-4138-858f-79d8b00a0550/
neojune.blogspot.com …
=> mediumcdn.today + more

_data/scams.yaml
starcoine.com
Fake exchange
https://urlscan.io/result/71ccff49-ae5d-4d77-a685-5451a3245e50/
address: 32sPuzVsc1HmJMaXr47GkNSKoMDxh89J2f (btc)
address: 0x55C556aE081b7c3dE12127d6Df9802698B301898 (eth)
cryptohype.world
https://urlscan.io/result/5b9448c4-58d1-45b7-9b48-e0458d3f0e90/
https://urlscan.io/result/e7e83b1a-ced6-4c77-8c07-41303ce9caf3/
https://urlscan.io/result/f8f79a15-3334-4f4c-ae91-79a4775df138/
https://urlscan.io/result/9342e133-bfc8-46d4-a2de-3d9b773708c3/
address: 3AX8n9zGBeeDmQRXaxQZnNR67sNyEwcagh (btc)
address: 0xa9fa7065701181d2D62234BAdeA16a33052FEA22 (eth)
address:
4AWa1ny75eoCcUVQWaWzL6Lp3WHZrFc3HVj9J8x1yautRYGkPLXUn72VP62HkF7oU4UqHd2nDLWhUWfx3F6cvekDRF5v5um
(xmr)
eths.gift …
=> starcoine.com + more

_data/scams.yaml
idax-market.ru
Fake Idex phishing for secrets with POST /login.php
https://urlscan.io/result/6b7ff624-7524-47b9-b9c2-eadfdea6f0be/
stopp.com.au
Fake BlockchainInfo phishing for logins with POST /check1.php
https://urlscan.io/result/eecf1f53-06e6-4bcc-a035-339b26ff34ab/
promo-from-buterin.site
https://urlscan.io/result/080fad9e-2a49-4ba5-85a5-99eae66d09f5/
https://urlscan.io/result/c3a2816b-ac55-4367-8b65-20ffa370bfc6/
address: 1KJYEvDADrvyT2TzZNCpBkF8m9fAbrVjhQ (btc)
address: 1JFg9MfdXBTyNVZZCCB6HBmsSuTyEKN1rk (btc)
address: 0x59c26dA37e1a97EEccc9Fe9Ae35E3FC2DF6Fb582 (eth)
address: 0x06d782793e8B14c7b02baB9b139D8E296995F292 (eth)
bnb-zendesk.com
https://urlscan.io/result/e6c4f683-9ec2-4747-a1e5-ef1f0e5afe26/ …
=> idax-market.ru + more

_data/scams.yaml
junecoinsx2.blogspot.com
https://urlscan.io/result/9ff8186e-35bc-4b9b-a90c-071ff146bdb6/
https://urlscan.io/result/2ad20259-d159-4fd0-848c-af1f1d36cff7/
https://urlscan.io/result/964c0169-5d26-4098-894c-3c71186edb5c/
https://urlscan.io/result/9856356b-ff7e-45f0-9cbd-4973eaf52f25/
https://urlscan.io/result/da3a0650-6a1f-4d19-a703-7b02a644451a/
address: 0x80f43E67169c917c68391F823FcFf41b9B786D69 (eth)
address: bnb12vfz64rxhtmjp85nwuq09fx6976g7smvzwdm9x (bnb)
address: TRyZs5aTpVrS6ZgWb1NxCnGjktxHYtrD1F (trx)
address: rhTCdpaZQSKbHNYY85xPLMEWQbyxYr4SFY (xrp)
cryptexplatform.com
Fake exchange
https://urlscan.io/result/8dd86a5f-17af-4a6b-8922-acb6ff09ef63/
address: 3PWzgL8n9NoK4SxratetDABid2bFgE8ftW (btc)
address: …
=> junecoinsx2.blogspot.com + more

_data/scams.yaml
bigdrop.pro
https://urlscan.io/result/1bd09efb-c9f6-4b87-af5b-334f0227ac4b/
address: 0xF738D0B7E34d7B5A63d8e0CcFa25a0d9d4271816 (eth)
medium.exchange-promo.fun
https://urlscan.io/result/352a6573-7730-48df-8480-6015c6a1e35e/
https://urlscan.io/result/a1d77926-0574-438a-9b0a-d4cf40e79d21/
address: 0x964c31AF5B240faC67fe3C1105537D1647050a63 (eth)
address: 1LLiTbEQE1jUayUKyeyokYCYBEi5rZ1Ghx (btc)
pompliano-promo.netlify.com
https://urlscan.io/result/be892396-0894-4744-8d2d-3cd8b0d27fa6/
https://urlscan.io/result/de7a8889-7001-4868-8576-02deb762d7b7/
address: 0x030a027cdd6994a712fbb1efd6d36369ec7cca89 (eth)
address: 1EWdps7P7o2u616u9a36CK6Jjnbr1A2HUJ  (btc)
coinbase.getforge.io …
=> bigdrop.pro + more

_data/scams.yaml
coinbasepro10000.webcindario.com
https://urlscan.io/result/780a550c-55a4-4d70-be80-bd6b2d47ffd4/
address: 0x00650a784EE109797BA8C05F3496bDbF2b2B7a1C  (eth)
neojulyx2.blogspot.com
https://urlscan.io/result/529d1d5c-a25b-48f7-8601-f3a3c5e04ce5/
ethdrop.net
https://urlscan.io/result/c10a9387-36e9-45e5-8c7b-21cadb09c57c/
address: 0xd8F203a2cFD7C647Cd5a6619E90003724895d570 (eth)
eth.gift
https://urlscan.io/result/92a5eede-10b9-4626-9d49-5974fba46969/
address: 0x6a3482D5e573B9a5C26ECac634CD77C83D30948C (eth)
chainlink.pro
Fake Chainlink airdrop phishing for keys with POST /sign.php
https://urlscan.io/result/c5836fae-bbf5-409d-8438-b64d39cc1c60/ …
=> coinbasepro10000.webcindario.com + more

_data/scams.yaml
hitbtc.co.ua
Fake Hitbtc phishing for logins with POST /login.php
https://urlscan.io/result/4943ee46-374b-4ca2-84a6-092d3d1620e1/
https://urlscan.io/result/d2b44d2a-1713-450c-94a2-e230da093598/
binance-claims.netlify.com
https://urlscan.io/result/475b914e-875d-421c-8322-aa16cc8f0846/
https://urlscan.io/result/ec0bf44b-86b0-4159-960e-629303c6a64d/
address: 0x0eB1e76F51517c0c04a6994E41C10B3D81794D04
address: 198hbS6FzPjKnTe7YoHLmyKRP2nvbNeqWA
eth-btcpromotion.online
https://urlscan.io/result/d9d5ba5c-a9f5-418f-aa86-301d10dac200/
https://urlscan.io/result/0097de04-3861-4fc1-beee-2f47c401838e/
address: 0xe33086e461749C687c2DDC3ec4EB24EA591c0dc7
address: 1GoX4gtrUyPBSPGYKJPx6WXonPD2YTZnSe
ethcharity.net …
=> hitbtc.co.ua + more

_data/scams.yaml
bitcoindrop.net
https://urlscan.io/result/d2dc6e31-6d5a-4c7c-971b-acc26e76a939/
address: 1LUUyyRDP6AjDUJ7D7iG2LA1jPGoTnKamy (btc)
binancepromo-now.online
https://urlscan.io/result/b36fd22e-adb6-41e0-88a8-fbfa5cdceb50/
https://urlscan.io/result/8e27c233-8708-4a7d-bef6-3f64afc52a90/
https://urlscan.io/result/f1294e3e-7277-4f3b-b9a8-5b7f18bc31fd/
https://urlscan.io/result/6d0c6bed-d25a-4807-8ff3-e6adf0c7a528/
address: 0xe33086e461749C687c2DDC3ec4EB24EA591c0dc7 (eth)
address: 1BiyLYjfDNQSP81uvr5gzNW77P2viGWi8m (btc)
giveaway-crypto.tech
https://urlscan.io/result/adb8fc08-18fb-43eb-8314-a50c6cf05c1f/
https://urlscan.io/result/e2240663-35fa-4fd9-9e2e-5272d2c8e65b/
address: 0x6DE7ee53947515Fa163BdcB7e63411449eCe2C82 (eth) …
=> bitcoindrop.net + more

_data/scams.yaml
btcholiday.net
https://urlscan.io/result/c28ab2fe-3a83-4f44-8d25-dd3563bf750a/
vitalik.cf
https://urlscan.io/result/590b0d96-4789-417f-b6fb-5646e5300dc4/
address: 0x738a8589924B5C924997DDFB23238064eD238920
ether-give.org
https://urlscan.io/result/2a0c5b92-bc53-4ced-b5cc-88be7d873cad/
address: 0xf9c87DCf56598cE676FDdA2FEbfDB3Eb45e5007E
idexx-market.pw
Fake Idex phishing for secrets with POST /log.php
https://urlscan.io/result/e7bf7e80-a405-40cd-a069-f15fad4df68b/
https://urlscan.io/result/0ccf0064-8f54-41e4-aa69-4017af1ad38d/
bittrex-global-site.com
Fake Bittrex phishing for logins
https://urlscan.io/result/be02ee81-3452-4b19-b1aa-7a452085ff60/
https://urlscan.io/result/f0079ab5-40e0-4e95-a9b3-11330977c64f/ …
=> btcholiday.net + more

_data/scams.yaml
eth20.org
https://urlscan.io/result/7fc62296-45d7-445c-9f40-3db2605fe805
address: 0x027A46b6cD1E80dF60F5Cf0f22c3f3Fb899B2EFD (eth)
binance-bit.net
https://urlscan.io/result/c9a27441-7e13-4950-b656-7f449b2f20d0/
address: 1NM4VJ9deWtjLq8zPKVop5rwCHjLdynTnY (btc)
extravaganza-event.website
https://urlscan.io/result/2323b5ba-1be5-4f5d-8186-f9548b459ba4/
https://urlscan.io/result/e8702d72-a2da-483c-a42f-bbb085e9e531/
address: 0x714b56C2454E2EF5E908daA7CCfcE1A73184F2B9 (eth)
address: 1M2vwn8f93hEJwM4Pd4Wak59HeHkRK842d (btc)
teslapromo.info
https://urlscan.io/result/170940e7-f844-4fd8-8b52-f8c5391c73a8/
https://urlscan.io/result/5f777740-11ce-4ad3-9140-e5974f097674/
address: …
=> eth20.org + more

_data/scams.yaml
elon-musk.xyz
https://urlscan.io/result/e5269bcd-a21c-46e8-8464-fe34576ae0a0/
https://urlscan.io/result/3c601577-5762-43ae-bf27-e57c5f0f0fd9/
https://urlscan.io/result/fa8708ab-ffc9-419f-bc67-9236088a7bc5/
address: 0xaaddf2d14ef347360f50c50f2337a1fb8a673eb1 (eth)
address: 134BbK9A35erMCMvn8khA7JxkSoohwGTRq (btc)
bllockchain.tk
Fake BlockchainInfo phishing for logins with POST /hitler
https://urlscan.io/result/b214dd1e-09f0-4da0-97aa-ccb4dd347f6d/
hiltbtc.com
Fake HitBTC phishing for logins with POST /login.php
https://urlscan.io/result/dd2835f3-f86b-4e3d-a6fa-de810e9934b5/
login.bilockcnain.com
Fake BlockchainInfo phishing for logins with POST /sess.php. Suspected addresses: ETH: 0xE8f42CB54991a25EAe58d2602F21C8d5d5105a7D BTC: 1Hg5ahckVEJRLC3Y4hcMkPYTgw8V2cCRpd …
=> elon-musk.xyz + more

_data/scams.yaml
bitcoingift.net
https://urlscan.io/result/ac826801-da0c-4de6-a02b-160d8ec6640d/
address: 1Mb3rqiT9cSFYMipdA6T4xWb4z2GAXXrJN (btc)
x2neojuly.blogspot.com
https://urlscan.io/result/5f13f56e-ee51-4361-aeca-376d02ea6815/
address: ATVMaR3SXKRBtwCNgPjV5k2YzEgzMDYeaf (NEO)
celebration-binance.netlify.com
https://urlscan.io/result/d58e8449-3f34-4d27-b62d-9f0883d6f94c
https://urlscan.io/result/d53ef774-a1d6-4f0f-8191-0934fe1516bc
https://urlscan.io/result/8b9e5e97-be58-4dbd-967b-a53a5ddbaead
address: 0x3869Db12591382eD94Eefe6b55c4e82C6b8c1489  (ETH)
address: 1PfgLydXR2MAg21hNeUJL5LdxFmDeS26Lo  (BTC)
---
binance-bit.net
https://urlscan.io/result/3662080b-fe00-4b76-b81e-6961ecb8b1a8/ …
=> bitcoingift.net + more

_data/scams.yaml
binance-promo.netlify.com
https://urlscan.io/result/cf921f23-b5ac-420b-9979-4e5b3ae0efc9/
https://urlscan.io/result/30439018-f356-46af-ac97-3d765be5a87d/
address: 0xB93184F8cFd3012E77114c93BF6ef08e9D6779A3 (eth)
address: 13kg4Ah7vhMXeaHhDhqRVkETnWscTTFMv2 (btc)
=> binance-promo.netlify.com

_data/scams.yaml
binance-gives.com
https://urlscan.io/result/505ab960-af4f-43d9-8df4-b6dd32263532/
address: 3Jhqy7b9gYo3i1HLZT4HFMcCf74CFoE7UP (btc)
binance2.vip
https://urlscan.io/result/a0787617-d970-4d68-97e8-2b9b0d76c44b/
address: 1A72oXVqv2t3mzir26tFNrtCXZ8MyvzaDa (btc)
5000drop.com
https://urlscan.io/result/9d6b37c5-f53b-4e9a-a23d-2a1b8c0ea0e7/
address: 13mXSgBUrKKjuJZ9bcofCwf5abbPMzmox4 (btc)
getpromo.me
https://urlscan.io/result/37909263-633b-4c99-89d9-fdd24591d2f6/content/
address: 1BVnXUv6HprtrjGnrceMr9y1wRhDuMSr2Z (btc)
siawallet.io
Phishing for secrets with POST apps.simbla.com/parse/classes/consensus
https://urlscan.io/result/aeda09f4-4a97-4e10-9c5c-56c8b53e7588/
dothereumwallet.net
Fake wallet …
=> binance-gives.com + more

_data/scams.yaml
binance-team.com
https://urlscan.io/result/b87dd5bd-0c35-4139-9bfc-4720bb4ea553/
https://urlscan.io/result/fc2c5b83-1e7b-4970-9395-d7867a51abe4/
https://urlscan.io/result/15962123-1c0b-4a85-bd4b-a2440359b2bb/
address: 0xF4c996752C0346dA4D290553fD58b3fcB6774ed6 (eth)
address: 1CDH7oUUxMyo6T5QHovu82ygUEXpQ5rgWV (btc)
binanceteams.net
https://urlscan.io/result/8f53cec4-e2d0-456a-8086-7556437111a1/
address: 1Mn386ue8o3mW9866octLNP8HFqcYsphJC (btc)
binance2.epizy.com
https://urlscan.io/result/d0770782-8b5c-4093-aade-d7f68035c025/
https://urlscan.io/result/fb2c5098-9335-4100-be11-fc04ba264fce/
address: 1CK9kT35qZHGAb7kuqZeKfKQc3j6Ezt8JZ (btc)
xrpx2july.blogspot.com …
=> binance-team.com + more

_data/scams.yaml
binpromo.net
https://urlscan.io/result/47a87d9b-237f-4cfe-a79a-96944eb5b3ff/
https://urlscan.io/result/44093f58-cd66-4178-828a-909064699bd3/
https://urlscan.io/result/67c2436b-06df-4a92-9f99-bb120795748b/
address: 0x71D663DE2Df38D61A1871Bb8eF503d18D19964d6 (eth)
address: 16NwAMjoYUxYzBTqWFFHApRUubJRFCAEwj (btc)
cbn-project.com
Scam ICO project - see https://bitcointalk.org/index.php?topic=5165803.0
https://urlscan.io/result/6cf8c4d6-5752-4c11-b13d-97cf531a7217/
dropfestextravaganza.tech
https://urlscan.io/result/ceeddf26-5a7f-4aee-a4d3-fd9e55f05367/
https://urlscan.io/result/f3e41614-8ebe-489b-bd9f-5a540c880904/
address: 0xe33086e461749C687c2DDC3ec4EB24EA591c0dc7 (eth)
address: 1BiyLYjfDNQSP81uvr5gzNW77P2viGWi8m (btc)
fly-promo.online
Trust …
=> binpromo.net + more

_data/scams.yaml
dropbinance.com
https://urlscan.io/result/e50ac92f-6cfe-4760-a3e6-39a3d24f6c8f/
https://urlscan.io/result/359864d7-9218-42ec-8b12-ff43c5b6ce3f/
address: 0x1058afFcf5cd061abCAb30dD1bfeF82727F9e96F (eth)
address: 1CdWQJMiQF1uYbwKc7fb5VBb9JBrhykcNf (btc)
xrpx2july.blogspot.co.ke
https://urlscan.io/result/0376ede0-c9a9-4171-b1d6-005a273bd93a/
address: rhTCdpaZQSKbHNYY85xPLMEWQbyxYr4SFY (xrp)
giftbinance.com
https://urlscan.io/result/d41d8aa1-234f-4737-b1b6-5ef112bb2ed5
https://urlscan.io/result/001951a3-7e58-4ea4-85aa-3c9b90b70bc7/
https://urlscan.io/result/6c08e2ec-ea08-460e-8f37-b1f8fe582f24/
address: 0x1058afFcf5cd061abCAb30dD1bfeF82727F9e96F (eth)
address: 1CdWQJMiQF1uYbwKc7fb5VBb9JBrhykcNf (btc)
anniversary-eth.com …
=> dropbinance.com + more

run.js
* Validate user input with regex mask
* Catch decode errors and return a 400 if anything is caught
=> Fix XSS issues

_layouts/default.html, _static/css/general.css, _static/js/ip.js, package-lock.json, package.json, run.js
- Added CSP header ruleset
- HackerOne ticket 712376
=> CSP Header

_static/css/general.css, package-lock.json, package.json, run.js
=> CSP, X-Frame-Options, X-XSS-Protection headers
